import type { SourceSpan } from "../../../ast.ts";
import type {
  BrlIrBlock,
  BrlIrExpression,
  BrlIrField,
  BrlIrFunction,
  BrlIrInstruction,
  BrlIrProgram,
  BrlIrRecord,
  BrlIrTerminator,
  BrlIrType,
} from "../../ir.ts";
import { formatBrlIrType } from "../../ir.ts";
import { verifyRuntimeIr } from "../../verify.ts";

export interface BrlTypeScriptBackendOptions {
  readonly moduleName?: string;
  readonly exportFunctions?: boolean;
}

export class BrlTypeScriptBackendError extends Error {
  readonly span?: SourceSpan;

  constructor(message: string, span?: SourceSpan) {
    super(message);
    this.name = "BrlTypeScriptBackendError";
    this.span = span;
  }
}

export function emitBrlTypeScriptRuntime(
  program: BrlIrProgram,
  options: BrlTypeScriptBackendOptions = {},
): string {
  const diagnostics = [
    ...program.diagnostics.filter((diagnostic) =>
      diagnostic.severity !== "warning"
    ),
    ...verifyRuntimeIr(program),
  ];
  if (diagnostics.length > 0) {
    const first = diagnostics[0];
    throw new BrlTypeScriptBackendError(
      `Cannot emit TypeScript from unverified BRL IR: ${first.code}: ${first.message}`,
      first.span,
    );
  }

  const lines: string[] = [
    "// Generated by @mewhhaha/baba BRL TypeScript backend.",
    "// Source: verified BRL IR.",
  ];
  if (options.moduleName) {
    lines.push(`// Module: ${options.moduleName}`);
  }
  lines.push("");

  for (const record of program.records) {
    lines.push(`interface ${typeName(record.name)} {`);
    for (const field of record.fields) {
      lines.push(
        `  readonly ${propertyName(field.name)}: ${emitType(field.type)};`,
      );
    }
    lines.push("}", "");
  }
  lines.push(emitIndexHelper(), "");

  const functions = new Map(program.functions.map((fn) => [fn.id, fn]));
  const records = new Map(program.records.map((record) => [record.id, record]));
  for (const fn of program.functions) {
    lines.push(emitFunction(fn, functions, records, options), "");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function emitFunction(
  fn: BrlIrFunction,
  functions: ReadonlyMap<number, BrlIrFunction>,
  records: ReadonlyMap<number, BrlIrRecord>,
  options: BrlTypeScriptBackendOptions,
): string {
  const context = functionContext(fn, functions, records);
  const exportPrefix = options.exportFunctions === false ? "" : "export ";
  const params = fn.params.map((param) =>
    `${localName(param.name, param.id)}: ${emitType(param.type)}`
  ).join(", ");
  const lines = [
    `${exportPrefix}function ${functionName(fn.name)}(${params}): ${
      emitReturnType(fn.result)
    } {`,
  ];

  const paramIds = new Set(fn.params.map((param) => param.id));
  for (const local of fn.locals) {
    if (paramIds.has(local.id)) continue;
    lines.push(
      `  let ${localName(local.name, local.id)}: ${emitType(local.type)} = ${
        defaultValue(local.type, context)
      };`,
    );
  }

  if (fn.blocks.length === 0) {
    throw new BrlTypeScriptBackendError(
      `Function '${fn.name}' has no IR blocks.`,
      fn.span,
    );
  }
  lines.push(`  let __block = ${fn.blocks[0].id};`);
  lines.push("  while (true) {");
  lines.push("    switch (__block) {");
  for (const block of fn.blocks) {
    lines.push(`      case ${block.id}: {`);
    lines.push(...emitBlock(block, context).map((line) => `        ${line}`));
    lines.push("      }");
  }
  lines.push("      default:");
  lines.push(
    `        throw new Error("Invalid BRL block " + String(__block));`,
  );
  lines.push("    }");
  lines.push("  }");

  lines.push("}");
  return lines.join("\n");
}

function emitBlock(
  block: BrlIrBlock,
  context: EmitContext,
): string[] {
  const lines: string[] = [`// block ${block.id}`];
  for (const instruction of block.instructions) {
    lines.push(...emitInstruction(instruction, context));
  }
  if (block.terminator) {
    lines.push(...emitTerminator(block.terminator, context));
  }
  return lines;
}

function emitInstruction(
  instruction: BrlIrInstruction,
  context: EmitContext,
): string[] {
  switch (instruction.kind) {
    case "assign":
      return [
        `${requiredLocal(context, instruction.local, instruction.span)} = ${
          emitExpression(instruction.value, context)
        };`,
      ];
    case "evaluate":
      return [`void (${emitExpression(instruction.value, context)});`];
    case "trap":
      return [
        `throw new Error(${
          JSON.stringify(instruction.message || "BRL trap")
        });`,
      ];
  }
}

function emitTerminator(
  terminator: BrlIrTerminator,
  context: EmitContext,
): string[] {
  switch (terminator.kind) {
    case "return":
      return terminator.value
        ? [`return ${emitExpression(terminator.value, context)};`]
        : ["return;"];
    case "jump":
      return [`__block = ${terminator.target};`, "continue;"];
    case "branch":
      return [
        `__block = ${
          emitExpression(terminator.condition, context)
        } ? ${terminator.consequent} : ${terminator.alternate};`,
        "continue;",
      ];
  }
}

function emitExpression(
  expression: BrlIrExpression,
  context: EmitContext,
): string {
  switch (expression.kind) {
    case "literal":
      if (
        expression.type.kind === "scalar" && expression.type.name === "bool"
      ) {
        return expression.value ? "true" : "false";
      }
      return `(${Number(expression.value) >>> 0})`;
    case "local":
      return requiredLocal(context, expression.local, expression.span);
    case "record":
      return emitRecordExpression(expression, context);
    case "unary":
      return emitUnaryExpression(expression, context);
    case "binary":
      return emitBinaryExpression(expression, context);
    case "cast":
      return coerceExpression(
        emitExpression(expression.expression, context),
        expression.type,
      );
    case "field":
      if (expression.fieldId === -1) {
        return `(${emitExpression(expression.receiver, context)}.length >>> 0)`;
      }
      return coerceExpression(
        fieldAccessExpression(
          emitExpression(expression.receiver, context),
          requiredField(context, expression),
        ),
        expression.type,
      );
    case "index":
      return coerceExpression(
        `__brlIndex(${emitExpression(expression.receiver, context)}, ${
          emitExpression(expression.index, context)
        })`,
        expression.type,
      );
    case "call": {
      const target = context.functions.get(expression.functionId);
      if (!target) {
        throw new BrlTypeScriptBackendError(
          `Unknown function id ${expression.functionId}.`,
          expression.span,
        );
      }
      return coerceExpression(
        `${functionName(target.name)}(${
          expression.args.map((arg) => emitExpression(arg, context)).join(", ")
        })`,
        expression.type,
      );
    }
  }
}

function emitRecordExpression(
  expression: Extract<BrlIrExpression, { readonly kind: "record" }>,
  context: EmitContext,
): string {
  if (expression.type.kind !== "record") {
    throw new BrlTypeScriptBackendError(
      "Record expression has non-record type.",
      expression.span,
    );
  }
  const record = context.records.get(expression.type.id);
  if (!record) {
    throw new BrlTypeScriptBackendError(
      `Unknown record type ${formatBrlIrType(expression.type)}.`,
      expression.span,
    );
  }
  return `({ ${
    record.fields.map((field) => {
      const value = expression.fields.find((entry) =>
        entry.fieldId === field.id
      );
      if (!value) {
        throw new BrlTypeScriptBackendError(
          `Missing field ${field.id} in record expression.`,
          expression.span,
        );
      }
      return `${propertyName(field.name)}: ${
        emitExpression(value.value, context)
      }`;
    }).join(", ")
  } })`;
}

function emitUnaryExpression(
  expression: Extract<BrlIrExpression, { readonly kind: "unary" }>,
  context: EmitContext,
): string {
  const operand = emitExpression(expression.operand, context);
  switch (expression.operator) {
    case "!":
      return `(!(${operand}))`;
    default:
      throw new BrlTypeScriptBackendError(
        `Unsupported BRL unary operator '${expression.operator}'.`,
        expression.span,
      );
  }
}

function emitBinaryExpression(
  expression: Extract<BrlIrExpression, { readonly kind: "binary" }>,
  context: EmitContext,
): string {
  const left = emitExpression(expression.left, context);
  const right = emitExpression(expression.right, context);
  const leftType = expression.left.type;
  const width = scalarBitWidth(leftType);
  switch (expression.operator) {
    case "+":
      return coerceExpression(`(${left} + ${right})`, expression.type);
    case "-":
      return coerceExpression(`(${left} - ${right})`, expression.type);
    case "*":
      return coerceExpression(`Math.imul(${left}, ${right})`, expression.type);
    case "/":
      return coerceExpression(
        `((__left: number, __right: number) => (__right === 0 ? ${
          trapExpression("BRL division by zero")
        } : Math.trunc(__left / __right)))(${left}, ${right})`,
        expression.type,
      );
    case "%":
      return coerceExpression(
        `((__left: number, __right: number) => (__right === 0 ? ${
          trapExpression("BRL remainder by zero")
        } : (__left % __right)))(${left}, ${right})`,
        expression.type,
      );
    case "<<":
      return coerceExpression(
        `((__left: number, __right: number) => (__right >= ${width} ? ${
          trapExpression("BRL shift count out of range")
        } : (__left << __right)))(${left}, ${right})`,
        expression.type,
      );
    case ">>":
      return coerceExpression(
        `((__left: number, __right: number) => (__right >= ${width} ? ${
          trapExpression("BRL shift count out of range")
        } : (__left ${
          leftType.kind === "scalar" && leftType.name === "i32" ? ">>" : ">>>"
        } __right)))(${left}, ${right})`,
        expression.type,
      );
    case "==":
      return `(${left} === ${right})`;
    case "!=":
      return `(${left} !== ${right})`;
    case "<":
      return comparisonExpression(left, right, "<", leftType);
    case "<=":
      return comparisonExpression(left, right, "<=", leftType);
    case ">":
      return comparisonExpression(left, right, ">", leftType);
    case ">=":
      return comparisonExpression(left, right, ">=", leftType);
    case "&&":
      return `((__left: boolean, __right: boolean) => (__left && __right))(${left}, ${right})`;
    case "||":
      return `((__left: boolean, __right: boolean) => (__left || __right))(${left}, ${right})`;
    default:
      throw new BrlTypeScriptBackendError(
        `Unsupported BRL binary operator '${expression.operator}'.`,
        expression.span,
      );
  }
}

interface EmitContext {
  readonly locals: ReadonlyMap<number, string>;
  readonly functions: ReadonlyMap<number, BrlIrFunction>;
  readonly records: ReadonlyMap<number, BrlIrRecord>;
}

function functionContext(
  fn: BrlIrFunction,
  functions: ReadonlyMap<number, BrlIrFunction>,
  records: ReadonlyMap<number, BrlIrRecord>,
): EmitContext {
  return {
    locals: new Map(fn.locals.map((local) => [
      local.id,
      localName(local.name, local.id),
    ])),
    functions,
    records,
  };
}

function requiredField(
  context: EmitContext,
  expression: Extract<BrlIrExpression, { readonly kind: "field" }>,
): BrlIrField {
  const receiverType = expression.receiver.type;
  if (receiverType.kind !== "record") {
    throw new BrlTypeScriptBackendError(
      `Field id ${expression.fieldId} is used on non-record type ${
        formatBrlIrType(receiverType)
      }.`,
      expression.span,
    );
  }
  const record = context.records.get(receiverType.id);
  const field = record?.fields.find((entry) => entry.id === expression.fieldId);
  if (!field) {
    throw new BrlTypeScriptBackendError(
      `Unknown field id ${expression.fieldId} on record ${receiverType.name}.`,
      expression.span,
    );
  }
  return field;
}

function requiredLocal(
  context: EmitContext,
  id: number,
  span?: SourceSpan,
): string {
  const name = context.locals.get(id);
  if (!name) {
    throw new BrlTypeScriptBackendError(`Unknown local id ${id}.`, span);
  }
  return name;
}

function emitType(type: BrlIrType): string {
  switch (type.kind) {
    case "scalar":
      return type.name === "bool" ? "boolean" : "number";
    case "array":
    case "span":
    case "vec":
      return `ReadonlyArray<${emitType(type.element)}>`;
    case "record":
      return typeName(type.name);
  }
}

function emitReturnType(type: BrlIrType | null): string {
  return type ? emitType(type) : "void";
}

function emitIndexHelper(): string {
  return [
    "function __brlIndex<T>(value: ReadonlyArray<T>, index: number): T {",
    '  if (!Number.isInteger(index) || index < 0 || index >= value.length) throw new Error("BRL index out of bounds");',
    "  return value[index];",
    "}",
  ].join("\n");
}

function defaultValue(type: BrlIrType, context: EmitContext): string {
  switch (type.kind) {
    case "scalar":
      return type.name === "bool" ? "false" : "0";
    case "span":
    case "vec":
      return "[]";
    case "array":
      return `Array.from({ length: ${type.length} }, () => ${
        defaultValue(type.element, context)
      })`;
    case "record": {
      const record = context.records.get(type.id);
      if (!record) {
        throw new BrlTypeScriptBackendError(
          `Unknown record type ${formatBrlIrType(type)}.`,
        );
      }
      return `({ ${
        record.fields.map((field) =>
          `${propertyName(field.name)}: ${defaultValue(field.type, context)}`
        ).join(", ")
      } })`;
    }
  }
}
function coerceExpression(source: string, type: BrlIrType): string {
  if (type.kind === "scalar") {
    if (type.name === "bool") return `Boolean(${source})`;
    if (type.name === "u8") return `((${source}) & 0xff)`;
    if (type.name === "u16") return `((${source}) & 0xffff)`;
    if (type.name === "i32") return `((${source}) | 0)`;
    return `((${source}) >>> 0)`;
  }
  return source;
}

function comparisonExpression(
  left: string,
  right: string,
  operator: string,
  type: BrlIrType,
): string {
  if (type.kind === "scalar" && type.name === "i32") {
    return `((${left}) | 0) ${operator} ((${right}) | 0)`;
  }
  return `((${left}) >>> 0) ${operator} ((${right}) >>> 0)`;
}

function scalarBitWidth(type: BrlIrType): number {
  if (type.kind !== "scalar") return 32;
  switch (type.name) {
    case "bool":
      return 1;
    case "u8":
      return 8;
    case "u16":
      return 16;
    case "u32":
    case "i32":
      return 32;
  }
}

function trapExpression(message: string): string {
  return `((): never => { throw new Error(${JSON.stringify(message)}); })()`;
}

function functionName(name: string): string {
  return identifier(name);
}

function localName(name: string, id: number): string {
  return `${identifier(name)}_${id}`;
}

function typeName(name: string): string {
  const base = identifier(name);
  return `${base[0]?.toUpperCase() ?? "T"}${base.slice(1)}`;
}

function propertyName(name: string): string {
  const identifierName = identifier(name);
  return identifierName === name ? name : JSON.stringify(name);
}

function fieldAccessExpression(receiver: string, field: BrlIrField): string {
  const name = propertyName(field.name);
  return name.startsWith('"') ? `${receiver}[${name}]` : `${receiver}.${name}`;
}

function identifier(name: string): string {
  const safe = name.replaceAll(/[^A-Za-z0-9_$]/g, "_");
  const prefixed = /^[A-Za-z_$]/.test(safe) ? safe : `_${safe}`;
  return reserved.has(prefixed) ? `${prefixed}_` : prefixed;
}

const reserved = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
]);
