(INTEGER) @number
(increment) @operator
(decrement) @operator
(move_left) @operator
(move_right) @operator
(output) @function.call
(input) @function.call
"[" @punctuation.bracket
"]" @punctuation.bracket
"{" @punctuation.bracket
"}" @punctuation.bracket
