use-grammars = { only = ["thunkwasm"] }

[[language]]
name = "thunkwasm"
scope = "source.thunkwasm"
file-types = ["tw"]
comment-token = "#"
grammar = "thunkwasm"
roots = ["grammar.ebnf"]
rainbow-brackets = true

[[grammar]]
name = "thunkwasm"
source = { path = "generated" }
