import {
  applyBundle,
  assert,
  assertEquals,
  assertIncludes,
  assertNotIncludes,
  assertThrowsIncludes,
  compile,
  denoCheck,
} from "./helpers.ts";
import {
  hashRuntimeImplementationManifest,
  hashRuntimeImplementationSource,
  RUNTIME_IMPLEMENTATION_METADATA,
} from "../src/targets/runtime/implementation.ts";
import { validateCombinedWasmParserPlan } from "../src/runtime/wasm_plan.ts";

const STATEMENT_GRAMMAR = `
  token IDENT = /[A-Za-z_][A-Za-z0-9_]*/ ;
  token INT = /[0-9]+/ ;
  skip WS = /[ \\t\\r\\n]+/ ;

  module = statement* ;
  statement = "let" name:IDENT "=" value:INT ";" | "if" condition:IDENT ";" ;
`;

interface TokenLike {
  type: string;
  text: string;
  span: { start: number; end: number };
  channel: string;
  kind?: string;
  literal?: string;
}

interface NodeLike {
  fields: Record<string, TokenLike>;
  children: NodeLike[];
  span: { start: number; end: number };
}

interface DiagnosticLike {
  code: string;
  expected?: readonly string[];
}

interface LexResultLike {
  tokens: readonly TokenLike[];
  diagnostics: readonly DiagnosticLike[];
}

type ParseResultLike =
  | { ok: true; root: NodeLike; diagnostics: readonly DiagnosticLike[] }
  | { ok: false; root: null; diagnostics: readonly DiagnosticLike[] };

type ValidateResultLike = {
  ok: boolean;
  diagnostics: readonly DiagnosticLike[];
};

interface GeneratedParser {
  lex(source: string, options?: Record<string, unknown>): LexResultLike;
  parse(
    source: string,
    options?: Record<string, unknown>,
  ): ParseResultLike | LexResultLike | ValidateResultLike;
  parseTokens(
    source: string,
    tokens: readonly unknown[],
    options?: Record<string, unknown>,
  ): ParseResultLike | LexResultLike | ValidateResultLike;
  parseTokensUnchecked(
    source: string,
    tokens: readonly unknown[],
    options?: Record<string, unknown>,
  ): ParseResultLike | LexResultLike | ValidateResultLike;
  dispose(): void;
}

interface GeneratedWasmModule {
  createParser(options: {
    bytes?: Uint8Array;
    module?: WebAssembly.Module;
    plan?: Uint8Array;
  }): GeneratedParser;
  createParserAsync(options: {
    url?: URL;
    planUrl?: URL;
    plan?: Uint8Array;
  }): Promise<GeneratedParser>;
}

Deno.test("Wasm target validates generated size and parser stats options", () => {
  const invalidByteLimit = compile(`module = "ok" ;`, {
    targets: ["wasm"],
    wasm: { generatedByteLimit: 0 },
  });
  assertEquals(invalidByteLimit.bundle, undefined);
  assertEquals(
    invalidByteLimit.diagnostics[0].code,
    "WASM_GENERATED_BYTE_LIMIT",
  );

  const generatedByteLimit = compile(`module = "a" | "b" ;`, {
    targets: ["wasm"],
    wasm: { generatedByteLimit: 1 },
  });
  assertEquals(generatedByteLimit.bundle, undefined);
  assertEquals(
    generatedByteLimit.diagnostics[0].code,
    "WASM_GENERATED_BYTE_LIMIT",
  );

  const stats = compile(`module = "a" | "b" ;`, {
    targets: ["wasm"],
    wasm: { reportParserStats: true },
  });
  assert(stats.bundle);
  assertEquals(stats.diagnostics[0].code, "WASM_PARSER_STATS");
  assertIncludes(stats.diagnostics[0].message, "BNF productions: 4");
  assertIncludes(stats.diagnostics[0].message, "lexer states:");
  assertIncludes(stats.diagnostics[0].message, "generated bytes:");
  assertIncludes(stats.diagnostics[0].message, "adapter/source bytes:");
  assertIncludes(stats.diagnostics[0].message, "core Wasm binary bytes:");
  assertIncludes(stats.diagnostics[0].message, "external plan binary bytes:");
  assertNotIncludes(
    stats.diagnostics[0].message,
    "parser trace Wasm binary bytes:",
  );
});

Deno.test("Wasm target emits minimal external artifacts", async () => {
  const bundle = wasmBundle(`module = "ok" ;`);
  assertEquals(
    bundle.files.map((file) => file.path).join(","),
    "wasm/abi.json,wasm/manifest.json,wasm/mod.ts,wasm/parser.plan,wasm/parser.wasm,wasm/syntax.ts",
  );
  const modSource = textFile(bundle, "wasm/mod.ts");
  assertIncludes(modSource, "@mewhhaha/baba/runtime/wasm");
  assertNotIncludes(modSource, "parserTraceRuntimeBytes");
  assertNotIncludes(modSource, "wasmBytes");
  assertNotIncludes(
    bundle.files.map((file) => file.path).join(","),
    "lexer.ts",
  );
  assertNotIncludes(
    bundle.files.map((file) => file.path).join(","),
    "parser.ts",
  );
  assertNotIncludes(bundle.files.map((file) => file.path).join(","), "wasm.ts");

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(bundle, { root: dir });
    await denoCheck(`${dir}/wasm/mod.ts`);
    const mod = await import(`file://${dir}/wasm/mod.ts`);
    assertEquals("lex" in mod, false);
    assertThrowsIncludes(
      () =>
        mod.createParser({
          bytes: Deno.readFileSync(`${dir}/wasm/parser.wasm`),
        }),
      "Wasm parser creation requires parser plan bytes",
    );
    const parser = mod.createParser({
      bytes: await Deno.readFile(`${dir}/wasm/parser.wasm`),
      plan: await Deno.readFile(`${dir}/wasm/parser.plan`),
    });
    const parsed = parser.parse("ok") as ParseResultLike;
    assertEquals(parsed.ok, true);
    parser.dispose();
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("runtime manifest contains only active shared sources", async () => {
  assertEquals(RUNTIME_IMPLEMENTATION_METADATA.sources.length, 27);
  const roles = RUNTIME_IMPLEMENTATION_METADATA.sources.map((source) =>
    source.role
  );
  assertEquals(
    roles.join("\n"),
    [
      "shared-brl-source-map",
      "shared-brl-lexer",
      "shared-brl-parser",
      "shared-brl-branch-search",
      "shared-brl-reductions",
      "shared-brl-cst",
      "shared-brl-token-stream",
      "shared-brl-diagnostics",
      "public-source-text-boundary",
      "public-lex-diagnostic-materializer",
      "public-lex-result-materializer",
      "public-token-materializer",
      "public-diagnostic-materializer",
      "public-parse-result-materializer",
      "public-field-materializer",
      "public-rule-node-materializer",
      "parser-diagnostic-codes",
      "runtime-language-source",
      "runtime-language-compiler",
      "runtime-language-artifact-manifest",
      "wasm-abi-constants",
      "wasm-core-runtime",
      "shared-parser-plan-adapter-api",
      "shared-wasm-runtime-api",
      "shared-generic-wasm-executor",
      "shared-runtime-parser-plan",
      "generated-source-provenance",
    ].join("\n"),
  );

  const sources = [];
  for (const source of RUNTIME_IMPLEMENTATION_METADATA.sources) {
    const content = await Deno.readTextFile(source.path);
    assertEquals(hashRuntimeImplementationSource(content), source.hash);
    sources.push(source);
  }
  assertEquals(
    hashRuntimeImplementationManifest(sources),
    RUNTIME_IMPLEMENTATION_METADATA.hash,
  );
});

Deno.test("Wasm core and wrapper are stable across grammars", () => {
  const alpha = wasmBundle(`module = "alpha" ;`);
  const beta = wasmBundle(`module = "beta" "!" ;`);
  for (
    const path of [
      "wasm/parser.wasm",
      "wasm/mod.ts",
      "wasm/abi.json",
      "wasm/manifest.json",
    ]
  ) {
    assertEquals(serializedFile(alpha, path), serializedFile(beta, path), path);
  }
  assert(
    serializedFile(alpha, "wasm/parser.plan") !==
      serializedFile(beta, "wasm/parser.plan"),
    "Expected grammar-specific parser.plan bytes.",
  );
  assert(
    serializedFile(alpha, "wasm/syntax.ts") !==
      serializedFile(beta, "wasm/syntax.ts"),
    "Expected grammar-specific syntax types.",
  );
});

Deno.test("shared Wasm adapter preserves lexer and parser behavior", async () => {
  const { dir, mod, bytes, plan } = await materialize(STATEMENT_GRAMMAR);
  try {
    const parser = mod.createParser({ bytes, plan });
    const lexed = parser.lex("let x = 42;");
    assertEquals(lexed.diagnostics.length, 0);
    assertEquals(lexed.tokens[0].type, "literal");
    assertEquals(lexed.tokens[0].text, "let");
    assertEquals(lexed.tokens[2].kind, "IDENT");
    assertEquals(lexed.tokens[2].span.start, 4);
    assert(
      lexed.tokens.some((token: { kind?: string; channel: string }) =>
        token.kind === "WS" && token.channel === "trivia"
      ),
      "Expected trivia token.",
    );

    const parsed = parser.parse("let x = 42;") as ParseResultLike;
    assertEquals(parsed.ok, true);
    assert(parsed.root);
    const statement = parsed.root.children[0];
    assertEquals(statement.fields.name.text, "x");
    assertEquals(statement.fields.value.text, "42");
    assertEquals(parsed.root.span.start, 0);
    assertEquals(parsed.root.span.end, 11);

    const checked = parser.parseTokens(
      "let x = 42;",
      lexed.tokens,
    ) as ParseResultLike;
    const unchecked = parser.parseTokensUnchecked(
      "let x = 42;",
      lexed.tokens,
    ) as ParseResultLike;
    assertEquals(checked.ok, true);
    assertEquals(unchecked.ok, true);

    const invalid = parser.parse("let = 42;") as ParseResultLike;
    assertEquals(invalid.ok, false);
    assertEquals(invalid.diagnostics[0].code, "PARSE_UNEXPECTED_TOKEN");
    assert(invalid.diagnostics[0].expected);
    assertIncludes(invalid.diagnostics[0].expected.join(","), "IDENT");

    const tokenMode = parser.parse("let x = 42;", {
      mode: "tokens",
    }) as LexResultLike;
    assertEquals(tokenMode.tokens.length, lexed.tokens.length);
    const validateMode = parser.parse("let x = 42;", {
      mode: "validate",
    }) as ValidateResultLike;
    assertEquals(validateMode.ok, true);
    parser.dispose();
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("shared Wasm adapter loads concurrent parser instances with different plans", async () => {
  const alpha = await materialize(`module = "alpha" ;`);
  const beta = await materialize(`module = "beta" "!" ;`);
  try {
    const alphaParser = alpha.mod.createParser({
      bytes: alpha.bytes,
      plan: alpha.plan,
    });
    const betaParser = alpha.mod.createParser({
      bytes: beta.bytes,
      plan: beta.plan,
    });
    assertEquals((alphaParser.parse("alpha") as ParseResultLike).ok, true);
    assertEquals((alphaParser.parse("beta!") as ParseResultLike).ok, false);
    assertEquals((betaParser.parse("beta!") as ParseResultLike).ok, true);
    assertEquals((betaParser.parse("alpha") as ParseResultLike).ok, false);
    alphaParser.dispose();
    betaParser.dispose();
  } finally {
    await Deno.remove(alpha.dir, { recursive: true });
    await Deno.remove(beta.dir, { recursive: true });
  }
});

Deno.test("shared Wasm adapter validates external plan bytes", async () => {
  const { dir, mod, bytes, plan } = await materialize(`module = "ok" ;`);
  try {
    assertThrowsIncludes(
      () => mod.createParser({ bytes }),
      "requires parser plan bytes",
    );
    assertThrowsIncludes(
      () => mod.createParser({ bytes, plan: plan.slice(0, 12) }),
      "truncated",
    );

    const wrongVersion = new Uint8Array(plan);
    new DataView(
      wrongVersion.buffer,
      wrongVersion.byteOffset,
      wrongVersion.byteLength,
    ).setInt32(8, 999, true);
    assertThrowsIncludes(
      () => mod.createParser({ bytes, plan: wrongVersion }),
      "Unsupported parser plan version 999",
    );

    const corruptOffset = new Uint8Array(plan);
    new DataView(
      corruptOffset.buffer,
      corruptOffset.byteOffset,
      corruptOffset.byteLength,
    ).setInt32(20, corruptOffset.byteLength + 4, true);
    assertThrowsIncludes(
      () => mod.createParser({ bytes, plan: corruptOffset }),
      "accepts offset is not aligned",
    );

    const corruptRuntimeMetadata = new Uint8Array(plan);
    const validated = validateCombinedWasmParserPlan(corruptRuntimeMetadata);
    corruptRuntimeMetadata[validated.runtimeMetadataOffset] = 0;
    const parser = mod.createParser({ bytes, plan: corruptRuntimeMetadata });
    assertThrowsIncludes(
      () => parser.lex("ok"),
      "Invalid compact plan magic",
    );
    parser.dispose();
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("shared Wasm adapter supports async URL loading", async () => {
  const { dir, mod, bytes, plan } = await materialize(`module = "ok" ;`);
  try {
    const parser = await mod.createParserAsync({
      url: dataUrl(bytes, "application/wasm"),
      planUrl: dataUrl(plan, "application/octet-stream"),
    });
    const parsed = parser.parse("ok") as ParseResultLike;
    assertEquals(parsed.ok, true);
    parser.dispose();
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

function wasmBundle(source: string) {
  const result = compile(source, { targets: ["wasm"] });
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);
  return result.bundle;
}

async function materialize(source: string): Promise<{
  dir: string;
  mod: GeneratedWasmModule;
  bytes: Uint8Array;
  plan: Uint8Array;
}> {
  const bundle = wasmBundle(source);
  const dir = await Deno.makeTempDir();
  await applyBundle(bundle, { root: dir });
  await denoCheck(`${dir}/wasm/mod.ts`);
  return {
    dir,
    mod: await import(`file://${dir}/wasm/mod.ts`) as GeneratedWasmModule,
    bytes: await Deno.readFile(`${dir}/wasm/parser.wasm`),
    plan: await Deno.readFile(`${dir}/wasm/parser.plan`),
  };
}

function textFile(bundle: ReturnType<typeof wasmBundle>, path: string): string {
  const file = bundle.files.find((entry) => entry.path === path);
  assert(file, `Expected generated file ${path}.`);
  assert(file.encoding === "utf-8", `Expected text file ${path}.`);
  return file.content;
}

function serializedFile(
  bundle: ReturnType<typeof wasmBundle>,
  path: string,
): string {
  const file = bundle.files.find((entry) => entry.path === path);
  assert(file, `Expected generated file ${path}.`);
  if (file.encoding === "utf-8") return file.content;
  return [...file.content].join(",");
}

function dataUrl(bytes: Uint8Array, mime: string): URL {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return new URL(`data:${mime};base64,${btoa(binary)}`);
}
