import {
  applyBundle,
  assert,
  assertEquals,
  assertIncludes,
  assertNotIncludes,
  assertThrowsIncludes,
  captureConsoleError,
  captureConsoleLog,
  compile,
  denoCheck,
  main,
} from "./helpers.ts";

const hasWasmTools = await commandAvailable("wasm-tools");
const hasWasmtime = await commandAvailable("wasmtime");
const legacySpecializedWasm = { packaging: "embedded-typescript" } as const;

Deno.test("Wasm target validates generated size and parser stats options", () => {
  const invalidByteLimit = compile(`module = "ok" ;`, {
    targets: ["wasm"],
    wasm: { generatedByteLimit: 0 },
  });
  assertEquals(invalidByteLimit.bundle, undefined);
  assertEquals(
    invalidByteLimit.diagnostics[0].code,
    "WASM_GENERATED_BYTE_LIMIT",
  );

  const generatedByteLimit = compile(`module = "a" | "b" ;`, {
    targets: ["wasm"],
    wasm: { generatedByteLimit: 1 },
  });
  assertEquals(generatedByteLimit.bundle, undefined);
  assertEquals(
    generatedByteLimit.diagnostics[0].code,
    "WASM_GENERATED_BYTE_LIMIT",
  );

  const stats = compile(`module = "a" | "b" ;`, {
    targets: ["wasm"],
    wasm: { reportParserStats: true },
  });
  assert(stats.bundle);
  assertEquals(stats.diagnostics[0].code, "WASM_PARSER_STATS");
  assertIncludes(stats.diagnostics[0].message, "BNF productions: 4");
  assertIncludes(stats.diagnostics[0].message, "lexer states:");
  assertIncludes(stats.diagnostics[0].message, "lexer accept candidates:");
  assertIncludes(
    stats.diagnostics[0].message,
    "lexer average accept candidates/state:",
  );
  assertIncludes(
    stats.diagnostics[0].message,
    "lexer max accept candidates/state:",
  );
  assertIncludes(
    stats.diagnostics[0].message,
    "lexer ambiguous accept states:",
  );
  assertIncludes(stats.diagnostics[0].message, "regex AST nodes:");
  assertIncludes(stats.diagnostics[0].message, "regex NFA states:");
  assertIncludes(stats.diagnostics[0].message, "regex DFA states:");
  assertIncludes(
    stats.diagnostics[0].message,
    "overlap token pairs compared:",
  );
  assertIncludes(stats.diagnostics[0].message, "grammar SCCs:");
  assertIncludes(stats.diagnostics[0].message, "nullable iterations:");
  assertIncludes(stats.diagnostics[0].message, "productive iterations:");
  assertIncludes(stats.diagnostics[0].message, "LR closure work:");
  assertIncludes(stats.diagnostics[0].message, "diagnostics emitted:");
  assertIncludes(stats.diagnostics[0].message, "diagnostics suppressed:");
  assertIncludes(stats.diagnostics[0].message, "generated bytes:");
  assertIncludes(stats.diagnostics[0].message, "adapter/source bytes:");
  assertIncludes(stats.diagnostics[0].message, "core Wasm binary bytes:");
  assertIncludes(
    stats.diagnostics[0].message,
    "parser trace Wasm binary bytes:",
  );
});

Deno.test("Wasm target defaults to shared generic adapter without emitted bytes", async () => {
  const result = compile(`module = "ok" ;`, { targets: ["wasm"] });
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);
  assertEquals(
    result.bundle.files.map((file) => file.path).join(","),
    "wasm/abi.json,wasm/lexer.ts,wasm/mod.ts,wasm/parser.ts,wasm/plan.ts,wasm/syntax.ts",
  );
  assert(
    !result.bundle.files.some((file) =>
      file.path === "wasm/wasm.ts" || file.path === "wasm/parser.wasm"
    ),
  );
  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    await denoCheck(`${dir}/wasm/mod.ts`);
    const source = await Deno.readTextFile(`${dir}/wasm/mod.ts`);
    assertIncludes(source, "shared-generic-runtime-data");
    assertNotIncludes(source, "wasmBytes");
    const mod = await import(`file://${dir}/wasm/mod.ts`);
    assertEquals("wasmBytes" in mod, false);
    assertEquals((mod.parse("ok") as { ok: boolean }).ok, true);
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("generates standalone Wasm lexer and parser", async () => {
  const source = `
    token IDENT = /[A-Za-z_][A-Za-z0-9_]*/ ;
    token INTEGER = /[0-9]+/ ;
    skip WS = /[ \\t\\r\\n]+/ ;
    skip LINE_COMMENT = /\\/\\/[^\\n]*/ ;

    module = statement* ;
    statement = "let" name:IDENT "=" value:INTEGER ";" ;
  `;
  const result = compile(source, {
    targets: ["wasm"],
    wasm: legacySpecializedWasm,
  });
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);
  assertEquals(
    result.bundle.files.map((file) => file.path).join(","),
    "wasm/abi.json,wasm/lexer.ts,wasm/mod.ts,wasm/parser.ts,wasm/syntax.ts,wasm/wasm.ts",
  );

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    await denoCheck(`${dir}/wasm/mod.ts`);
    const wasmSource = await Deno.readTextFile(`${dir}/wasm/wasm.ts`);
    assertIncludes(wasmSource, "lex_all");
    assertIncludes(wasmSource, "parserTraceRuntimeBytes");
    assertIncludes(wasmSource, "parserTraceRuntime.parserTrace");
    assertIncludes(
      wasmSource,
      "#parserTraceRuntime = instantiateParserTraceRuntime();",
    );
    assertIncludes(wasmSource, "class WasmParserInstanceImpl");
    assertIncludes(wasmSource, "withWasmParserInstance");
    assertIncludes(wasmSource, "validateWasmAbi(wasm);");
    assertIncludes(wasmSource, "wasm.input_base()");
    assertIncludes(wasmSource, "wasm.source_encoding()");
    assertIncludes(wasmSource, "wasm.host_ownership_model()");
    assertIncludes(wasmSource, "wasm.result_lifetime_model()");
    assertNotIncludes(wasmSource, "wasm.parse_trace");
    assertIncludes(wasmSource, "const MAX_WASM_PAGES = 65535");
    assertIncludes(wasmSource, "memory.grow(requiredPages - currentPages)");
    const abi = JSON.parse(await Deno.readTextFile(`${dir}/wasm/abi.json`));
    const mod = await import(`file://${dir}/wasm/mod.ts`);
    const wasmModule = new WebAssembly.Module(mod.wasmBytes);
    const wasmInstance = new WebAssembly.Instance(wasmModule, {});
    const wasmExports = wasmInstance.exports as unknown as {
      parse_trace?: unknown;
      abi_version(): number;
      plan_version(): number;
      semantics_version(): number;
      reset(): void;
      input_base(): number;
      max_pages(): number;
      source_encoding(): number;
      span_unit(): number;
      lex_result_i32_count(): number;
      token_record_i32_count(): number;
      host_ownership_model(): number;
      result_lifetime_model(): number;
    };
    assertEquals(wasmExports.parse_trace, undefined);
    assertEquals(wasmExports.abi_version(), 1);
    assertEquals(wasmExports.plan_version(), 1);
    assertEquals(wasmExports.semantics_version(), 1);
    assert(wasmExports.input_base() > 0);
    assertEquals(wasmExports.max_pages(), 65_535);
    assertEquals(wasmExports.source_encoding(), 1);
    assertEquals(wasmExports.span_unit(), 1);
    assertEquals(wasmExports.lex_result_i32_count(), 2);
    assertEquals(wasmExports.token_record_i32_count(), 3);
    assertEquals(wasmExports.host_ownership_model(), 1);
    assertEquals(wasmExports.result_lifetime_model(), 1);
    wasmExports.reset();
    assertEquals(mod.wasmTargetKind, "javascript-hosted-core-wasm");
    assertEquals(mod.wasmAbiVersion, 1);
    assertEquals(mod.wasmSemanticsVersion, mod.runtimeImplementationVersion);
    assertEquals(mod.wasmInputBase, wasmExports.input_base());
    assertEquals(mod.wasmMaxPages, 65_535);
    assertEquals(mod.wasmSourceEncoding, 1);
    assertEquals(mod.wasmSpanUnit, 1);
    assertEquals(mod.wasmLexResultI32Count, 2);
    assertEquals(mod.wasmTokenRecordI32Count, 3);
    assertEquals(mod.wasmHostOwnershipModel, 1);
    assertEquals(mod.wasmResultLifetimeModel, 1);
    assertEquals(mod.wasmAdapterHandleCapabilityModel, 1);
    assertEquals(mod.wasmTraceStatusOk, 0);
    assertEquals(mod.wasmTraceStatusUnexpected, 1);
    assertEquals(mod.wasmTraceStatusInternal, 2);
    assertEquals(mod.wasmTraceStatusBranchLimit, 3);
    assertEquals(mod.wasmTraceStatusTraceLimit, 4);
    assertEquals(mod.wasmTraceStatusAmbiguous, 5);
    assertEquals(mod.parserDiagnosticCodeParseLexicalError, 1);
    assertEquals(mod.parserDiagnosticCodeParseUnexpectedToken, 2);
    assertEquals(mod.parserDiagnosticCodeParseTrailingInput, 3);
    assertEquals(mod.parserDiagnosticCodeParseInvalidTokenStream, 4);
    assertEquals(mod.parserDiagnosticCodeInternalError, 5);
    assertEquals(mod.parserDiagnosticCodeBranchLimit, 6);
    assertEquals(mod.parserDiagnosticCodeTraceLimit, 7);
    assertEquals(mod.parserDiagnosticCodeAmbiguousParse, 8);
    assertEquals(mod.parserDiagnosticDetailKindNone, 0);
    assertEquals(mod.parserDiagnosticDetailKindParserState, 1);
    assertEquals(abi.format, "baba-wasm-abi");
    assertEquals(abi.version, 1);
    assertEquals(abi.targetKind, mod.wasmTargetKind);
    assertEquals(abi.parserPlan.format, mod.parserPlanFormat);
    assertEquals(abi.parserPlan.version, mod.parserPlanVersion);
    assertEquals(abi.parserPlan.semantics, mod.parserPlanSemantics);
    assertEquals(abi.parserPlan.hash, mod.parserPlanHash);
    assertEquals(
      abi.runtimeImplementation.format,
      mod.runtimeImplementationFormat,
    );
    assertEquals(
      abi.runtimeImplementation.version,
      mod.runtimeImplementationVersion,
    );
    assertEquals(
      abi.runtimeImplementation.semantics,
      mod.runtimeImplementationSemantics,
    );
    assertEquals(
      abi.runtimeImplementation.hash,
      mod.runtimeImplementationHash,
    );
    assertEquals(abi.core.abiVersion, mod.wasmAbiVersion);
    assertEquals(abi.core.memory.export, "memory");
    assertEquals(abi.core.memory.maxPages, mod.wasmMaxPages);
    assertEquals(abi.core.memory.inputBase, mod.wasmInputBase);
    assertEquals(abi.core.sourceEncoding.value, mod.wasmSourceEncoding);
    assertEquals(abi.core.sourceEncoding.kind, "utf16");
    assertEquals(abi.core.sourceEncoding.unitBytes, 2);
    assertEquals(abi.core.spanUnit.value, mod.wasmSpanUnit);
    assertEquals(abi.core.ownership.value, mod.wasmHostOwnershipModel);
    assertEquals(abi.core.resultLifetime.value, mod.wasmResultLifetimeModel);
    assertEquals(
      abi.core.layouts.lexResult.i32Count,
      mod.wasmLexResultI32Count,
    );
    assertEquals(
      abi.core.layouts.tokenRecord.i32Count,
      mod.wasmTokenRecordI32Count,
    );
    assertEquals(
      abi.core.exports.map((entry: { name: string }) => entry.name).join(","),
      "memory,lex_one,parser_action,parser_goto,lex_all,abi_version,plan_version,semantics_version,reset,input_base,max_pages,source_encoding,span_unit,lex_result_i32_count,token_record_i32_count,host_ownership_model,result_lifetime_model",
    );
    assertEquals(
      abi.adapter.handleCapability.value,
      mod.wasmAdapterHandleCapabilityModel,
    );
    assertEquals(abi.traceStatuses.ok, mod.wasmTraceStatusOk);
    assertEquals(abi.traceStatuses.unexpected, mod.wasmTraceStatusUnexpected);
    assertEquals(abi.traceStatuses.internal, mod.wasmTraceStatusInternal);
    assertEquals(abi.traceStatuses.branchLimit, mod.wasmTraceStatusBranchLimit);
    assertEquals(abi.traceStatuses.traceLimit, mod.wasmTraceStatusTraceLimit);
    assertEquals(abi.traceStatuses.ambiguous, mod.wasmTraceStatusAmbiguous);
    assertEquals(
      abi.parserDiagnosticCodes.parseLexicalError,
      mod.parserDiagnosticCodeParseLexicalError,
    );
    assertEquals(
      abi.parserDiagnosticCodes.parseUnexpectedToken,
      mod.parserDiagnosticCodeParseUnexpectedToken,
    );
    assertEquals(
      abi.parserDiagnosticCodes.parseTrailingInput,
      mod.parserDiagnosticCodeParseTrailingInput,
    );
    assertEquals(
      abi.parserDiagnosticCodes.parseInvalidTokenStream,
      mod.parserDiagnosticCodeParseInvalidTokenStream,
    );
    assertEquals(
      abi.parserDiagnosticCodes.internalError,
      mod.parserDiagnosticCodeInternalError,
    );
    assertEquals(
      abi.parserDiagnosticCodes.branchLimit,
      mod.parserDiagnosticCodeBranchLimit,
    );
    assertEquals(
      abi.parserDiagnosticCodes.traceLimit,
      mod.parserDiagnosticCodeTraceLimit,
    );
    assertEquals(
      abi.parserDiagnosticCodes.ambiguousParse,
      mod.parserDiagnosticCodeAmbiguousParse,
    );
    assertEquals(abi.parserDiagnostics.detailKinds.none, 0);
    assertEquals(abi.parserDiagnostics.detailKinds.parserState, 1);
    assertEquals(
      abi.parserDiagnostics.detailKinds.none,
      mod.parserDiagnosticDetailKindNone,
    );
    assertEquals(
      abi.parserDiagnostics.detailKinds.parserState,
      mod.parserDiagnosticDetailKindParserState,
    );
    const unexpectedSchema = abi.parserDiagnostics.schemas.find((
      schema: { name: string },
    ) => schema.name === "parseUnexpectedToken");
    assert(unexpectedSchema);
    assertEquals(unexpectedSchema.publicCode, "PARSE_UNEXPECTED_TOKEN");
    assertEquals(
      unexpectedSchema.runtimeCode,
      mod.parserDiagnosticCodeParseUnexpectedToken,
    );
    assertEquals(unexpectedSchema.detailKind, "parser-state");
    assertEquals(unexpectedSchema.detailKindId, 1);
    assertEquals(unexpectedSchema.payloadFields.join(","), "expected,found");
    const lexicalSchema = abi.parserDiagnostics.schemas.find((
      schema: { name: string },
    ) => schema.name === "parseLexicalError");
    assert(lexicalSchema);
    assertEquals(lexicalSchema.detailKind, "none");
    assertEquals(lexicalSchema.payloadFields.join(","), "found");
    assertEquals(mod.parserPlanFormat, "baba-parser-plan");
    assertEquals(mod.parserPlanVersion, 1);
    assertEquals(mod.parserPlanSemantics, "baba-portable-v1");
    assert(mod.parserPlanHash.startsWith("fnv1a64:"));
    assertEquals(
      mod.runtimeImplementationFormat,
      "baba-runtime-implementation",
    );
    assertEquals(mod.runtimeImplementationVersion, 1);
    assertEquals(
      mod.runtimeImplementationSemantics,
      "baba-runtime-portable-v1",
    );
    assert(mod.runtimeImplementationHash.startsWith("fnv1a64:"));
    assert(typeof mod.reset === "function");

    const lexed = mod.lex("let x = 42; // ok");
    assertEquals(
      lexed.tokens
        .filter((token: { channel: string }) => token.channel !== "trivia")
        .map((token: { type: string; literal?: string; kind?: string }) =>
          token.type === "literal" ? token.literal : token.kind ?? token.type
        )
        .join(","),
      "let,IDENT,=,INTEGER,;,eof",
    );
    assert(
      lexed.tokens.some((token: { kind?: string; channel: string }) =>
        token.kind === "LINE_COMMENT" && token.channel === "trivia"
      ),
    );
    const invalid = mod.lex("let @ = 1;");
    assertEquals(invalid.diagnostics.length, 1);
    assertEquals(
      invalid.tokens.find((token: { type: string }) => token.type === "error")
        ?.text,
      "@",
    );

    const parsed = mod.parse("let x = 42;");
    assertEquals(parsed.ok, true);
    const statement = parsed.root.children[0];
    assertEquals(statement.fields.name.text, "x");
    assertEquals(statement.fields.value.text, "42");

    const reparsed = mod.parseTokensUnchecked(
      "let x = 42;",
      mod.lex("let x = 42;").tokens,
    );
    assertEquals(reparsed.ok, true);
    const checkedReparse = mod.parseTokens(
      "let x = 42;",
      mod.lex("let x = 42;").tokens,
    );
    assertEquals(checkedReparse.ok, true);

    const parseError = mod.parse("let x 42;");
    assertEquals(parseError.ok, false);
    assertEquals(parseError.diagnostics[0].code, "PARSE_UNEXPECTED_TOKEN");
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("embedded Wasm adapter import does not synchronously compile", async () => {
  const result = compile(`module = "a" ;`, {
    targets: ["wasm"],
    wasm: legacySpecializedWasm,
  });
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  const originalModule = WebAssembly.Module;
  try {
    await applyBundle(result.bundle, { root: dir });
    const wasmSource = await Deno.readTextFile(`${dir}/wasm/wasm.ts`);
    assertIncludes(wasmSource, "let wasmModule: WebAssembly.Module | null");
    assertIncludes(
      wasmSource,
      "let parserTraceRuntimeModule: WebAssembly.Module | null",
    );
    (WebAssembly as unknown as { Module: typeof WebAssembly.Module }).Module =
      function blockedModule(): WebAssembly.Module {
        throw new Error(
          "unexpected synchronous Wasm compilation during import",
        );
      } as unknown as typeof WebAssembly.Module;

    const mod = await import(`file://${dir}/wasm/mod.ts`);
    assertEquals(mod.wasmAbiVersion, 1);
    assertEquals(mod.wasmTargetKind, "javascript-hosted-core-wasm");

    (WebAssembly as unknown as { Module: typeof WebAssembly.Module }).Module =
      originalModule;
    assertEquals(mod.parse("a").ok, true);
  } finally {
    (WebAssembly as unknown as { Module: typeof WebAssembly.Module }).Module =
      originalModule;
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("Wasm target can emit external binary packaging", async () => {
  const source = `
    token IDENT = /[A-Za-z_][A-Za-z0-9_]*/ ;
    skip WS = /[ \\t\\r\\n]+/ ;
    module = "let" IDENT ;
  `;
  const first = compile(source, {
    targets: ["wasm"],
    wasm: { packaging: "external-binary" },
  });
  const second = compile(source, {
    targets: ["wasm"],
    wasm: { packaging: "external-binary" },
  });
  assertEquals(first.diagnostics.length, 0);
  assertEquals(second.diagnostics.length, 0);
  assert(first.bundle);
  assert(second.bundle);
  assertEquals(
    first.bundle.files.map((file) => `${file.path}:${file.encoding}`).join(","),
    "wasm/abi.json:utf-8,wasm/lexer.ts:utf-8,wasm/manifest.json:utf-8,wasm/mod.ts:utf-8,wasm/parser.ts:utf-8,wasm/parser.wasm:binary,wasm/syntax.ts:utf-8,wasm/wasm.ts:utf-8",
  );
  const firstWasm = first.bundle.files.find((file) =>
    file.path === "wasm/parser.wasm"
  );
  const secondWasm = second.bundle.files.find((file) =>
    file.path === "wasm/parser.wasm"
  );
  assert(firstWasm?.encoding === "binary");
  assert(secondWasm?.encoding === "binary");
  assertEquals(
    [...firstWasm.content].join(","),
    [...secondWasm.content].join(","),
  );
  assert(WebAssembly.validate(arrayBuffer(firstWasm.content)));

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(first.bundle, { root: dir });
    const wasmSource = await Deno.readTextFile(`${dir}/wasm/wasm.ts`);
    assertNotIncludes(wasmSource, "export const wasmBytes");
    assertIncludes(wasmSource, "export function createWasmParserInstance");
    assertNotIncludes(wasmSource, "createParserFromBytes");
    assertNotIncludes(wasmSource, "createParserFromModule");
    assertNotIncludes(wasmSource, "createParserFromUrl");
    const bytes = await Deno.readFile(`${dir}/wasm/parser.wasm`);
    assert(WebAssembly.validate(arrayBuffer(bytes)));
    const mod = await import(`file://${dir}/wasm/mod.ts`);
    assertEquals("wasmBytes" in mod, false);
    assertEquals("createParserFromBytes" in mod, false);
    assertEquals("createParserFromModule" in mod, false);
    assertEquals("createParserFromUrl" in mod, false);
    assertEquals(typeof mod.createWasmParserInstance, "function");
    assertThrowsIncludes(
      () => mod.parse("let x"),
      "Wasm parser runtime is not initialized",
    );
    const fromBytes = mod.createParser({ bytes });
    assertEquals(fromBytes.parse("let x").ok, true);
    fromBytes.dispose();
    const module = new WebAssembly.Module(arrayBuffer(bytes));
    const fromModule = mod.createParser({ module });
    assertEquals(fromModule.parse("let x").ok, true);
    fromModule.dispose();
    const asyncFromBytes = await mod.createParserAsync({ bytes });
    assertEquals(asyncFromBytes.lex("let x").diagnostics.length, 0);
    asyncFromBytes.dispose();
    const wasm = mod.createWasmParserInstance({ bytes });
    const fromWasm = mod.createParser({ wasm });
    assertEquals(fromWasm.parse("let x").ok, true);
    fromWasm.dispose();
    mod.createParser({ bytes });
    const parsed = mod.parse("let x");
    assertEquals(parsed.ok, true);
    assertEquals(parsed.root.children[1].kind, "IDENT");
    const instance = new WebAssembly.Instance(
      new WebAssembly.Module(arrayBuffer(bytes)),
      {},
    );
    const exports = instance.exports as unknown as {
      abi_version(): number;
      plan_version(): number;
    };
    assertEquals(exports.abi_version(), 1);
    assertEquals(exports.plan_version(), 1);
    const manifest = JSON.parse(
      await Deno.readTextFile(`${dir}/wasm/manifest.json`),
    );
    assertEquals(manifest.format, "baba-wasm-runtime");
    assertEquals(manifest.version, 1);
    assertEquals(manifest.abiVersion, 1);
    assertEquals(manifest.parserPlanVersion, 1);
    assertEquals(manifest.module, "parser.wasm");
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test({
  name: hasWasmTools
    ? "Wasm core module validates with wasm-tools"
    : "Wasm core module validation skipped: install wasm-tools",
  ignore: !hasWasmTools,
  async fn() {
    const { dir, wasmPath } = await writeGeneratedCoreWasm(`
      token A = /a/ ;
      module = A ;
    `);
    try {
      const result = await runCommandResult("wasm-tools", [
        "validate",
        wasmPath,
      ]);
      assert(
        result.success,
        `wasm-tools validate failed:\n${result.stdout}${result.stderr}`,
      );
    } finally {
      await Deno.remove(dir, { recursive: true });
    }
  },
});

Deno.test({
  name: hasWasmtime
    ? "Wasm core ABI exports execute in Wasmtime"
    : "Wasmtime core ABI execution skipped: install wasmtime",
  ignore: !hasWasmtime,
  async fn() {
    const { dir, wasmPath } = await writeGeneratedCoreWasm(`
      token A = /a/ ;
      module = A ;
    `);
    try {
      const attempts = [
        ["--invoke", "abi_version", wasmPath],
        ["run", "--invoke", "abi_version", wasmPath],
      ];
      let lastResult: CommandResult | null = null;
      for (const args of attempts) {
        const result = await runCommandResult("wasmtime", args);
        if (result.success) return;
        lastResult = result;
      }
      assert(
        false,
        `wasmtime could not invoke abi_version:\n${
          lastResult ? lastResult.stdout + lastResult.stderr : ""
        }`,
      );
    } finally {
      await Deno.remove(dir, { recursive: true });
    }
  },
});

Deno.test("Wasm runtime reset keeps repeated parses within high-water memory", async () => {
  const result = compile(
    `
    token A = /a/ ;
    skip WS = /[ \\t\\r\\n]+/ ;
    module = A* ;
  `,
    { targets: ["wasm"], wasm: legacySpecializedWasm },
  );
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    const mod = await import(`file://${dir}/wasm/mod.ts`);
    const large = `${"a ".repeat(10_000)}`;
    assertEquals(mod.parse(large).ok, true);
    const highWaterBytes = mod.memory.buffer.byteLength;

    mod.reset();
    for (let index = 0; index < 10_000; index++) {
      assertEquals(mod.parse("a").ok, true);
    }
    assertEquals(mod.memory.buffer.byteLength, highWaterBytes);
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("Wasm parser instances own memory, reset, and disposal state", async () => {
  const result = compile(
    `
    token A = /a/ ;
    skip WS = /[ \\t\\r\\n]+/ ;
    module = items:item* ;
    item = A ;
  `,
    { targets: ["wasm"], wasm: legacySpecializedWasm },
  );
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    const mod = await import(`file://${dir}/wasm/mod.ts`);
    const first = mod.createParser();
    const second = mod.createParser();

    assertEquals(first.parse("a a").ok, true);
    const firstHighWaterBytes = mod.memory.buffer.byteLength;
    assertEquals(second.parse("a").ok, true);
    const secondHighWaterBytes = mod.memory.buffer.byteLength;
    assertEquals(first.parse("a a a").ok, true);
    assert(firstHighWaterBytes > 0);
    assert(secondHighWaterBytes > 0);

    first.reset();
    assertEquals(first.parse("a").ok, true);
    assertEquals(second.parse("a a").ok, true);

    first.dispose();
    assertThrowsIncludes(
      () => first.parse("a"),
      "Wasm parser instance is disposed",
    );
    assertEquals(second.parse("a").ok, true);
    second.dispose();
    assertThrowsIncludes(
      () => second.lex("a"),
      "Wasm parser instance is disposed",
    );
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("Wasm parser instances run concurrently in workers", async () => {
  const result = compile(
    `
    token A = /a/ ;
    skip WS = /[ \\t\\r\\n]+/ ;
    module = items:item* ;
    item = A ;
  `,
    { targets: ["wasm"], wasm: legacySpecializedWasm },
  );
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  const workers: Worker[] = [];
  try {
    await applyBundle(result.bundle, { root: dir });
    await Deno.writeTextFile(
      `${dir}/wasm_worker.ts`,
      `
        import { createParser } from "./wasm/mod.ts";

        const parser = createParser();
        const sibling = createParser();
        for (let index = 0; index < 250; index++) {
          const source = "a ".repeat((index % 7) + 1);
          const parsed = parser.parse(source);
          if (!parsed.ok) {
            throw new Error(\`worker parse failed at iteration \${index}\`);
          }
          parser.reset();

          const siblingParsed = sibling.parse(index % 2 === 0 ? "a" : "a a");
          if (!siblingParsed.ok) {
            throw new Error(\`worker sibling parse failed at iteration \${index}\`);
          }
          sibling.reset();
        }
        parser.dispose();
        sibling.dispose();
        self.postMessage({ ok: true });
      `,
    );

    const runWorker = (index: number): Promise<unknown> => {
      const worker = new Worker(new URL(`file://${dir}/wasm_worker.ts`), {
        type: "module",
        name: `wasm-parser-${index}`,
      });
      workers.push(worker);
      return new Promise((resolve, reject) => {
        worker.onmessage = (event) => {
          worker.terminate();
          resolve(event.data);
        };
        worker.onerror = (event) => {
          worker.terminate();
          reject(new Error(event.message));
        };
        worker.onmessageerror = () => {
          worker.terminate();
          reject(new Error("worker message could not be deserialized"));
        };
      });
    };

    const results = await Promise.all(
      Array.from({ length: 4 }, (_, index) => runWorker(index)),
    );
    assert(results.every((result) => (result as { ok?: unknown }).ok === true));
  } finally {
    for (const worker of workers) worker.terminate();
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("Wasm parser instances enforce structured resource limits", async () => {
  const result = compile(
    `
    token A = /a/ ;
    skip WS = /[ \\t\\r\\n]+/ ;
    module = items:item* ;
    item = A ;
  `,
    { targets: ["wasm"], wasm: legacySpecializedWasm },
  );
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    const mod = await import(`file://${dir}/wasm/mod.ts`);
    const runtime = await import(`file://${dir}/wasm/wasm.ts`);

    const inputLimited = mod.createParser({ limits: { maxInputUnits: 1 } });
    assertWasmLimit(
      () => inputLimited.lex("aa"),
      mod.WasmResourceLimitError,
      "INPUT_LIMIT_EXCEEDED",
    );

    const tokenLimited = mod.createParser({ limits: { maxTokens: 1 } });
    assertWasmLimit(
      () => tokenLimited.parse("a a"),
      mod.WasmResourceLimitError,
      "TOKEN_LIMIT_EXCEEDED",
    );

    const traceLimited = mod.createParser({ limits: { maxTraceActions: 1 } });
    assertWasmLimit(
      () => traceLimited.parse("a"),
      mod.WasmResourceLimitError,
      "TRACE_LIMIT_EXCEEDED",
    );

    const branchLimited = mod.createParser({
      limits: { maxExploredBranches: 1 },
    });
    assertWasmLimit(
      () => branchLimited.parse("a", { maxExploredBranches: 2 }),
      mod.WasmResourceLimitError,
      "PARSER_BRANCH_LIMIT_EXCEEDED",
    );

    const stackLimited = mod.createParser({ limits: { maxParserStack: 2 } });
    assertWasmLimit(
      () => stackLimited.parse("a a"),
      mod.WasmResourceLimitError,
      "PARSER_STACK_LIMIT_EXCEEDED",
    );

    const branchCellLimited = mod.createParser({
      limits: { maxBranchCells: 2 },
    });
    assertWasmLimit(
      () => branchCellLimited.parse("a a", { maxQueuedBranches: 2 }),
      mod.WasmResourceLimitError,
      "PARSER_BRANCH_LIMIT_EXCEEDED",
    );

    const diagnosticLimited = mod.createParser({
      limits: { maxDiagnostics: 1 },
    });
    assertWasmLimit(
      () => diagnosticLimited.lex("??"),
      mod.WasmResourceLimitError,
      "DIAGNOSTIC_LIMIT_EXCEEDED",
    );
    assertWasmLimit(
      () => diagnosticLimited.parse("??"),
      mod.WasmResourceLimitError,
      "DIAGNOSTIC_LIMIT_EXCEEDED",
    );

    const memoryLimited = runtime.createWasmParserInstance({
      limits: { maxMemoryPages: 1 },
    });
    assertWasmLimit(
      () => memoryLimited.writeSource("a".repeat(40_000)),
      runtime.WasmResourceLimitError,
      "MEMORY_LIMIT_EXCEEDED",
    );

    const cstNodeLimited = mod.createParser({ limits: { maxCstNodes: 1 } });
    assertWasmLimit(
      () => cstNodeLimited.parse("a a"),
      mod.WasmResourceLimitError,
      "CST_NODE_LIMIT_EXCEEDED",
    );

    const cstChildLimited = mod.createParser({
      limits: { maxCstChildren: 1 },
    });
    assertWasmLimit(
      () => cstChildLimited.parse("a a"),
      mod.WasmResourceLimitError,
      "CST_NODE_LIMIT_EXCEEDED",
    );

    assertThrowsIncludes(
      () => mod.createParser({ limits: { maxInputUnits: 0 } }),
      "maxInputUnits must be a positive integer",
    );
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("Wasm parser reports trailing input through trace replay", async () => {
  const result = compile(`module = "a" ;`, {
    targets: ["wasm"],
    wasm: legacySpecializedWasm,
  });
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    const mod = await import(`file://${dir}/wasm/mod.ts`);

    const parsed = mod.parse("aa");
    assertEquals(parsed.ok, false);
    assertEquals(parsed.diagnostics[0].code, "PARSE_TRAILING_INPUT");
    assertEquals(
      parsed.diagnostics[0].runtimeCode,
      mod.parserDiagnosticCodeParseTrailingInput,
    );
    assertEquals(
      Number.isInteger(parsed.diagnostics[0].runtimeDetail),
      true,
    );
    assertEquals(parsed.diagnostics[0].runtimeDetailKind, "parser-state");
    assertEquals(
      parsed.diagnostics[0].runtimeDetailKindId,
      mod.parserDiagnosticDetailKindParserState,
    );
    assertEquals(parsed.diagnostics[0].found, JSON.stringify("a"));
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("Wasm runtime validates parse trace input bounds", async () => {
  const result = compile(`module = "a" ;`, {
    targets: ["wasm"],
    wasm: legacySpecializedWasm,
  });
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    const runtime = await import(`file://${dir}/wasm/wasm.ts`);

    assertThrowsIncludes(
      () => runtime.createParseTraceInput(0),
      "terminalCapacity must be a positive integer",
    );
    const input = runtime.createParseTraceInput(1);
    input.terminals[0] = 0;
    const unexpected = runtime.parseTrace(input, 1);
    assertEquals(unexpected.ok, false);
    assertEquals(unexpected.failureKind, "unexpected");
    assertEquals(unexpected.statusKind, runtime.wasmTraceStatusUnexpected);
    assertEquals(unexpected.internal, false);
    assertEquals(unexpected.limit, false);
    assertThrowsIncludes(
      () => runtime.parseTrace(input, 2),
      "terminalCount exceeds parse input terminalCapacity",
    );
    assertThrowsIncludes(
      () => runtime.parseTrace(input, -1),
      "terminalCount must be a non-negative integer",
    );
    assertThrowsIncludes(
      () => runtime.parseTrace(input, 1, { maxBranches: 0 }),
      "maxBranches must be a positive integer",
    );
    assertThrowsIncludes(
      () => runtime.parseTrace(input, 1, { maxQueuedBranches: 0 }),
      "maxQueuedBranches must be a positive integer",
    );
    assertThrowsIncludes(
      () => runtime.parseTrace(input, 1, { maxTraceActions: 0 }),
      "maxTraceActions must be a positive integer",
    );
    assertThrowsIncludes(
      () => runtime.parseTrace(input, 1, { ambiguityMode: 2 }),
      "ambiguityMode must be 0 or 1",
    );
    assertThrowsIncludes(
      () =>
        runtime.parseTrace({
          terminals: new Int32Array(0),
          terminalCapacity: 1,
        }, 0),
      "ParseTraceInput is not owned by this adapter",
    );
    const tamperedInput = runtime.createParseTraceInput(1);
    tamperedInput.terminals = new Int32Array(0);
    assertThrowsIncludes(
      () => runtime.parseTrace(tamperedInput, 0),
      "terminals length must cover parse input terminalCapacity",
    );
    const staleInput = runtime.createParseTraceInput(1);
    runtime.reset();
    assertThrowsIncludes(
      () => runtime.parseTrace(staleInput, 0),
      "ParseTraceInput is stale; call createParseTraceInput() again",
    );
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("Wasm source buffers are adapter-owned capabilities", async () => {
  const result = compile(`module = "a" ;`, {
    targets: ["wasm"],
    wasm: legacySpecializedWasm,
  });
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    const runtime = await import(`file://${dir}/wasm/wasm.ts`);

    const buffer = runtime.writeSource("a");
    assertEquals(runtime.lexOne(buffer, 0)?.end, 1);
    assertEquals(runtime.lexAll(buffer).length, 3);
    assertThrowsIncludes(
      () => runtime.lexOne({ ...buffer }, 0),
      "WasmSourceBuffer is not owned by this adapter",
    );
    assertThrowsIncludes(
      () => runtime.lexAll({ ...buffer }),
      "WasmSourceBuffer is not owned by this adapter",
    );

    runtime.writeSource("aa");
    assertThrowsIncludes(
      () => runtime.lexOne(buffer, 0),
      "WasmSourceBuffer is stale; call writeSource() again",
    );

    const resetBuffer = runtime.writeSource("a");
    assertEquals(runtime.lexOne(resetBuffer, 0)?.end, 1);
    assertThrowsIncludes(
      () => runtime.lexOne(resetBuffer, 2),
      "offset exceeds source buffer length",
    );
    runtime.reset();
    assertThrowsIncludes(
      () => runtime.lexAll(resetBuffer),
      "WasmSourceBuffer is stale; call writeSource() again",
    );

    const nextBuffer = runtime.writeSource("a");
    assertEquals(runtime.lexOne(nextBuffer, 0)?.end, 1);
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("Wasm target generates deterministic runtime bytes", () => {
  const source = `
    token ID = /[A-Za-z_][A-Za-z0-9_]*/ ;
    skip WS = /[ \\t\\r\\n]+/ ;
    module = "let" name:ID ";" ;
  `;
  const first = compile(source, {
    targets: ["wasm"],
    wasm: legacySpecializedWasm,
  });
  const second = compile(source, {
    targets: ["wasm"],
    wasm: legacySpecializedWasm,
  });
  assertEquals(first.diagnostics.length, 0);
  assertEquals(second.diagnostics.length, 0);
  assert(first.bundle);
  assert(second.bundle);

  const firstWasmSource = first.bundle.files.find((file) =>
    file.path === "wasm/wasm.ts"
  )?.content;
  const secondWasmSource = second.bundle.files.find((file) =>
    file.path === "wasm/wasm.ts"
  )?.content;
  const firstAbiSource = first.bundle.files.find((file) =>
    file.path === "wasm/abi.json"
  )?.content;
  const secondAbiSource = second.bundle.files.find((file) =>
    file.path === "wasm/abi.json"
  )?.content;
  assertEquals(firstWasmSource, secondWasmSource);
  assertEquals(firstAbiSource, secondAbiSource);
});

Deno.test("Wasm ABI documentation covers generated descriptor contract", async () => {
  const documentation = await Deno.readTextFile("docs/wasm-abi.md");
  for (
    const required of [
      "baba-wasm-abi",
      "javascript-hosted-core-wasm",
      "abi_version() -> i32",
      "plan_version() -> i32",
      "semantics_version() -> i32",
      "source_encoding() -> i32",
      "span_unit() -> i32",
      "host_ownership_model() -> i32",
      "result_lifetime_model() -> i32",
      "UTF-16 code units",
      "WasmSourceBuffer",
      "ParseTraceInput",
      "createParser()",
      "createParserAsync()",
      "dispose()",
      "memory.grow()",
      "PARSER_BRANCH_LIMIT",
      "PARSER_TRACE_LIMIT",
      "wasm/abi.json",
    ]
  ) {
    assertIncludes(documentation, required);
  }
  assertNotIncludes(documentation, "planned separately from this core ABI");
});

Deno.test("Wasm lexer preserves UTF-16 offsets for non-BMP literals", async () => {
  const result = compile(`module = face:"😀" ;`, {
    targets: ["wasm"],
    wasm: legacySpecializedWasm,
  });
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    const mod = await import(`file://${dir}/wasm/mod.ts`);
    const parsed = mod.parse("😀");
    assertEquals(parsed.ok, true);
    assertEquals(parsed.root.span.end, 2);
    assertEquals(parsed.root.fields.face.span.end, 2);
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("Wasm spans use UTF-16 units for edge-case source text", async () => {
  const cases = [
    {
      name: "empty input",
      grammar: `module = ;`,
      source: "",
      end: 0,
      position: { line: 1, column: 1 },
    },
    {
      name: "BMP literal",
      grammar: null,
      source: "A",
      end: 1,
      position: { line: 1, column: 2 },
    },
    {
      name: "combining mark",
      grammar: null,
      source: "e\u0301",
      end: 2,
      position: { line: 1, column: 3 },
    },
    {
      name: "CRLF",
      grammar: null,
      source: "\r\n",
      end: 2,
      position: { line: 2, column: 1 },
    },
    {
      name: "NUL",
      grammar: null,
      source: "\u0000",
      end: 1,
      position: { line: 1, column: 2 },
    },
    {
      name: "line separator",
      grammar: null,
      source: "\u2028",
      end: 1,
      position: { line: 1, column: 2 },
    },
    {
      name: "paragraph separator",
      grammar: null,
      source: "\u2029",
      end: 1,
      position: { line: 1, column: 2 },
    },
  ] as const;

  for (const entry of cases) {
    const grammar = entry.grammar ?? `module = value:"${entry.source}" ;`;
    const result = compile(grammar, {
      targets: ["wasm"],
      wasm: legacySpecializedWasm,
    });
    assertEquals(
      result.diagnostics.filter((diagnostic) => diagnostic.severity === "error")
        .length,
      0,
      entry.name,
    );
    assert(result.bundle, entry.name);

    const dir = await Deno.makeTempDir();
    try {
      await applyBundle(result.bundle, { root: dir });
      const mod = await import(`file://${dir}/wasm/mod.ts`);
      const parsed = mod.parse(entry.source);
      assertEquals(parsed.ok, true, entry.name);
      assertEquals(parsed.root.span.end, entry.end, entry.name);
      assertEquals(parsed.root.tokenRange.end, entry.source === "" ? 0 : 1);
      assertEquals(
        JSON.stringify(mod.positionAt(entry.source, entry.end)),
        JSON.stringify(entry.position),
        entry.name,
      );
      if (entry.source !== "") {
        const value = parsed.root.fields.value;
        assertEquals(
          JSON.stringify(value.span),
          JSON.stringify({ start: 0, end: entry.end }),
          entry.name,
        );
        assertEquals(value.text, entry.source, entry.name);
        assertEquals(
          JSON.stringify(parsed.tokens[0].span),
          JSON.stringify({ start: 0, end: entry.end }),
          entry.name,
        );
      }
    } finally {
      await Deno.remove(dir, { recursive: true });
    }
  }
});

Deno.test("Wasm parse fast path handles large parser buffers", async () => {
  const source = `
    token INT = /[0-9]+/ ;
    skip WS = /[ \\t\\r\\n]+/ ;

    module = expr ;
    expr = additive ;
    additive = first:multiplicative rest:(("+" | "-") multiplicative)* ;
    multiplicative = first:primary rest:(("*" | "/") primary)* ;
    primary = INT | "(" expr ")" ;
  `;
  const result = compile(source, {
    targets: ["wasm"],
    wasm: legacySpecializedWasm,
  });
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    const mod = await import(`file://${dir}/wasm/mod.ts`);
    const parsed = mod.parse(expressionSource(900));
    assertEquals(parsed.ok, true);
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

Deno.test("CLI generates Wasm target with custom directory", async () => {
  const dir = await Deno.makeTempDir();
  try {
    const grammarPath = `${dir}/grammar.ebnf`;
    await Deno.writeTextFile(
      grammarPath,
      `
        token ident = /[a-z]+/ ;
        skip whitespace = /[ \\t\\n]+/ ;
        module = "fn" ident ;
      `,
    );

    let logs: string[] = [];
    await captureConsoleError(async () => {
      logs = await captureConsoleLog(() =>
        main([
          "check",
          grammarPath,
          "--target",
          "wasm",
          "--wasm-dir",
          "runtime",
          "--list-files",
        ])
      );
    });
    assertIncludes(logs.join("\n"), "runtime/mod.ts");
    assertIncludes(logs.join("\n"), "runtime/plan.ts");
    assertIncludes(logs.join("\n"), "runtime/abi.json");
    assertNotIncludes(logs.join("\n"), "runtime/wasm.ts");
    assertNotIncludes(logs.join("\n"), "runtime/parser.wasm");

    let externalLogs: string[] = [];
    await captureConsoleError(async () => {
      externalLogs = await captureConsoleLog(() =>
        main([
          "check",
          grammarPath,
          "--target",
          "wasm",
          "--wasm-dir",
          "runtime",
          "--wasm-packaging",
          "external-binary",
          "--list-files",
        ])
      );
    });
    assertIncludes(externalLogs.join("\n"), "runtime/parser.wasm");
    assertIncludes(externalLogs.join("\n"), "runtime/manifest.json");

    const outDir = `${dir}/out`;
    await captureConsoleError(() =>
      main([
        "generate",
        grammarPath,
        "--target",
        "wasm",
        "--wasm-dir",
        "runtime",
        "--wasm-packaging",
        "embedded-typescript",
        "--discard-trivia",
        "--out",
        outDir,
      ])
    );
    assertIncludes(
      await Deno.readTextFile(`${outDir}/runtime/lexer.ts`),
      "const DEFAULT_PRESERVE_TRIVIA = false",
    );
    await denoCheck(`${outDir}/runtime/mod.ts`);

    const externalOutDir = `${dir}/external-out`;
    await captureConsoleError(() =>
      main([
        "generate",
        grammarPath,
        "--target",
        "wasm",
        "--wasm-dir",
        "runtime",
        "--wasm-packaging",
        "external-binary",
        "--wasm-stats",
        "--wasm-generated-byte-limit",
        "1000000",
        "--out",
        externalOutDir,
      ])
    );
    const bytes = await Deno.readFile(`${externalOutDir}/runtime/parser.wasm`);
    assert(WebAssembly.validate(arrayBuffer(bytes)));
    const manifest = JSON.parse(
      await Deno.readTextFile(`${externalOutDir}/runtime/manifest.json`),
    );
    assertEquals(manifest.module, "parser.wasm");
  } finally {
    await Deno.remove(dir, { recursive: true });
  }
});

function expressionSource(count: number): string {
  const parts: string[] = [];
  for (let index = 1; index <= count; index++) {
    if (index > 1) parts.push(index % 2 === 0 ? " + " : " - ");
    parts.push(String(index), index % 3 === 0 ? " * 2" : "");
  }
  return parts.join("");
}

interface CommandResult {
  readonly success: boolean;
  readonly stdout: string;
  readonly stderr: string;
}

async function commandAvailable(commandName: string): Promise<boolean> {
  try {
    const result = await new Deno.Command(commandName, {
      args: ["--version"],
      stdout: "null",
      stderr: "null",
    }).output();
    return result.success;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return false;
    throw error;
  }
}

function arrayBuffer(bytes: Uint8Array): ArrayBuffer {
  const copy = new Uint8Array(bytes.byteLength);
  copy.set(bytes);
  return copy.buffer as ArrayBuffer;
}

function assertWasmLimit(
  callback: () => unknown,
  errorClass: new (...args: never[]) => Error,
  code: string,
): void {
  try {
    callback();
  } catch (error) {
    assert(error instanceof errorClass);
    assertEquals((error as { code?: unknown }).code, code);
    return;
  }
  assert(false, `Expected Wasm resource limit ${code}.`);
}

async function runCommandResult(
  commandName: string,
  args: readonly string[],
): Promise<CommandResult> {
  const result = await new Deno.Command(commandName, {
    args: [...args],
    stdout: "piped",
    stderr: "piped",
  }).output();
  const decoder = new TextDecoder();
  return {
    success: result.success,
    stdout: decoder.decode(result.stdout),
    stderr: decoder.decode(result.stderr),
  };
}

async function writeGeneratedCoreWasm(
  source: string,
): Promise<{ readonly dir: string; readonly wasmPath: string }> {
  const result = compile(source, {
    targets: ["wasm"],
    wasm: legacySpecializedWasm,
  });
  assertEquals(result.diagnostics.length, 0);
  assert(result.bundle);

  const dir = await Deno.makeTempDir();
  try {
    await applyBundle(result.bundle, { root: dir });
    const mod = await import(`file://${dir}/wasm/mod.ts`);
    const wasmPath = `${dir}/parser.wasm`;
    await Deno.writeFile(wasmPath, mod.wasmBytes);
    return { dir, wasmPath };
  } catch (error) {
    await Deno.remove(dir, { recursive: true });
    throw error;
  }
}
