import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import type { BnfGrammar } from "../typescript/bnf.ts";

export function emitWasmLexer(
  analyzed: AnalyzedGrammar,
  bnf: BnfGrammar,
  preserveTrivia: boolean,
): string {
  const namedTerminals = new Map(
    bnf.terminals
      .filter((terminal) => terminal.kind === "named")
      .map((terminal) => [terminal.tokenId, terminal.id]),
  );
  const literalTerminals = new Map(
    bnf.terminals
      .filter((terminal) => terminal.kind === "literal")
      .map((terminal) => [terminal.literalId, terminal.id]),
  );
  const namedSpecs = analyzed.tokens
    .filter((token) =>
      token.kind === "skip" ||
      (token.kind === "token" && analyzed.reachableTokens.has(token.id))
    )
    .map((token) => ({
      kind: token.name,
      channel: token.kind === "skip" ? "trivia" : "main",
      terminal: token.kind === "skip" ? -1 : namedTerminals.get(token.id) ?? -1,
    }));
  const literalSpecs = analyzed.literals
    .filter((literal) => analyzed.reachableLiterals.has(literal.id))
    .map((literal) => ({
      literal: literal.value,
      terminal: literalTerminals.get(literal.id) ?? -1,
    }));
  const specs = [
    ...namedSpecs.map((spec) => ({ type: "named", ...spec })),
    ...literalSpecs.map((spec) => ({ type: "literal", ...spec })),
  ];

  return `// Generated by @mewhhaha/baba. Do not edit by hand.
import type {
  LexDiagnostic,
  LexOptions,
  LexResult,
  NamedTokenKind,
  Token,
} from "./syntax.ts";
import {
  createParseTraceInput,
  lexAll,
  writeSource,
  type ParseTraceInput,
} from "./wasm.ts";

const DEFAULT_PRESERVE_TRIVIA = ${JSON.stringify(preserveTrivia)};

const SPECS: readonly (
  | {
    type: "named";
    kind: NamedTokenKind;
    channel: "main" | "trivia";
    terminal: number;
  }
  | { type: "literal"; literal: string; terminal: number }
)[] = ${JSON.stringify(specs, null, 2)} as const;

export function lex(source: string, options: LexOptions = {}): LexResult {
  return lexInternal(source, options, false);
}

export interface WasmParseStream {
  tokens: readonly Token[];
  tokenIndices: readonly number[];
  input: ParseTraceInput;
  terminalCount: number;
}

export function lexForParse(
  source: string,
  options: LexOptions = {},
): LexResult & { parseStream: WasmParseStream } {
  return lexInternal(source, options, true) as LexResult & {
    parseStream: WasmParseStream;
  };
}

function lexInternal(
  source: string,
  options: LexOptions,
  includeParseStream: boolean,
): LexResult & { parseStream?: WasmParseStream } {
  const preserveTrivia = options.preserveTrivia ?? DEFAULT_PRESERVE_TRIVIA;
  const sourceBuffer = writeSource(source);
  const records = lexAll(sourceBuffer);
  const tokens: Token[] = new Array(records.length / 3 + 1);
  let tokenCount = 0;
  const diagnostics: LexDiagnostic[] = [];
  const streamTokens: Token[] = includeParseStream && !preserveTrivia
    ? tokens
    : includeParseStream
    ? new Array(records.length / 3 + 1)
    : [];
  const streamTokenIndices: number[] = includeParseStream
    ? new Array(records.length / 3 + 1)
    : [];
  const duplicateStreamTokens = streamTokens !== tokens;
  let streamTokenCount = 0;
  const parseTerminals = includeParseStream
    ? new Int32Array(records.length / 3 + 1)
    : null;
  let terminalCount = 0;

  for (let index = 0; index < records.length; index += 3) {
    const specIndex = records[index];
    const start = records[index + 1];
    const end = records[index + 2];
    if (specIndex >= 0) {
      const spec = SPECS[specIndex];
      if (spec) {
        if (spec.type === "literal") {
          const token: Token = {
            type: "literal",
            literal: spec.literal as never,
            text: spec.literal as never,
            span: { start, end },
            channel: "main",
          };
          tokens[tokenCount] = token;
          if (includeParseStream) streamTokenIndices[terminalCount] = tokenCount;
          tokenCount++;
          if (includeParseStream) {
            if (duplicateStreamTokens) {
              streamTokens[streamTokenCount] = token;
              streamTokenCount++;
            }
            parseTerminals![terminalCount] = spec.terminal;
            terminalCount++;
          }
        } else {
          if (spec.channel === "trivia") {
            if (preserveTrivia) {
              tokens[tokenCount] = {
                type: "named",
                kind: spec.kind as never,
                text: source.slice(start, end),
                span: { start, end },
                channel: "trivia",
              };
              tokenCount++;
            }
          } else {
            const token: Token = {
              type: "named",
              kind: spec.kind as never,
              text: source.slice(start, end),
              span: { start, end },
              channel: "main",
            };
            tokens[tokenCount] = token;
            if (includeParseStream) streamTokenIndices[terminalCount] = tokenCount;
            tokenCount++;
            if (includeParseStream) {
              if (duplicateStreamTokens) {
                streamTokens[streamTokenCount] = token;
                streamTokenCount++;
              }
              parseTerminals![terminalCount] = spec.terminal;
              terminalCount++;
            }
          }
        }
        continue;
      }
    }

    const text = source.slice(start, end);
    tokens[tokenCount] = {
      type: "error",
      text,
      span: { start, end },
      channel: "error",
    };
    tokenCount++;
    diagnostics.push({
      code: "LEX_UNEXPECTED_CHARACTER",
      message: \`Unexpected character \${JSON.stringify(text)}.\`,
      span: { start, end },
    });
  }

  const eofToken: Token = {
    type: "eof",
    text: "",
    span: { start: source.length, end: source.length },
    channel: "main",
  };
  tokens[tokenCount] = eofToken;
  if (includeParseStream) streamTokenIndices[terminalCount] = tokenCount;
  tokenCount++;
  tokens.length = tokenCount;
  if (includeParseStream) {
    if (duplicateStreamTokens) {
      streamTokens[streamTokenCount] = eofToken;
      streamTokenCount++;
      streamTokens.length = streamTokenCount;
    }
    parseTerminals![terminalCount] = 0;
    terminalCount++;
    streamTokenIndices.length = terminalCount;
    const parseInput = createParseTraceInput(terminalCount);
    parseInput.terminals.set(parseTerminals!.subarray(0, terminalCount));
    return {
      source,
      tokens,
      diagnostics,
      parseStream: {
        tokens: streamTokens,
        tokenIndices: streamTokenIndices,
        input: parseInput,
        terminalCount,
      },
    };
  }
  return { source, tokens, diagnostics };
}
`;
}
