import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import { emitRuntimeLanguageTypeScriptFunction } from "../runtime/language.ts";
import {
  createParserTokenRecordRuntimeProgram,
  RUNTIME_NO_TERMINAL,
  RUNTIME_PUBLIC_TOKEN_ERROR,
  RUNTIME_PUBLIC_TOKEN_LITERAL,
  RUNTIME_PUBLIC_TOKEN_MAIN,
  RUNTIME_PUBLIC_TOKEN_TRIVIA,
} from "../runtime/language_sources.ts";
import type { BnfGrammar } from "../typescript/bnf.ts";

export function emitWasmLexer(
  analyzed: AnalyzedGrammar,
  bnf: BnfGrammar,
  preserveTrivia: boolean,
): string {
  const namedTerminals = new Map(
    bnf.terminals
      .filter((terminal) => terminal.kind === "named")
      .map((terminal) => [terminal.tokenId, terminal.id]),
  );
  const literalTerminals = new Map(
    bnf.terminals
      .filter((terminal) => terminal.kind === "literal")
      .map((terminal) => [terminal.literalId, terminal.id]),
  );
  const namedSpecs = analyzed.tokens
    .filter((token) =>
      token.kind === "skip" ||
      (token.kind === "token" && analyzed.reachableTokens.has(token.id))
    )
    .map((token) => ({
      kind: token.name,
      channel: token.kind === "skip" ? "trivia" : "main",
      terminal: token.kind === "skip" ? -1 : namedTerminals.get(token.id) ?? -1,
    }));
  const literalSpecs = analyzed.literals
    .filter((literal) => analyzed.reachableLiterals.has(literal.id))
    .map((literal) => ({
      literal: literal.value,
      terminal: literalTerminals.get(literal.id) ?? -1,
    }));
  const specs = [
    ...namedSpecs.map((spec) => ({ type: "named", ...spec })),
    ...literalSpecs.map((spec) => ({ type: "literal", ...spec })),
  ];
  const runtimeProgram = createParserTokenRecordRuntimeProgram();

  return `// Generated by @mewhhaha/baba. Do not edit by hand.
import type {
  LexDiagnostic,
  LexOptions,
  LexResult,
  NamedTokenKind,
  Token,
} from "./syntax.ts";
import {
  createParseTraceInput,
  lexAll,
  writeSource,
  type ParseTraceInput,
} from "./wasm.ts";

const DEFAULT_PRESERVE_TRIVIA = ${JSON.stringify(preserveTrivia)};
const NO_TERMINAL = ${RUNTIME_NO_TERMINAL};
const PUBLIC_TOKEN_LITERAL = ${RUNTIME_PUBLIC_TOKEN_LITERAL};
const PUBLIC_TOKEN_MAIN = ${RUNTIME_PUBLIC_TOKEN_MAIN};
const PUBLIC_TOKEN_TRIVIA = ${RUNTIME_PUBLIC_TOKEN_TRIVIA};
const PUBLIC_TOKEN_ERROR = ${RUNTIME_PUBLIC_TOKEN_ERROR};

const SPECS: readonly (
  | {
    type: "named";
    kind: NamedTokenKind;
    channel: "main" | "trivia";
    terminal: number;
  }
  | { type: "literal"; literal: string; terminal: number }
)[] = ${JSON.stringify(specs, null, 2)} as const;

interface RuntimeTerminalToken {
  __babaTerminal?: number;
}

${emitRuntimeLanguageTypeScriptFunction(runtimeProgram).trimEnd()}

export function lex(source: string, options: LexOptions = {}): LexResult {
  return lexInternal(source, options, false);
}

export interface WasmParseStream {
  tokens: readonly Token[];
  tokenIndices: readonly number[];
  input: ParseTraceInput;
  terminalCount: number;
}

export function lexForParse(
  source: string,
  options: LexOptions = {},
): LexResult & { parseStream: WasmParseStream } {
  return lexInternal(source, options, true) as LexResult & {
    parseStream: WasmParseStream;
  };
}

function lexInternal(
  source: string,
  options: LexOptions,
  includeParseStream: boolean,
): LexResult & { parseStream?: WasmParseStream } {
  runtimeArenaReset();
  const preserveTrivia = options.preserveTrivia ?? DEFAULT_PRESERVE_TRIVIA;
  const sourceBuffer = writeSource(source);
  const records = lexAll(sourceBuffer);
  const tokens: Token[] = new Array(records.length / 3 + 1);
  let tokenCount = 0;
  const diagnostics: LexDiagnostic[] = [];
  const streamTokens: Token[] = includeParseStream && !preserveTrivia
    ? tokens
    : includeParseStream
    ? new Array(records.length / 3 + 1)
    : [];
  const streamTokenIndices: number[] = includeParseStream
    ? new Array(records.length / 3 + 1)
    : [];
  const duplicateStreamTokens = streamTokens !== tokens;
  let streamTokenCount = 0;
  const parseTerminals = includeParseStream
    ? new Int32Array(records.length / 3 + 1)
    : null;
  let terminalCount = 0;

  for (let index = 0; index < records.length; index += 3) {
    const specIndex = records[index];
    const start = records[index + 1];
    const end = records[index + 2];
    if (specIndex >= 0) {
      const spec = SPECS[specIndex];
      if (spec) {
        const tokenClass = spec.type === "literal"
          ? PUBLIC_TOKEN_LITERAL
          : spec.channel === "trivia"
          ? PUBLIC_TOKEN_TRIVIA
          : PUBLIC_TOKEN_MAIN;
        if (tokenClass !== PUBLIC_TOKEN_TRIVIA || preserveTrivia) {
          const handle = parserTokenNew(
            tokenClass,
            specIndex,
            spec.terminal < 0 ? NO_TERMINAL : spec.terminal,
            start,
            end,
          );
          const token = materializeToken(source, handle);
          tokens[tokenCount] = token;
          if (tokenClass !== PUBLIC_TOKEN_TRIVIA) {
            if (includeParseStream) streamTokenIndices[terminalCount] = tokenCount;
            if (includeParseStream) {
              if (duplicateStreamTokens) {
                streamTokens[streamTokenCount] = token;
                streamTokenCount++;
              }
              parseTerminals![terminalCount] = spec.terminal;
              terminalCount++;
            }
          }
          tokenCount++;
        }
        continue;
      }
    }

    const handle = parserTokenNew(
      PUBLIC_TOKEN_ERROR,
      0,
      NO_TERMINAL,
      start,
      end,
    );
    const token = materializeToken(source, handle);
    tokens[tokenCount] = token;
    tokenCount++;
    diagnostics.push({
      code: "LEX_UNEXPECTED_CHARACTER",
      message: \`Unexpected character \${JSON.stringify(token.text)}.\`,
      span: token.span,
    });
  }

  const eofToken: Token = {
    type: "eof",
    text: "",
    span: { start: source.length, end: source.length },
    channel: "main",
  };
  tokens[tokenCount] = eofToken;
  if (includeParseStream) streamTokenIndices[terminalCount] = tokenCount;
  tokenCount++;
  tokens.length = tokenCount;
  if (includeParseStream) {
    if (duplicateStreamTokens) {
      streamTokens[streamTokenCount] = eofToken;
      streamTokenCount++;
      streamTokens.length = streamTokenCount;
    }
    parseTerminals![terminalCount] = 0;
    terminalCount++;
    streamTokenIndices.length = terminalCount;
    const parseInput = createParseTraceInput(terminalCount);
    parseInput.terminals.set(parseTerminals!.subarray(0, terminalCount));
    return {
      source,
      tokens,
      diagnostics,
      parseStream: {
        tokens: streamTokens,
        tokenIndices: streamTokenIndices,
        input: parseInput,
        terminalCount,
      },
    };
  }
  return { source, tokens, diagnostics };
}

function materializeToken(source: string, handle: number): Token {
  const tokenClass = parserTokenClass(handle);
  const payload = parserTokenPayload(handle);
  const span = {
    start: parserTokenSpanStart(handle),
    end: parserTokenSpanEnd(handle),
  };
  const terminal = parserTokenTerminal(handle);
  const runtimeTerminal: RuntimeTerminalToken = {
    __babaTerminal: terminal === NO_TERMINAL ? -1 : terminal,
  };

  if (tokenClass === PUBLIC_TOKEN_LITERAL) {
    const spec = SPECS[payload];
    if (!spec || spec.type !== "literal") {
      throw new Error("Wasm lexer runtime emitted an invalid literal token.");
    }
    return {
      type: "literal",
      literal: spec.literal as never,
      text: spec.literal as never,
      span,
      channel: "main",
      ...runtimeTerminal,
    } as Token & RuntimeTerminalToken;
  }
  if (tokenClass === PUBLIC_TOKEN_MAIN || tokenClass === PUBLIC_TOKEN_TRIVIA) {
    const spec = SPECS[payload];
    if (!spec || spec.type !== "named") {
      throw new Error("Wasm lexer runtime emitted an invalid named token.");
    }
    return {
      type: "named",
      kind: spec.kind as never,
      text: source.slice(span.start, span.end),
      span,
      channel: tokenClass === PUBLIC_TOKEN_TRIVIA ? "trivia" : "main",
      ...runtimeTerminal,
    } as Token & RuntimeTerminalToken;
  }
  if (tokenClass === PUBLIC_TOKEN_ERROR) {
    return {
      type: "error",
      text: source.slice(span.start, span.end),
      span,
      channel: "error",
    };
  }
  throw new Error("Wasm lexer runtime emitted an unknown public token class.");
}
`;
}
