import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import { emitRuntimeLanguageTypeScriptFunction } from "../runtime/language.ts";
import {
  createParserTokenRecordRuntimeProgram,
  RUNTIME_NO_TERMINAL,
  RUNTIME_PUBLIC_TOKEN_EOF,
  RUNTIME_PUBLIC_TOKEN_ERROR,
  RUNTIME_PUBLIC_TOKEN_LITERAL,
  RUNTIME_PUBLIC_TOKEN_MAIN,
  RUNTIME_PUBLIC_TOKEN_TRIVIA,
} from "../runtime/language_sources.ts";
import { emitPublicLexDiagnosticMaterializer } from "../runtime/public_lex_diagnostic_materializer.ts";
import { emitPublicLexResultMaterializer } from "../runtime/public_lex_result_materializer.ts";
import { emitPublicSourceTextBoundary } from "../runtime/public_source_text.ts";
import { emitPublicTokenMaterializer } from "../runtime/public_token_materializer.ts";
import type { BnfGrammar } from "../typescript/bnf.ts";

export function emitWasmLexer(
  analyzed: AnalyzedGrammar,
  bnf: BnfGrammar,
  preserveTrivia: boolean,
): string {
  const namedTerminals = new Map(
    bnf.terminals
      .filter((terminal) => terminal.kind === "named")
      .map((terminal) => [terminal.tokenId, terminal.id]),
  );
  const literalTerminals = new Map(
    bnf.terminals
      .filter((terminal) => terminal.kind === "literal")
      .map((terminal) => [terminal.literalId, terminal.id]),
  );
  const namedSpecs = analyzed.tokens
    .filter((token) =>
      token.kind === "skip" ||
      (token.kind === "token" && analyzed.reachableTokens.has(token.id))
    )
    .map((token) => ({
      kind: token.name,
      channel: token.kind === "skip" ? "trivia" : "main",
      terminal: token.kind === "skip" ? -1 : namedTerminals.get(token.id) ?? -1,
    }));
  const literalSpecs = analyzed.literals
    .filter((literal) => analyzed.reachableLiterals.has(literal.id))
    .map((literal) => ({
      literal: literal.value,
      terminal: literalTerminals.get(literal.id) ?? -1,
    }));
  const runtimeProgram = createParserTokenRecordRuntimeProgram();

  return `// Generated by @mewhhaha/baba. Do not edit by hand.
import type {
  LexDiagnostic,
  LexOptions,
  LexResult,
  NamedTokenKind,
  Span,
  Token,
} from "./syntax.ts";
import {
  createParseTraceInput,
  lexAll,
  writeSource,
  type ParseTraceInput,
} from "./wasm.ts";

const DEFAULT_PRESERVE_TRIVIA = ${JSON.stringify(preserveTrivia)};
const NO_TERMINAL = ${RUNTIME_NO_TERMINAL};
const PUBLIC_TOKEN_LITERAL = ${RUNTIME_PUBLIC_TOKEN_LITERAL};
const PUBLIC_TOKEN_MAIN = ${RUNTIME_PUBLIC_TOKEN_MAIN};
const PUBLIC_TOKEN_TRIVIA = ${RUNTIME_PUBLIC_TOKEN_TRIVIA};
const PUBLIC_TOKEN_ERROR = ${RUNTIME_PUBLIC_TOKEN_ERROR};
const PUBLIC_TOKEN_EOF = ${RUNTIME_PUBLIC_TOKEN_EOF};

const NAMED_SPECS: readonly {
  kind: NamedTokenKind;
  channel: "main" | "trivia";
  terminal: number;
}[] = ${JSON.stringify(namedSpecs, null, 2)} as const;

const LITERAL_SPECS: readonly {
  literal: string;
  terminal: number;
}[] = ${JSON.stringify(literalSpecs, null, 2)} as const;

${emitRuntimeLanguageTypeScriptFunction(runtimeProgram).trimEnd()}
${emitPublicSourceTextBoundary()}
${emitPublicTokenMaterializer({ label: "Wasm lexer" })}
${emitPublicLexDiagnosticMaterializer()}
${emitPublicLexResultMaterializer()}

export function lex(source: string, options: LexOptions = {}): LexResult {
  return lexInternal(source, options, false);
}

export interface WasmParseStream {
  tokens: readonly Token[];
  tokenIndices: readonly number[];
  input: ParseTraceInput;
  terminalCount: number;
}

export function lexForParse(
  source: string,
  options: LexOptions = {},
): LexResult & { parseStream: WasmParseStream } {
  return lexInternal(source, options, true) as LexResult & {
    parseStream: WasmParseStream;
  };
}

function lexInternal(
  source: string,
  options: LexOptions,
  includeParseStream: boolean,
): LexResult & { parseStream?: WasmParseStream } {
  runtimeArenaReset();
  const preserveTrivia = options.preserveTrivia ?? DEFAULT_PRESERVE_TRIVIA;
  const sourceBuffer = writeSource(source);
  const records = lexAll(sourceBuffer);
  const tokens: Token[] = new Array(records.length / 3 + 1);
  let tokenCount = 0;
  const diagnostics: LexDiagnostic[] = [];
  const streamTokens: Token[] = includeParseStream && !preserveTrivia
    ? tokens
    : includeParseStream
    ? new Array(records.length / 3 + 1)
    : [];
  const streamTokenIndices: number[] = includeParseStream
    ? new Array(records.length / 3 + 1)
    : [];
  const duplicateStreamTokens = streamTokens !== tokens;
  let streamTokenCount = 0;
  const parseTerminals = includeParseStream
    ? new Int32Array(records.length / 3 + 1)
    : null;
  let terminalCount = 0;

  for (let index = 0; index < records.length; index += 3) {
    const specIndex = records[index];
    const start = records[index + 1];
    const end = records[index + 2];
    if (specIndex >= 0) {
      let tokenClass = PUBLIC_TOKEN_ERROR;
      let payload = 0;
      let terminal = NO_TERMINAL;
      let foundSpec = false;
      if (specIndex < NAMED_SPECS.length) {
        const spec = NAMED_SPECS[specIndex];
        if (spec) {
          tokenClass = spec.channel === "trivia"
            ? PUBLIC_TOKEN_TRIVIA
            : PUBLIC_TOKEN_MAIN;
          payload = specIndex;
          terminal = spec.terminal;
          foundSpec = true;
        }
      } else {
        const literalIndex = specIndex - NAMED_SPECS.length;
        const spec = LITERAL_SPECS[literalIndex];
        if (spec) {
          tokenClass = PUBLIC_TOKEN_LITERAL;
          payload = literalIndex;
          terminal = spec.terminal;
          foundSpec = true;
        }
      }
      if (foundSpec) {
        if (tokenClass !== PUBLIC_TOKEN_TRIVIA || preserveTrivia) {
          const handle = parserTokenNew(
            tokenClass,
            payload,
            terminal < 0 ? NO_TERMINAL : terminal,
            start,
            end,
          );
          const token = materializeToken(source, handle);
          tokens[tokenCount] = token;
          if (tokenClass !== PUBLIC_TOKEN_TRIVIA) {
            if (includeParseStream) streamTokenIndices[terminalCount] = tokenCount;
            if (includeParseStream) {
              if (duplicateStreamTokens) {
                streamTokens[streamTokenCount] = token;
                streamTokenCount++;
              }
              parseTerminals![terminalCount] = terminal;
              terminalCount++;
            }
          }
          tokenCount++;
        }
        continue;
      }
    }

    const handle = parserTokenNew(
      PUBLIC_TOKEN_ERROR,
      0,
      NO_TERMINAL,
      start,
      end,
    );
    const token = materializeToken(source, handle);
    tokens[tokenCount] = token;
    tokenCount++;
    diagnostics.push(lexUnexpectedCharacterDiagnostic(token));
  }

  const eofHandle = parserTokenNew(
    PUBLIC_TOKEN_EOF,
    0,
    NO_TERMINAL,
    source.length,
    source.length,
  );
  const eofToken = materializeToken(source, eofHandle);
  tokens[tokenCount] = eofToken;
  if (includeParseStream) streamTokenIndices[terminalCount] = tokenCount;
  tokenCount++;
  tokens.length = tokenCount;
  if (includeParseStream) {
    if (duplicateStreamTokens) {
      streamTokens[streamTokenCount] = eofToken;
      streamTokenCount++;
      streamTokens.length = streamTokenCount;
    }
    parseTerminals![terminalCount] = 0;
    terminalCount++;
    streamTokenIndices.length = terminalCount;
    const parseInput = createParseTraceInput(terminalCount);
    parseInput.terminals.set(parseTerminals!.subarray(0, terminalCount));
    return {
      source,
      tokens,
      diagnostics,
      parseStream: {
        tokens: streamTokens,
        tokenIndices: streamTokenIndices,
        input: parseInput,
        terminalCount,
      },
    };
  }
  return lexResult(source, tokens, diagnostics);
}
`;
}
