import type {
  BabaMetadata,
  Diagnostic,
  GeneratedFile,
  PortabilityMode,
  TypeScriptTargetOptions,
  WasmTargetOptions,
} from "../../ast.ts";
import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import type { RegexAst } from "../../compiler/regex/ast.ts";
import { buildLexerDfa } from "../../compiler/regex/lexer.ts";
import { parsePortableRegex } from "../../compiler/regex/parser.ts";
import type { Dfa } from "../../compiler/regex/dfa.ts";
import type { BnfGrammar } from "../typescript/bnf.ts";
import type { LrTable } from "../typescript/lr1.ts";
import {
  planTypeScriptTarget,
  type TypeScriptPlan,
} from "../typescript/plan.ts";
import { emitSyntax } from "../typescript/syntax_emit.ts";
import { emitWasmLexer } from "./lexer_emit.ts";
import { emitWasmModule, type WasmModuleImage } from "./module_emit.ts";
import { emitWasmParser } from "./parser_emit.ts";
import { emitWasmRuntime } from "./runtime_emit.ts";

export interface WasmPlan {
  analyzed: AnalyzedGrammar;
  bnf: BnfGrammar;
  lr: LrTable;
  dfa: Dfa;
  wasm: WasmModuleImage;
  directory: string;
  preserveTrivia: boolean;
  diagnostics: readonly Diagnostic[];
}

export function planWasmTarget(
  analyzed: AnalyzedGrammar,
  options: WasmTargetOptions = {},
  metadata: BabaMetadata = {},
  portability: PortabilityMode = "warn",
): WasmPlan | { diagnostics: readonly Diagnostic[] } {
  const diagnostics = [...wasmOptionsDiagnostics(options)];
  const typeScriptPlan = planTypeScriptTarget(
    analyzed,
    typeScriptPlanningOptions(options),
    metadata,
    portability,
  );
  diagnostics.push(...typeScriptPlan.diagnostics.map(wasmDiagnostic));
  if (hasErrors(diagnostics) || !isTypeScriptPlan(typeScriptPlan)) {
    return { diagnostics };
  }

  const dfa = buildLexerDfa(lexerSpecs(analyzed));
  const wasm = emitWasmModule(dfa, typeScriptPlan.bnf, typeScriptPlan.lr);
  return {
    analyzed,
    bnf: typeScriptPlan.bnf,
    lr: typeScriptPlan.lr,
    dfa,
    wasm,
    directory: options.directory ?? "wasm",
    preserveTrivia: options.preserveTrivia ?? true,
    diagnostics,
  };
}

export function emitWasmTarget(
  plan: WasmPlan,
  _options: WasmTargetOptions = {},
): GeneratedFile[] {
  const dir = plan.directory;
  return [
    {
      path: `${dir}/syntax.ts`,
      content: emitSyntax(plan.analyzed),
      kind: "source",
    },
    {
      path: `${dir}/wasm.ts`,
      content: emitWasmRuntime(plan.wasm),
      kind: "source",
    },
    {
      path: `${dir}/lexer.ts`,
      content: emitWasmLexer(plan.analyzed, plan.bnf, plan.preserveTrivia),
      kind: "source",
    },
    {
      path: `${dir}/parser.ts`,
      content: emitWasmParser(plan.analyzed, plan.bnf, plan.lr),
      kind: "source",
    },
    {
      path: `${dir}/mod.ts`,
      content: wasmModSource(),
      kind: "source",
    },
  ];
}

function wasmModSource(): string {
  return `// Generated by @mewhhaha/baba. Do not edit by hand.
export * from "./syntax.ts";
export { lex } from "./lexer.ts";
export { parse, parseTokens, parseTokensUnchecked } from "./parser.ts";
export { wasmBytes } from "./wasm.ts";
`;
}

function lexerSpecs(analyzed: AnalyzedGrammar) {
  return [
    ...analyzed.tokens
      .filter((token) =>
        token.kind === "skip" ||
        (token.kind === "token" && analyzed.reachableTokens.has(token.id))
      )
      .map((token) => ({
        ast: parsePortableRegex(token.pattern),
        type: "named" as const,
        priority: token.priority,
        order: token.declarationOrder,
      })),
    ...analyzed.literals
      .filter((literal) => analyzed.reachableLiterals.has(literal.id))
      .map((literal) => ({
        ast: literalAst(literal.value),
        type: "literal" as const,
        priority: 0,
        order: literal.sourceOrder,
      })),
  ];
}

function literalAst(value: string): RegexAst {
  const items: RegexAst[] = [];
  for (let index = 0; index < value.length;) {
    const codePoint = value.codePointAt(index)!;
    items.push({ kind: "literal", codePoint });
    index += codePoint > 0xffff ? 2 : 1;
  }
  if (items.length === 0) return { kind: "empty" };
  return items.length === 1 ? items[0] : { kind: "sequence", items };
}

function typeScriptPlanningOptions(
  options: WasmTargetOptions,
): TypeScriptTargetOptions {
  return {
    preserveTrivia: options.preserveTrivia,
    lexerStateLimit: options.lexerStateLimit,
    parserStateLimit: options.parserStateLimit,
    parserItemLimit: options.parserItemLimit,
    parserTableEntryLimit: options.parserTableEntryLimit,
  };
}

function wasmOptionsDiagnostics(options: WasmTargetOptions): Diagnostic[] {
  const directory = options.directory ?? "wasm";
  const diagnostics: Diagnostic[] = [];
  if (!isSafeRelativeDirectory(directory)) {
    diagnostics.push({
      code: "WASM_GENERATION_ERROR",
      severity: "error",
      backend: "wasm",
      message:
        `Invalid Wasm output directory '${directory}'. Use a relative directory without '.', '..', empty components, absolute paths, drive prefixes, or backslashes.`,
    });
  }
  return diagnostics;
}

function wasmDiagnostic(diagnostic: Diagnostic): Diagnostic {
  return {
    ...diagnostic,
    backend: "wasm",
    code: diagnostic.code.startsWith("TS_")
      ? `WASM_${diagnostic.code.slice("TS_".length)}`
      : diagnostic.code,
    message: diagnostic.message
      .replaceAll("TypeScript target", "Wasm target")
      .replaceAll("TypeScript parser", "Wasm parser")
      .replaceAll("TypeScript lexer", "Wasm lexer")
      .replaceAll("TypeScript output", "Wasm output")
      .replaceAll("TypeScript LR", "Wasm LR")
      .replaceAll("TypeScript ACTION/GOTO", "Wasm ACTION/GOTO"),
  };
}

function isSafeRelativeDirectory(directory: string): boolean {
  if (
    directory.length === 0 ||
    directory.includes("\0") ||
    directory.includes("\\") ||
    directory.startsWith("/") ||
    /^[A-Za-z]:/.test(directory)
  ) {
    return false;
  }
  return directory.split("/").every((component) =>
    component !== "" && component !== "." && component !== ".."
  );
}

function isTypeScriptPlan(
  value: TypeScriptPlan | { diagnostics: readonly Diagnostic[] },
): value is TypeScriptPlan {
  return "bnf" in value;
}

function hasErrors(diagnostics: readonly Diagnostic[]): boolean {
  return diagnostics.some((diagnostic) =>
    (diagnostic.severity ?? "error") === "error"
  );
}
