import type {
  BabaMetadata,
  Diagnostic,
  GeneratedFile,
  PortabilityMode,
  WasmTargetOptions,
} from "../../ast.ts";
import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import type { Dfa } from "../../compiler/regex/dfa.ts";
import type { BnfGrammar } from "../typescript/bnf.ts";
import type { LrTable } from "../typescript/lr1.ts";
import type {
  PortableParserPlanMetadata,
  PortableParserPlanV1,
} from "../runtime/portable_plan.ts";
import { emitSyntax } from "../typescript/syntax_emit.ts";
import {
  planRuntimeParserTarget,
  type RuntimeParserPlan,
  type RuntimeParserPlanningOptions,
} from "../runtime/plan.ts";
import { emitWasmLexer } from "./lexer_emit.ts";
import { emitWasmModule, type WasmModuleImage } from "./module_emit.ts";
import { emitWasmParser } from "./parser_emit.ts";
import { emitWasmRuntime } from "./runtime_emit.ts";

export interface WasmPlan {
  analyzed: AnalyzedGrammar;
  bnf: BnfGrammar;
  lr: LrTable;
  dfa: Dfa;
  portable: PortableParserPlanV1;
  portableMetadata: PortableParserPlanMetadata;
  wasm: WasmModuleImage;
  directory: string;
  preserveTrivia: boolean;
  diagnostics: readonly Diagnostic[];
}

export function planWasmTarget(
  analyzed: AnalyzedGrammar,
  options: WasmTargetOptions = {},
  metadata: BabaMetadata = {},
  portability: PortabilityMode = "warn",
): WasmPlan | { diagnostics: readonly Diagnostic[] } {
  const diagnostics = [...wasmOptionsDiagnostics(options)];
  const runtimePlan = planRuntimeParserTarget(
    analyzed,
    runtimePlanningOptions(options),
    metadata,
    portability,
    { backend: "wasm", codePrefix: "WASM", label: "Wasm" },
  );
  diagnostics.push(...runtimePlan.diagnostics);
  if (hasErrors(diagnostics) || !isRuntimePlan(runtimePlan)) {
    return { diagnostics };
  }
  const wasm = emitWasmModule(
    runtimePlan.dfa,
    runtimePlan.bnf,
    runtimePlan.lr,
    runtimePlan.portable.version,
  );
  return {
    analyzed,
    bnf: runtimePlan.bnf,
    lr: runtimePlan.lr,
    dfa: runtimePlan.dfa,
    portable: runtimePlan.portable,
    portableMetadata: runtimePlan.portableMetadata,
    wasm,
    directory: options.directory ?? "wasm",
    preserveTrivia: options.preserveTrivia ?? true,
    diagnostics,
  };
}

export function emitWasmTarget(
  plan: WasmPlan,
  _options: WasmTargetOptions = {},
): GeneratedFile[] {
  const dir = plan.directory;
  return [
    {
      path: `${dir}/syntax.ts`,
      content: emitSyntax(plan.analyzed),
      kind: "source",
    },
    {
      path: `${dir}/wasm.ts`,
      content: emitWasmRuntime(plan.wasm, plan.portableMetadata),
      kind: "source",
    },
    {
      path: `${dir}/lexer.ts`,
      content: emitWasmLexer(plan.analyzed, plan.bnf, plan.preserveTrivia),
      kind: "source",
    },
    {
      path: `${dir}/parser.ts`,
      content: emitWasmParser(plan.analyzed, plan.bnf, plan.lr),
      kind: "source",
    },
    {
      path: `${dir}/mod.ts`,
      content: wasmModSource(),
      kind: "source",
    },
  ];
}

function wasmModSource(): string {
  return `// Generated by @mewhhaha/baba. Do not edit by hand.
export * from "./syntax.ts";
export { lex } from "./lexer.ts";
export { parse, parseTokens, parseTokensUnchecked } from "./parser.ts";
export { memory, parserPlanFormat, parserPlanHash, parserPlanSemantics, parserPlanVersion, reset, wasmAbiVersion, wasmBytes, wasmTargetKind } from "./wasm.ts";
`;
}

function runtimePlanningOptions(
  options: WasmTargetOptions,
): RuntimeParserPlanningOptions {
  return {
    lexerStateLimit: options.lexerStateLimit,
    regexAstNodeLimit: options.regexAstNodeLimit,
    regexBoundedRepeatLimit: options.regexBoundedRepeatLimit,
    regexNfaStateLimit: options.regexNfaStateLimit,
    regexDfaStateLimit: options.regexDfaStateLimit,
    regexOverlapStateLimit: options.regexOverlapStateLimit,
    parserStateLimit: options.parserStateLimit,
    parserItemLimit: options.parserItemLimit,
    parserTableEntryLimit: options.parserTableEntryLimit,
  };
}

function wasmOptionsDiagnostics(options: WasmTargetOptions): Diagnostic[] {
  const directory = options.directory ?? "wasm";
  const diagnostics: Diagnostic[] = [];
  if (!isSafeRelativeDirectory(directory)) {
    diagnostics.push({
      code: "WASM_GENERATION_ERROR",
      severity: "error",
      backend: "wasm",
      message:
        `Invalid Wasm output directory '${directory}'. Use a relative directory without '.', '..', empty components, absolute paths, drive prefixes, or backslashes.`,
    });
  }
  return diagnostics;
}

function isSafeRelativeDirectory(directory: string): boolean {
  if (
    directory.length === 0 ||
    directory.includes("\0") ||
    directory.includes("\\") ||
    directory.startsWith("/") ||
    /^[A-Za-z]:/.test(directory)
  ) {
    return false;
  }
  return directory.split("/").every((component) =>
    component !== "" && component !== "." && component !== ".."
  );
}

function isRuntimePlan(
  value: RuntimeParserPlan | { diagnostics: readonly Diagnostic[] },
): value is RuntimeParserPlan {
  return "bnf" in value;
}

function hasErrors(diagnostics: readonly Diagnostic[]): boolean {
  return diagnostics.some((diagnostic) =>
    (diagnostic.severity ?? "error") === "error"
  );
}
