import type { PortableParserPlanMetadata } from "../runtime/portable_plan.ts";
import { RUNTIME_IMPLEMENTATION_METADATA } from "../runtime/implementation.ts";
import {
  RUNTIME_TRACE_STATUS_BRANCH_LIMIT,
  RUNTIME_TRACE_STATUS_INTERNAL,
  RUNTIME_TRACE_STATUS_OK,
  RUNTIME_TRACE_STATUS_UNEXPECTED,
} from "../runtime/language_sources.ts";
import type { WasmModuleImage } from "./module_emit.ts";

export function emitWasmRuntime(
  image: WasmModuleImage,
  parserTraceBytes: Uint8Array,
  portableMetadata: PortableParserPlanMetadata,
): string {
  return `// Generated by @mewhhaha/baba. Do not edit by hand.
export const wasmTargetKind = "javascript-hosted-core-wasm" as const;
export const wasmBytes = new Uint8Array([
${byteLines(image.bytes)}
]);
const parserTraceRuntimeBytes = new Uint8Array([
${byteLines(parserTraceBytes)}
]);

const INPUT_BASE = ${image.inputBase};
const I32_BYTES = 4;
const LEX_RESULT_BYTES = 8;
const TOKEN_RECORD_BYTES = 12;
const UTF16_UNIT_BYTES = 2;
const WASM_PAGE_BYTES = 65536;
const MAX_WASM_BYTES = 0xffff_ffff;
const MAX_WASM_PAGES = 65535;
const WASM_SOURCE_ENCODING_UTF16 = 1;
const WASM_SPAN_UNIT_UTF16 = 1;
const WASM_HOST_OWNERSHIP_CALLER_MANAGED = 1;
const WASM_RESULT_LIFETIME_CALLER_BUFFER = 1;
const WASM_ADAPTER_HANDLE_CAPABILITY_EPOCH = 1;
const LEX_RESULT_I32_COUNT = 2;
const TOKEN_RECORD_I32_COUNT = 3;
const TRACE_STATUS_OK = ${RUNTIME_TRACE_STATUS_OK};
const TRACE_STATUS_UNEXPECTED = ${RUNTIME_TRACE_STATUS_UNEXPECTED};
const TRACE_STATUS_INTERNAL = ${RUNTIME_TRACE_STATUS_INTERNAL};
const TRACE_STATUS_BRANCH_LIMIT = ${RUNTIME_TRACE_STATUS_BRANCH_LIMIT};

interface ParserWasmExports {
  memory: WebAssembly.Memory;
  lex_one(sourcePtr: number, sourceLength: number, offset: number, resultPtr: number): number;
  lex_all(sourcePtr: number, sourceLength: number, resultPtr: number, tokenPtr: number): number;
  parser_action(state: number, terminal: number): number;
  parser_goto(state: number, nonterminal: number): number;
  abi_version(): number;
  plan_version(): number;
  reset(): void;
  input_base(): number;
  max_pages(): number;
  source_encoding(): number;
  span_unit(): number;
  lex_result_i32_count(): number;
  token_record_i32_count(): number;
  host_ownership_model(): number;
  result_lifetime_model(): number;
}

interface ParserTraceRuntimeExports {
  parserTraceSetTerminal(index: number, terminal: number): number;
  parserTrace(terminalCount: number): number;
  parserTraceErrorState(): number;
  parserTraceErrorIndex(): number;
  parserTraceCount(): number;
  parserTraceAction(index: number): number;
  parserTraceStatusKind(status: number): number;
}

const wasmModule = new WebAssembly.Module(wasmBytes);
const wasmInstance = new WebAssembly.Instance(wasmModule, {});
const wasm = wasmInstance.exports as unknown as ParserWasmExports;
const parserTraceRuntimeModule = new WebAssembly.Module(parserTraceRuntimeBytes);
let parserTraceRuntime = instantiateParserTraceRuntime();

function instantiateParserTraceRuntime(): ParserTraceRuntimeExports {
  const instance = new WebAssembly.Instance(parserTraceRuntimeModule, {});
  return instance.exports as unknown as ParserTraceRuntimeExports;
}

export const memory = wasm.memory;
export const parserAction = wasm.parser_action;
export const parserGoto = wasm.parser_goto;
export const wasmAbiVersion = wasm.abi_version();
export const wasmInputBase = wasm.input_base();
export const wasmMaxPages = wasm.max_pages();
export const wasmSourceEncoding = wasm.source_encoding();
export const wasmSpanUnit = wasm.span_unit();
export const wasmLexResultI32Count = wasm.lex_result_i32_count();
export const wasmTokenRecordI32Count = wasm.token_record_i32_count();
export const wasmHostOwnershipModel = wasm.host_ownership_model();
export const wasmResultLifetimeModel = wasm.result_lifetime_model();
export const wasmAdapterHandleCapabilityModel = WASM_ADAPTER_HANDLE_CAPABILITY_EPOCH;
export const wasmTraceStatusOk = TRACE_STATUS_OK;
export const wasmTraceStatusUnexpected = TRACE_STATUS_UNEXPECTED;
export const wasmTraceStatusInternal = TRACE_STATUS_INTERNAL;
export const wasmTraceStatusBranchLimit = TRACE_STATUS_BRANCH_LIMIT;
export const parserPlanFormat = ${
    JSON.stringify(portableMetadata.format)
  } as const;
export const parserPlanVersion = wasm.plan_version();
export const parserPlanSemantics = ${
    JSON.stringify(portableMetadata.semantics)
  } as const;
export const parserPlanHash = ${JSON.stringify(portableMetadata.hash)} as const;
export const runtimeImplementationFormat = ${
    JSON.stringify(RUNTIME_IMPLEMENTATION_METADATA.format)
  } as const;
export const runtimeImplementationVersion = ${RUNTIME_IMPLEMENTATION_METADATA.version};
export const runtimeImplementationSemantics = ${
    JSON.stringify(RUNTIME_IMPLEMENTATION_METADATA.semantics)
  } as const;
export const runtimeImplementationHash = ${
    JSON.stringify(RUNTIME_IMPLEMENTATION_METADATA.hash)
  } as const;

validateWasmAbi();

export interface WasmSourceBuffer {
  sourcePtr: number;
  sourceLength: number;
  resultPtr: number;
  tokenPtr: number;
  tokenCapacity: number;
}

let cachedSource: string | null = null;
let cachedBuffer: WasmSourceBuffer | null = null;
let sourceBufferEpoch = 0;
const sourceBufferOwners = new WeakMap<WasmSourceBuffer, number>();

export function reset(): void {
  wasm.reset();
  parserTraceRuntime = instantiateParserTraceRuntime();
  sourceBufferEpoch++;
  parseTraceInputEpoch++;
  cachedSource = null;
  cachedBuffer = null;
}

export function writeSource(source: string): WasmSourceBuffer {
  if (cachedSource === source && cachedBuffer) return cachedBuffer;
  sourceBufferEpoch++;
  const sourcePtr = INPUT_BASE;
  const sourceBytes = checkedMul(
    source.length,
    UTF16_UNIT_BYTES,
    "source byte length",
  );
  const resultPtr = align4(
    checkedAdd(sourcePtr, sourceBytes, "lexer result offset"),
  );
  const tokenPtr = align4(
    checkedAdd(resultPtr, LEX_RESULT_BYTES, "token table offset"),
  );
  const tokenCapacity = source.length;
  const tokenBytes = checkedMul(
    tokenCapacity,
    TOKEN_RECORD_BYTES,
    "token table byte length",
  );
  ensureCapacity(checkedAdd(tokenPtr, tokenBytes, "token table end offset"));
  const units = new Uint16Array(memory.buffer, sourcePtr, source.length);
  for (let index = 0; index < source.length; index++) {
    units[index] = source.charCodeAt(index);
  }
  const buffer = {
    sourcePtr,
    sourceLength: source.length,
    resultPtr,
    tokenPtr,
    tokenCapacity,
  };
  sourceBufferOwners.set(buffer, sourceBufferEpoch);
  cachedSource = source;
  cachedBuffer = buffer;
  return cachedBuffer;
}

export function lexOne(buffer: WasmSourceBuffer, offset: number): {
  specIndex: number;
  end: number;
} | null {
  assertOwnedSourceBuffer(buffer);
  assertNonNegativeInteger("offset", offset);
  if (offset > buffer.sourceLength) {
    throw new RangeError("offset exceeds source buffer length.");
  }
  const matched = wasm.lex_one(
    buffer.sourcePtr,
    buffer.sourceLength,
    offset,
    buffer.resultPtr,
  );
  if (matched === 0) return null;
  const view = new DataView(memory.buffer);
  return {
    specIndex: view.getInt32(buffer.resultPtr, true),
    end: view.getInt32(buffer.resultPtr + 4, true),
  };
}

export function lexAll(buffer: WasmSourceBuffer): Int32Array {
  assertOwnedSourceBuffer(buffer);
  const count = wasm.lex_all(
    buffer.sourcePtr,
    buffer.sourceLength,
    buffer.resultPtr,
    buffer.tokenPtr,
  );
  return new Int32Array(memory.buffer, buffer.tokenPtr, count * 3);
}

export type ParseTraceResult =
  | { ok: true; trace: Int32Array }
  | {
    ok: false;
    state: number;
    index: number;
    statusKind: number;
    failureKind: "unexpected" | "internal" | "branch-limit";
    internal: boolean;
    limit: boolean;
  };

export interface ParseTraceInput {
  terminals: Int32Array;
  terminalCapacity: number;
}

let parseTraceInputEpoch = 0;
const parseTraceInputOwners = new WeakMap<ParseTraceInput, number>();

export function createParseTraceInput(terminalCapacity: number): ParseTraceInput {
  assertPositiveInteger("terminalCapacity", terminalCapacity);
  const input = {
    terminals: new Int32Array(terminalCapacity),
    terminalCapacity,
  };
  parseTraceInputOwners.set(input, parseTraceInputEpoch);
  return input;
}

export function parseTrace(
  input: ParseTraceInput,
  terminalCount: number,
): ParseTraceResult {
  assertParseTraceInput(input);
  assertNonNegativeInteger("terminalCount", terminalCount);
  if (terminalCount > input.terminalCapacity) {
    throw new RangeError("terminalCount exceeds parse input terminalCapacity.");
  }
  try {
    for (let index = 0; index < terminalCount; index++) {
      parserTraceRuntime.parserTraceSetTerminal(index, input.terminals[index]);
    }
    const status = parserTraceRuntime.parserTrace(terminalCount);
    const traceStatus = parserTraceRuntime.parserTraceStatusKind(status);
    if (traceStatus !== TRACE_STATUS_OK) {
      return {
        ok: false,
        state: parserTraceRuntime.parserTraceErrorState(),
        index: parserTraceRuntime.parserTraceErrorIndex(),
        statusKind: traceStatus,
        failureKind: traceStatus === TRACE_STATUS_INTERNAL
          ? "internal"
          : traceStatus === TRACE_STATUS_BRANCH_LIMIT
          ? "branch-limit"
          : "unexpected",
        internal: traceStatus === TRACE_STATUS_INTERNAL,
        limit: traceStatus === TRACE_STATUS_BRANCH_LIMIT,
      };
    }
    const count = parserTraceRuntime.parserTraceCount();
    const trace = new Int32Array(count);
    for (let index = 0; index < count; index++) {
      trace[index] = parserTraceRuntime.parserTraceAction(index) | 0;
    }
    return {
      ok: true,
      trace,
    };
  } catch {
    return {
      ok: false,
      state: 0,
      index: terminalCount,
      statusKind: TRACE_STATUS_INTERNAL,
      failureKind: "internal",
      internal: true,
      limit: false,
    };
  }
}

function ensureCapacity(requiredBytes: number): void {
  assertNonNegativeInteger("requiredBytes", requiredBytes);
  if (requiredBytes > MAX_WASM_BYTES) {
    throw new RangeError("requiredBytes exceeds the 32-bit Wasm address space.");
  }
  const current = memory.buffer.byteLength;
  if (requiredBytes <= current) return;
  const requiredPages = Math.ceil(requiredBytes / WASM_PAGE_BYTES);
  const currentPages = current / WASM_PAGE_BYTES;
  if (requiredPages > MAX_WASM_PAGES) {
    throw new RangeError("requiredBytes exceeds the configured Wasm page limit.");
  }
  memory.grow(requiredPages - currentPages);
}

function align4(value: number): number {
  assertNonNegativeInteger("byte offset", value);
  const remainder = value % I32_BYTES;
  return remainder === 0
    ? value
    : checkedAdd(value, I32_BYTES - remainder, "aligned byte offset");
}

function assertParseTraceInput(input: ParseTraceInput): void {
  assertOwnedParseTraceInput(input);
  assertPositiveInteger("terminalCapacity", input.terminalCapacity);
  if (!(input.terminals instanceof Int32Array)) {
    throw new TypeError("terminals must be an Int32Array.");
  }
  if (input.terminals.length < input.terminalCapacity) {
    throw new RangeError(
      "terminals length must cover parse input terminalCapacity.",
    );
  }
}

function validateWasmAbi(): void {
  if (wasmInputBase !== INPUT_BASE) {
    throw new Error("Wasm input base does not match generated adapter.");
  }
  if (wasmMaxPages !== MAX_WASM_PAGES) {
    throw new Error("Wasm max page count does not match generated adapter.");
  }
  if (wasmSourceEncoding !== WASM_SOURCE_ENCODING_UTF16) {
    throw new Error("Wasm source encoding is not UTF-16.");
  }
  if (wasmSpanUnit !== WASM_SPAN_UNIT_UTF16) {
    throw new Error("Wasm span unit is not UTF-16.");
  }
  if (wasmLexResultI32Count !== LEX_RESULT_I32_COUNT) {
    throw new Error("Wasm lex result width does not match generated adapter.");
  }
  if (wasmTokenRecordI32Count !== TOKEN_RECORD_I32_COUNT) {
    throw new Error("Wasm token record width does not match generated adapter.");
  }
  if (wasmHostOwnershipModel !== WASM_HOST_OWNERSHIP_CALLER_MANAGED) {
    throw new Error("Wasm host ownership model does not match generated adapter.");
  }
  if (wasmResultLifetimeModel !== WASM_RESULT_LIFETIME_CALLER_BUFFER) {
    throw new Error("Wasm result lifetime model does not match generated adapter.");
  }
}

function assertOwnedSourceBuffer(buffer: WasmSourceBuffer): void {
  const epoch = sourceBufferOwners.get(buffer);
  if (epoch === undefined) {
    throw new TypeError("WasmSourceBuffer is not owned by this adapter.");
  }
  if (epoch !== sourceBufferEpoch) {
    throw new TypeError("WasmSourceBuffer is stale; call writeSource() again.");
  }
}

function assertOwnedParseTraceInput(input: ParseTraceInput): void {
  const epoch = parseTraceInputOwners.get(input);
  if (epoch === undefined) {
    throw new TypeError("ParseTraceInput is not owned by this adapter.");
  }
  if (epoch !== parseTraceInputEpoch) {
    throw new TypeError("ParseTraceInput is stale; call createParseTraceInput() again.");
  }
}

function assertPositiveInteger(name: string, value: number): void {
  if (!Number.isInteger(value) || value <= 0) {
    throw new RangeError(name + " must be a positive integer.");
  }
}

function assertNonNegativeInteger(name: string, value: number): void {
  if (!Number.isInteger(value) || value < 0) {
    throw new RangeError(name + " must be a non-negative integer.");
  }
}

function checkedAdd(left: number, right: number, label: string): number {
  assertNonNegativeInteger(label, left);
  assertNonNegativeInteger(label, right);
  const value = left + right;
  if (!Number.isSafeInteger(value) || value > MAX_WASM_BYTES) {
    throw new RangeError(label + " exceeds the 32-bit Wasm address space.");
  }
  return value;
}

function checkedMul(left: number, right: number, label: string): number {
  assertNonNegativeInteger(label, left);
  assertNonNegativeInteger(label, right);
  const value = left * right;
  if (!Number.isSafeInteger(value) || value > MAX_WASM_BYTES) {
    throw new RangeError(label + " exceeds the 32-bit Wasm address space.");
  }
  return value;
}
`;
}

function byteLines(bytes: Uint8Array): string {
  const lines: string[] = [];
  for (let index = 0; index < bytes.length; index += 16) {
    lines.push(
      `  ${
        [...bytes.slice(index, index + 16)].map((byte) =>
          `0x${byte.toString(16).padStart(2, "0")}`
        ).join(", ")
      },`,
    );
  }
  return lines.join("\n");
}
