import type { PortableParserPlanMetadata } from "../runtime/portable_plan.ts";
import { RUNTIME_IMPLEMENTATION_METADATA } from "../runtime/implementation.ts";
import {
  RUNTIME_TRACE_STATUS_AMBIGUOUS,
  RUNTIME_TRACE_STATUS_BRANCH_LIMIT,
  RUNTIME_TRACE_STATUS_INTERNAL,
  RUNTIME_TRACE_STATUS_OK,
  RUNTIME_TRACE_STATUS_TRACE_LIMIT,
  RUNTIME_TRACE_STATUS_UNEXPECTED,
} from "../runtime/language_sources.ts";
import {
  WASM_ADAPTER_HANDLE_CAPABILITY_EPOCH,
  WASM_HOST_OWNERSHIP_CALLER_MANAGED,
  WASM_I32_BYTES,
  WASM_LEX_RESULT_I32_COUNT,
  WASM_MAX_BYTES,
  WASM_MAX_PAGES,
  WASM_PAGE_BYTES,
  WASM_RESULT_LIFETIME_CALLER_BUFFER,
  WASM_SOURCE_ENCODING_UTF16,
  WASM_SPAN_UNIT_UTF16,
  WASM_TARGET_KIND,
  WASM_TOKEN_RECORD_I32_COUNT,
  WASM_UTF16_UNIT_BYTES,
} from "../runtime/wasm_abi.ts";
import type { WasmModuleImage } from "./module_emit.ts";

export function emitWasmRuntime(
  image: WasmModuleImage,
  parserTraceBytes: Uint8Array,
  portableMetadata: PortableParserPlanMetadata,
  options: { packaging?: "embedded-typescript" | "external-binary" } = {},
): string {
  const packaging = options.packaging ?? "embedded-typescript";
  return `// Generated by @mewhhaha/baba. Do not edit by hand.
export const wasmTargetKind = ${JSON.stringify(WASM_TARGET_KIND)} as const;
${wasmBytesSource(image.bytes, packaging)}
const parserTraceRuntimeBytes = new Uint8Array([
${byteLines(parserTraceBytes)}
]);

const INPUT_BASE = ${image.inputBase};
const I32_BYTES = ${WASM_I32_BYTES};
const LEX_RESULT_BYTES = ${WASM_LEX_RESULT_I32_COUNT * WASM_I32_BYTES};
const TOKEN_RECORD_BYTES = ${WASM_TOKEN_RECORD_I32_COUNT * WASM_I32_BYTES};
const UTF16_UNIT_BYTES = ${WASM_UTF16_UNIT_BYTES};
const WASM_PAGE_BYTES = ${WASM_PAGE_BYTES};
const MAX_WASM_BYTES = ${WASM_MAX_BYTES};
const MAX_WASM_PAGES = ${WASM_MAX_PAGES};
const WASM_SOURCE_ENCODING_UTF16 = ${WASM_SOURCE_ENCODING_UTF16};
const WASM_SPAN_UNIT_UTF16 = ${WASM_SPAN_UNIT_UTF16};
const WASM_HOST_OWNERSHIP_CALLER_MANAGED = ${WASM_HOST_OWNERSHIP_CALLER_MANAGED};
const WASM_RESULT_LIFETIME_CALLER_BUFFER = ${WASM_RESULT_LIFETIME_CALLER_BUFFER};
const WASM_ADAPTER_HANDLE_CAPABILITY_EPOCH = ${WASM_ADAPTER_HANDLE_CAPABILITY_EPOCH};
const LEX_RESULT_I32_COUNT = ${WASM_LEX_RESULT_I32_COUNT};
const TOKEN_RECORD_I32_COUNT = ${WASM_TOKEN_RECORD_I32_COUNT};
const TRACE_STATUS_OK = ${RUNTIME_TRACE_STATUS_OK};
const TRACE_STATUS_UNEXPECTED = ${RUNTIME_TRACE_STATUS_UNEXPECTED};
const TRACE_STATUS_INTERNAL = ${RUNTIME_TRACE_STATUS_INTERNAL};
const TRACE_STATUS_BRANCH_LIMIT = ${RUNTIME_TRACE_STATUS_BRANCH_LIMIT};
const TRACE_STATUS_TRACE_LIMIT = ${RUNTIME_TRACE_STATUS_TRACE_LIMIT};
const TRACE_STATUS_AMBIGUOUS = ${RUNTIME_TRACE_STATUS_AMBIGUOUS};
const DEFAULT_MAX_PARSE_BRANCHES = 100_000;
const DEFAULT_MAX_QUEUED_BRANCHES = 100_000;
const DEFAULT_MAX_TRACE_ACTIONS = 1_000_000;

interface ParserWasmExports {
  memory: WebAssembly.Memory;
  lex_one(sourcePtr: number, sourceLength: number, offset: number, resultPtr: number): number;
  lex_all(sourcePtr: number, sourceLength: number, resultPtr: number, tokenPtr: number): number;
  parser_action(state: number, terminal: number): number;
  parser_goto(state: number, nonterminal: number): number;
  abi_version(): number;
  plan_version(): number;
  reset(): void;
  input_base(): number;
  max_pages(): number;
  source_encoding(): number;
  span_unit(): number;
  lex_result_i32_count(): number;
  token_record_i32_count(): number;
  host_ownership_model(): number;
  result_lifetime_model(): number;
}

interface ParserTraceRuntimeExports {
  parserTraceSetTerminal(index: number, terminal: number): number;
  parserTrace(
    terminalCount: number,
    maxBranches: number,
    maxTraceActions: number,
    maxQueuedBranches: number,
    ambiguityMode: number,
  ): number;
  parserTraceErrorState(): number;
  parserTraceErrorIndex(): number;
  parserTraceCount(): number;
  parserTraceAction(index: number): number;
  parserTraceStatusKind(status: number): number;
}

const parserTraceRuntimeModule = new WebAssembly.Module(parserTraceRuntimeBytes);
let parserTraceRuntime = instantiateParserTraceRuntime();

function instantiateParserTraceRuntime(): ParserTraceRuntimeExports {
  const instance = new WebAssembly.Instance(parserTraceRuntimeModule, {});
  return instance.exports as unknown as ParserTraceRuntimeExports;
}

export const parserPlanFormat = ${
    JSON.stringify(portableMetadata.format)
  } as const;
export const parserPlanSemantics = ${
    JSON.stringify(portableMetadata.semantics)
  } as const;
export const parserPlanHash = ${JSON.stringify(portableMetadata.hash)} as const;
export const runtimeImplementationFormat = ${
    JSON.stringify(RUNTIME_IMPLEMENTATION_METADATA.format)
  } as const;
export const runtimeImplementationVersion = ${RUNTIME_IMPLEMENTATION_METADATA.version};
export const runtimeImplementationSemantics = ${
    JSON.stringify(RUNTIME_IMPLEMENTATION_METADATA.semantics)
  } as const;
export const runtimeImplementationHash = ${
    JSON.stringify(RUNTIME_IMPLEMENTATION_METADATA.hash)
  } as const;

${wasmInstantiationSource(portableMetadata, packaging)}

export interface WasmSourceBuffer {
  sourcePtr: number;
  sourceLength: number;
  resultPtr: number;
  tokenPtr: number;
  tokenCapacity: number;
}

let cachedSource: string | null = null;
let cachedBuffer: WasmSourceBuffer | null = null;
let sourceBufferEpoch = 0;
const sourceBufferOwners = new WeakMap<WasmSourceBuffer, number>();

export function reset(): void {
  requireWasm().reset();
  parserTraceRuntime = instantiateParserTraceRuntime();
  sourceBufferEpoch++;
  parseTraceInputEpoch++;
  cachedSource = null;
  cachedBuffer = null;
}

export function writeSource(source: string): WasmSourceBuffer {
  if (cachedSource === source && cachedBuffer) return cachedBuffer;
  sourceBufferEpoch++;
  const sourcePtr = INPUT_BASE;
  const sourceBytes = checkedMul(
    source.length,
    UTF16_UNIT_BYTES,
    "source byte length",
  );
  const resultPtr = align4(
    checkedAdd(sourcePtr, sourceBytes, "lexer result offset"),
  );
  const tokenPtr = align4(
    checkedAdd(resultPtr, LEX_RESULT_BYTES, "token table offset"),
  );
  const tokenCapacity = source.length;
  const tokenBytes = checkedMul(
    tokenCapacity,
    TOKEN_RECORD_BYTES,
    "token table byte length",
  );
  ensureCapacity(checkedAdd(tokenPtr, tokenBytes, "token table end offset"));
  const units = new Uint16Array(memory.buffer, sourcePtr, source.length);
  for (let index = 0; index < source.length; index++) {
    units[index] = source.charCodeAt(index);
  }
  const buffer = {
    sourcePtr,
    sourceLength: source.length,
    resultPtr,
    tokenPtr,
    tokenCapacity,
  };
  sourceBufferOwners.set(buffer, sourceBufferEpoch);
  cachedSource = source;
  cachedBuffer = buffer;
  return cachedBuffer;
}

export function lexOne(buffer: WasmSourceBuffer, offset: number): {
  specIndex: number;
  end: number;
} | null {
  assertOwnedSourceBuffer(buffer);
  assertNonNegativeInteger("offset", offset);
  if (offset > buffer.sourceLength) {
    throw new RangeError("offset exceeds source buffer length.");
  }
  const matched = requireWasm().lex_one(
    buffer.sourcePtr,
    buffer.sourceLength,
    offset,
    buffer.resultPtr,
  );
  if (matched === 0) return null;
  const view = new DataView(memory.buffer);
  return {
    specIndex: view.getInt32(buffer.resultPtr, true),
    end: view.getInt32(buffer.resultPtr + 4, true),
  };
}

export function lexAll(buffer: WasmSourceBuffer): Int32Array {
  assertOwnedSourceBuffer(buffer);
  const count = requireWasm().lex_all(
    buffer.sourcePtr,
    buffer.sourceLength,
    buffer.resultPtr,
    buffer.tokenPtr,
  );
  return new Int32Array(memory.buffer, buffer.tokenPtr, count * 3);
}

export type ParseTraceResult =
  | { ok: true; trace: Int32Array }
  | {
    ok: false;
    state: number;
    index: number;
    statusKind: number;
    failureKind:
      | "unexpected"
      | "internal"
      | "branch-limit"
      | "trace-limit"
      | "ambiguous";
    internal: boolean;
    limit: boolean;
  };

export interface ParseTraceInput {
  terminals: Int32Array;
  terminalCapacity: number;
}

export interface ParseTraceOptions {
  maxBranches?: number;
  maxQueuedBranches?: number;
  maxTraceActions?: number;
  ambiguityMode?: number;
}

let parseTraceInputEpoch = 0;
const parseTraceInputOwners = new WeakMap<ParseTraceInput, number>();

export function createParseTraceInput(terminalCapacity: number): ParseTraceInput {
  assertPositiveInteger("terminalCapacity", terminalCapacity);
  const input = {
    terminals: new Int32Array(terminalCapacity),
    terminalCapacity,
  };
  parseTraceInputOwners.set(input, parseTraceInputEpoch);
  return input;
}

export function parseTrace(
  input: ParseTraceInput,
  terminalCount: number,
  options: ParseTraceOptions = {},
): ParseTraceResult {
  assertParseTraceInput(input);
  assertNonNegativeInteger("terminalCount", terminalCount);
  const maxBranches = options.maxBranches ?? DEFAULT_MAX_PARSE_BRANCHES;
  const maxQueuedBranches = options.maxQueuedBranches ?? DEFAULT_MAX_QUEUED_BRANCHES;
  const maxTraceActions = options.maxTraceActions ?? DEFAULT_MAX_TRACE_ACTIONS;
  const ambiguityMode = options.ambiguityMode ?? 0;
  assertPositiveInteger("maxBranches", maxBranches);
  assertPositiveInteger("maxQueuedBranches", maxQueuedBranches);
  assertPositiveInteger("maxTraceActions", maxTraceActions);
  assertAmbiguityMode(ambiguityMode);
  if (terminalCount > input.terminalCapacity) {
    throw new RangeError("terminalCount exceeds parse input terminalCapacity.");
  }
  try {
    for (let index = 0; index < terminalCount; index++) {
      parserTraceRuntime.parserTraceSetTerminal(index, input.terminals[index]);
    }
    const status = parserTraceRuntime.parserTrace(
      terminalCount,
      maxBranches,
      maxTraceActions,
      maxQueuedBranches,
      ambiguityMode,
    );
    const traceStatus = parserTraceRuntime.parserTraceStatusKind(status);
    if (traceStatus !== TRACE_STATUS_OK) {
      return {
        ok: false,
        state: parserTraceRuntime.parserTraceErrorState(),
        index: parserTraceRuntime.parserTraceErrorIndex(),
        statusKind: traceStatus,
        failureKind: traceStatus === TRACE_STATUS_INTERNAL
          ? "internal"
          : traceStatus === TRACE_STATUS_BRANCH_LIMIT
          ? "branch-limit"
          : traceStatus === TRACE_STATUS_TRACE_LIMIT
          ? "trace-limit"
          : traceStatus === TRACE_STATUS_AMBIGUOUS
          ? "ambiguous"
          : "unexpected",
        internal: traceStatus === TRACE_STATUS_INTERNAL,
        limit: traceStatus === TRACE_STATUS_BRANCH_LIMIT ||
          traceStatus === TRACE_STATUS_TRACE_LIMIT,
      };
    }
    const count = parserTraceRuntime.parserTraceCount();
    const trace = new Int32Array(count);
    for (let index = 0; index < count; index++) {
      trace[index] = parserTraceRuntime.parserTraceAction(index) | 0;
    }
    return {
      ok: true,
      trace,
    };
  } catch {
    return {
      ok: false,
      state: 0,
      index: terminalCount,
      statusKind: TRACE_STATUS_INTERNAL,
      failureKind: "internal",
      internal: true,
      limit: false,
    };
  }
}

function ensureCapacity(requiredBytes: number): void {
  requireWasm();
  assertNonNegativeInteger("requiredBytes", requiredBytes);
  if (requiredBytes > MAX_WASM_BYTES) {
    throw new RangeError("requiredBytes exceeds the 32-bit Wasm address space.");
  }
  const current = memory.buffer.byteLength;
  if (requiredBytes <= current) return;
  const requiredPages = Math.ceil(requiredBytes / WASM_PAGE_BYTES);
  const currentPages = current / WASM_PAGE_BYTES;
  if (requiredPages > MAX_WASM_PAGES) {
    throw new RangeError("requiredBytes exceeds the configured Wasm page limit.");
  }
  memory.grow(requiredPages - currentPages);
}

function align4(value: number): number {
  assertNonNegativeInteger("byte offset", value);
  const remainder = value % I32_BYTES;
  return remainder === 0
    ? value
    : checkedAdd(value, I32_BYTES - remainder, "aligned byte offset");
}

function assertParseTraceInput(input: ParseTraceInput): void {
  assertOwnedParseTraceInput(input);
  assertPositiveInteger("terminalCapacity", input.terminalCapacity);
  if (!(input.terminals instanceof Int32Array)) {
    throw new TypeError("terminals must be an Int32Array.");
  }
  if (input.terminals.length < input.terminalCapacity) {
    throw new RangeError(
      "terminals length must cover parse input terminalCapacity.",
    );
  }
}

function validateWasmAbi(): void {
  if (wasmInputBase !== INPUT_BASE) {
    throw new Error("Wasm input base does not match generated adapter.");
  }
  if (wasmMaxPages !== MAX_WASM_PAGES) {
    throw new Error("Wasm max page count does not match generated adapter.");
  }
  if (wasmSourceEncoding !== WASM_SOURCE_ENCODING_UTF16) {
    throw new Error("Wasm source encoding is not UTF-16.");
  }
  if (wasmSpanUnit !== WASM_SPAN_UNIT_UTF16) {
    throw new Error("Wasm span unit is not UTF-16.");
  }
  if (wasmLexResultI32Count !== LEX_RESULT_I32_COUNT) {
    throw new Error("Wasm lex result width does not match generated adapter.");
  }
  if (wasmTokenRecordI32Count !== TOKEN_RECORD_I32_COUNT) {
    throw new Error("Wasm token record width does not match generated adapter.");
  }
  if (wasmHostOwnershipModel !== WASM_HOST_OWNERSHIP_CALLER_MANAGED) {
    throw new Error("Wasm host ownership model does not match generated adapter.");
  }
  if (wasmResultLifetimeModel !== WASM_RESULT_LIFETIME_CALLER_BUFFER) {
    throw new Error("Wasm result lifetime model does not match generated adapter.");
  }
}

function assertOwnedSourceBuffer(buffer: WasmSourceBuffer): void {
  const epoch = sourceBufferOwners.get(buffer);
  if (epoch === undefined) {
    throw new TypeError("WasmSourceBuffer is not owned by this adapter.");
  }
  if (epoch !== sourceBufferEpoch) {
    throw new TypeError("WasmSourceBuffer is stale; call writeSource() again.");
  }
}

function assertOwnedParseTraceInput(input: ParseTraceInput): void {
  const epoch = parseTraceInputOwners.get(input);
  if (epoch === undefined) {
    throw new TypeError("ParseTraceInput is not owned by this adapter.");
  }
  if (epoch !== parseTraceInputEpoch) {
    throw new TypeError("ParseTraceInput is stale; call createParseTraceInput() again.");
  }
}

function assertPositiveInteger(name: string, value: number): void {
  if (!Number.isInteger(value) || value <= 0) {
    throw new RangeError(name + " must be a positive integer.");
  }
}

function assertNonNegativeInteger(name: string, value: number): void {
  if (!Number.isInteger(value) || value < 0) {
    throw new RangeError(name + " must be a non-negative integer.");
  }
}

function assertAmbiguityMode(value: number): void {
  if (value !== 0 && value !== 1) {
    throw new RangeError("ambiguityMode must be 0 or 1.");
  }
}

function checkedAdd(left: number, right: number, label: string): number {
  assertNonNegativeInteger(label, left);
  assertNonNegativeInteger(label, right);
  const value = left + right;
  if (!Number.isSafeInteger(value) || value > MAX_WASM_BYTES) {
    throw new RangeError(label + " exceeds the 32-bit Wasm address space.");
  }
  return value;
}

function checkedMul(left: number, right: number, label: string): number {
  assertNonNegativeInteger(label, left);
  assertNonNegativeInteger(label, right);
  const value = left * right;
  if (!Number.isSafeInteger(value) || value > MAX_WASM_BYTES) {
    throw new RangeError(label + " exceeds the 32-bit Wasm address space.");
  }
  return value;
}
`;
}

function wasmBytesSource(
  bytes: Uint8Array,
  packaging: "embedded-typescript" | "external-binary",
): string {
  if (packaging === "external-binary") {
    return "";
  }
  return `export const wasmBytes = new Uint8Array([
${byteLines(bytes)}
]);`;
}

function wasmInstantiationSource(
  portableMetadata: PortableParserPlanMetadata,
  packaging: "embedded-typescript" | "external-binary",
): string {
  if (packaging === "embedded-typescript") {
    return `const wasmModule = new WebAssembly.Module(wasmBytes);
const wasmInstance = new WebAssembly.Instance(wasmModule, {});
const wasm = wasmInstance.exports as unknown as ParserWasmExports;

export const memory = wasm.memory;
export const parserAction = wasm.parser_action;
export const parserGoto = wasm.parser_goto;
export const wasmAbiVersion = wasm.abi_version();
export const wasmInputBase = wasm.input_base();
export const wasmMaxPages = wasm.max_pages();
export const wasmSourceEncoding = wasm.source_encoding();
export const wasmSpanUnit = wasm.span_unit();
export const wasmLexResultI32Count = wasm.lex_result_i32_count();
export const wasmTokenRecordI32Count = wasm.token_record_i32_count();
export const wasmHostOwnershipModel = wasm.host_ownership_model();
export const wasmResultLifetimeModel = wasm.result_lifetime_model();
export const wasmAdapterHandleCapabilityModel = WASM_ADAPTER_HANDLE_CAPABILITY_EPOCH;
export const wasmTraceStatusOk = TRACE_STATUS_OK;
export const wasmTraceStatusUnexpected = TRACE_STATUS_UNEXPECTED;
export const wasmTraceStatusInternal = TRACE_STATUS_INTERNAL;
export const wasmTraceStatusBranchLimit = TRACE_STATUS_BRANCH_LIMIT;
export const wasmTraceStatusTraceLimit = TRACE_STATUS_TRACE_LIMIT;
export const wasmTraceStatusAmbiguous = TRACE_STATUS_AMBIGUOUS;
export const parserPlanVersion = wasm.plan_version();

function requireWasm(): ParserWasmExports {
  return wasm;
}

validateWasmAbi();`;
  }
  return `let wasm: ParserWasmExports | null = null;
export let memory = undefined as unknown as WebAssembly.Memory;
export let parserAction: ParserWasmExports["parser_action"] = uninitializedWasmExport;
export let parserGoto: ParserWasmExports["parser_goto"] = uninitializedWasmExport;
export let wasmAbiVersion = 0;
export let wasmInputBase = 0;
export let wasmMaxPages = 0;
export let wasmSourceEncoding = 0;
export let wasmSpanUnit = 0;
export let wasmLexResultI32Count = 0;
export let wasmTokenRecordI32Count = 0;
export let wasmHostOwnershipModel = 0;
export let wasmResultLifetimeModel = 0;
export const wasmAdapterHandleCapabilityModel = WASM_ADAPTER_HANDLE_CAPABILITY_EPOCH;
export const wasmTraceStatusOk = TRACE_STATUS_OK;
export const wasmTraceStatusUnexpected = TRACE_STATUS_UNEXPECTED;
export const wasmTraceStatusInternal = TRACE_STATUS_INTERNAL;
export const wasmTraceStatusBranchLimit = TRACE_STATUS_BRANCH_LIMIT;
export const wasmTraceStatusTraceLimit = TRACE_STATUS_TRACE_LIMIT;
export const wasmTraceStatusAmbiguous = TRACE_STATUS_AMBIGUOUS;
export let parserPlanVersion = ${portableMetadata.version};

export function createParserFromBytes(bytes: Uint8Array): void {
  const copy = new Uint8Array(bytes.byteLength);
  copy.set(bytes);
  createParserFromModule(new WebAssembly.Module(copy.buffer as ArrayBuffer));
}

export function createParserFromModule(module: WebAssembly.Module): void {
  const instance = new WebAssembly.Instance(module, {});
  initializeWasm(instance.exports as unknown as ParserWasmExports);
}

export async function createParserFromUrl(url: URL): Promise<void> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error("Failed to load Wasm parser module from " + url.href + ".");
  }
  createParserFromBytes(new Uint8Array(await response.arrayBuffer()));
}

function initializeWasm(nextWasm: ParserWasmExports): void {
  wasm = nextWasm;
  memory = nextWasm.memory;
  parserAction = nextWasm.parser_action;
  parserGoto = nextWasm.parser_goto;
  wasmAbiVersion = nextWasm.abi_version();
  wasmInputBase = nextWasm.input_base();
  wasmMaxPages = nextWasm.max_pages();
  wasmSourceEncoding = nextWasm.source_encoding();
  wasmSpanUnit = nextWasm.span_unit();
  wasmLexResultI32Count = nextWasm.lex_result_i32_count();
  wasmTokenRecordI32Count = nextWasm.token_record_i32_count();
  wasmHostOwnershipModel = nextWasm.host_ownership_model();
  wasmResultLifetimeModel = nextWasm.result_lifetime_model();
  parserPlanVersion = nextWasm.plan_version();
  validateWasmAbi();
  reset();
}

function requireWasm(): ParserWasmExports {
  if (!wasm) {
    throw new Error("Wasm parser runtime is not initialized. Call createParserFromBytes(), createParserFromModule(), or createParserFromUrl() first.");
  }
  return wasm;
}

function uninitializedWasmExport(): never {
  throw new Error("Wasm parser runtime is not initialized. Call createParserFromBytes(), createParserFromModule(), or createParserFromUrl() first.");
}`;
}

function byteLines(bytes: Uint8Array): string {
  const lines: string[] = [];
  for (let index = 0; index < bytes.length; index += 16) {
    lines.push(
      `  ${
        [...bytes.slice(index, index + 16)].map((byte) =>
          `0x${byte.toString(16).padStart(2, "0")}`
        ).join(", ")
      },`,
    );
  }
  return lines.join("\n");
}
