import type {
  BabaMetadata,
  GeneratedFile,
  SourceSpan,
  TreeSitterExtra,
  TreeSitterPathMetadata,
  TreeSitterRuleMetadata,
  TreeSitterRuleToken,
  TreeSitterRuleWrap,
} from "../ast.ts";
import type { AnalyzedExpression, AnalyzedGrammar } from "../compiler/ir.ts";
import { BabaError } from "../errors.ts";

interface TreeSitterRulePlan {
  readonly name: string;
  readonly expression: AnalyzedExpression;
  readonly span: SourceSpan;
}

interface TreeSitterTokenPlan {
  readonly name: string;
  readonly kind: "token" | "skip";
  readonly pattern: string;
  readonly priority: number;
}

interface TreeSitterPlan {
  readonly name: string;
  readonly rootRuleName: string;
  readonly rules: readonly TreeSitterRulePlan[];
  readonly tokens: readonly TreeSitterTokenPlan[];
  readonly reachableRules: ReadonlySet<string>;
  readonly reachableTokens: ReadonlySet<string>;
  readonly externals: readonly string[];
}

interface NormalizedRuleMetadata {
  readonly paths: ReadonlyMap<string, TreeSitterPathMetadata>;
  readonly token?: TreeSitterRuleToken;
}

interface RenderContext {
  readonly metadata: BabaMetadata;
  readonly rules: ReadonlyMap<string, AnalyzedExpression>;
  readonly normalizedRules: ReadonlyMap<string, NormalizedRuleMetadata>;
  readonly aliasRules: Map<string, string>;
}

export function emitTreeSitterGrammarFile(
  analyzed: AnalyzedGrammar,
  metadata: BabaMetadata,
): GeneratedFile {
  const plan = createTreeSitterPlan(analyzed);
  validateTreeSitterMetadata(plan, metadata);
  return {
    path: "grammar.js",
    content: renderTreeSitterGrammar(plan, metadata),
    kind: "source",
    encoding: "utf-8",
  };
}

function createTreeSitterPlan(analyzed: AnalyzedGrammar): TreeSitterPlan {
  const rootRule = analyzed.rules[analyzed.rootRule];
  if (rootRule === undefined) {
    throw new BabaError({
      code: "TREE_SITTER_MISSING_ROOT_RULE",
      severity: "error",
      backend: "tree-sitter",
      message: "Tree-sitter generation requires a root rule.",
    });
  }

  const reachableRules = new Set<string>();
  for (const ruleId of analyzed.reachableRules) {
    const rule = analyzed.rules[ruleId];
    if (rule === undefined) {
      throw new Error(
        `Tree-sitter generation found unknown rule id ${ruleId}.`,
      );
    }
    reachableRules.add(rule.name);
  }

  const reachableTokens = new Set<string>();
  for (const tokenId of analyzed.reachableTokens) {
    const token = analyzed.tokens[tokenId];
    if (token === undefined) {
      throw new Error(
        `Tree-sitter generation found unknown token id ${tokenId}.`,
      );
    }
    reachableTokens.add(token.name);
  }

  return {
    name: analyzed.name,
    rootRuleName: rootRule.name,
    rules: analyzed.rules.map((rule) => ({
      name: rule.name,
      expression: rule.expression,
      span: rule.span,
    })),
    tokens: analyzed.tokens.map((token) => ({
      name: token.name,
      kind: token.kind,
      pattern: token.patternSource,
      priority: token.priority,
    })),
    reachableRules,
    reachableTokens,
    externals: analyzed.externals.map((external) => external.name),
  };
}

function renderTreeSitterGrammar(
  plan: TreeSitterPlan,
  metadata: BabaMetadata,
): string {
  const context = createRenderContext(plan, metadata);
  const lines = [
    "// Generated by @mewhhaha/baba. Do not edit by hand.",
    "export default grammar({",
    `  name: ${JSON.stringify(plan.name)},`,
    "",
    "  extras: $ => [",
  ];

  const extras: TreeSitterExtra[] = [];
  if (metadata.extras !== undefined) {
    extras.push(...metadata.extras);
  }
  for (const token of plan.tokens) {
    if (token.kind === "skip") {
      extras.push({ kind: "rule", name: token.name });
    }
  }
  for (const extra of extras) {
    lines.push(`    ${renderExtra(extra)},`);
  }
  lines.push("  ],", "");

  if (metadata.word !== undefined) {
    lines.push(`  word: $ => $.${metadata.word},`, "");
  }
  if (plan.externals.length > 0) {
    lines.push(`  externals: $ => ${renderRuleRefArray(plan.externals)},`, "");
  }
  if (metadata.supertypes !== undefined && metadata.supertypes.length > 0) {
    lines.push(
      `  supertypes: $ => ${renderRuleRefArray(metadata.supertypes)},`,
      "",
    );
  }
  if (metadata.conflicts !== undefined && metadata.conflicts.length > 0) {
    lines.push("  conflicts: $ => [");
    for (const conflict of metadata.conflicts) {
      lines.push(`    ${renderRuleRefArray(conflict)},`);
    }
    lines.push("  ],", "");
  }

  const inlineRules = collectInlineRules(metadata);
  if (inlineRules.length > 0) {
    lines.push(`  inline: $ => ${renderRuleRefArray(inlineRules)},`, "");
  }

  lines.push("  rules: {");
  lines.push(`    source_file: $ => $.${plan.rootRuleName},`);
  for (const rule of plan.rules) {
    if (!plan.reachableRules.has(rule.name)) {
      continue;
    }
    lines.push(
      `    ${formatRuleKey(rule.name)}: $ => ${
        renderRuleExpression(rule.name, rule.expression, context, new Set())
      },`,
    );
  }
  for (const token of plan.tokens) {
    if (token.kind === "token" && !plan.reachableTokens.has(token.name)) {
      continue;
    }
    lines.push(
      `    ${formatRuleKey(token.name)}: $ => ${renderToken(token)},`,
    );
  }
  for (const [name, expression] of context.aliasRules) {
    lines.push(`    ${formatRuleKey(name)}: $ => ${expression},`);
  }
  lines.push("  },", "});");
  return `${lines.join("\n")}\n`;
}

function createRenderContext(
  plan: TreeSitterPlan,
  metadata: BabaMetadata,
): RenderContext {
  const rules = new Map<string, AnalyzedExpression>();
  for (const rule of plan.rules) {
    rules.set(rule.name, rule.expression);
  }

  const normalizedRules = new Map<string, NormalizedRuleMetadata>();
  if (metadata.rules !== undefined) {
    for (const [ruleName, ruleMetadata] of Object.entries(metadata.rules)) {
      const expression = rules.get(ruleName);
      if (expression === undefined) {
        continue;
      }
      normalizedRules.set(
        ruleName,
        normalizeRuleMetadata(ruleName, expression, ruleMetadata),
      );
    }
  }
  return { metadata, rules, normalizedRules, aliasRules: new Map() };
}

function normalizeRuleMetadata(
  ruleName: string,
  expression: AnalyzedExpression,
  metadata: TreeSitterRuleMetadata,
): NormalizedRuleMetadata {
  const paths = new Map<string, TreeSitterPathMetadata>();
  if (metadata.wrap !== undefined) {
    paths.set("", { wrap: metadata.wrap });
  }
  if (metadata.paths !== undefined) {
    for (const [selector, pathMetadata] of Object.entries(metadata.paths)) {
      if (selector === "" && pathMetadata.hidden_path === true) {
        continue;
      }
      const path = resolvePathSelector(ruleName, expression, selector);
      const existing = paths.get(path);
      if (
        existing !== undefined && existing.wrap !== undefined &&
        pathMetadata.wrap !== undefined
      ) {
        treeSitterMetadataError(
          "METADATA_PATH_CONFLICT",
          `Rule '${ruleName}' has conflicting metadata for path '${selector}'.`,
          `metadata.rules.${ruleName}.paths.${selector}`,
        );
      }
      paths.set(path, { ...existing, ...pathMetadata });
    }
  }
  return { paths, token: metadata.token };
}

function resolvePathSelector(
  ruleName: string,
  expression: AnalyzedExpression,
  selector: string,
): string {
  if (selector === "") {
    return "";
  }
  const matches: string[] = [];
  collectFieldPaths(expression, [], selector, matches);
  if (matches.length === 0) {
    treeSitterMetadataError(
      "METADATA_UNKNOWN_FIELD_SELECTOR",
      `Unknown field selector '${selector}' on rule '${ruleName}'.`,
      `metadata.rules.${ruleName}.paths.${selector}`,
    );
  }
  if (matches.length > 1) {
    treeSitterMetadataError(
      "METADATA_AMBIGUOUS_FIELD_SELECTOR",
      `Field selector '${selector}' is ambiguous on rule '${ruleName}'.`,
      `metadata.rules.${ruleName}.paths.${selector}`,
    );
  }
  const match = matches[0];
  if (match === undefined) {
    throw new Error(`Field selector '${selector}' did not resolve.`);
  }
  return match;
}

function collectFieldPaths(
  expression: AnalyzedExpression,
  path: readonly number[],
  selector: string,
  matches: string[],
): void {
  switch (expression.kind) {
    case "field": {
      const childPath = [...path, 0];
      if (expression.name === selector) {
        matches.push(pathKey(childPath));
      }
      collectFieldPaths(expression.expression, childPath, selector, matches);
      return;
    }
    case "sequence":
      expression.items.forEach((child, index) =>
        collectFieldPaths(child, [...path, index], selector, matches)
      );
      return;
    case "choice":
      expression.options.forEach((child, index) =>
        collectFieldPaths(child, [...path, index], selector, matches)
      );
      return;
    case "optional":
    case "repeat":
    case "repeat1":
      collectFieldPaths(expression.expression, [...path, 0], selector, matches);
      return;
    case "separated":
      collectFieldPaths(expression.item, [...path, 0], selector, matches);
      collectFieldPaths(expression.separator, [...path, 1], selector, matches);
      return;
    case "ref":
    case "literal":
      return;
  }
}

function renderRuleExpression(
  ruleName: string,
  expression: AnalyzedExpression,
  context: RenderContext,
  inlineStack: ReadonlySet<string>,
): string {
  let metadata = context.normalizedRules.get(ruleName);
  if (metadata === undefined) {
    metadata = { paths: new Map() };
  }
  const rendered = renderExpression(
    ruleName,
    expression,
    [],
    metadata,
    context,
    inlineStack,
  );
  return applyToken(rendered, metadata.token);
}

function renderExpression(
  ruleName: string,
  expression: AnalyzedExpression,
  path: readonly number[],
  metadata: NormalizedRuleMetadata,
  context: RenderContext,
  inlineStack: ReadonlySet<string>,
): string {
  const pathMetadata = metadata.paths.get(pathKey(path));
  let rendered = renderRawExpression(
    ruleName,
    expression,
    path,
    metadata,
    context,
    inlineStack,
  );

  if (expression.kind !== "ref") {
    rendered = applyWrap(rendered, pathMetadata?.wrap);
    rendered = applyNodeAlias(rendered, pathMetadata, context);
  }
  if (pathMetadata?.field !== undefined) {
    rendered = `field(${JSON.stringify(pathMetadata.field)}, ${rendered})`;
  }
  return rendered;
}

function renderRawExpression(
  ruleName: string,
  expression: AnalyzedExpression,
  path: readonly number[],
  metadata: NormalizedRuleMetadata,
  context: RenderContext,
  inlineStack: ReadonlySet<string>,
): string {
  switch (expression.kind) {
    case "field":
      return `field(${JSON.stringify(expression.name)}, ${
        renderExpression(
          ruleName,
          expression.expression,
          [...path, 0],
          metadata,
          context,
          inlineStack,
        )
      })`;
    case "ref":
      return renderReference(
        ruleName,
        expression.name,
        metadata.paths.get(pathKey(path)),
        context,
        inlineStack,
      );
    case "literal":
      return JSON.stringify(expression.value);
    case "sequence":
      return `seq(${
        expression.items.map((child, index) =>
          renderExpression(
            ruleName,
            child,
            [...path, index],
            metadata,
            context,
            inlineStack,
          )
        ).join(", ")
      })`;
    case "choice":
      return `choice(${
        expression.options.map((child, index) =>
          renderExpression(
            ruleName,
            child,
            [...path, index],
            metadata,
            context,
            inlineStack,
          )
        ).join(", ")
      })`;
    case "optional":
      return `optional(${
        renderExpression(
          ruleName,
          expression.expression,
          [...path, 0],
          metadata,
          context,
          inlineStack,
        )
      })`;
    case "repeat":
      return `repeat(${
        renderExpression(
          ruleName,
          expression.expression,
          [...path, 0],
          metadata,
          context,
          inlineStack,
        )
      })`;
    case "repeat1":
      return `repeat1(${
        renderExpression(
          ruleName,
          expression.expression,
          [...path, 0],
          metadata,
          context,
          inlineStack,
        )
      })`;
    case "separated": {
      const element = renderExpression(
        ruleName,
        expression.item,
        [...path, 0],
        metadata,
        context,
        inlineStack,
      );
      const separator = renderExpression(
        ruleName,
        expression.separator,
        [...path, 1],
        metadata,
        context,
        inlineStack,
      );
      return `seq(${element}, repeat(seq(${separator}, ${element})))`;
    }
  }
}

function renderReference(
  ruleName: string,
  referenceName: string,
  metadata: TreeSitterPathMetadata | undefined,
  context: RenderContext,
  inlineStack: ReadonlySet<string>,
): string {
  let rendered = `$.${referenceName}`;
  if (metadata?.inline_path === true || metadata?.hidden_path === true) {
    const target = context.rules.get(referenceName);
    if (target === undefined) {
      treeSitterMetadataError(
        "METADATA_PATH_TARGET_MISMATCH",
        `Rule '${ruleName}' cannot inline non-rule reference '${referenceName}'.`,
      );
    }
    if (inlineStack.has(referenceName)) {
      treeSitterMetadataError(
        "METADATA_RECURSIVE_INLINE",
        `Rule '${ruleName}' cannot inline recursive rule '${referenceName}'.`,
      );
    }
    const nextStack = new Set(inlineStack);
    nextStack.add(referenceName);
    rendered = renderRuleExpression(referenceName, target, context, nextStack);
  } else if (metadata?.alias_ref !== undefined) {
    rendered = `alias(${rendered}, $.${metadata.alias_ref})`;
  }
  return applyWrap(rendered, metadata?.wrap);
}

function applyNodeAlias(
  rendered: string,
  metadata: TreeSitterPathMetadata | undefined,
  context: RenderContext,
): string {
  if (metadata?.alias_node === undefined) {
    return rendered;
  }
  const existing = context.aliasRules.get(metadata.alias_node);
  if (existing !== undefined && existing !== rendered) {
    treeSitterMetadataError(
      "METADATA_ALIAS_CONFLICT",
      `Alias node '${metadata.alias_node}' has conflicting expressions.`,
    );
  }
  context.aliasRules.set(metadata.alias_node, rendered);
  return `$.${metadata.alias_node}`;
}

function applyWrap(
  rendered: string,
  metadata: TreeSitterRuleWrap | undefined,
): string {
  if (metadata === undefined) {
    return rendered;
  }
  if (metadata.kind === "prec") {
    return `prec(${metadata.value}, ${rendered})`;
  }
  if (metadata.value === undefined) {
    return `${metadata.kind}(${rendered})`;
  }
  return `${metadata.kind}(${metadata.value}, ${rendered})`;
}

function applyToken(
  rendered: string,
  metadata: TreeSitterRuleToken | undefined,
): string {
  if (metadata === undefined) {
    return rendered;
  }
  return `${metadata.kind}(${rendered})`;
}

function renderToken(token: TreeSitterTokenPlan): string {
  const regex = formatRegexLiteral(token.pattern);
  if (token.priority !== 0) {
    return `token(prec(${token.priority}, ${regex}))`;
  }
  if (token.kind === "token") {
    return `token(${regex})`;
  }
  return regex;
}

function renderExtra(extra: TreeSitterExtra): string {
  if (extra.kind === "rule") {
    return `$.${extra.name}`;
  }
  return formatRegexLiteral(extra.value);
}

function formatRegexLiteral(pattern: string): string {
  let rendered = "";
  let escaped = false;
  let inCharacterClass = false;
  for (const character of pattern) {
    if (character === "/" && !escaped && !inCharacterClass) {
      rendered += "\\/";
    } else {
      rendered += character;
    }
    if (character === "\\") {
      escaped = !escaped;
      continue;
    }
    if (!escaped && character === "[") {
      inCharacterClass = true;
    }
    if (!escaped && character === "]") {
      inCharacterClass = false;
    }
    escaped = false;
  }
  return `/${rendered}/`;
}

function collectInlineRules(metadata: BabaMetadata): string[] {
  const rules = new Set<string>();
  if (metadata.inline !== undefined) {
    for (const rule of metadata.inline) {
      rules.add(rule);
    }
  }
  if (metadata.rules !== undefined) {
    for (const [ruleName, ruleMetadata] of Object.entries(metadata.rules)) {
      if (ruleMetadata.paths?.[""]?.hidden_path === true) {
        rules.add(ruleName);
      }
    }
  }
  return [...rules];
}

function renderRuleRefArray(names: readonly string[]): string {
  return `[${names.map((name) => `$.${name}`).join(", ")}]`;
}

function formatRuleKey(name: string): string {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) {
    return name;
  }
  return JSON.stringify(name);
}

function pathKey(path: readonly number[]): string {
  return path.join(".");
}

function validateTreeSitterMetadata(
  plan: TreeSitterPlan,
  metadata: BabaMetadata,
): void {
  const parserRules = new Set(plan.rules.map((rule) => rule.name));
  const tokenRules = new Set(plan.tokens.map((token) => token.name));
  const knownSymbols = new Set([
    ...parserRules,
    ...tokenRules,
    ...plan.externals,
  ]);

  for (const [index, external] of plan.externals.entries()) {
    validateSymbolName(external, `metadata.externals[${index}]`);
    if (parserRules.has(external) || tokenRules.has(external)) {
      treeSitterMetadataError(
        "METADATA_EXTERNAL_CONFLICT",
        `External token '${external}' conflicts with a grammar declaration.`,
        `metadata.externals[${index}]`,
      );
    }
  }
  if (metadata.word !== undefined && !tokenRules.has(metadata.word)) {
    treeSitterMetadataError(
      "METADATA_UNKNOWN_REFERENCE",
      `Unknown Tree-sitter word token '${metadata.word}'.`,
      "metadata.word",
    );
  }
  validateRuleList(metadata.supertypes, parserRules, "supertypes");
  validateRuleList(metadata.inline, parserRules, "inline");
  if (metadata.conflicts !== undefined) {
    for (const [conflictIndex, conflict] of metadata.conflicts.entries()) {
      for (const [ruleIndex, rule] of conflict.entries()) {
        if (!parserRules.has(rule)) {
          treeSitterMetadataError(
            "METADATA_UNKNOWN_REFERENCE",
            `Unknown Tree-sitter conflict rule '${rule}'.`,
            `metadata.conflicts[${conflictIndex}][${ruleIndex}]`,
          );
        }
      }
    }
  }
  if (metadata.extras !== undefined) {
    for (const [index, extra] of metadata.extras.entries()) {
      if (extra.kind === "rule" && !knownSymbols.has(extra.name)) {
        treeSitterMetadataError(
          "METADATA_UNKNOWN_REFERENCE",
          `Unknown Tree-sitter extra rule '${extra.name}'.`,
          `metadata.extras[${index}].name`,
        );
      }
    }
  }
  if (metadata.rules === undefined) {
    return;
  }
  const aliasNodes = new Set<string>();
  for (const [ruleName, ruleMetadata] of Object.entries(metadata.rules)) {
    const expression = plan.rules.find((rule) => rule.name === ruleName);
    if (expression === undefined) {
      treeSitterMetadataError(
        "METADATA_UNKNOWN_RULE",
        `Unknown Tree-sitter metadata rule '${ruleName}'.`,
        `metadata.rules.${ruleName}`,
      );
    }
    if (!plan.reachableRules.has(ruleName)) {
      treeSitterMetadataError(
        "METADATA_UNREACHABLE_RULE",
        `Tree-sitter metadata rule '${ruleName}' is unreachable from '${plan.rootRuleName}'.`,
        `metadata.rules.${ruleName}`,
      );
    }
    validateRuleMetadata(ruleName, expression.expression, ruleMetadata);
    if (ruleMetadata.paths === undefined) {
      continue;
    }
    for (const [selector, pathMetadata] of Object.entries(ruleMetadata.paths)) {
      if (pathMetadata.alias_node === undefined) {
        continue;
      }
      const path = `metadata.rules.${ruleName}.paths.${selector}.alias_node`;
      if (knownSymbols.has(pathMetadata.alias_node)) {
        treeSitterMetadataError(
          "METADATA_ALIAS_CONFLICT",
          `Alias node '${pathMetadata.alias_node}' conflicts with a grammar declaration.`,
          path,
        );
      }
      if (aliasNodes.has(pathMetadata.alias_node)) {
        treeSitterMetadataError(
          "METADATA_DUPLICATE_ALIAS",
          `Alias node '${pathMetadata.alias_node}' is declared more than once.`,
          path,
        );
      }
      aliasNodes.add(pathMetadata.alias_node);
    }
  }
}

function validateRuleList(
  rules: readonly string[] | undefined,
  knownRules: ReadonlySet<string>,
  metadataName: string,
): void {
  if (rules === undefined) {
    return;
  }
  for (const [index, rule] of rules.entries()) {
    if (!knownRules.has(rule)) {
      treeSitterMetadataError(
        "METADATA_UNKNOWN_REFERENCE",
        `Unknown Tree-sitter ${metadataName} rule '${rule}'.`,
        `metadata.${metadataName}[${index}]`,
      );
    }
  }
}

function validateRuleMetadata(
  ruleName: string,
  expression: AnalyzedExpression,
  metadata: TreeSitterRuleMetadata,
): void {
  if (metadata.paths !== undefined) {
    for (const [selector, pathMetadata] of Object.entries(metadata.paths)) {
      const path = `metadata.rules.${ruleName}.paths.${selector}`;
      if (
        pathMetadata.alias_ref !== undefined &&
        pathMetadata.alias_node !== undefined
      ) {
        treeSitterMetadataError(
          "METADATA_PATH_CONFLICT",
          `Rule '${ruleName}' path '${selector}' cannot declare two aliases.`,
          path,
        );
      }
      if (
        (pathMetadata.inline_path === true ||
          pathMetadata.hidden_path === true) &&
        (pathMetadata.alias_ref !== undefined ||
          pathMetadata.alias_node !== undefined)
      ) {
        treeSitterMetadataError(
          "METADATA_PATH_CONFLICT",
          `Rule '${ruleName}' path '${selector}' cannot be both inlined and aliased.`,
          path,
        );
      }
    }
  }
  const normalized = normalizeRuleMetadata(ruleName, expression, metadata);
  for (const [path, pathMetadata] of normalized.paths) {
    const target = expressionAtPath(ruleName, expression, path);
    if (pathMetadata.alias_ref !== undefined) {
      validateSymbolName(
        pathMetadata.alias_ref,
        `metadata.rules.${ruleName}.paths.${path}.alias_ref`,
      );
      if (target.kind !== "ref") {
        treeSitterMetadataError(
          "METADATA_PATH_TARGET_MISMATCH",
          `Alias reference on rule '${ruleName}' must target a reference.`,
          `metadata.rules.${ruleName}.paths.${path}.alias_ref`,
        );
      }
    }
    if (pathMetadata.alias_node !== undefined) {
      validateSymbolName(
        pathMetadata.alias_node,
        `metadata.rules.${ruleName}.paths.${path}.alias_node`,
      );
      if (target.kind === "ref") {
        treeSitterMetadataError(
          "METADATA_PATH_TARGET_MISMATCH",
          `Alias node on rule '${ruleName}' must target a non-reference expression.`,
          `metadata.rules.${ruleName}.paths.${path}.alias_node`,
        );
      }
    }
    if (
      (pathMetadata.inline_path === true ||
        pathMetadata.hidden_path === true) &&
      target.kind !== "ref" && path !== ""
    ) {
      treeSitterMetadataError(
        "METADATA_PATH_TARGET_MISMATCH",
        `Hidden or inline path on rule '${ruleName}' must target a reference.`,
        `metadata.rules.${ruleName}.paths.${path}`,
      );
    }
  }
}

function expressionAtPath(
  ruleName: string,
  expression: AnalyzedExpression,
  path: string,
): AnalyzedExpression {
  if (path === "") {
    return expression;
  }
  const indexes = path.split(".").map(Number);
  let current = expression;
  for (const index of indexes) {
    if (current.kind === "field") {
      if (index !== 0) {
        break;
      }
      current = current.expression;
      continue;
    }
    if (current.kind === "sequence") {
      const child = current.items[index];
      if (child === undefined) {
        break;
      }
      current = child;
      continue;
    }
    if (current.kind === "choice") {
      const child = current.options[index];
      if (child === undefined) {
        break;
      }
      current = child;
      continue;
    }
    if (
      current.kind === "optional" || current.kind === "repeat" ||
      current.kind === "repeat1"
    ) {
      if (index !== 0) {
        break;
      }
      current = current.expression;
      continue;
    }
    if (current.kind === "separated") {
      if (index === 0) {
        current = current.item;
        continue;
      }
      if (index === 1) {
        current = current.separator;
        continue;
      }
    }
    break;
  }
  return current;
}

function validateSymbolName(name: string, path: string): void {
  if (/^[_A-Za-z$][_A-Za-z0-9$]*$/.test(name)) {
    return;
  }
  treeSitterMetadataError(
    "METADATA_INVALID_SYMBOL",
    `Invalid Tree-sitter symbol name '${name}'.`,
    path,
  );
}

function treeSitterMetadataError(
  code: string,
  message: string,
  path?: string,
): never {
  throw new BabaError({
    code,
    severity: "error",
    backend: "tree-sitter",
    message,
    path,
  });
}
