const crateRoot = new URL(
  "../src/targets/runtime/wasm_engine_rs/",
  import.meta.url,
);
const outputPath = new URL(
  "../src/targets/runtime/wasm_core_runtime_bytes.ts",
  import.meta.url,
);
const wasmPath = new URL(
  "../src/targets/runtime/wasm_engine_rs/target/wasm32-unknown-unknown/release/baba_wasm_lexer_engine.wasm",
  import.meta.url,
);
const checkOnly = Deno.args.includes("--check");

const command = new Deno.Command("cargo", {
  args: [
    "build",
    "--release",
    "--target",
    "wasm32-unknown-unknown",
  ],
  cwd: crateRoot.pathname,
  stdout: "inherit",
  stderr: "inherit",
});
const result = await command.output();
if (!result.success) {
  Deno.exit(result.code);
}

const bytes = await Deno.readFile(wasmPath);
if (!WebAssembly.validate(bytes)) {
  throw new Error("Built Rust lexer engine is not valid WebAssembly.");
}

let binary = "";
for (const byte of bytes) {
  binary += String.fromCharCode(byte);
}
const base64 = btoa(binary);
const matchedChunks = base64.match(/.{1,100}/g);
let chunks: string[] = [];
if (matchedChunks !== null) {
  chunks = matchedChunks;
}
const source =
  `// Generated by scripts/build_wasm_engine.ts. Do not edit by hand.\n\nconst WASM_CORE_RUNTIME_BASE64 = [\n${
    chunks.map((chunk) => `  "${chunk}",`).join("\n")
  }\n].join("");\n\nexport function wasmCoreRuntimeBytes(): Uint8Array {\n  const binary = atob(WASM_CORE_RUNTIME_BASE64);\n  const bytes = new Uint8Array(binary.length);\n  for (let index = 0; index < binary.length; index++) {\n    bytes[index] = binary.charCodeAt(index);\n  }\n  return bytes;\n}\n`;

if (checkOnly) {
  let current: string;
  try {
    current = await Deno.readTextFile(outputPath);
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      throw new Error(
        `${outputPath.pathname} is missing; run deno task build:wasm-engine.`,
      );
    }
    throw error;
  }
  if (current !== source) {
    throw new Error(
      `${outputPath.pathname} is stale; run deno task build:wasm-engine.`,
    );
  }
  console.log(
    `Verified ${outputPath.pathname} (${bytes.byteLength} bytes)`,
  );
  Deno.exit(0);
}

await Deno.writeTextFile(outputPath, source);
console.log(`Wrote ${outputPath.pathname} (${bytes.byteLength} bytes)`);
