export const PARSER_DIAGNOSTIC_CODE_PARSE_LEXICAL_ERROR = 1;
export const PARSER_DIAGNOSTIC_CODE_PARSE_UNEXPECTED_TOKEN = 2;
export const PARSER_DIAGNOSTIC_CODE_PARSE_TRAILING_INPUT = 3;
export const PARSER_DIAGNOSTIC_CODE_PARSE_INVALID_TOKEN_STREAM = 4;
export const PARSER_DIAGNOSTIC_CODE_INTERNAL_ERROR = 5;
export const PARSER_DIAGNOSTIC_CODE_BRANCH_LIMIT = 6;

export const PARSER_DIAGNOSTIC_CODES = {
  parseLexicalError: PARSER_DIAGNOSTIC_CODE_PARSE_LEXICAL_ERROR,
  parseUnexpectedToken: PARSER_DIAGNOSTIC_CODE_PARSE_UNEXPECTED_TOKEN,
  parseTrailingInput: PARSER_DIAGNOSTIC_CODE_PARSE_TRAILING_INPUT,
  parseInvalidTokenStream: PARSER_DIAGNOSTIC_CODE_PARSE_INVALID_TOKEN_STREAM,
  internalError: PARSER_DIAGNOSTIC_CODE_INTERNAL_ERROR,
  branchLimit: PARSER_DIAGNOSTIC_CODE_BRANCH_LIMIT,
} as const;
