export const RUNTIME_LANGUAGE_VERSION = 1 as const;
export const RUNTIME_LANGUAGE_SEMANTICS = "baba-runtime-language-v1" as const;

export interface RuntimeLanguageProgram {
  readonly name: string;
  readonly entry: string;
  readonly functions: readonly RuntimeLanguageFunction[];
}

export interface RuntimeLanguageFunction {
  readonly name: string;
  readonly parameters?: readonly RuntimeLanguageVariable[];
  readonly locals?: readonly RuntimeLanguageVariable[];
  readonly result: RuntimeScalarType;
  readonly body: readonly RuntimeStatement[];
}

export interface RuntimeLanguageVariable {
  readonly name: string;
  readonly type: RuntimeScalarType;
}

export type RuntimeScalarType = "u32";

export type RuntimeStatement =
  | {
    readonly kind: "return";
    readonly expression: RuntimeExpression;
  }
  | {
    readonly kind: "trap";
  }
  | {
    readonly kind: "setLocal";
    readonly name: string;
    readonly expression: RuntimeExpression;
  }
  | {
    readonly kind: "if";
    readonly condition: RuntimeExpression;
    readonly consequent: readonly RuntimeStatement[];
    readonly alternate?: readonly RuntimeStatement[];
  }
  | {
    readonly kind: "while";
    readonly condition: RuntimeExpression;
    readonly body: readonly RuntimeStatement[];
  };

export type RuntimeExpression =
  | {
    readonly kind: "u32";
    readonly value: number;
  }
  | {
    readonly kind: "local";
    readonly name: string;
  }
  | {
    readonly kind:
      | "addU32"
      | "subU32"
      | "mulU32"
      | "divU32"
      | "eqU32"
      | "ltS32"
      | "shlU32"
      | "shrU32";
    readonly left: RuntimeExpression;
    readonly right: RuntimeExpression;
  };

export class RuntimeLanguageTrap extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RuntimeLanguageTrap";
  }
}

export interface RuntimeLanguageTypeScriptFunctionOptions {
  readonly exported?: boolean;
}

export function emitRuntimeLanguageTypeScript(
  program: RuntimeLanguageProgram,
): string {
  const entry = runtimeLanguageEntryFunction(program);
  const parameters = functionParameters(entry);
  const locals = functionLocals(entry);
  const localNames = new Set([
    ...parameters.map((parameter) => parameter.name),
    ...locals.map((local) => local.name),
  ]);
  validateVariableSet(entry, parameters, locals);
  return `// Generated by @mewhhaha/baba runtime-language stage 0.
export const runtimeLanguageVersion = ${RUNTIME_LANGUAGE_VERSION};
export const runtimeLanguageSemantics = ${
    JSON.stringify(RUNTIME_LANGUAGE_SEMANTICS)
  } as const;

export class RuntimeLanguageTrap extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RuntimeLanguageTrap";
  }
}

function divU32(left: number, right: number): number {
  const divisor = right >>> 0;
  if (divisor === 0) throw new RuntimeLanguageTrap("division by zero");
  return Math.trunc((left >>> 0) / divisor) >>> 0;
}

export function ${identifier(entry.name)}(${
    parameters.map((parameter) => `${identifier(parameter.name)}: number`).join(
      ", ",
    )
  }): number {
${locals.map((local) => `  let ${identifier(local.name)} = 0;`).join("\n")}${
    locals.length > 0 ? "\n" : ""
  }${
    entry.body.map((statement) =>
      emitTypeScriptStatement(statement, localNames, "  ")
    ).join("\n")
  }
  throw new RuntimeLanguageTrap("function completed without a return");
}
`;
}

export function emitRuntimeLanguageTypeScriptFunction(
  program: RuntimeLanguageProgram,
  options: RuntimeLanguageTypeScriptFunctionOptions = {},
): string {
  const entry = runtimeLanguageEntryFunction(program);
  const parameters = functionParameters(entry);
  const locals = functionLocals(entry);
  const localNames = new Set([
    ...parameters.map((parameter) => parameter.name),
    ...locals.map((local) => local.name),
  ]);
  validateVariableSet(entry, parameters, locals);
  const prefix = options.exported ? "export " : "";
  return `class RuntimeLanguageTrap extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RuntimeLanguageTrap";
  }
}

${prefix}function ${identifier(entry.name)}(${
    parameters.map((parameter) => `${identifier(parameter.name)}: number`).join(
      ", ",
    )
  }): number {
${locals.map((local) => `  let ${identifier(local.name)} = 0;`).join("\n")}${
    locals.length > 0 ? "\n" : ""
  }${
    entry.body.map((statement) =>
      emitTypeScriptStatement(statement, localNames, "  ")
    ).join("\n")
  }
  throw new RuntimeLanguageTrap("function completed without a return");
}
`;
}

export function compileRuntimeLanguageWasm(
  program: RuntimeLanguageProgram,
): Uint8Array {
  const entry = runtimeLanguageEntryFunction(program);
  const parameters = functionParameters(entry);
  const locals = functionLocals(entry);
  validateVariableSet(entry, parameters, locals);
  const localIndexes = localIndexMap(parameters, locals);
  const body = [
    ...localDeclarations(locals),
    ...entry.body.flatMap((statement) =>
      emitWasmStatement(statement, localIndexes)
    ),
    0x00,
    0x0b,
  ];
  const sections = [
    section(1, [
      ...u32(1),
      0x60,
      ...u32(parameters.length),
      ...parameters.flatMap(wasmType),
      0x01,
      0x7f,
    ]),
    section(3, [
      ...u32(1),
      ...u32(0),
    ]),
    section(7, [
      ...u32(1),
      ...name(entry.name),
      0x00,
      ...u32(0),
    ]),
    section(10, [
      ...u32(1),
      ...u32(body.length),
      ...body,
    ]),
  ];
  return new Uint8Array([
    0x00,
    0x61,
    0x73,
    0x6d,
    0x01,
    0x00,
    0x00,
    0x00,
    ...sections.flat(),
  ]);
}

export function runtimeLanguageEntryFunction(
  program: RuntimeLanguageProgram,
): RuntimeLanguageFunction {
  const entry = program.functions.find((fn) => fn.name === program.entry);
  if (!entry) {
    throw new Error(
      `Runtime-language program '${program.name}' has no entry function '${program.entry}'.`,
    );
  }
  if (entry.result !== "u32") {
    throw new Error(
      `Runtime-language function '${entry.name}' has unsupported result type '${entry.result}'.`,
    );
  }
  return entry;
}

function emitTypeScriptStatement(
  statement: RuntimeStatement,
  locals: ReadonlySet<string>,
  indent: string,
): string {
  switch (statement.kind) {
    case "trap":
      return `${indent}throw new RuntimeLanguageTrap("explicit trap");`;
    case "return":
      return `${indent}return (${
        emitTypeScriptExpression(statement.expression, locals)
      }) >>> 0;`;
    case "setLocal":
      assertKnownLocal(statement.name, locals);
      return `${indent}${identifier(statement.name)} = (${
        emitTypeScriptExpression(statement.expression, locals)
      }) >>> 0;`;
    case "if":
      return emitTypeScriptIf(statement, locals, indent);
    case "while":
      return emitTypeScriptWhile(statement, locals, indent);
  }
}

function emitTypeScriptIf(
  statement: Extract<RuntimeStatement, { readonly kind: "if" }>,
  locals: ReadonlySet<string>,
  indent: string,
): string {
  const consequent = emitTypeScriptBlock(
    statement.consequent,
    locals,
    `${indent}  `,
  );
  const alternate = emitTypeScriptBlock(
    statement.alternate ?? [],
    locals,
    `${indent}  `,
  );
  if (alternate.length === 0) {
    return `${indent}if ((${
      emitTypeScriptExpression(statement.condition, locals)
    }) !== 0) {\n${consequent}${consequent ? "\n" : ""}${indent}}`;
  }
  return `${indent}if ((${
    emitTypeScriptExpression(statement.condition, locals)
  }) !== 0) {\n${consequent}${
    consequent ? "\n" : ""
  }${indent}} else {\n${alternate}${alternate ? "\n" : ""}${indent}}`;
}

function emitTypeScriptWhile(
  statement: Extract<RuntimeStatement, { readonly kind: "while" }>,
  locals: ReadonlySet<string>,
  indent: string,
): string {
  const body = emitTypeScriptBlock(statement.body, locals, `${indent}  `);
  return `${indent}while ((${
    emitTypeScriptExpression(statement.condition, locals)
  }) !== 0) {\n${body}${body ? "\n" : ""}${indent}}`;
}

function emitTypeScriptBlock(
  statements: readonly RuntimeStatement[],
  locals: ReadonlySet<string>,
  indent: string,
): string {
  return statements.map((statement) =>
    emitTypeScriptStatement(statement, locals, indent)
  ).join("\n");
}

function emitTypeScriptExpression(
  expression: RuntimeExpression,
  locals: ReadonlySet<string>,
): string {
  switch (expression.kind) {
    case "u32":
      return String(expression.value >>> 0);
    case "local":
      assertKnownLocal(expression.name, locals);
      return identifier(expression.name);
    case "addU32":
      return `((${emitTypeScriptExpression(expression.left, locals)}) + (${
        emitTypeScriptExpression(expression.right, locals)
      })) >>> 0`;
    case "subU32":
      return `((${emitTypeScriptExpression(expression.left, locals)}) - (${
        emitTypeScriptExpression(expression.right, locals)
      })) >>> 0`;
    case "mulU32":
      return `Math.imul((${
        emitTypeScriptExpression(expression.left, locals)
      }) >>> 0, (${
        emitTypeScriptExpression(expression.right, locals)
      }) >>> 0) >>> 0`;
    case "divU32":
      return `divU32(${emitTypeScriptExpression(expression.left, locals)}, ${
        emitTypeScriptExpression(expression.right, locals)
      })`;
    case "eqU32":
      return `(((${
        emitTypeScriptExpression(expression.left, locals)
      }) >>> 0) === ((${
        emitTypeScriptExpression(expression.right, locals)
      }) >>> 0) ? 1 : 0)`;
    case "ltS32":
      return `(((${
        emitTypeScriptExpression(expression.left, locals)
      }) | 0) < ((${
        emitTypeScriptExpression(expression.right, locals)
      }) | 0) ? 1 : 0)`;
    case "shlU32":
      return `((${emitTypeScriptExpression(expression.left, locals)}) << ((${
        emitTypeScriptExpression(expression.right, locals)
      }) & 31)) >>> 0`;
    case "shrU32":
      return `((${emitTypeScriptExpression(expression.left, locals)}) >>> ((${
        emitTypeScriptExpression(expression.right, locals)
      }) & 31)) >>> 0`;
  }
}

function emitWasmStatement(
  statement: RuntimeStatement,
  locals: ReadonlyMap<string, number>,
): number[] {
  switch (statement.kind) {
    case "trap":
      return [0x00];
    case "return":
      return [
        ...emitWasmExpression(statement.expression, locals),
        0x0f,
      ];
    case "setLocal":
      return [
        ...emitWasmExpression(statement.expression, locals),
        0x21,
        ...u32(localIndex(statement.name, locals)),
      ];
    case "if":
      return [
        ...emitWasmExpression(statement.condition, locals),
        0x04,
        0x40,
        ...statement.consequent.flatMap((item) =>
          emitWasmStatement(item, locals)
        ),
        ...(statement.alternate && statement.alternate.length > 0
          ? [
            0x05,
            ...statement.alternate.flatMap((item) =>
              emitWasmStatement(item, locals)
            ),
          ]
          : []),
        0x0b,
      ];
    case "while":
      return [
        0x02,
        0x40,
        0x03,
        0x40,
        ...emitWasmExpression(statement.condition, locals),
        0x45,
        0x0d,
        ...u32(1),
        ...statement.body.flatMap((item) => emitWasmStatement(item, locals)),
        0x0c,
        ...u32(0),
        0x0b,
        0x0b,
      ];
  }
}

function emitWasmExpression(
  expression: RuntimeExpression,
  locals: ReadonlyMap<string, number>,
): number[] {
  switch (expression.kind) {
    case "u32":
      return [0x41, ...i32(expression.value | 0)];
    case "local":
      return [0x20, ...u32(localIndex(expression.name, locals))];
    case "addU32":
      return binaryExpression(expression, locals, 0x6a);
    case "subU32":
      return binaryExpression(expression, locals, 0x6b);
    case "mulU32":
      return binaryExpression(expression, locals, 0x6c);
    case "divU32":
      return binaryExpression(expression, locals, 0x6e);
    case "eqU32":
      return binaryExpression(expression, locals, 0x46);
    case "ltS32":
      return binaryExpression(expression, locals, 0x48);
    case "shlU32":
      return binaryExpression(expression, locals, 0x74);
    case "shrU32":
      return binaryExpression(expression, locals, 0x76);
  }
}

function binaryExpression(
  expression: Extract<
    RuntimeExpression,
    { readonly left: RuntimeExpression; readonly right: RuntimeExpression }
  >,
  locals: ReadonlyMap<string, number>,
  opcode: number,
): number[] {
  return [
    ...emitWasmExpression(expression.left, locals),
    ...emitWasmExpression(expression.right, locals),
    opcode,
  ];
}

function functionParameters(
  fn: RuntimeLanguageFunction,
): readonly RuntimeLanguageVariable[] {
  return fn.parameters ?? [];
}

function functionLocals(
  fn: RuntimeLanguageFunction,
): readonly RuntimeLanguageVariable[] {
  return fn.locals ?? [];
}

function validateVariableSet(
  fn: RuntimeLanguageFunction,
  parameters: readonly RuntimeLanguageVariable[],
  locals: readonly RuntimeLanguageVariable[],
): void {
  const seen = new Set<string>();
  for (const variable of [...parameters, ...locals]) {
    if (variable.type !== "u32") {
      throw new Error(
        `Runtime-language variable '${variable.name}' has unsupported type '${variable.type}'.`,
      );
    }
    identifier(variable.name);
    if (seen.has(variable.name)) {
      throw new Error(
        `Runtime-language function '${fn.name}' has duplicate variable '${variable.name}'.`,
      );
    }
    seen.add(variable.name);
  }
  identifier(fn.name);
}

function localIndexMap(
  parameters: readonly RuntimeLanguageVariable[],
  locals: readonly RuntimeLanguageVariable[],
): ReadonlyMap<string, number> {
  const indexes = new Map<string, number>();
  for (const [index, parameter] of parameters.entries()) {
    indexes.set(parameter.name, index);
  }
  for (const [index, local] of locals.entries()) {
    indexes.set(local.name, parameters.length + index);
  }
  return indexes;
}

function localIndex(
  name: string,
  locals: ReadonlyMap<string, number>,
): number {
  const index = locals.get(name);
  if (index === undefined) {
    throw new Error(`Runtime-language variable '${name}' is not declared.`);
  }
  return index;
}

function assertKnownLocal(
  name: string,
  locals: ReadonlySet<string>,
): void {
  if (!locals.has(name)) {
    throw new Error(`Runtime-language variable '${name}' is not declared.`);
  }
}

function localDeclarations(
  locals: readonly RuntimeLanguageVariable[],
): number[] {
  if (locals.length === 0) return [0x00];
  return [0x01, ...u32(locals.length), 0x7f];
}

function wasmType(variable: RuntimeLanguageVariable): number[] {
  if (variable.type !== "u32") {
    throw new Error(
      `Runtime-language variable '${variable.name}' has unsupported type '${variable.type}'.`,
    );
  }
  return [0x7f];
}

function identifier(name: string): string {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) || RESERVED.has(name)) {
    throw new Error(
      `Runtime-language identifier '${name}' is not a valid target identifier.`,
    );
  }
  return name;
}

const RESERVED = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
]);

function section(id: number, payload: number[]): number[] {
  return [id, ...u32(payload.length), ...payload];
}

function name(value: string): number[] {
  const bytes = new TextEncoder().encode(value);
  return [...u32(bytes.length), ...bytes];
}

function u32(value: number): number[] {
  let remaining = value >>> 0;
  const bytes = [];
  do {
    let byte = remaining & 0x7f;
    remaining >>>= 7;
    if (remaining !== 0) byte |= 0x80;
    bytes.push(byte);
  } while (remaining !== 0);
  return bytes;
}

function i32(value: number): number[] {
  let remaining = value | 0;
  const bytes = [];
  let more = true;
  while (more) {
    let byte = remaining & 0x7f;
    remaining >>= 7;
    const signBitSet = (byte & 0x40) !== 0;
    more = !(
      (remaining === 0 && !signBitSet) ||
      (remaining === -1 && signBitSet)
    );
    if (more) byte |= 0x80;
    bytes.push(byte);
  }
  return bytes;
}
