export const RUNTIME_LANGUAGE_VERSION = 1 as const;
export const RUNTIME_LANGUAGE_SEMANTICS = "baba-runtime-language-v1" as const;

export interface RuntimeLanguageProgram {
  readonly name: string;
  readonly entry: string;
  readonly tables?: readonly RuntimeLanguageTable[];
  readonly functions: readonly RuntimeLanguageFunction[];
}

export interface RuntimeLanguageTable {
  readonly name: string;
  readonly type: RuntimeScalarType;
  readonly values: readonly number[];
}

export interface RuntimeLanguageFunction {
  readonly name: string;
  readonly parameters?: readonly RuntimeLanguageVariable[];
  readonly locals?: readonly RuntimeLanguageVariable[];
  readonly result: RuntimeScalarType;
  readonly body: readonly RuntimeStatement[];
}

export interface RuntimeLanguageVariable {
  readonly name: string;
  readonly type: RuntimeScalarType;
}

export type RuntimeScalarType = "u32";

export type RuntimeStatement =
  | {
    readonly kind: "return";
    readonly expression: RuntimeExpression;
  }
  | {
    readonly kind: "trap";
  }
  | {
    readonly kind: "setLocal";
    readonly name: string;
    readonly expression: RuntimeExpression;
  }
  | {
    readonly kind: "if";
    readonly condition: RuntimeExpression;
    readonly consequent: readonly RuntimeStatement[];
    readonly alternate?: readonly RuntimeStatement[];
  }
  | {
    readonly kind: "while";
    readonly condition: RuntimeExpression;
    readonly body: readonly RuntimeStatement[];
  };

export type RuntimeExpression =
  | {
    readonly kind: "u32";
    readonly value: number;
  }
  | {
    readonly kind: "local";
    readonly name: string;
  }
  | {
    readonly kind: "call";
    readonly function: string;
    readonly args: readonly RuntimeExpression[];
  }
  | {
    readonly kind: "loadTableU32";
    readonly table: string;
    readonly index: RuntimeExpression;
  }
  | {
    readonly kind:
      | "addU32"
      | "subU32"
      | "mulU32"
      | "divU32"
      | "eqU32"
      | "ltS32"
      | "shlU32"
      | "shrU32";
    readonly left: RuntimeExpression;
    readonly right: RuntimeExpression;
  };

export class RuntimeLanguageTrap extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RuntimeLanguageTrap";
  }
}

export interface RuntimeLanguageTypeScriptFunctionOptions {
  readonly exported?: boolean;
}

export function emitRuntimeLanguageTypeScript(
  program: RuntimeLanguageProgram,
): string {
  validateRuntimeLanguageProgram(program);
  return `// Generated by @mewhhaha/baba runtime-language stage 0.
export const runtimeLanguageVersion = ${RUNTIME_LANGUAGE_VERSION};
export const runtimeLanguageSemantics = ${
    JSON.stringify(RUNTIME_LANGUAGE_SEMANTICS)
  } as const;

${emitTypeScriptRuntime(program, { exportEntry: true })}
`;
}

export function emitRuntimeLanguageTypeScriptFunction(
  program: RuntimeLanguageProgram,
  options: RuntimeLanguageTypeScriptFunctionOptions = {},
): string {
  validateRuntimeLanguageProgram(program);
  return emitTypeScriptRuntime(program, { exportEntry: options.exported });
}

function emitTypeScriptRuntime(
  program: RuntimeLanguageProgram,
  options: { readonly exportEntry?: boolean },
): string {
  const functions = runtimeLanguageFunctions(program);
  const tables = runtimeLanguageTables(program);
  return `class RuntimeLanguageTrap extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RuntimeLanguageTrap";
  }
}

function divU32(left: number, right: number): number {
  const divisor = right >>> 0;
  if (divisor === 0) throw new RuntimeLanguageTrap("division by zero");
  return Math.trunc((left >>> 0) / divisor) >>> 0;
}

${tables.map(emitTypeScriptTable).join("\n")}
${tables.map((table) => emitTypeScriptTableLoader(table)).join("\n")}${
    tables.length > 0 ? "\n" : ""
  }
${
    functions.map((fn) =>
      emitTypeScriptFunction(program, fn, {
        exported: options.exportEntry === true && fn.name === program.entry,
      })
    ).join("\n")
  }`;
}

function emitTypeScriptTable(table: RuntimeLanguageTable): string {
  return `const ${runtimeTableIdentifier(table)}: readonly number[] = ${
    JSON.stringify(table.values.map((value) => value >>> 0))
  };`;
}

function emitTypeScriptTableLoader(table: RuntimeLanguageTable): string {
  const tableName = runtimeTableIdentifier(table);
  return `function ${
    runtimeTableLoaderIdentifier(table)
  }(index: number): number {
  const normalized = index >>> 0;
  if (normalized >= ${tableName}.length) {
    throw new RuntimeLanguageTrap("table index out of bounds");
  }
  return ${tableName}[normalized] >>> 0;
}
`;
}

function emitTypeScriptFunction(
  program: RuntimeLanguageProgram,
  fn: RuntimeLanguageFunction,
  options: { readonly exported?: boolean },
): string {
  const parameters = functionParameters(fn);
  const locals = functionLocals(fn);
  const localNames = new Set([
    ...parameters.map((parameter) => parameter.name),
    ...locals.map((local) => local.name),
  ]);
  const prefix = options.exported ? "export " : "";
  return `${prefix}function ${identifier(fn.name)}(${
    parameters.map((parameter) => `${identifier(parameter.name)}: number`).join(
      ", ",
    )
  }): number {
${locals.map((local) => `  let ${identifier(local.name)} = 0;`).join("\n")}${
    locals.length > 0 ? "\n" : ""
  }${
    fn.body.map((statement) =>
      emitTypeScriptStatement(statement, localNames, program, "  ")
    ).join("\n")
  }
  throw new RuntimeLanguageTrap("function completed without a return");
}
`;
}

export function compileRuntimeLanguageWasm(
  program: RuntimeLanguageProgram,
): Uint8Array {
  validateRuntimeLanguageProgram(program);
  const functions = runtimeLanguageFunctions(program);
  const tables = runtimeLanguageTables(program);
  const tableLayout = buildRuntimeTableLayout(tables);
  const tableLoaders = tables.map((table) => ({
    table,
    name: runtimeTableLoaderIdentifier(table),
    offset: tableLayout.offsets.get(table.name) ?? 0,
  }));
  const allFunctions = [
    ...functions.map((fn) => ({ kind: "program" as const, fn })),
    ...tableLoaders.map((loader) => ({ kind: "tableLoader" as const, loader })),
  ];
  const functionIndexes = new Map(
    functions.map((fn, index) => [fn.name, index]),
  );
  const tableLoaderIndexes = new Map(
    tableLoaders.map((loader, index) => [
      loader.table.name,
      functions.length + index,
    ]),
  );
  const entryIndex = functionIndex(program.entry, functionIndexes);
  const bodies = allFunctions.map((item) => {
    const body = item.kind === "program"
      ? wasmProgramFunctionBody(item.fn, functionIndexes, tableLoaderIndexes)
      : wasmTableLoaderBody(item.loader);
    return [...u32(body.length), ...body];
  });
  const sections = [
    section(1, [
      ...u32(allFunctions.length),
      ...allFunctions.flatMap((item) =>
        item.kind === "program"
          ? wasmFunctionType(item.fn)
          : wasmTableLoaderType()
      ),
    ]),
    section(3, [
      ...u32(allFunctions.length),
      ...allFunctions.map((_, index) => u32(index)).flat(),
    ]),
    ...(tables.length > 0
      ? [section(5, memorySection(tableLayout.bytes))]
      : []),
    section(7, [
      ...u32(1),
      ...name(program.entry),
      0x00,
      ...u32(entryIndex),
    ]),
    section(10, [
      ...u32(allFunctions.length),
      ...bodies.flat(),
    ]),
    ...(tables.length > 0 ? [section(11, dataSection(tableLayout.bytes))] : []),
  ];
  return new Uint8Array([
    0x00,
    0x61,
    0x73,
    0x6d,
    0x01,
    0x00,
    0x00,
    0x00,
    ...sections.flat(),
  ]);
}

export function runtimeLanguageEntryFunction(
  program: RuntimeLanguageProgram,
): RuntimeLanguageFunction {
  const entry = runtimeLanguageFunction(program, program.entry);
  if (entry.result !== "u32") {
    throw new Error(
      `Runtime-language function '${entry.name}' has unsupported result type '${entry.result}'.`,
    );
  }
  return entry;
}

function runtimeLanguageFunctions(
  program: RuntimeLanguageProgram,
): readonly RuntimeLanguageFunction[] {
  if (program.functions.length === 0) {
    throw new Error(
      `Runtime-language program '${program.name}' has no functions.`,
    );
  }
  return program.functions;
}

function runtimeLanguageFunction(
  program: RuntimeLanguageProgram,
  name: string,
): RuntimeLanguageFunction {
  const fn = program.functions.find((candidate) => candidate.name === name);
  if (!fn) {
    throw new Error(
      `Runtime-language program '${program.name}' has no function '${name}'.`,
    );
  }
  return fn;
}

function validateRuntimeLanguageProgram(program: RuntimeLanguageProgram): void {
  identifier(program.name);
  identifier(program.entry);
  runtimeLanguageEntryFunction(program);
  const functions = runtimeLanguageFunctions(program);
  const tables = runtimeLanguageTables(program);
  const tableNames = new Set<string>();
  for (const table of tables) {
    validateRuntimeLanguageTable(table);
    if (tableNames.has(table.name)) {
      throw new Error(
        `Runtime-language program '${program.name}' has duplicate table '${table.name}'.`,
      );
    }
    tableNames.add(table.name);
  }
  const names = new Set<string>();
  for (const fn of functions) {
    identifier(fn.name);
    assertNotReservedRuntimeName(fn.name);
    if (names.has(fn.name)) {
      throw new Error(
        `Runtime-language program '${program.name}' has duplicate function '${fn.name}'.`,
      );
    }
    names.add(fn.name);
    if (fn.result !== "u32") {
      throw new Error(
        `Runtime-language function '${fn.name}' has unsupported result type '${fn.result}'.`,
      );
    }
    validateVariableSet(fn, functionParameters(fn), functionLocals(fn));
  }
  const functionMap = new Map(functions.map((fn) => [fn.name, fn]));
  for (const fn of functions) {
    const locals = new Set([
      ...functionParameters(fn).map((parameter) => parameter.name),
      ...functionLocals(fn).map((local) => local.name),
    ]);
    for (const statement of fn.body) {
      validateStatement(statement, locals, functionMap, tableNames);
    }
  }
}

function validateRuntimeLanguageTable(table: RuntimeLanguageTable): void {
  identifier(table.name);
  assertNotReservedRuntimeName(table.name);
  if (table.type !== "u32") {
    throw new Error(
      `Runtime-language table '${table.name}' has unsupported type '${table.type}'.`,
    );
  }
  for (const value of table.values) {
    if (!Number.isInteger(value) || value < 0 || value > 0xffff_ffff) {
      throw new Error(
        `Runtime-language table '${table.name}' contains non-u32 value '${value}'.`,
      );
    }
  }
}

function validateStatement(
  statement: RuntimeStatement,
  locals: ReadonlySet<string>,
  functions: ReadonlyMap<string, RuntimeLanguageFunction>,
  tables: ReadonlySet<string>,
): void {
  switch (statement.kind) {
    case "trap":
      return;
    case "return":
      validateExpression(statement.expression, locals, functions, tables);
      return;
    case "setLocal":
      assertKnownLocal(statement.name, locals);
      validateExpression(statement.expression, locals, functions, tables);
      return;
    case "if":
      validateExpression(statement.condition, locals, functions, tables);
      for (const item of statement.consequent) {
        validateStatement(item, locals, functions, tables);
      }
      for (const item of statement.alternate ?? []) {
        validateStatement(item, locals, functions, tables);
      }
      return;
    case "while":
      validateExpression(statement.condition, locals, functions, tables);
      for (const item of statement.body) {
        validateStatement(item, locals, functions, tables);
      }
      return;
  }
}

function validateExpression(
  expression: RuntimeExpression,
  locals: ReadonlySet<string>,
  functions: ReadonlyMap<string, RuntimeLanguageFunction>,
  tables: ReadonlySet<string>,
): void {
  switch (expression.kind) {
    case "u32":
      return;
    case "local":
      assertKnownLocal(expression.name, locals);
      return;
    case "call": {
      const target = functions.get(expression.function);
      if (!target) {
        throw new Error(
          `Runtime-language function '${expression.function}' is not declared.`,
        );
      }
      validateCallExpression(expression, target);
      for (const argument of expression.args) {
        validateExpression(argument, locals, functions, tables);
      }
      return;
    }
    case "loadTableU32":
      if (!tables.has(expression.table)) {
        throw new Error(
          `Runtime-language table '${expression.table}' is not declared.`,
        );
      }
      validateSimpleTableIndex(expression.index, locals);
      return;
    default:
      validateExpression(expression.left, locals, functions, tables);
      validateExpression(expression.right, locals, functions, tables);
      return;
  }
}

function emitTypeScriptStatement(
  statement: RuntimeStatement,
  locals: ReadonlySet<string>,
  program: RuntimeLanguageProgram,
  indent: string,
): string {
  switch (statement.kind) {
    case "trap":
      return `${indent}throw new RuntimeLanguageTrap("explicit trap");`;
    case "return":
      return `${indent}return (${
        emitTypeScriptExpression(statement.expression, locals, program)
      }) >>> 0;`;
    case "setLocal":
      assertKnownLocal(statement.name, locals);
      return `${indent}${identifier(statement.name)} = (${
        emitTypeScriptExpression(statement.expression, locals, program)
      }) >>> 0;`;
    case "if":
      return emitTypeScriptIf(statement, locals, program, indent);
    case "while":
      return emitTypeScriptWhile(statement, locals, program, indent);
  }
}

function emitTypeScriptIf(
  statement: Extract<RuntimeStatement, { readonly kind: "if" }>,
  locals: ReadonlySet<string>,
  program: RuntimeLanguageProgram,
  indent: string,
): string {
  const consequent = emitTypeScriptBlock(
    statement.consequent,
    locals,
    program,
    `${indent}  `,
  );
  const alternate = emitTypeScriptBlock(
    statement.alternate ?? [],
    locals,
    program,
    `${indent}  `,
  );
  if (alternate.length === 0) {
    return `${indent}if ((${
      emitTypeScriptExpression(statement.condition, locals, program)
    }) !== 0) {\n${consequent}${consequent ? "\n" : ""}${indent}}`;
  }
  return `${indent}if ((${
    emitTypeScriptExpression(statement.condition, locals, program)
  }) !== 0) {\n${consequent}${
    consequent ? "\n" : ""
  }${indent}} else {\n${alternate}${alternate ? "\n" : ""}${indent}}`;
}

function emitTypeScriptWhile(
  statement: Extract<RuntimeStatement, { readonly kind: "while" }>,
  locals: ReadonlySet<string>,
  program: RuntimeLanguageProgram,
  indent: string,
): string {
  const body = emitTypeScriptBlock(
    statement.body,
    locals,
    program,
    `${indent}  `,
  );
  return `${indent}while ((${
    emitTypeScriptExpression(statement.condition, locals, program)
  }) !== 0) {\n${body}${body ? "\n" : ""}${indent}}`;
}

function emitTypeScriptBlock(
  statements: readonly RuntimeStatement[],
  locals: ReadonlySet<string>,
  program: RuntimeLanguageProgram,
  indent: string,
): string {
  return statements.map((statement) =>
    emitTypeScriptStatement(statement, locals, program, indent)
  ).join("\n");
}

function emitTypeScriptExpression(
  expression: RuntimeExpression,
  locals: ReadonlySet<string>,
  program: RuntimeLanguageProgram,
): string {
  switch (expression.kind) {
    case "u32":
      return String(expression.value >>> 0);
    case "local":
      assertKnownLocal(expression.name, locals);
      return identifier(expression.name);
    case "call": {
      const target = runtimeLanguageFunction(program, expression.function);
      validateCallExpression(expression, target);
      return `${identifier(expression.function)}(${
        expression.args.map((argument) =>
          emitTypeScriptExpression(argument, locals, program)
        ).join(", ")
      }) >>> 0`;
    }
    case "loadTableU32": {
      const table = runtimeLanguageTable(program, expression.table);
      validateSimpleTableIndex(expression.index, locals);
      return `${runtimeTableLoaderIdentifier(table)}(${
        emitTypeScriptExpression(expression.index, locals, program)
      }) >>> 0`;
    }
    case "addU32":
      return `((${
        emitTypeScriptExpression(expression.left, locals, program)
      }) + (${
        emitTypeScriptExpression(expression.right, locals, program)
      })) >>> 0`;
    case "subU32":
      return `((${
        emitTypeScriptExpression(expression.left, locals, program)
      }) - (${
        emitTypeScriptExpression(expression.right, locals, program)
      })) >>> 0`;
    case "mulU32":
      return `Math.imul((${
        emitTypeScriptExpression(expression.left, locals, program)
      }) >>> 0, (${
        emitTypeScriptExpression(expression.right, locals, program)
      }) >>> 0) >>> 0`;
    case "divU32":
      return `divU32(${
        emitTypeScriptExpression(expression.left, locals, program)
      }, ${emitTypeScriptExpression(expression.right, locals, program)})`;
    case "eqU32":
      return `(((${
        emitTypeScriptExpression(expression.left, locals, program)
      }) >>> 0) === ((${
        emitTypeScriptExpression(expression.right, locals, program)
      }) >>> 0) ? 1 : 0)`;
    case "ltS32":
      return `(((${
        emitTypeScriptExpression(expression.left, locals, program)
      }) | 0) < ((${
        emitTypeScriptExpression(expression.right, locals, program)
      }) | 0) ? 1 : 0)`;
    case "shlU32":
      return `((${
        emitTypeScriptExpression(expression.left, locals, program)
      }) << ((${
        emitTypeScriptExpression(expression.right, locals, program)
      }) & 31)) >>> 0`;
    case "shrU32":
      return `((${
        emitTypeScriptExpression(expression.left, locals, program)
      }) >>> ((${
        emitTypeScriptExpression(expression.right, locals, program)
      }) & 31)) >>> 0`;
  }
}

function emitWasmStatement(
  statement: RuntimeStatement,
  locals: ReadonlyMap<string, number>,
  functions: ReadonlyMap<string, number>,
  tables: ReadonlyMap<string, number>,
): number[] {
  switch (statement.kind) {
    case "trap":
      return [0x00];
    case "return":
      return [
        ...emitWasmExpression(statement.expression, locals, functions, tables),
        0x0f,
      ];
    case "setLocal":
      return [
        ...emitWasmExpression(statement.expression, locals, functions, tables),
        0x21,
        ...u32(localIndex(statement.name, locals)),
      ];
    case "if":
      return [
        ...emitWasmExpression(statement.condition, locals, functions, tables),
        0x04,
        0x40,
        ...statement.consequent.flatMap((item) =>
          emitWasmStatement(item, locals, functions, tables)
        ),
        ...(statement.alternate && statement.alternate.length > 0
          ? [
            0x05,
            ...statement.alternate.flatMap((item) =>
              emitWasmStatement(item, locals, functions, tables)
            ),
          ]
          : []),
        0x0b,
      ];
    case "while":
      return [
        0x02,
        0x40,
        0x03,
        0x40,
        ...emitWasmExpression(statement.condition, locals, functions, tables),
        0x45,
        0x0d,
        ...u32(1),
        ...statement.body.flatMap((item) =>
          emitWasmStatement(item, locals, functions, tables)
        ),
        0x0c,
        ...u32(0),
        0x0b,
        0x0b,
      ];
  }
}

function emitWasmExpression(
  expression: RuntimeExpression,
  locals: ReadonlyMap<string, number>,
  functions: ReadonlyMap<string, number>,
  tables: ReadonlyMap<string, number>,
): number[] {
  switch (expression.kind) {
    case "u32":
      return [0x41, ...i32(expression.value | 0)];
    case "local":
      return [0x20, ...u32(localIndex(expression.name, locals))];
    case "call":
      return [
        ...expression.args.flatMap((argument) =>
          emitWasmExpression(argument, locals, functions, tables)
        ),
        0x10,
        ...u32(functionIndex(expression.function, functions)),
      ];
    case "loadTableU32":
      return [
        ...emitWasmExpression(expression.index, locals, functions, tables),
        0x10,
        ...u32(tableLoaderIndex(expression.table, tables)),
      ];
    case "addU32":
      return binaryExpression(expression, locals, functions, tables, 0x6a);
    case "subU32":
      return binaryExpression(expression, locals, functions, tables, 0x6b);
    case "mulU32":
      return binaryExpression(expression, locals, functions, tables, 0x6c);
    case "divU32":
      return binaryExpression(expression, locals, functions, tables, 0x6e);
    case "eqU32":
      return binaryExpression(expression, locals, functions, tables, 0x46);
    case "ltS32":
      return binaryExpression(expression, locals, functions, tables, 0x48);
    case "shlU32":
      return binaryExpression(expression, locals, functions, tables, 0x74);
    case "shrU32":
      return binaryExpression(expression, locals, functions, tables, 0x76);
  }
}

function binaryExpression(
  expression: Extract<
    RuntimeExpression,
    { readonly left: RuntimeExpression; readonly right: RuntimeExpression }
  >,
  locals: ReadonlyMap<string, number>,
  functions: ReadonlyMap<string, number>,
  tables: ReadonlyMap<string, number>,
  opcode: number,
): number[] {
  return [
    ...emitWasmExpression(expression.left, locals, functions, tables),
    ...emitWasmExpression(expression.right, locals, functions, tables),
    opcode,
  ];
}

function wasmProgramFunctionBody(
  fn: RuntimeLanguageFunction,
  functions: ReadonlyMap<string, number>,
  tables: ReadonlyMap<string, number>,
): number[] {
  const localIndexes = localIndexMap(
    functionParameters(fn),
    functionLocals(fn),
  );
  return [
    ...localDeclarations(functionLocals(fn)),
    ...fn.body.flatMap((statement) =>
      emitWasmStatement(statement, localIndexes, functions, tables)
    ),
    0x00,
    0x0b,
  ];
}

function wasmTableLoaderBody(
  loader: RuntimeTableLoader,
): number[] {
  return [
    0x00,
    0x20,
    ...u32(0),
    0x41,
    ...i32(loader.table.values.length),
    0x4f,
    0x04,
    0x40,
    0x00,
    0x0b,
    0x41,
    ...i32(loader.offset),
    0x20,
    ...u32(0),
    0x41,
    ...i32(2),
    0x74,
    0x6a,
    0x28,
    ...u32(2),
    ...u32(0),
    0x0f,
    0x00,
    0x0b,
  ];
}

interface RuntimeTableLoader {
  readonly table: RuntimeLanguageTable;
  readonly name: string;
  readonly offset: number;
}

interface RuntimeTableLayout {
  readonly offsets: ReadonlyMap<string, number>;
  readonly bytes: Uint8Array;
}

function buildRuntimeTableLayout(
  tables: readonly RuntimeLanguageTable[],
): RuntimeTableLayout {
  const offsets = new Map<string, number>();
  const bytes: number[] = [];
  for (const table of tables) {
    while (bytes.length % 4 !== 0) bytes.push(0);
    offsets.set(table.name, bytes.length);
    for (const value of table.values) {
      const normalized = value >>> 0;
      bytes.push(normalized & 0xff);
      bytes.push((normalized >>> 8) & 0xff);
      bytes.push((normalized >>> 16) & 0xff);
      bytes.push((normalized >>> 24) & 0xff);
    }
  }
  return { offsets, bytes: Uint8Array.from(bytes) };
}

function memorySection(data: Uint8Array): number[] {
  return [
    ...u32(1),
    0x00,
    ...u32(Math.max(1, Math.ceil(data.length / 65_536))),
  ];
}

function dataSection(data: Uint8Array): number[] {
  return [
    ...u32(1),
    0x00,
    0x41,
    ...i32(0),
    0x0b,
    ...u32(data.length),
    ...data,
  ];
}

function functionParameters(
  fn: RuntimeLanguageFunction,
): readonly RuntimeLanguageVariable[] {
  return fn.parameters ?? [];
}

function functionLocals(
  fn: RuntimeLanguageFunction,
): readonly RuntimeLanguageVariable[] {
  return fn.locals ?? [];
}

function runtimeLanguageTables(
  program: RuntimeLanguageProgram,
): readonly RuntimeLanguageTable[] {
  return program.tables ?? [];
}

function runtimeLanguageTable(
  program: RuntimeLanguageProgram,
  name: string,
): RuntimeLanguageTable {
  const table = runtimeLanguageTables(program).find((item) =>
    item.name === name
  );
  if (!table) {
    throw new Error(
      `Runtime-language program '${program.name}' has no table '${name}'.`,
    );
  }
  return table;
}

function validateVariableSet(
  fn: RuntimeLanguageFunction,
  parameters: readonly RuntimeLanguageVariable[],
  locals: readonly RuntimeLanguageVariable[],
): void {
  const seen = new Set<string>();
  for (const variable of [...parameters, ...locals]) {
    if (variable.type !== "u32") {
      throw new Error(
        `Runtime-language variable '${variable.name}' has unsupported type '${variable.type}'.`,
      );
    }
    identifier(variable.name);
    if (seen.has(variable.name)) {
      throw new Error(
        `Runtime-language function '${fn.name}' has duplicate variable '${variable.name}'.`,
      );
    }
    seen.add(variable.name);
  }
  identifier(fn.name);
}

function localIndexMap(
  parameters: readonly RuntimeLanguageVariable[],
  locals: readonly RuntimeLanguageVariable[],
): ReadonlyMap<string, number> {
  const indexes = new Map<string, number>();
  for (const [index, parameter] of parameters.entries()) {
    indexes.set(parameter.name, index);
  }
  for (const [index, local] of locals.entries()) {
    indexes.set(local.name, parameters.length + index);
  }
  return indexes;
}

function localIndex(
  name: string,
  locals: ReadonlyMap<string, number>,
): number {
  const index = locals.get(name);
  if (index === undefined) {
    throw new Error(`Runtime-language variable '${name}' is not declared.`);
  }
  return index;
}

function functionIndex(
  name: string,
  functions: ReadonlyMap<string, number>,
): number {
  const index = functions.get(name);
  if (index === undefined) {
    throw new Error(`Runtime-language function '${name}' is not declared.`);
  }
  return index;
}

function tableLoaderIndex(
  name: string,
  tables: ReadonlyMap<string, number>,
): number {
  const index = tables.get(name);
  if (index === undefined) {
    throw new Error(`Runtime-language table '${name}' is not declared.`);
  }
  return index;
}

function assertKnownLocal(
  name: string,
  locals: ReadonlySet<string>,
): void {
  if (!locals.has(name)) {
    throw new Error(`Runtime-language variable '${name}' is not declared.`);
  }
}

function localDeclarations(
  locals: readonly RuntimeLanguageVariable[],
): number[] {
  if (locals.length === 0) return [0x00];
  return [0x01, ...u32(locals.length), 0x7f];
}

function wasmType(variable: RuntimeLanguageVariable): number[] {
  if (variable.type !== "u32") {
    throw new Error(
      `Runtime-language variable '${variable.name}' has unsupported type '${variable.type}'.`,
    );
  }
  return [0x7f];
}

function wasmFunctionType(fn: RuntimeLanguageFunction): number[] {
  const parameters = functionParameters(fn);
  return [
    0x60,
    ...u32(parameters.length),
    ...parameters.flatMap(wasmType),
    0x01,
    0x7f,
  ];
}

function wasmTableLoaderType(): number[] {
  return [
    0x60,
    ...u32(1),
    0x7f,
    0x01,
    0x7f,
  ];
}

function validateCallExpression(
  expression: Extract<RuntimeExpression, { readonly kind: "call" }>,
  target: RuntimeLanguageFunction,
): void {
  const expected = functionParameters(target).length;
  if (expression.args.length !== expected) {
    throw new Error(
      `Runtime-language call to '${expression.function}' has ${expression.args.length} arguments, expected ${expected}.`,
    );
  }
}

function validateSimpleTableIndex(
  expression: RuntimeExpression,
  locals: ReadonlySet<string>,
): void {
  if (expression.kind === "u32") return;
  if (expression.kind === "local") {
    assertKnownLocal(expression.name, locals);
    return;
  }
  throw new Error(
    "Runtime-language table indexes currently must be u32 constants or locals.",
  );
}

function runtimeTableIdentifier(table: RuntimeLanguageTable): string {
  return `__baba_table_${identifier(table.name)}`;
}

function runtimeTableLoaderIdentifier(table: RuntimeLanguageTable): string {
  return `__baba_load_${identifier(table.name)}`;
}

function assertNotReservedRuntimeName(name: string): void {
  if (name.startsWith("__baba_")) {
    throw new Error(
      `Runtime-language name '${name}' uses the reserved __baba_ prefix.`,
    );
  }
}

function identifier(name: string): string {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) || RESERVED.has(name)) {
    throw new Error(
      `Runtime-language identifier '${name}' is not a valid target identifier.`,
    );
  }
  return name;
}

const RESERVED = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
]);

function section(id: number, payload: number[]): number[] {
  return [id, ...u32(payload.length), ...payload];
}

function name(value: string): number[] {
  const bytes = new TextEncoder().encode(value);
  return [...u32(bytes.length), ...bytes];
}

function u32(value: number): number[] {
  let remaining = value >>> 0;
  const bytes = [];
  do {
    let byte = remaining & 0x7f;
    remaining >>>= 7;
    if (remaining !== 0) byte |= 0x80;
    bytes.push(byte);
  } while (remaining !== 0);
  return bytes;
}

function i32(value: number): number[] {
  let remaining = value | 0;
  const bytes = [];
  let more = true;
  while (more) {
    let byte = remaining & 0x7f;
    remaining >>= 7;
    const signBitSet = (byte & 0x40) !== 0;
    more = !(
      (remaining === 0 && !signBitSet) ||
      (remaining === -1 && signBitSet)
    );
    if (more) byte |= 0x80;
    bytes.push(byte);
  }
  return bytes;
}
