export const RUNTIME_LANGUAGE_VERSION = 1 as const;
export const RUNTIME_LANGUAGE_SEMANTICS = "baba-runtime-language-v1" as const;

export interface RuntimeLanguageProgram {
  readonly name: string;
  readonly entry: string;
  readonly functions: readonly RuntimeLanguageFunction[];
}

export interface RuntimeLanguageFunction {
  readonly name: string;
  readonly result: RuntimeScalarType;
  readonly body: readonly RuntimeStatement[];
}

export type RuntimeScalarType = "u32";

export type RuntimeStatement =
  | {
    readonly kind: "return";
    readonly expression: RuntimeExpression;
  }
  | {
    readonly kind: "trap";
  };

export type RuntimeExpression =
  | {
    readonly kind: "u32";
    readonly value: number;
  }
  | {
    readonly kind:
      | "addU32"
      | "subU32"
      | "mulU32"
      | "divU32"
      | "eqU32"
      | "ltS32"
      | "shlU32"
      | "shrU32";
    readonly left: RuntimeExpression;
    readonly right: RuntimeExpression;
  };

export class RuntimeLanguageTrap extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RuntimeLanguageTrap";
  }
}

export function emitRuntimeLanguageTypeScript(
  program: RuntimeLanguageProgram,
): string {
  const entry = runtimeLanguageEntryFunction(program);
  return `// Generated by @mewhhaha/baba runtime-language stage 0.
export const runtimeLanguageVersion = ${RUNTIME_LANGUAGE_VERSION};
export const runtimeLanguageSemantics = ${
    JSON.stringify(RUNTIME_LANGUAGE_SEMANTICS)
  } as const;

export class RuntimeLanguageTrap extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RuntimeLanguageTrap";
  }
}

function divU32(left: number, right: number): number {
  const divisor = right >>> 0;
  if (divisor === 0) throw new RuntimeLanguageTrap("division by zero");
  return Math.trunc((left >>> 0) / divisor) >>> 0;
}

export function ${entry.name}(): number {
${entry.body.map((statement) => emitTypeScriptStatement(statement)).join("\n")}
  throw new RuntimeLanguageTrap("function completed without a return");
}
`;
}

export function compileRuntimeLanguageWasm(
  program: RuntimeLanguageProgram,
): Uint8Array {
  const entry = runtimeLanguageEntryFunction(program);
  const body = [
    0x00,
    ...entry.body.flatMap((statement) => emitWasmStatement(statement)),
    0x00,
    0x0b,
  ];
  const sections = [
    section(1, [
      ...u32(1),
      0x60,
      0x00,
      0x01,
      0x7f,
    ]),
    section(3, [
      ...u32(1),
      ...u32(0),
    ]),
    section(7, [
      ...u32(1),
      ...name(entry.name),
      0x00,
      ...u32(0),
    ]),
    section(10, [
      ...u32(1),
      ...u32(body.length),
      ...body,
    ]),
  ];
  return new Uint8Array([
    0x00,
    0x61,
    0x73,
    0x6d,
    0x01,
    0x00,
    0x00,
    0x00,
    ...sections.flat(),
  ]);
}

export function runtimeLanguageEntryFunction(
  program: RuntimeLanguageProgram,
): RuntimeLanguageFunction {
  const entry = program.functions.find((fn) => fn.name === program.entry);
  if (!entry) {
    throw new Error(
      `Runtime-language program '${program.name}' has no entry function '${program.entry}'.`,
    );
  }
  if (entry.result !== "u32") {
    throw new Error(
      `Runtime-language function '${entry.name}' has unsupported result type '${entry.result}'.`,
    );
  }
  return entry;
}

function emitTypeScriptStatement(statement: RuntimeStatement): string {
  if (statement.kind === "trap") {
    return `  throw new RuntimeLanguageTrap("explicit trap");`;
  }
  return `  return (${emitTypeScriptExpression(statement.expression)}) >>> 0;`;
}

function emitTypeScriptExpression(expression: RuntimeExpression): string {
  switch (expression.kind) {
    case "u32":
      return String(expression.value >>> 0);
    case "addU32":
      return `((${emitTypeScriptExpression(expression.left)}) + (${
        emitTypeScriptExpression(expression.right)
      })) >>> 0`;
    case "subU32":
      return `((${emitTypeScriptExpression(expression.left)}) - (${
        emitTypeScriptExpression(expression.right)
      })) >>> 0`;
    case "mulU32":
      return `Math.imul((${
        emitTypeScriptExpression(expression.left)
      }) >>> 0, (${emitTypeScriptExpression(expression.right)}) >>> 0) >>> 0`;
    case "divU32":
      return `divU32(${emitTypeScriptExpression(expression.left)}, ${
        emitTypeScriptExpression(expression.right)
      })`;
    case "eqU32":
      return `(((${emitTypeScriptExpression(expression.left)}) >>> 0) === ((${
        emitTypeScriptExpression(expression.right)
      }) >>> 0) ? 1 : 0)`;
    case "ltS32":
      return `(((${emitTypeScriptExpression(expression.left)}) | 0) < ((${
        emitTypeScriptExpression(expression.right)
      }) | 0) ? 1 : 0)`;
    case "shlU32":
      return `((${emitTypeScriptExpression(expression.left)}) << ((${
        emitTypeScriptExpression(expression.right)
      }) & 31)) >>> 0`;
    case "shrU32":
      return `((${emitTypeScriptExpression(expression.left)}) >>> ((${
        emitTypeScriptExpression(expression.right)
      }) & 31)) >>> 0`;
  }
}

function emitWasmStatement(statement: RuntimeStatement): number[] {
  if (statement.kind === "trap") return [0x00];
  return [
    ...emitWasmExpression(statement.expression),
    0x0f,
  ];
}

function emitWasmExpression(expression: RuntimeExpression): number[] {
  switch (expression.kind) {
    case "u32":
      return [0x41, ...i32(expression.value | 0)];
    case "addU32":
      return binaryExpression(expression, 0x6a);
    case "subU32":
      return binaryExpression(expression, 0x6b);
    case "mulU32":
      return binaryExpression(expression, 0x6c);
    case "divU32":
      return binaryExpression(expression, 0x6e);
    case "eqU32":
      return binaryExpression(expression, 0x46);
    case "ltS32":
      return binaryExpression(expression, 0x48);
    case "shlU32":
      return binaryExpression(expression, 0x74);
    case "shrU32":
      return binaryExpression(expression, 0x76);
  }
}

function binaryExpression(
  expression: Extract<
    RuntimeExpression,
    { readonly left: RuntimeExpression; readonly right: RuntimeExpression }
  >,
  opcode: number,
): number[] {
  return [
    ...emitWasmExpression(expression.left),
    ...emitWasmExpression(expression.right),
    opcode,
  ];
}

function section(id: number, payload: number[]): number[] {
  return [id, ...u32(payload.length), ...payload];
}

function name(value: string): number[] {
  const bytes = new TextEncoder().encode(value);
  return [...u32(bytes.length), ...bytes];
}

function u32(value: number): number[] {
  let remaining = value >>> 0;
  const bytes = [];
  do {
    let byte = remaining & 0x7f;
    remaining >>>= 7;
    if (remaining !== 0) byte |= 0x80;
    bytes.push(byte);
  } while (remaining !== 0);
  return bytes;
}

function i32(value: number): number[] {
  let remaining = value | 0;
  const bytes = [];
  let more = true;
  while (more) {
    let byte = remaining & 0x7f;
    remaining >>= 7;
    const signBitSet = (byte & 0x40) !== 0;
    more = !(
      (remaining === 0 && !signBitSet) ||
      (remaining === -1 && signBitSet)
    );
    if (more) byte |= 0x80;
    bytes.push(byte);
  }
  return bytes;
}
