import { emitRuntimeLanguageTypeScriptFunction } from "./language.ts";
import {
  createLexerRuntimeProgram,
  RUNTIME_LEXER_DRIVER_EVENT_DONE,
  RUNTIME_LEXER_DRIVER_EVENT_ERROR,
  RUNTIME_LEXER_DRIVER_EVENT_NEED_CODE_POINT,
  RUNTIME_LEXER_DRIVER_EVENT_TOKEN,
  RUNTIME_LEXER_DRIVER_SCRATCH_WORDS,
  RUNTIME_LEXER_SPEC_LITERAL,
  RUNTIME_LEXER_SPEC_TRIVIA,
  RUNTIME_NO_TERMINAL,
  RUNTIME_PUBLIC_TOKEN_EOF,
  RUNTIME_PUBLIC_TOKEN_ERROR,
  RUNTIME_PUBLIC_TOKEN_LITERAL,
  RUNTIME_PUBLIC_TOKEN_MAIN,
  RUNTIME_PUBLIC_TOKEN_TRIVIA,
} from "./language_sources.ts";
import { emitPublicLexDiagnosticMaterializer } from "./public_lex_diagnostic_materializer.ts";
import { emitPublicLexResultMaterializer } from "./public_lex_result_materializer.ts";
import { emitPublicSourceTextBoundary } from "./public_source_text.ts";
import { emitPublicTokenMaterializer } from "./public_token_materializer.ts";

export interface TypeScriptLexerNamedSpec {
  readonly kind: string;
  readonly pattern: string;
  readonly channel: "main" | "trivia";
  readonly terminal: number;
  readonly priority: number;
  readonly order: number;
}

export interface TypeScriptLexerLiteralSpec {
  readonly literal: string;
  readonly terminal: number;
  readonly priority: number;
  readonly order: number;
}

export interface TypeScriptLexerRuntimePlan {
  readonly preserveTrivia: boolean;
  readonly namedSpecs: readonly TypeScriptLexerNamedSpec[];
  readonly literalSpecs: readonly TypeScriptLexerLiteralSpec[];
  readonly transitions: readonly (readonly (readonly [
    start: number,
    end: number,
    target: number,
  ])[])[];
  readonly asciiTransitions: readonly (readonly number[])[] | null;
  readonly accepts: readonly number[];
}

export function emitTypeScriptLexerRuntime(
  plan: TypeScriptLexerRuntimePlan,
): string {
  const runtimeProgram = createLexerRuntimeProgram({
    transitions: plan.transitions,
    asciiTransitions: plan.asciiTransitions,
    accepts: plan.accepts,
    specs: [
      ...plan.namedSpecs.map((spec, payload) =>
        [
          spec.channel === "trivia" ? RUNTIME_LEXER_SPEC_TRIVIA : 0,
          payload,
          spec.terminal,
        ] as const
      ),
      ...plan.literalSpecs.map((spec, payload) =>
        [
          RUNTIME_LEXER_SPEC_LITERAL,
          payload,
          spec.terminal,
        ] as const
      ),
    ],
    includeTokenRecords: true,
  });
  return `// Generated by @mewhhaha/baba. Do not edit by hand.
import type {
  LexDiagnostic,
  LexOptions,
  LexResult,
  NamedTokenKind,
  Span,
  Token,
} from "./syntax.ts";

const DEFAULT_PRESERVE_TRIVIA = ${JSON.stringify(plan.preserveTrivia)};

const NAMED_SPECS: readonly {
  kind: NamedTokenKind;
  pattern: string;
  channel: "main" | "trivia";
  terminal: number;
  priority: number;
  order: number;
}[] = ${JSON.stringify(plan.namedSpecs, null, 2)} as const;

const LITERAL_SPECS: readonly {
  literal: string;
  terminal: number;
  priority: number;
  order: number;
}[] = ${JSON.stringify(plan.literalSpecs, null, 2)} as const;

const NO_TERMINAL = ${RUNTIME_NO_TERMINAL};
const PUBLIC_TOKEN_LITERAL = ${RUNTIME_PUBLIC_TOKEN_LITERAL};
const PUBLIC_TOKEN_MAIN = ${RUNTIME_PUBLIC_TOKEN_MAIN};
const PUBLIC_TOKEN_TRIVIA = ${RUNTIME_PUBLIC_TOKEN_TRIVIA};
const PUBLIC_TOKEN_ERROR = ${RUNTIME_PUBLIC_TOKEN_ERROR};
const PUBLIC_TOKEN_EOF = ${RUNTIME_PUBLIC_TOKEN_EOF};
const LEXER_DRIVER_DONE = ${RUNTIME_LEXER_DRIVER_EVENT_DONE};
const LEXER_DRIVER_NEED_CODE_POINT = ${RUNTIME_LEXER_DRIVER_EVENT_NEED_CODE_POINT};
const LEXER_DRIVER_TOKEN = ${RUNTIME_LEXER_DRIVER_EVENT_TOKEN};
const LEXER_DRIVER_ERROR = ${RUNTIME_LEXER_DRIVER_EVENT_ERROR};
const LEXER_DRIVER_SCRATCH_WORDS = ${RUNTIME_LEXER_DRIVER_SCRATCH_WORDS};

${
    emitRuntimeLanguageTypeScriptFunction(runtimeProgram)
      .trimEnd()
  }
${emitPublicSourceTextBoundary({ includeCodePoint: true })}
${emitPublicTokenMaterializer({ label: "Lexer" })}
${emitPublicLexDiagnosticMaterializer()}
${emitPublicLexResultMaterializer()}

export function lex(source: string, options: LexOptions = {}): LexResult {
  runtimeArenaReset();
  const sourceText = createSourceTextBoundary(source);
  const preserveTrivia = options.preserveTrivia ?? DEFAULT_PRESERVE_TRIVIA;
  const tokens: Token[] = [];
  const diagnostics: LexDiagnostic[] = [];

  lexerDriverStart(sourceText.length, preserveTrivia ? 1 : 0);
  while (lexerDriverEvent() !== LEXER_DRIVER_DONE) {
    while (lexerDriverEvent() === LEXER_DRIVER_NEED_CODE_POINT) {
      const codePoint = sourceTextCodePointAt(
        sourceText,
        lexerDriverReadOffset(),
      );
      lexerDriverAdvance(codePoint);
    }

    const event = lexerDriverEvent();
    if (event === LEXER_DRIVER_DONE) break;
    runtimeArenaResetTo(LEXER_DRIVER_SCRATCH_WORDS);
    const handle = parserTokenNew(
      lexerDriverTokenClass(),
      lexerDriverTokenPayload(),
      lexerDriverTokenTerminal(),
      lexerDriverTokenStart(),
      lexerDriverTokenEnd(),
    );
    const token = materializeToken(sourceText, handle);
    if (event === LEXER_DRIVER_TOKEN) {
      tokens.push(token);
      lexerDriverConsume();
      continue;
    }
    if (event === LEXER_DRIVER_ERROR) {
      tokens.push(token);
      diagnostics.push(lexUnexpectedCharacterDiagnostic(token));
      lexerDriverConsume();
      continue;
    }
    throw new Error("Lexer driver produced an unknown event.");
  }

  runtimeArenaResetTo(LEXER_DRIVER_SCRATCH_WORDS);
  const eofHandle = parserTokenNew(
    PUBLIC_TOKEN_EOF,
    0,
    NO_TERMINAL,
    sourceText.length,
    sourceText.length,
  );
  tokens.push(materializeToken(sourceText, eofHandle));
  return lexResult(sourceText.source, tokens, diagnostics);
}
`;
}
