import { emitRuntimeLanguageTypeScriptFunction } from "./language.ts";
import {
  createLexerRuntimeProgram,
  RUNTIME_NO_ACCEPT,
  RUNTIME_NO_TERMINAL,
} from "./language_sources.ts";

export interface TypeScriptLexerNamedSpec {
  readonly kind: string;
  readonly pattern: string;
  readonly channel: "main" | "trivia";
  readonly terminal: number;
  readonly priority: number;
  readonly order: number;
}

export interface TypeScriptLexerLiteralSpec {
  readonly literal: string;
  readonly terminal: number;
  readonly priority: number;
  readonly order: number;
}

export interface TypeScriptLexerRuntimePlan {
  readonly preserveTrivia: boolean;
  readonly namedSpecs: readonly TypeScriptLexerNamedSpec[];
  readonly literalSpecs: readonly TypeScriptLexerLiteralSpec[];
  readonly transitions: readonly (readonly (readonly [
    start: number,
    end: number,
    target: number,
  ])[])[];
  readonly asciiTransitions: readonly (readonly number[])[] | null;
  readonly accepts: readonly number[];
}

export function emitTypeScriptLexerRuntime(
  plan: TypeScriptLexerRuntimePlan,
): string {
  const runtimeProgram = createLexerRuntimeProgram({
    transitions: plan.transitions,
    asciiTransitions: plan.asciiTransitions,
    accepts: plan.accepts,
    specTerminals: [
      ...plan.namedSpecs.map((spec) => spec.terminal),
      ...plan.literalSpecs.map((spec) => spec.terminal),
    ],
  });
  return `// Generated by @mewhhaha/baba. Do not edit by hand.
import type {
  LexDiagnostic,
  LexOptions,
  LexResult,
  NamedTokenKind,
  Token,
} from "./syntax.ts";

const DEFAULT_PRESERVE_TRIVIA = ${JSON.stringify(plan.preserveTrivia)};

const NAMED_SPECS: readonly {
  kind: NamedTokenKind;
  pattern: string;
  channel: "main" | "trivia";
  terminal: number;
  priority: number;
  order: number;
}[] = ${JSON.stringify(plan.namedSpecs, null, 2)} as const;

const LITERAL_SPECS: readonly {
  literal: string;
  terminal: number;
  priority: number;
  order: number;
}[] = ${JSON.stringify(plan.literalSpecs, null, 2)} as const;

const SPECS: readonly (
  | { type: "named"; specIndex: number }
  | { type: "literal"; specIndex: number }
)[] = ${
    JSON.stringify([
      ...plan.namedSpecs.map((_, specIndex) => ({ type: "named", specIndex })),
      ...plan.literalSpecs.map((_, specIndex) => ({
        type: "literal",
        specIndex,
      })),
    ])
  } as const;

const NO_ACCEPT = ${RUNTIME_NO_ACCEPT};
const NO_TERMINAL = ${RUNTIME_NO_TERMINAL};

interface Candidate {
  specIndex: number;
  end: number;
}

interface RuntimeTerminalToken {
  __babaTerminal?: number;
}

${
    emitRuntimeLanguageTypeScriptFunction(runtimeProgram)
      .trimEnd()
  }

export function lex(source: string, options: LexOptions = {}): LexResult {
  const preserveTrivia = options.preserveTrivia ?? DEFAULT_PRESERVE_TRIVIA;
  const tokens: Token[] = [];
  const diagnostics: LexDiagnostic[] = [];
  let offset = 0;

  while (offset < source.length) {
    const candidate = bestCandidate(source, offset);
    if (candidate) {
      const start = offset;
      const end = candidate.end;
      const specRef = SPECS[candidate.specIndex];
      const terminal = runtimeTerminal(candidate.specIndex);
      if (specRef.type === "literal") {
        const spec = LITERAL_SPECS[specRef.specIndex];
        tokens.push({
          type: "literal",
          literal: spec.literal as never,
          text: spec.literal as never,
          span: { start, end },
          channel: "main",
          __babaTerminal: terminal,
        } as Token & RuntimeTerminalToken);
      } else {
        const spec = NAMED_SPECS[specRef.specIndex];
        if (spec.channel === "trivia") {
          if (preserveTrivia) {
            tokens.push({
              type: "named",
              kind: spec.kind as never,
              text: source.slice(start, end),
              span: { start, end },
              channel: "trivia",
              __babaTerminal: terminal,
            } as Token & RuntimeTerminalToken);
          }
        } else {
          tokens.push({
            type: "named",
            kind: spec.kind as never,
            text: source.slice(start, end),
            span: { start, end },
            channel: "main",
            __babaTerminal: terminal,
          } as Token & RuntimeTerminalToken);
        }
      }
      offset = end;
      continue;
    }

    const start = offset;
    const codePoint = source.codePointAt(offset);
    offset += codePoint === undefined ? 1 : utf16CodePointWidth(codePoint);
    const text = source.slice(start, offset);
    tokens.push({
      type: "error",
      text,
      span: { start, end: offset },
      channel: "error",
    });
    diagnostics.push({
      code: "LEX_UNEXPECTED_CHARACTER",
      message: \`Unexpected character \${JSON.stringify(text)}.\`,
      span: { start, end: offset },
    });
  }

  tokens.push({
    type: "eof",
    text: "",
    span: { start: source.length, end: source.length },
    channel: "main",
  });
  return { source, tokens, diagnostics };
}

function runtimeTerminal(specIndex: number): number {
  const terminal = lexerSpecTerminal(specIndex);
  return terminal === NO_TERMINAL ? -1 : terminal;
}

function bestCandidate(source: string, offset: number): Candidate | null {
  let index = offset;
  lexerScanReset();

  while (index < source.length) {
    const codePoint = source.codePointAt(index);
    if (codePoint === undefined) break;
    if (lexerScanAdvance(codePoint) === 0) break;
    index += utf16CodePointWidth(codePoint);
  }

  const specIndex = lexerScanBestSpec();
  if (specIndex === NO_ACCEPT) return null;
  return { specIndex, end: offset + lexerScanBestEnd() };
}
`;
}
