import { emitRuntimeLanguageTypeScriptFunction } from "./language.ts";
import {
  createLexerRuntimeProgram,
  RUNTIME_NO_TRANSITION,
} from "./language_sources.ts";

export interface TypeScriptLexerNamedSpec {
  readonly kind: string;
  readonly pattern: string;
  readonly channel: "main" | "trivia";
  readonly priority: number;
  readonly order: number;
}

export interface TypeScriptLexerLiteralSpec {
  readonly literal: string;
  readonly priority: number;
  readonly order: number;
}

export interface TypeScriptLexerRuntimePlan {
  readonly preserveTrivia: boolean;
  readonly namedSpecs: readonly TypeScriptLexerNamedSpec[];
  readonly literalSpecs: readonly TypeScriptLexerLiteralSpec[];
  readonly transitions: readonly (readonly (readonly [
    start: number,
    end: number,
    target: number,
  ])[])[];
  readonly asciiTransitions: readonly (readonly number[])[] | null;
  readonly accepts: readonly number[];
}

export function emitTypeScriptLexerRuntime(
  plan: TypeScriptLexerRuntimePlan,
): string {
  const runtimeProgram = createLexerRuntimeProgram({
    transitions: plan.transitions,
    asciiTransitions: plan.asciiTransitions,
  });
  return `// Generated by @mewhhaha/baba. Do not edit by hand.
import type {
  LexDiagnostic,
  LexOptions,
  LexResult,
  NamedTokenKind,
  Token,
} from "./syntax.ts";

const DEFAULT_PRESERVE_TRIVIA = ${JSON.stringify(plan.preserveTrivia)};

const NAMED_SPECS: readonly {
  kind: NamedTokenKind;
  pattern: string;
  channel: "main" | "trivia";
  priority: number;
  order: number;
}[] = ${JSON.stringify(plan.namedSpecs, null, 2)} as const;

const LITERAL_SPECS: readonly {
  literal: string;
  priority: number;
  order: number;
}[] = ${JSON.stringify(plan.literalSpecs, null, 2)} as const;

const SPECS: readonly (
  | { type: "named"; specIndex: number }
  | { type: "literal"; specIndex: number }
)[] = ${
    JSON.stringify([
      ...plan.namedSpecs.map((_, specIndex) => ({ type: "named", specIndex })),
      ...plan.literalSpecs.map((_, specIndex) => ({
        type: "literal",
        specIndex,
      })),
    ])
  } as const;

const DFA_ACCEPTS: readonly number[] = ${JSON.stringify(plan.accepts)};
const NO_TRANSITION = ${RUNTIME_NO_TRANSITION};

interface Candidate {
  specIndex: number;
  end: number;
}

${
    emitRuntimeLanguageTypeScriptFunction(runtimeProgram)
      .trimEnd()
  }

export function lex(source: string, options: LexOptions = {}): LexResult {
  const preserveTrivia = options.preserveTrivia ?? DEFAULT_PRESERVE_TRIVIA;
  const tokens: Token[] = [];
  const diagnostics: LexDiagnostic[] = [];
  let offset = 0;

  while (offset < source.length) {
    const candidate = bestCandidate(source, offset);
    if (candidate) {
      const start = offset;
      const end = candidate.end;
      const specRef = SPECS[candidate.specIndex];
      if (specRef.type === "literal") {
        const spec = LITERAL_SPECS[specRef.specIndex];
        tokens.push({
          type: "literal",
          literal: spec.literal as never,
          text: spec.literal as never,
          span: { start, end },
          channel: "main",
        });
      } else {
        const spec = NAMED_SPECS[specRef.specIndex];
        if (spec.channel === "trivia") {
          if (preserveTrivia) {
            tokens.push({
              type: "named",
              kind: spec.kind as never,
              text: source.slice(start, end),
              span: { start, end },
              channel: "trivia",
            });
          }
        } else {
          tokens.push({
            type: "named",
            kind: spec.kind as never,
            text: source.slice(start, end),
            span: { start, end },
            channel: "main",
          });
        }
      }
      offset = end;
      continue;
    }

    const start = offset;
    const codePoint = source.codePointAt(offset);
    offset += codePoint !== undefined && codePoint > 0xffff ? 2 : 1;
    const text = source.slice(start, offset);
    tokens.push({
      type: "error",
      text,
      span: { start, end: offset },
      channel: "error",
    });
    diagnostics.push({
      code: "LEX_UNEXPECTED_CHARACTER",
      message: \`Unexpected character \${JSON.stringify(text)}.\`,
      span: { start, end: offset },
    });
  }

  tokens.push({
    type: "eof",
    text: "",
    span: { start: source.length, end: source.length },
    channel: "main",
  });
  return { source, tokens, diagnostics };
}

function bestCandidate(source: string, offset: number): Candidate | null {
  let state = 0;
  let index = offset;
  let best: Candidate | null = null;

  while (index < source.length) {
    const codePoint = source.codePointAt(index);
    if (codePoint === undefined) break;
    const target = dfaTransition(state, codePoint);
    if (target === NO_TRANSITION) break;
    index += utf16CodePointWidth(codePoint);
    state = target;
    const specIndex = DFA_ACCEPTS[state] ?? -1;
    if (specIndex >= 0) best = { specIndex, end: index };
  }

  return best;
}
`;
}
