import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import type { BnfGrammar, ReducerSpec } from "../typescript/bnf.ts";
import type { LrAction, LrActionSet, LrTable } from "../typescript/lr1.ts";
import { collectRuleFieldSchemas } from "./field_schema.ts";
import {
  emitRuntimeLanguageTypeScriptFunction,
  type RuntimeLanguageProgram,
} from "./language.ts";
import {
  createParserGotoRuntimeProgram,
  createParserTableRuntimeProgram,
  RUNTIME_ACTION_ACCEPT,
  RUNTIME_ACTION_KIND_MASK,
  RUNTIME_ACTION_NONE,
  RUNTIME_ACTION_PAYLOAD_MASK,
  RUNTIME_ACTION_REDUCE,
  RUNTIME_ACTION_SHIFT,
  RUNTIME_NO_GOTO,
} from "./language_sources.ts";

export type ParserEmitMode = "typescript" | "wasm";

export interface ParserEmitOptions {
  mode?: ParserEmitMode;
}

type EncodedAction =
  | readonly [terminal: number, kind: 1, state: number]
  | readonly [terminal: number, kind: 2, production: number]
  | readonly [terminal: number, kind: 3];

type GotoEntry = readonly [nonterminal: number, state: number];

export function emitParser(
  analyzed: AnalyzedGrammar,
  bnf: BnfGrammar,
  lr: LrTable,
  options: ParserEmitOptions = {},
): string {
  const mode = options.mode ?? "typescript";
  const emitTypeScriptTables = mode === "typescript";
  const emitBranchRuntime = mode === "typescript" &&
    hasMultiActionEntries(lr.actions);
  const actionRows = bnfActionTableRows(lr.actions);
  const gotoRows = bnfTableRows(lr.gotos, (nonterminal, target) => [
    nonterminal,
    target,
  ]);
  const tableRuntimeProgram = emitTypeScriptTables
    ? emitBranchRuntime
      ? createParserGotoRuntimeProgram({ gotoRows })
      : createParserTableRuntimeProgram({
        actionRows: parserRuntimeActionRows(actionRows),
        gotoRows,
      })
    : null;
  const productions = bnf.productions.map((production) => ({
    lhs: production.lhs,
    rhsLength: production.rhs.length,
    reducer: production.reducer,
  }));
  const expectedRows = expectedTerminalRows(bnf, lr);
  const namedTerminals: Array<readonly [string, number]> = [];
  const literalTerminals: Array<readonly [string, number]> = [];
  for (const terminal of bnf.terminals) {
    if (terminal.kind === "named") {
      namedTerminals.push([
        analyzed.tokens[terminal.tokenId!].name,
        terminal.id,
      ]);
    }
    if (terminal.kind === "literal") {
      literalTerminals.push([
        analyzed.literals[terminal.literalId!].value,
        terminal.id,
      ]);
    }
  }
  const ruleNames = analyzed.rules.map((rule) => rule.name);
  const fieldSchemas = collectRuleFieldSchemas(analyzed).map((schema) =>
    [
      schema.ruleId,
      schema.fields.map((field) => [
        field.name,
        { array: field.array, nullable: field.nullable },
      ]),
    ] as const
  );
  const mainTokenKinds = analyzed.tokens
    .filter((token) =>
      token.kind === "token" && analyzed.reachableTokens.has(token.id)
    )
    .map((token) => token.name);
  const triviaTokenKinds = analyzed.tokens
    .filter((token) => token.kind === "skip")
    .map((token) => token.name);

  return `// Generated by @mewhhaha/baba. Do not edit by hand.
${importSource(mode)}

${emitTypeScriptTables ? typeScriptActionTypes() : ""}${commonTypes()}
${emitBranchRuntime ? branchTypes() : ""}
${
    commonConstants({
      bnf,
      actionRows,
      productions,
      expectedRows,
      namedTerminals,
      literalTerminals,
      mainTokenKinds,
      triviaTokenKinds,
      ruleNames,
      fieldSchemas,
      emitActionTable: emitTypeScriptTables && emitBranchRuntime,
      emitBranchRuntime,
    })
  }

${
    tableRuntimeProgram
      ? parserTableRuntime(tableRuntimeProgram, {
        emitActionConstants: !emitBranchRuntime,
      })
      : ""
  }

${parseEntryPoints(mode)}

${
    mode === "wasm"
      ? wasmParseRuntime()
      : emitBranchRuntime
      ? branchParseRuntime()
      : deterministicParseRuntime()
  }

${reductionRuntime()}
`;
}

function importSource(mode: ParserEmitMode): string {
  const lexerImport = mode === "wasm"
    ? `import { lex, lexForParse, type WasmParseStream } from "./lexer.ts";
import { createParseTraceInput, parseTrace, type ParseTraceInput } from "./wasm.ts";`
    : `import { lex } from "./lexer.ts";`;
  return `${lexerImport}
import type {
  AnyRuleNode,
  LexDiagnostic,
  LiteralToken,
  MainNamedToken,
  ParseDiagnostic,
  ParseOptions,
  ParseResult,
  RootNode,
  Span,
  SyntaxElement,
  Token,
} from "./syntax.ts";`;
}

function typeScriptActionTypes(): string {
  return `type EncodedAction =
  | readonly [terminal: number, kind: 1, state: number]
  | readonly [terminal: number, kind: 2, production: number]
  | readonly [terminal: number, kind: 3];

type RuntimeAction =
  | { kind: "shift"; state: number }
  | { kind: "reduce"; production: number }
  | { kind: "accept" };

`;
}

function commonTypes(): string {
  return `interface Production {
  lhs: number;
  rhsLength: number;
  reducer: ReducerSpec;
}

type ReducerSpec =
  | { kind: "start" }
  | { kind: "rule"; ruleId: number }
  | { kind: "terminal" }
  | { kind: "ruleRef" }
  | { kind: "identity" }
  | { kind: "sequence" }
  | { kind: "optionalEmpty" }
  | { kind: "optionalSome" }
  | { kind: "repeatEmpty" }
  | { kind: "repeatAppend" }
  | { kind: "repeat1First" }
  | { kind: "repeat1Append" }
  | { kind: "separatedFirst" }
  | { kind: "separatedAppend" }
  | { kind: "field"; name: string };

interface Fragment {
  value: unknown;
  children: SyntaxElement[];
  fields: FieldCapture[];
  span: Span | null;
  tokenRange: TokenRange | null;
}

interface FieldCapture {
  name: string;
  value: unknown;
}

interface TokenRange {
  start: number;
  end: number;
}

interface ShiftedToken {
  token: Token;
  tokenIndex: number;
}

interface FieldConfig {
  array: boolean;
  nullable: boolean;
}

interface RuntimeRuleFieldSchema {
  entries: readonly (readonly [name: string, config: FieldConfig])[];
  byName: Record<string, FieldConfig>;
}`;
}

function branchTypes(): string {
  return `
interface ParseBranch {
  states: number[];
  values: unknown[];
  index: number;
}

type BranchAdvanceResult =
  | { kind: "continue" }
  | { kind: "forked" }
  | { kind: "success"; result: ParseResult<RootNode> }
  | { kind: "failure"; failure: ParseFailure };

interface ParseFailure {
  diagnostic: ParseDiagnostic;
  offset: number;
}
`;
}

function commonConstants(values: {
  bnf: BnfGrammar;
  actionRows: readonly (readonly EncodedAction[])[];
  productions: unknown[];
  expectedRows: readonly (readonly string[])[];
  namedTerminals: Array<readonly [string, number]>;
  literalTerminals: Array<readonly [string, number]>;
  mainTokenKinds: string[];
  triviaTokenKinds: string[];
  ruleNames: string[];
  fieldSchemas: unknown;
  emitActionTable: boolean;
  emitBranchRuntime: boolean;
}): string {
  return `const EOF_TERMINAL = ${values.bnf.eofTerminal};
${
    values.emitActionTable
      ? `const ACTIONS: readonly (readonly EncodedAction[])[] = ${
        JSON.stringify(values.actionRows)
      };
`
      : ""
  }const PRODUCTIONS: readonly Production[] = ${
    JSON.stringify(values.productions)
  };
const EXPECTED_TERMINALS: readonly (readonly string[])[] = ${
    JSON.stringify(values.expectedRows)
  };
const NAMED_TERMINALS = new Map<string, number>(${
    JSON.stringify(values.namedTerminals)
  });
const LITERAL_TERMINALS = new Map<string, number>(${
    JSON.stringify(values.literalTerminals)
  });
const MAIN_TOKEN_KINDS = new Set<string>(${
    JSON.stringify(values.mainTokenKinds)
  });
const TRIVIA_TOKEN_KINDS = new Set<string>(${
    JSON.stringify(values.triviaTokenKinds)
  });
const RULE_NAMES: readonly string[] = ${JSON.stringify(values.ruleNames)};
const EMPTY_PARSE_DIAGNOSTICS: readonly ParseDiagnostic[] = [];
${
    values.emitBranchRuntime
      ? "const MAX_PARSE_BRANCHES = 100000;\n"
      : ""
  }const RULE_FIELD_SCHEMA_ENTRIES: readonly (
  readonly [
    ruleId: number,
    fields: readonly (readonly [
      name: string,
      config: FieldConfig,
    ])[],
  ]
)[] = ${JSON.stringify(values.fieldSchemas)};
const RULE_FIELD_SCHEMAS: readonly (RuntimeRuleFieldSchema | undefined)[] = (() => {
  const schemas: (RuntimeRuleFieldSchema | undefined)[] = [];
  for (const [ruleId, entries] of RULE_FIELD_SCHEMA_ENTRIES) {
    const byName = Object.create(null) as Record<string, FieldConfig>;
    for (const [name, config] of entries) byName[name] = config;
    schemas[ruleId] = { entries, byName };
  }
  return schemas;
})();`;
}

function parserTableRuntime(
  program: RuntimeLanguageProgram,
  options: { readonly emitActionConstants: boolean },
): string {
  const actionConstants = options.emitActionConstants
    ? `const ACTION_NONE = ${RUNTIME_ACTION_NONE};
const ACTION_SHIFT = ${RUNTIME_ACTION_SHIFT};
const ACTION_REDUCE = ${RUNTIME_ACTION_REDUCE};
const ACTION_ACCEPT = ${RUNTIME_ACTION_ACCEPT};
const ACTION_KIND_MASK = ${RUNTIME_ACTION_KIND_MASK};
const ACTION_PAYLOAD_MASK = ${RUNTIME_ACTION_PAYLOAD_MASK};
`
    : "";
  return `${actionConstants}const NO_GOTO = ${RUNTIME_NO_GOTO};

${emitRuntimeLanguageTypeScriptFunction(program).trimEnd()}`;
}

function parseEntryPoints(mode: ParserEmitMode): string {
  const parseBody = mode === "wasm"
    ? `  const lexed = lexForParse(source, options);
  return parseTokenList(
    source,
    lexed.tokens,
    lexicalDiagnostics(lexed.diagnostics),
    lexed.parseStream,
  );`
    : `  const lexed = lex(source, options);
  return parseTokenList(
    source,
    lexed.tokens,
    lexicalDiagnostics(lexed.diagnostics),
  );`;
  return `export function parse(
  source: string,
  options: ParseOptions = {},
): ParseResult<RootNode> {
${parseBody}
}

export function parseTokens(
  source: string,
  tokens: readonly Token[],
): ParseResult<RootNode> {
  const streamDiagnostics = validateTokenStream(source, tokens);
  const tokenDiagnostics = lexicalTokenDiagnostics(tokens);
  return parseTokenList(
    source,
    tokens,
    combineDiagnostics(streamDiagnostics, tokenDiagnostics),
  );
}

export function parseTokensUnchecked(
  source: string,
  tokens: readonly Token[],
): ParseResult<RootNode> {
  return parseTokenList(source, tokens, lexicalTokenDiagnostics(tokens));
}`;
}

function deterministicParseRuntime(): string {
  return `function parseTokenList(
  source: string,
  tokens: readonly Token[],
  lexicalDiagnostics: readonly ParseDiagnostic[],
): ParseResult<RootNode> {
  if (lexicalDiagnostics.length > 0) {
    return {
      ok: false,
      root: null,
      source,
      tokens,
      diagnostics: lexicalDiagnostics,
    };
  }

  const states: number[] = [0];
  const values: unknown[] = [null];
  let index = 0;

  while (true) {
    index = skipTrivia(tokens, index);
    const token = tokens[index] ?? eofToken(source.length);
    const terminal = tokenToTerminal(token);
    const state = states[states.length - 1];
    const action = findAction(state, terminal);

    if (!action) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [unexpectedTokenDiagnostic(token, state)],
      };
    }

    if (action.kind === "shift") {
      states.push(action.state);
      values.push(shiftedToken(token, index));
      index++;
      continue;
    }

    if (action.kind === "accept") {
      return acceptedParseResult(source, tokens, values[values.length - 1]);
    }

    const production = PRODUCTIONS[action.production];
    const rhsValues = production.rhsLength === 0
      ? []
      : values.splice(values.length - production.rhsLength, production.rhsLength);
    states.splice(states.length - production.rhsLength, production.rhsLength);
    let reduced: unknown;
    try {
      reduced = reduceProduction(
        production.reducer,
        rhsValues,
        token.span.start,
        index,
      );
    } catch (error) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [internalParserDiagnostic(error, token.span)],
      };
    }
    const gotoState = findGoto(states[states.length - 1], production.lhs);
    if (gotoState === undefined) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [{
          code: "PARSER_INTERNAL_ERROR",
          message: "Parser table is missing a goto entry.",
          span: currentSpan(token),
        }],
      };
    }
    states.push(gotoState);
    values.push(reduced);
  }
}

function findAction(state: number, terminal: number): RuntimeAction | undefined {
  const encoded = parserAction(state, terminal);
  if (encoded === ACTION_NONE) return undefined;
  const kind = encoded & ACTION_KIND_MASK;
  const payload = encoded & ACTION_PAYLOAD_MASK;
  if (kind === ACTION_SHIFT) return { kind: "shift", state: payload };
  if (kind === ACTION_REDUCE) return { kind: "reduce", production: payload };
  if (kind === ACTION_ACCEPT) return { kind: "accept" };
  return undefined;
}

function findGoto(state: number, nonterminal: number): number | undefined {
  const next = parserGoto(state, nonterminal);
  return next === NO_GOTO ? undefined : next;
}`;
}

function branchParseRuntime(): string {
  return `function parseTokenList(
  source: string,
  tokens: readonly Token[],
  lexicalDiagnostics: readonly ParseDiagnostic[],
): ParseResult<RootNode> {
  if (lexicalDiagnostics.length > 0) {
    return {
      ok: false,
      root: null,
      source,
      tokens,
      diagnostics: lexicalDiagnostics,
    };
  }

  const pending: ParseBranch[] = [{
    states: [0],
    values: [null],
    index: 0,
  }];
  let bestFailure: ParseFailure | null = null;
  let exploredBranches = 0;

  while (pending.length > 0) {
    const branch = pending.pop()!;
    exploredBranches++;
    if (exploredBranches > MAX_PARSE_BRANCHES) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [{
          code: "PARSER_BRANCH_LIMIT",
          message: "Parser exceeded the branch exploration limit.",
          span: { start: source.length, end: source.length },
        }],
      };
    }

    while (true) {
      const advanced = advanceBranch(source, tokens, branch, pending);
      if (advanced.kind === "continue") continue;
      if (advanced.kind === "forked") break;
      if (advanced.kind === "success") return advanced.result;
      bestFailure = betterFailure(bestFailure, advanced.failure);
      break;
    }
  }

  return {
    ok: false,
    root: null,
    source,
    tokens,
    diagnostics: [
      bestFailure?.diagnostic ?? {
        code: "PARSER_INTERNAL_ERROR",
        message: "Parser exhausted all branches without a diagnostic.",
        span: { start: source.length, end: source.length },
      },
    ],
  };
}

function advanceBranch(
  source: string,
  tokens: readonly Token[],
  branch: ParseBranch,
  pending: ParseBranch[],
): BranchAdvanceResult {
  branch.index = skipTrivia(tokens, branch.index);
  const token = tokens[branch.index] ?? eofToken(source.length);
  const terminal = tokenToTerminal(token);
  const state = branch.states[branch.states.length - 1];
  const actions = findActions(state, terminal);

  if (actions.length === 0) {
    return {
      kind: "failure",
      failure: {
        offset: token.span.start,
        diagnostic: unexpectedTokenDiagnostic(token, state),
      },
    };
  }

  if (actions.length > 1) {
    for (let index = actions.length - 1; index >= 0; index--) {
      const fork = cloneBranch(branch);
      const advanced = applyAction(source, tokens, fork, token, actions[index]);
      if (advanced.kind === "success" || advanced.kind === "failure") {
        return advanced;
      }
      pending.push(fork);
    }
    return { kind: "forked" };
  }

  return applyAction(source, tokens, branch, token, actions[0]);
}

function applyAction(
  source: string,
  tokens: readonly Token[],
  branch: ParseBranch,
  token: Token,
  action: RuntimeAction,
): BranchAdvanceResult {
  if (action.kind === "shift") {
    branch.states.push(action.state);
    branch.values.push(shiftedToken(token, branch.index));
    branch.index++;
    return { kind: "continue" };
  }

  if (action.kind === "accept") {
    return {
      kind: "success",
      result: acceptedParseResult(source, tokens, branch.values[branch.values.length - 1]),
    };
  }

  const production = PRODUCTIONS[action.production];
  const rhsValues = production.rhsLength === 0
    ? []
    : branch.values.splice(
      branch.values.length - production.rhsLength,
      production.rhsLength,
    );
  branch.states.splice(
    branch.states.length - production.rhsLength,
    production.rhsLength,
  );
  let reduced: unknown;
  try {
    reduced = reduceProduction(
      production.reducer,
      rhsValues,
      token.span.start,
      branch.index,
    );
  } catch (error) {
    return {
      kind: "failure",
      failure: {
        offset: token.span.start,
        diagnostic: internalParserDiagnostic(error, token.span),
      },
    };
  }
  const gotoState = findGoto(
    branch.states[branch.states.length - 1],
    production.lhs,
  );
  if (gotoState === undefined) {
    return {
      kind: "failure",
      failure: {
        offset: currentSpan(token).start,
        diagnostic: {
          code: "PARSER_INTERNAL_ERROR",
          message: "Parser table is missing a goto entry.",
          span: currentSpan(token),
        },
      },
    };
  }
  branch.states.push(gotoState);
  branch.values.push(reduced);
  return { kind: "continue" };
}

function cloneBranch(branch: ParseBranch): ParseBranch {
  return {
    states: [...branch.states],
    values: [...branch.values],
    index: branch.index,
  };
}

function betterFailure(
  current: ParseFailure | null,
  candidate: ParseFailure,
): ParseFailure {
  if (!current || candidate.offset > current.offset) return candidate;
  if (candidate.offset < current.offset) return current;
  const currentExpected = current.diagnostic.expected?.length ?? 0;
  const candidateExpected = candidate.diagnostic.expected?.length ?? 0;
  return candidateExpected > currentExpected ? candidate : current;
}

function findActions(state: number, terminal: number): RuntimeAction[] {
  const actions: RuntimeAction[] = [];
  for (const entry of ACTIONS[state] ?? []) {
    if (entry[0] !== terminal) continue;
    if (entry[1] === 1) {
      actions.push({ kind: "shift", state: entry[2] });
    } else if (entry[1] === 2) {
      actions.push({ kind: "reduce", production: entry[2] });
    } else {
      actions.push({ kind: "accept" });
    }
  }
  return actions;
}

function findGoto(state: number, nonterminal: number): number | undefined {
  const next = parserGoto(state, nonterminal);
  return next === NO_GOTO ? undefined : next;
}`;
}

function wasmParseRuntime(): string {
  return `function parseTokenList(
  source: string,
  tokens: readonly Token[],
  lexicalDiagnostics: readonly ParseDiagnostic[],
  parseStream?: WasmParseStream,
): ParseResult<RootNode> {
  if (lexicalDiagnostics.length > 0) {
    return {
      ok: false,
      root: null,
      source,
      tokens,
      diagnostics: lexicalDiagnostics,
    };
  }

  const stream = parseStream ?? compactTokenStream(source, tokens);
  const traced = parseTrace(stream.input, stream.terminalCount);
  if (!traced.ok) {
    const token = stream.tokens[traced.index] ?? eofToken(source.length);
    if (traced.internal) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [{
          code: "PARSER_INTERNAL_ERROR",
          message: "Wasm parser trace failed.",
          span: currentSpan(token),
        }],
      };
    }
    return {
      ok: false,
      root: null,
      source,
      tokens,
      diagnostics: [unexpectedTokenDiagnostic(token, traced.state)],
    };
  }

  return replayTrace(
    source,
    tokens,
    stream.tokens,
    stream.tokenIndices,
    traced.trace,
  );
}

interface CompactTokenStream {
  tokens: readonly Token[];
  tokenIndices: readonly number[];
  input: ParseTraceInput;
  terminalCount: number;
}

function compactTokenStream(
  source: string,
  tokens: readonly Token[],
): CompactTokenStream {
  const streamTokens: Token[] = new Array(tokens.length + 1);
  const streamTokenIndices: number[] = new Array(tokens.length + 1);
  const terminalIds = new Int32Array(tokens.length + 1);
  let streamTokenCount = 0;
  let terminalCount = 0;
  let index = 0;
  while (true) {
    index = skipTrivia(tokens, index);
    const token = tokens[index] ?? eofToken(source.length);
    streamTokens[streamTokenCount] = token;
    streamTokenIndices[streamTokenCount] = index < tokens.length ? index : tokens.length;
    streamTokenCount++;
    terminalIds[terminalCount] = tokenToTerminal(token);
    terminalCount++;
    if (token.type === "eof" || index >= tokens.length) break;
    index++;
  }
  streamTokens.length = streamTokenCount;
  streamTokenIndices.length = streamTokenCount;
  const input = createParseTraceInput(terminalCount);
  input.terminals.set(terminalIds.subarray(0, terminalCount));
  return { tokens: streamTokens, tokenIndices: streamTokenIndices, input, terminalCount };
}

function replayTrace(
  source: string,
  tokens: readonly Token[],
  streamTokens: readonly Token[],
  streamTokenIndices: readonly number[],
  trace: Int32Array,
): ParseResult<RootNode> {
  const values: unknown[] = [null];
  let index = 0;

  for (let traceIndex = 0; traceIndex < trace.length; traceIndex++) {
    const encoded = trace[traceIndex];
    const kind = encoded >>> 24;
    const payload = encoded & 0x00ffffff;

    if (kind === 1) {
      values.push(shiftedToken(
        streamTokens[index] ?? eofToken(source.length),
        streamTokenIndices[index] ?? tokens.length,
      ));
      index++;
      continue;
    }

    if (kind === 3) {
      return acceptedParseResult(source, tokens, values[values.length - 1]);
    }

    const token = streamTokens[index] ?? eofToken(source.length);
    if (kind !== 2) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [{
          code: "PARSER_INTERNAL_ERROR",
          message: "Wasm parser trace contained an unknown action kind.",
          span: currentSpan(token),
        }],
      };
    }

    const production = PRODUCTIONS[payload];
    if (!production) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [{
          code: "PARSER_INTERNAL_ERROR",
          message: "Wasm parser trace referenced an unknown production.",
          span: currentSpan(token),
        }],
      };
    }
    if (production.rhsLength > values.length - 1) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [{
          code: "PARSER_INTERNAL_ERROR",
          message: "Wasm parser trace underflowed the replay stack.",
          span: currentSpan(token),
        }],
      };
    }
    const rhsValues = production.rhsLength === 0
      ? []
      : values.splice(values.length - production.rhsLength, production.rhsLength);
    let reduced: unknown;
    try {
      reduced = reduceProduction(
        production.reducer,
        rhsValues,
        token.span.start,
        streamTokenIndices[index] ?? tokens.length,
      );
    } catch (error) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [internalParserDiagnostic(error, token.span)],
      };
    }
    values.push(reduced);
  }

  return {
    ok: false,
    root: null,
    source,
    tokens,
    diagnostics: [{
      code: "PARSER_INTERNAL_ERROR",
      message: "Wasm parser trace ended without accepting.",
      span: { start: source.length, end: source.length },
    }],
  };
}`;
}

function reductionRuntime(): string {
  return `function reduceProduction(
  reducer: ReducerSpec,
  rhs: readonly unknown[],
  offset: number,
  tokenIndex: number,
): unknown {
  switch (reducer.kind) {
    case "start":
      return rhs[0];
    case "rule": {
      const fragment = toFragment(rhs[0]);
      const node = {
        type: "rule",
        name: RULE_NAMES[reducer.ruleId],
        span: fragment.span ?? spanFromChildren(fragment.children) ?? { start: 0, end: 0 },
        tokenRange: fragment.tokenRange ?? tokenRangeFromChildren(fragment.children) ?? { start: tokenIndex, end: tokenIndex },
        children: fragment.children,
        fields: buildFields(reducer.ruleId, fragment.fields),
      };
      return node as unknown as AnyRuleNode;
    }
    case "terminal":
      return tokenFragment(rhs[0] as ShiftedToken);
    case "ruleRef":
      return ruleFragment(rhs[0] as AnyRuleNode);
    case "identity":
    case "optionalSome":
      return toFragment(rhs[0]);
    case "sequence":
      return sequenceFragment(rhs, offset, tokenIndex);
    case "optionalEmpty":
      return emptyFragment(null, offset, tokenIndex);
    case "repeatEmpty":
      return emptyFragment([], offset, tokenIndex);
    case "repeatAppend":
    case "repeat1Append":
      return appendFragment(toFragment(rhs[0]), toFragment(rhs[1]));
    case "repeat1First": {
      const item = toFragment(rhs[0]);
      item.value = [item.value];
      return item;
    }
    case "separatedFirst": {
      const item = toFragment(rhs[0]);
      item.value = [item.value];
      return item;
    }
    case "separatedAppend":
      return appendSeparatedFragment(
        toFragment(rhs[0]),
        toFragment(rhs[1]),
        toFragment(rhs[2]),
      );
    case "field": {
      const fragment = toFragment(rhs[0]);
      fragment.fields.push({ name: reducer.name, value: fragment.value });
      return fragment;
    }
  }
}

function tokenFragment(shifted: ShiftedToken): Fragment {
  const token = shifted.token;
  if (!isMainSyntaxToken(token)) {
    throw new Error("Expected shifted main syntax token.");
  }
  return {
    value: token,
    children: [token],
    fields: [],
    span: token.span,
    tokenRange: { start: shifted.tokenIndex, end: shifted.tokenIndex + 1 },
  };
}

function ruleFragment(node: AnyRuleNode): Fragment {
  return {
    value: node,
    children: [node],
    fields: [],
    span: node.span,
    tokenRange: node.tokenRange,
  };
}

function sequenceFragment(
  values: readonly unknown[],
  offset: number,
  tokenIndex: number,
): Fragment {
  const fragmentValues: unknown[] = [];
  const children: SyntaxElement[] = [];
  const fields: FieldCapture[] = [];
  let span: Span | null = null;
  let tokenRange: TokenRange | null = null;
  for (const value of values) {
    const part = toFragment(value);
    fragmentValues.push(part.value);
    appendAll(children, part.children);
    appendAll(fields, part.fields);
    span = combineSpans(span, part.span);
    tokenRange = combineTokenRanges(tokenRange, part.tokenRange);
  }
  return {
    value: fragmentValues,
    children,
    fields,
    span: span ?? { start: offset, end: offset },
    tokenRange: tokenRange ?? { start: tokenIndex, end: tokenIndex },
  };
}

function emptyFragment(
  value: unknown,
  offset: number,
  tokenIndex: number,
): Fragment {
  return {
    value,
    children: [],
    fields: [],
    span: { start: offset, end: offset },
    tokenRange: { start: tokenIndex, end: tokenIndex },
  };
}

function appendFragment(list: Fragment, item: Fragment): Fragment {
  const values = asMutableArray(list.value);
  values.push(item.value);
  appendAll(list.children, item.children);
  appendAll(list.fields, item.fields);
  return {
    value: values,
    children: list.children,
    fields: list.fields,
    span: combineSpans(list.span, item.span),
    tokenRange: combineTokenRanges(list.tokenRange, item.tokenRange),
  };
}

function appendSeparatedFragment(
  list: Fragment,
  separator: Fragment,
  item: Fragment,
): Fragment {
  const values = asMutableArray(list.value);
  values.push(item.value);
  appendAll(list.children, separator.children);
  appendAll(list.children, item.children);
  appendAll(list.fields, separator.fields);
  appendAll(list.fields, item.fields);
  return {
    value: values,
    children: list.children,
    fields: list.fields,
    span: combineSpans(combineSpans(list.span, separator.span), item.span),
    tokenRange: combineTokenRanges(
      combineTokenRanges(list.tokenRange, separator.tokenRange),
      item.tokenRange,
    ),
  };
}

function toFragment(value: unknown): Fragment {
  if (isFragment(value)) return value;
  if (isRuleNode(value)) return ruleFragment(value);
  if (isShiftedToken(value)) return tokenFragment(value);
  throw new Error("Expected parser reduction fragment, rule node, or token.");
}

function asMutableArray(value: unknown): unknown[] {
  if (Array.isArray(value)) return value;
  throw new Error("Expected parser reduction array.");
}

function appendAll<T>(target: T[], values: readonly T[]): T[] {
  for (const value of values) target.push(value);
  return target;
}

function combineDiagnostics(
  left: readonly ParseDiagnostic[],
  right: readonly ParseDiagnostic[],
): readonly ParseDiagnostic[] {
  if (left.length === 0) return right;
  if (right.length === 0) return left;
  return [...left, ...right];
}

function lexicalDiagnostics(
  diagnostics: readonly LexDiagnostic[],
): readonly ParseDiagnostic[] {
  if (diagnostics.length === 0) return EMPTY_PARSE_DIAGNOSTICS;
  const parsed: ParseDiagnostic[] = [];
  for (const diagnostic of diagnostics) {
    parsed.push(lexicalDiagnostic(diagnostic));
  }
  return parsed;
}

function lexicalTokenDiagnostics(
  tokens: readonly Token[],
): readonly ParseDiagnostic[] {
  let diagnostics: ParseDiagnostic[] | null = null;
  for (const token of tokens) {
    if (
      token.type !== "error" &&
      (isTriviaToken(token) || tokenToTerminal(token) >= 0)
    ) {
      continue;
    }
    diagnostics ??= [];
    diagnostics.push(lexicalTokenDiagnostic(token));
  }
  return diagnostics ?? EMPTY_PARSE_DIAGNOSTICS;
}

function buildFields(
  ruleId: number,
  captures: readonly FieldCapture[],
): Record<string, unknown> {
  const schema = RULE_FIELD_SCHEMAS[ruleId];
  if (!schema || schema.entries.length === 0) {
    if (captures.length > 0) {
      throw new Error("Rule has field captures but no field schema.");
    }
    return Object.create(null) as Record<string, unknown>;
  }
  const fields = Object.create(null) as Record<string, unknown>;
  const counts = Object.create(null) as Record<string, number>;
  for (const [name, config] of schema.entries) {
    fields[name] = config.array ? [] : config.nullable ? null : undefined;
    counts[name] = 0;
  }
  for (const capture of captures) {
    const config = schema.byName[capture.name];
    if (!config) {
      throw new Error(\`Unknown field capture '\${capture.name}'.\`);
    }
    counts[capture.name] = (counts[capture.name] ?? 0) + 1;
    if (config.array) {
      const values = fields[capture.name];
      if (!Array.isArray(values)) {
        throw new Error(\`Array field '\${capture.name}' was not initialized as an array.\`);
      }
      values.push(capture.value);
    } else {
      if ((counts[capture.name] ?? 0) > 1) {
        throw new Error(\`Scalar field '\${capture.name}' was captured more than once.\`);
      }
      fields[capture.name] = capture.value;
    }
  }
  for (const [name, config] of schema.entries) {
    const count = counts[name] ?? 0;
    if (config.array) {
      if (!Array.isArray(fields[name])) {
        throw new Error(\`Array field '\${name}' was not initialized as an array.\`);
      }
      continue;
    }
    if (!config.nullable && count !== 1) {
      throw new Error(\`Required field '\${name}' was captured \${count} times.\`);
    }
    if (config.nullable && count > 1) {
      throw new Error(\`Nullable field '\${name}' was captured more than once.\`);
    }
  }
  return fields;
}

function acceptedParseResult(
  source: string,
  tokens: readonly Token[],
  accepted: unknown,
): ParseResult<RootNode> {
  const root = isRuleNode(accepted)
    ? accepted as RootNode
    : isFragment(accepted) && isRuleNode(accepted.value)
    ? accepted.value as RootNode
    : null;
  if (root) {
    return {
      ok: true,
      root,
      source,
      tokens,
      diagnostics: [],
    };
  }
  return {
    ok: false,
    root: null,
    source,
    tokens,
    diagnostics: [{
      code: "PARSER_INTERNAL_ERROR",
      message: "Parser accepted without producing a root node.",
      span: { start: source.length, end: source.length },
    }],
  };
}

function expectedTerminals(state: number): readonly string[] {
  return EXPECTED_TERMINALS[state] ?? [];
}

function unexpectedTokenDiagnostic(token: Token, state: number): ParseDiagnostic {
  const expected = expectedTerminals(state);
  const found = tokenDisplay(token);
  const code = expected.includes("EOF") && found !== "EOF"
    ? "PARSE_TRAILING_INPUT"
    : "PARSE_UNEXPECTED_TOKEN";
  return {
    code,
    message: \`Unexpected token \${found}.\`,
    span: token.span,
    expected,
    found,
  };
}

function tokenToTerminal(token: Token): number {
  if (token.type === "eof") return EOF_TERMINAL;
  if (token.type === "named" && token.channel === "main") {
    return NAMED_TERMINALS.get(token.kind) ?? -1;
  }
  if (token.type === "literal") {
    return LITERAL_TERMINALS.get(token.literal) ?? -1;
  }
  return -1;
}

function isTriviaToken(token: Token): boolean {
  return token.type === "named" && token.channel === "trivia";
}

function lexicalTokenDiagnostic(token: Token): ParseDiagnostic {
  if (token.type === "error") {
    return {
      code: "PARSE_LEXICAL_ERROR",
      message: \`Unexpected character \${JSON.stringify(token.text)}.\`,
      span: token.span,
      found: JSON.stringify(token.text),
    };
  }
  return {
    code: "PARSE_LEXICAL_ERROR",
    message: \`Token \${tokenDisplay(token)} is not part of this parser's terminal set.\`,
    span: token.span,
    found: tokenDisplay(token),
  };
}

function shiftedToken(token: Token, tokenIndex: number): ShiftedToken {
  return { token, tokenIndex };
}

function isRuleNode(value: unknown): value is AnyRuleNode {
  return !!value &&
    typeof value === "object" &&
    (value as { type?: unknown }).type === "rule";
}

function isShiftedToken(value: unknown): value is ShiftedToken {
  return !!value &&
    typeof value === "object" &&
    "token" in value &&
    "tokenIndex" in value;
}

function isFragment(value: unknown): value is Fragment {
  return !!value &&
    typeof value === "object" &&
    "value" in value &&
    "children" in value &&
    "fields" in value &&
    "tokenRange" in value;
}

function isMainSyntaxToken(
  value: unknown,
): value is MainNamedToken | LiteralToken {
  return !!value &&
    typeof value === "object" &&
    (
      (value as { type?: unknown }).type === "literal" ||
      ((value as { type?: unknown; channel?: unknown }).type === "named" &&
        (value as { channel?: unknown }).channel === "main")
    );
}

function validateTokenStream(
  source: string,
  tokens: readonly Token[],
): ParseDiagnostic[] {
  const diagnostics: ParseDiagnostic[] = [];
  const canonical = lex(source, { preserveTrivia: true });
  const canonicalTokens = canonical.tokens;
  let canonicalIndex = 0;
  let previousEnd = 0;
  let eofIndex = -1;

  for (let index = 0; index < tokens.length; index++) {
    const token = tokens[index];
    const span = token.span;
    if (
      !Number.isInteger(span.start) ||
      !Number.isInteger(span.end) ||
      span.start < 0 ||
      span.end < span.start ||
      span.end > source.length
    ) {
      diagnostics.push(invalidTokenStream(
        \`Token at index \${index} has an invalid span.\`,
        clampSpan(span, source.length),
      ));
      continue;
    }

    if (span.start > previousEnd) {
      const gapDiagnostic = validateSourceGap(
        canonicalTokens,
        previousEnd,
        span.start,
      );
      if (gapDiagnostic) diagnostics.push(gapDiagnostic);
    }

    if (span.start < previousEnd) {
      diagnostics.push(invalidTokenStream(
        \`Token at index \${index} overlaps a previous token.\`,
        span,
      ));
    }
    previousEnd = Math.max(previousEnd, span.end);

    if (token.type === "eof") {
      const matched = matchCanonicalToken(
        canonicalTokens,
        canonicalIndex,
        token,
      );
      if (matched < 0) {
        diagnostics.push(invalidTokenStream(
          \`Token at index \${index} does not match canonical lexer output.\`,
          span,
        ));
      } else {
        canonicalIndex = matched + 1;
      }
      if (eofIndex !== -1) {
        diagnostics.push(invalidTokenStream(
          "Token stream contains more than one EOF token.",
          span,
        ));
      }
      eofIndex = index;
      if (
        token.text !== "" ||
        token.channel !== "main" ||
        span.start !== span.end ||
        span.start !== source.length
      ) {
        diagnostics.push(invalidTokenStream(
          "EOF token must have empty text, main channel, and an empty span at the end of the source.",
          span,
        ));
      }
      continue;
    }

    if (eofIndex !== -1) {
      diagnostics.push(invalidTokenStream(
        "Token stream contains tokens after EOF.",
        span,
      ));
    }

    if (span.start === span.end) {
      diagnostics.push(invalidTokenStream(
        \`Token at index \${index} has zero width.\`,
        span,
      ));
    }

    const sourceText = source.slice(span.start, span.end);
    if (token.text !== sourceText) {
      diagnostics.push(invalidTokenStream(
        \`Token at index \${index} text does not match the source slice.\`,
        span,
      ));
    }
    if (token.type === "literal") {
      if (token.channel !== "main" || token.text !== token.literal) {
        diagnostics.push(invalidTokenStream(
          "Literal tokens must use the main channel and text equal to the literal.",
          span,
        ));
      }
    } else if (token.type === "named") {
      if (token.channel !== "main" && token.channel !== "trivia") {
        diagnostics.push(invalidTokenStream(
          "Named tokens must use the main or trivia channel.",
          span,
        ));
      } else if (token.channel === "main") {
        if (!MAIN_TOKEN_KINDS.has(token.kind)) {
          diagnostics.push(invalidTokenStream(
            \`Named token kind '\${token.kind}' is not a main token kind.\`,
            span,
          ));
        }
      } else if (!TRIVIA_TOKEN_KINDS.has(token.kind)) {
        diagnostics.push(invalidTokenStream(
          \`Named token kind '\${token.kind}' is not a trivia token kind.\`,
          span,
        ));
      }
    } else if (token.type === "error") {
      if (token.channel !== "error") {
        diagnostics.push(invalidTokenStream(
          "Error tokens must use the error channel.",
          span,
        ));
      }
    } else {
      diagnostics.push(invalidTokenStream("Token has an unknown type.", span));
    }
    const matched = matchCanonicalToken(
      canonicalTokens,
      canonicalIndex,
      token,
    );
    if (matched < 0) {
      diagnostics.push(invalidTokenStream(
        \`Token at index \${index} does not match canonical lexer output.\`,
        span,
      ));
    } else {
      canonicalIndex = matched + 1;
    }
  }

  if (eofIndex !== -1 && eofIndex !== tokens.length - 1) {
    diagnostics.push(invalidTokenStream(
      "EOF must be the final token in the stream.",
      tokens[eofIndex]?.span ?? { start: source.length, end: source.length },
    ));
  }
  if (previousEnd < source.length && eofIndex === -1) {
    const gapDiagnostic = validateSourceGap(
      canonicalTokens,
      previousEnd,
      source.length,
    );
    if (gapDiagnostic) diagnostics.push(gapDiagnostic);
  }
  return diagnostics;
}

function validateSourceGap(
  canonicalTokens: readonly Token[],
  start: number,
  end: number,
): ParseDiagnostic | null {
  if (start === end) return null;
  for (const token of canonicalTokens) {
    if (token.type === "eof") continue;
    if (token.span.end <= start) continue;
    if (token.span.start >= end) break;
    if (
      token.type !== "named" ||
      token.channel !== "trivia" ||
      token.span.start < start ||
      token.span.end > end
    ) {
      return invalidTokenStream(
        "Token stream omits nontrivia source text.",
        { start, end },
      );
    }
  }
  return null;
}

function matchCanonicalToken(
  canonicalTokens: readonly Token[],
  startIndex: number,
  token: Token,
): number {
  for (let index = startIndex; index < canonicalTokens.length; index++) {
    const canonical = canonicalTokens[index];
    if (canonical.type !== "eof" && isTriviaToken(canonical)) {
      if (sameToken(canonical, token)) return index;
      if (canonical.span.end <= token.span.start) continue;
    }
    return sameToken(canonical, token) ? index : -1;
  }
  return -1;
}

function sameToken(left: Token, right: Token): boolean {
  if (
    left.type !== right.type ||
    left.text !== right.text ||
    left.channel !== right.channel ||
    left.span.start !== right.span.start ||
    left.span.end !== right.span.end
  ) {
    return false;
  }
  if (left.type === "named" && right.type === "named") {
    return left.kind === right.kind;
  }
  if (left.type === "literal" && right.type === "literal") {
    return left.literal === right.literal;
  }
  return true;
}

function invalidTokenStream(message: string, span: Span): ParseDiagnostic {
  return {
    code: "PARSE_INVALID_TOKEN_STREAM",
    message,
    span,
  };
}

function clampSpan(span: Span, sourceLength: number): Span {
  const start = Math.min(Math.max(0, span.start), sourceLength);
  const end = Math.min(Math.max(start, span.end), sourceLength);
  return { start, end };
}

function internalParserDiagnostic(error: unknown, span: Span): ParseDiagnostic {
  return {
    code: "PARSER_INTERNAL_ERROR",
    message: error instanceof Error ? error.message : String(error),
    span,
  };
}

function tokenDisplay(token: Token): string {
  if (token.type === "eof") return "EOF";
  if (token.type === "named") return token.kind;
  if (token.type === "literal") return JSON.stringify(token.literal);
  return JSON.stringify(token.text);
}

function skipTrivia(tokens: readonly Token[], start: number): number {
  let index = start;
  while (tokens[index]?.type === "named" && tokens[index].channel === "trivia") {
    index++;
  }
  return index;
}

function lexicalDiagnostic(diagnostic: LexDiagnostic): ParseDiagnostic {
  return {
    code: "PARSE_LEXICAL_ERROR",
    message: diagnostic.message,
    span: diagnostic.span,
  };
}

function eofToken(offset: number): Token {
  return {
    type: "eof",
    text: "",
    span: { start: offset, end: offset },
    channel: "main",
  };
}

function currentSpan(token: Token): Span {
  return token.span;
}

function spanFromChildren(children: readonly SyntaxElement[]): Span | null {
  return children.reduce<Span | null>(
    (span, child) => combineSpans(span, child.span),
    null,
  );
}

function tokenRangeFromChildren(
  children: readonly SyntaxElement[],
): TokenRange | null {
  return children.reduce<TokenRange | null>((range, child) => {
    if (child.type === "rule") {
      return combineTokenRanges(range, child.tokenRange);
    }
    return range;
  }, null);
}

function combineSpans(left: Span | null, right: Span | null): Span | null {
  if (!left) return right;
  if (!right) return left;
  return {
    start: Math.min(left.start, right.start),
    end: Math.max(left.end, right.end),
  };
}

function combineTokenRanges(
  left: TokenRange | null,
  right: TokenRange | null,
): TokenRange | null {
  if (!left) return right;
  if (!right) return left;
  return {
    start: Math.min(left.start, right.start),
    end: Math.max(left.end, right.end),
  };
}`;
}

function bnfTableRows<T>(
  table: ReadonlyMap<number, ReadonlyMap<number, T>>,
  encode: (key: number, value: T) => GotoEntry,
): GotoEntry[][] {
  const maxState = Math.max(-1, ...table.keys());
  const rows: GotoEntry[][] = [];
  for (let state = 0; state <= maxState; state++) {
    const entries = [...(table.get(state)?.entries() ?? [])]
      .sort(([left], [right]) => left - right)
      .map(([key, value]) => encode(key, value));
    rows.push(entries);
  }
  return rows;
}

function bnfActionTableRows(
  table: ReadonlyMap<number, ReadonlyMap<number, LrActionSet>>,
): EncodedAction[][] {
  const maxState = Math.max(-1, ...table.keys());
  const rows: EncodedAction[][] = [];
  for (let state = 0; state <= maxState; state++) {
    const entries = [...(table.get(state)?.entries() ?? [])]
      .sort(([left], [right]) => left - right)
      .flatMap(([terminal, actions]) =>
        actions.map((action) => actionEntry(terminal, action))
      );
    rows.push(entries);
  }
  return rows;
}

function actionEntry(terminal: number, action: LrAction): EncodedAction {
  if (action.kind === "shift") return [terminal, 1, action.state];
  if (action.kind === "reduce") return [terminal, 2, action.production];
  return [terminal, 3];
}

function parserRuntimeActionRows(
  rows: readonly (readonly EncodedAction[])[],
): readonly (readonly (readonly [key: number, value: number])[])[] {
  return rows.map((row) =>
    row.map((entry) => [entry[0], encodeParserRuntimeAction(entry)] as const)
  );
}

function encodeParserRuntimeAction(action: EncodedAction): number {
  if (action[1] === 1) {
    assertParserRuntimePayload(action[2]);
    return RUNTIME_ACTION_SHIFT + action[2];
  }
  if (action[1] === 2) {
    assertParserRuntimePayload(action[2]);
    return RUNTIME_ACTION_REDUCE + action[2];
  }
  return RUNTIME_ACTION_ACCEPT;
}

function assertParserRuntimePayload(payload: number): void {
  if (payload < 0 || payload > RUNTIME_ACTION_PAYLOAD_MASK) {
    throw new Error(
      `Parser runtime action payload ${payload} exceeds the encoded action limit.`,
    );
  }
}

function expectedTerminalRows(
  bnf: BnfGrammar,
  lr: LrTable,
): readonly (readonly string[])[] {
  return lr.states.map((state) => {
    const row = lr.actions.get(state.id);
    return [
      ...new Set(
        [...(row?.keys() ?? [])].map((terminal) =>
          bnf.terminals[terminal]?.display ?? `#${terminal}`
        ),
      ),
    ].sort();
  });
}

function hasMultiActionEntries(
  table: ReadonlyMap<number, ReadonlyMap<number, LrActionSet>>,
): boolean {
  for (const row of table.values()) {
    for (const actions of row.values()) {
      if (actions.length > 1) return true;
    }
  }
  return false;
}

void (undefined as ReducerSpec | undefined);
