import type { TypeScriptTargetOptions } from "../../ast.ts";
import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import type { Dfa } from "../../compiler/regex/dfa.ts";
import type { RegexAst } from "../../compiler/regex/ast.ts";
import { buildLexerDfa } from "../../compiler/regex/lexer.ts";
import { parsePortableRegex } from "../../compiler/regex/parser.ts";

export function emitLexer(
  analyzed: AnalyzedGrammar,
  options: TypeScriptTargetOptions = {},
  plannedDfa?: Dfa,
): string {
  const namedSpecs = analyzed.tokens
    .filter((token) =>
      token.kind === "skip" ||
      (token.kind === "token" && analyzed.reachableTokens.has(token.id))
    )
    .map((token) => ({
      kind: token.name,
      pattern: token.pattern,
      channel: token.kind === "skip" ? "trivia" : "main",
      priority: token.priority,
      order: token.declarationOrder,
    }));
  const literalSpecs = analyzed.literals
    .filter((literal) => analyzed.reachableLiterals.has(literal.id))
    .map((literal) => ({
      literal: literal.value,
      priority: 0,
      order: literal.sourceOrder,
    }));
  const lexerSpecs = [
    ...namedSpecs.map((spec) => ({
      ast: parsePortableRegex(spec.pattern),
      type: "named" as const,
      priority: spec.priority,
      order: spec.order,
    })),
    ...literalSpecs.map((spec) => ({
      ast: literalAst(spec.literal),
      type: "literal" as const,
      priority: spec.priority,
      order: spec.order,
    })),
  ];
  const dfa = plannedDfa ?? buildLexerDfa(lexerSpecs);
  const transitions = dfa.states.map((state) =>
    state.transitions.map((transition) => [
      transition.start,
      transition.end,
      transition.target,
    ])
  );
  const accepts = dfa.states.map((state) => state.selectedAccept ?? -1);
  const preserveTrivia = options.preserveTrivia ?? true;

  return `// Generated by @mewhhaha/baba. Do not edit by hand.
import type {
  LexDiagnostic,
  LexOptions,
  LexResult,
  NamedTokenKind,
  Token,
} from "./syntax.ts";

const DEFAULT_PRESERVE_TRIVIA = ${JSON.stringify(preserveTrivia)};

const NAMED_SPECS: readonly {
  kind: NamedTokenKind;
  pattern: string;
  channel: "main" | "trivia";
  priority: number;
  order: number;
}[] = ${JSON.stringify(namedSpecs, null, 2)} as const;

const LITERAL_SPECS: readonly {
  literal: string;
  priority: number;
  order: number;
}[] = ${JSON.stringify(literalSpecs, null, 2)} as const;

const SPECS: readonly (
  | { type: "named"; specIndex: number }
  | { type: "literal"; specIndex: number }
)[] = ${
    JSON.stringify([
      ...namedSpecs.map((_, specIndex) => ({ type: "named", specIndex })),
      ...literalSpecs.map((_, specIndex) => ({ type: "literal", specIndex })),
    ])
  } as const;

const DFA_TRANSITIONS: readonly (readonly (readonly [
  start: number,
  end: number,
  target: number,
])[])[] = ${JSON.stringify(transitions)};

const DFA_ACCEPTS: readonly number[] = ${JSON.stringify(accepts)};

interface Candidate {
  specIndex: number;
  end: number;
}

export function lex(source: string, options: LexOptions = {}): LexResult {
  const preserveTrivia = options.preserveTrivia ?? DEFAULT_PRESERVE_TRIVIA;
  const tokens: Token[] = [];
  const diagnostics: LexDiagnostic[] = [];
  let offset = 0;

  while (offset < source.length) {
    const candidate = bestCandidate(source, offset);
    if (candidate) {
      const start = offset;
      const end = candidate.end;
      const specRef = SPECS[candidate.specIndex];
      if (specRef.type === "literal") {
        const spec = LITERAL_SPECS[specRef.specIndex];
        tokens.push({
          type: "literal",
          literal: spec.literal as never,
          text: spec.literal as never,
          span: { start, end },
          channel: "main",
        });
      } else {
        const spec = NAMED_SPECS[specRef.specIndex];
        if (spec.channel === "trivia") {
          if (preserveTrivia) {
            tokens.push({
              type: "named",
              kind: spec.kind as never,
              text: source.slice(start, end),
              span: { start, end },
              channel: "trivia",
            });
          }
        } else {
          tokens.push({
            type: "named",
            kind: spec.kind as never,
            text: source.slice(start, end),
            span: { start, end },
            channel: "main",
          });
        }
      }
      offset = end;
      continue;
    }

    const start = offset;
    const codePoint = source.codePointAt(offset);
    offset += codePoint !== undefined && codePoint > 0xffff ? 2 : 1;
    const text = source.slice(start, offset);
    tokens.push({
      type: "error",
      text,
      span: { start, end: offset },
      channel: "error",
    });
    diagnostics.push({
      code: "LEX_UNEXPECTED_CHARACTER",
      message: \`Unexpected character \${JSON.stringify(text)}.\`,
      span: { start, end: offset },
    });
  }

  tokens.push({
    type: "eof",
    text: "",
    span: { start: source.length, end: source.length },
    channel: "main",
  });
  return { source, tokens, diagnostics };
}

function bestCandidate(source: string, offset: number): Candidate | null {
  let state = 0;
  let index = offset;
  let best: Candidate | null = null;

  while (index < source.length) {
    const codePoint = source.codePointAt(index);
    if (codePoint === undefined) break;
    const target = transition(state, codePoint);
    if (target < 0) break;
    index += codePointLength(codePoint);
    state = target;
    const specIndex = DFA_ACCEPTS[state] ?? -1;
    if (specIndex >= 0) best = { specIndex, end: index };
  }

  return best;
}

function transition(state: number, codePoint: number): number {
  for (const [start, end, target] of DFA_TRANSITIONS[state] ?? []) {
    if (start <= codePoint && codePoint <= end) return target;
  }
  return -1;
}

function codePointLength(codePoint: number): 1 | 2 {
  return codePoint > 0xffff ? 2 : 1;
}
`;
}

function literalAst(value: string): RegexAst {
  const items: RegexAst[] = [];
  for (let index = 0; index < value.length;) {
    const codePoint = value.codePointAt(index)!;
    items.push({ kind: "literal", codePoint });
    index += codePoint > 0xffff ? 2 : 1;
  }
  if (items.length === 0) return { kind: "empty" };
  return items.length === 1 ? items[0] : { kind: "sequence", items };
}
