import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import type { BnfGrammar, ReducerSpec } from "./bnf.ts";
import type { LrAction, LrTable } from "./lr1.ts";
import { collectRuleFieldSchemas } from "./syntax_emit.ts";

export function emitParser(
  analyzed: AnalyzedGrammar,
  bnf: BnfGrammar,
  lr: LrTable,
): string {
  const actionRows = bnfTableRows(lr.actions, actionEntry);
  const gotoRows = bnfTableRows(lr.gotos, (nonterminal, target) => [
    nonterminal,
    target,
  ]);
  const productions = bnf.productions.map((production) => ({
    lhs: production.lhs,
    rhsLength: production.rhs.length,
    reducer: production.reducer,
  }));
  const terminalNames = bnf.terminals.map((terminal) => terminal.display);
  const namedTerminals: Record<string, number> = {};
  const literalTerminals: Record<string, number> = {};
  for (const terminal of bnf.terminals) {
    if (terminal.kind === "named") {
      namedTerminals[analyzed.tokens[terminal.tokenId!].name] = terminal.id;
    }
    if (terminal.kind === "literal") {
      literalTerminals[analyzed.literals[terminal.literalId!].value] =
        terminal.id;
    }
  }
  const ruleNames = analyzed.rules.map((rule) => rule.name);
  const fieldSchemas = Object.fromEntries(
    collectRuleFieldSchemas(analyzed).map((schema) => [
      schema.ruleId,
      Object.fromEntries(
        schema.fields.map((field) => [
          field.name,
          { array: field.array, nullable: field.nullable },
        ]),
      ),
    ]),
  );

  return `// Generated by @mewhhaha/baba. Do not edit by hand.
import { lex } from "./lexer.ts";
import type {
  AnyRuleNode,
  LexDiagnostic,
  LiteralToken,
  NamedToken,
  ParseDiagnostic,
  ParseOptions,
  ParseResult,
  RootNode,
  Span,
  SyntaxElement,
  Token,
} from "./syntax.ts";

type EncodedAction =
  | readonly [terminal: number, kind: 1, state: number]
  | readonly [terminal: number, kind: 2, production: number]
  | readonly [terminal: number, kind: 3];

type RuntimeAction =
  | { kind: "shift"; state: number }
  | { kind: "reduce"; production: number }
  | { kind: "accept" };

interface Production {
  lhs: number;
  rhsLength: number;
  reducer: ReducerSpec;
}

type ReducerSpec =
  | { kind: "start" }
  | { kind: "rule"; ruleId: number }
  | { kind: "terminal" }
  | { kind: "ruleRef" }
  | { kind: "identity" }
  | { kind: "sequence" }
  | { kind: "optionalEmpty" }
  | { kind: "optionalSome" }
  | { kind: "repeatEmpty" }
  | { kind: "repeatAppend" }
  | { kind: "repeat1First" }
  | { kind: "repeat1Append" }
  | { kind: "separatedFirst" }
  | { kind: "separatedAppend" }
  | { kind: "field"; name: string };

interface Fragment {
  value: unknown;
  children: readonly SyntaxElement[];
  fields: readonly FieldCapture[];
  span: Span | null;
}

interface FieldCapture {
  name: string;
  value: unknown;
}

const EOF_TERMINAL = ${bnf.eofTerminal};
const ACTIONS: readonly (readonly EncodedAction[])[] = ${
    JSON.stringify(actionRows)
  };
const GOTOS: readonly (readonly (readonly [nonterminal: number, state: number])[])[] = ${
    JSON.stringify(gotoRows)
  };
const PRODUCTIONS: readonly Production[] = ${JSON.stringify(productions)};
const TERMINAL_NAMES: readonly string[] = ${JSON.stringify(terminalNames)};
const NAMED_TERMINALS: Record<string, number> = ${
    JSON.stringify(namedTerminals)
  };
const LITERAL_TERMINALS: Record<string, number> = ${
    JSON.stringify(literalTerminals)
  };
const RULE_NAMES: readonly string[] = ${JSON.stringify(ruleNames)};
const RULE_FIELD_SCHEMAS: Record<number, Record<string, { array: boolean; nullable: boolean }>> = ${
    JSON.stringify(fieldSchemas)
  };

export function parse(
  source: string,
  options: ParseOptions = {},
): ParseResult<RootNode> {
  const lexed = lex(source, options);
  return parseTokenList(
    source,
    lexed.tokens,
    lexed.diagnostics.map((diagnostic) => lexicalDiagnostic(diagnostic)),
  );
}

export function parseTokens(
  source: string,
  tokens: readonly Token[],
): ParseResult<RootNode> {
  const diagnostics = tokens
    .filter((token) =>
      token.type === "error" ||
      (!isTriviaToken(token) && tokenToTerminal(token) < 0)
    )
    .map((token): ParseDiagnostic => lexicalTokenDiagnostic(token));
  return parseTokenList(source, tokens, diagnostics);
}

function parseTokenList(
  source: string,
  tokens: readonly Token[],
  lexicalDiagnostics: readonly ParseDiagnostic[],
): ParseResult<RootNode> {
  if (lexicalDiagnostics.length > 0) {
    return {
      ok: false,
      root: null,
      source,
      tokens,
      diagnostics: lexicalDiagnostics,
    };
  }

  const states = [0];
  const values: unknown[] = [null];
  let index = 0;

  while (true) {
    index = skipTrivia(tokens, index);
    const token = tokens[index] ?? eofToken(source.length);
    const terminal = tokenToTerminal(token);
    const state = states[states.length - 1];
    const action = findAction(state, terminal);

    if (!action) {
      const expected = expectedTerminals(state);
      const found = tokenDisplay(token);
      const code = expected.includes("EOF") && found !== "EOF"
        ? "PARSE_TRAILING_INPUT"
        : "PARSE_UNEXPECTED_TOKEN";
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [{
          code,
          message: \`Unexpected token \${found}.\`,
          span: token.span,
          expected,
          found,
        }],
      };
    }

    if (action.kind === "shift") {
      states.push(action.state);
      values.push(token);
      index++;
      continue;
    }

    if (action.kind === "accept") {
      const accepted = values[values.length - 1];
      const root = isRuleNode(accepted)
        ? accepted as RootNode
        : isFragment(accepted) && isRuleNode(accepted.value)
        ? accepted.value as RootNode
        : null;
      return {
        ok: root !== null,
        root,
        source,
        tokens,
        diagnostics: root ? [] : [{
          code: "PARSE_UNEXPECTED_TOKEN",
          message: "Parser accepted without producing a root node.",
          span: { start: source.length, end: source.length },
        }],
      };
    }

    const production = PRODUCTIONS[action.production];
    const rhsValues = production.rhsLength === 0
      ? []
      : values.splice(values.length - production.rhsLength, production.rhsLength);
    states.splice(states.length - production.rhsLength, production.rhsLength);
    const reduced = reduceProduction(production.reducer, rhsValues);
    const gotoState = findGoto(states[states.length - 1], production.lhs);
    if (gotoState === undefined) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [{
          code: "PARSE_UNEXPECTED_TOKEN",
          message: "Parser table is missing a goto entry.",
          span: currentSpan(token),
        }],
      };
    }
    states.push(gotoState);
    values.push(reduced);
  }
}

function reduceProduction(reducer: ReducerSpec, rhs: readonly unknown[]): unknown {
  switch (reducer.kind) {
    case "start":
      return rhs[0];
    case "rule": {
      const fragment = asFragment(rhs[0]);
      const node = {
        type: "rule",
        name: RULE_NAMES[reducer.ruleId],
        span: fragment.span ?? spanFromChildren(fragment.children) ?? { start: 0, end: 0 },
        children: fragment.children,
        fields: buildFields(reducer.ruleId, fragment.fields),
      };
      return node as AnyRuleNode;
    }
    case "terminal":
      return tokenFragment(rhs[0] as NamedToken | LiteralToken);
    case "ruleRef":
      return ruleFragment(rhs[0] as AnyRuleNode);
    case "identity":
    case "optionalSome":
      return asFragment(rhs[0]);
    case "sequence":
      return sequenceFragment(rhs.map(asFragment));
    case "optionalEmpty":
      return emptyFragment(null);
    case "repeatEmpty":
      return emptyFragment([]);
    case "repeatAppend":
    case "repeat1Append":
      return appendFragment(asFragment(rhs[0]), asFragment(rhs[1]));
    case "repeat1First": {
      const item = asFragment(rhs[0]);
      return { ...item, value: [item.value] };
    }
    case "separatedFirst": {
      const item = asFragment(rhs[0]);
      return { ...item, value: [item.value] };
    }
    case "separatedAppend":
      return appendSeparatedFragment(
        asFragment(rhs[0]),
        asFragment(rhs[1]),
        asFragment(rhs[2]),
      );
    case "field": {
      const fragment = asFragment(rhs[0]);
      return {
        ...fragment,
        fields: [...fragment.fields, { name: reducer.name, value: fragment.value }],
      };
    }
  }
}

function tokenFragment(token: NamedToken | LiteralToken): Fragment {
  return {
    value: token,
    children: [token],
    fields: [],
    span: token.span,
  };
}

function ruleFragment(node: AnyRuleNode): Fragment {
  return {
    value: node,
    children: [node],
    fields: [],
    span: node.span,
  };
}

function sequenceFragment(parts: readonly Fragment[]): Fragment {
  return {
    value: parts.map((part) => part.value),
    children: parts.flatMap((part) => [...part.children]),
    fields: parts.flatMap((part) => [...part.fields]),
    span: spanFromFragments(parts),
  };
}

function emptyFragment(value: unknown): Fragment {
  return { value, children: [], fields: [], span: null };
}

function appendFragment(list: Fragment, item: Fragment): Fragment {
  return {
    value: [...asArray(list.value), item.value],
    children: [...list.children, ...item.children],
    fields: [...list.fields, ...item.fields],
    span: combineSpans(list.span, item.span),
  };
}

function appendSeparatedFragment(
  list: Fragment,
  separator: Fragment,
  item: Fragment,
): Fragment {
  return {
    value: [...asArray(list.value), item.value],
    children: [...list.children, ...separator.children, ...item.children],
    fields: [...list.fields, ...separator.fields, ...item.fields],
    span: spanFromFragments([list, separator, item]),
  };
}

function asFragment(value: unknown): Fragment {
  return value as Fragment;
}

function asArray(value: unknown): readonly unknown[] {
  return Array.isArray(value) ? value : [];
}

function buildFields(
  ruleId: number,
  captures: readonly FieldCapture[],
): Record<string, unknown> {
  const schema = RULE_FIELD_SCHEMAS[ruleId] ?? {};
  const fields: Record<string, unknown> = {};
  for (const [name, config] of Object.entries(schema)) {
    fields[name] = config.array ? [] : config.nullable ? null : undefined;
  }
  for (const capture of captures) {
    const config = schema[capture.name];
    if (config?.array) {
      (fields[capture.name] as unknown[]).push(capture.value);
    } else {
      fields[capture.name] = capture.value;
    }
  }
  return fields;
}

function findAction(state: number, terminal: number): RuntimeAction | null {
  for (const entry of ACTIONS[state] ?? []) {
    if (entry[0] !== terminal) continue;
    if (entry[1] === 1) return { kind: "shift", state: entry[2] };
    if (entry[1] === 2) return { kind: "reduce", production: entry[2] };
    return { kind: "accept" };
  }
  return null;
}

function findGoto(state: number, nonterminal: number): number | undefined {
  for (const entry of GOTOS[state] ?? []) {
    if (entry[0] === nonterminal) return entry[1];
  }
  return undefined;
}

function expectedTerminals(state: number): readonly string[] {
  return [...new Set((ACTIONS[state] ?? []).map((entry) => TERMINAL_NAMES[entry[0]]))]
    .sort();
}

function tokenToTerminal(token: Token): number {
  if (token.type === "eof") return EOF_TERMINAL;
  if (token.type === "named" && token.channel === "main") {
    return NAMED_TERMINALS[token.kind] ?? -1;
  }
  if (token.type === "literal") return LITERAL_TERMINALS[token.literal] ?? -1;
  return -1;
}

function isTriviaToken(token: Token): boolean {
  return token.type === "named" && token.channel === "trivia";
}

function lexicalTokenDiagnostic(token: Token): ParseDiagnostic {
  if (token.type === "error") {
    return {
      code: "PARSE_LEXICAL_ERROR",
      message: \`Unexpected character \${JSON.stringify(token.text)}.\`,
      span: token.span,
      found: JSON.stringify(token.text),
    };
  }
  return {
    code: "PARSE_LEXICAL_ERROR",
    message: \`Token \${tokenDisplay(token)} is not part of this parser's terminal set.\`,
    span: token.span,
    found: tokenDisplay(token),
  };
}

function isRuleNode(value: unknown): value is AnyRuleNode {
  return !!value &&
    typeof value === "object" &&
    (value as { type?: unknown }).type === "rule";
}

function isFragment(value: unknown): value is Fragment {
  return !!value &&
    typeof value === "object" &&
    "value" in value &&
    "children" in value &&
    "fields" in value;
}

function tokenDisplay(token: Token): string {
  if (token.type === "eof") return "EOF";
  if (token.type === "named") return token.kind;
  if (token.type === "literal") return JSON.stringify(token.literal);
  return JSON.stringify(token.text);
}

function skipTrivia(tokens: readonly Token[], start: number): number {
  let index = start;
  while (tokens[index]?.type === "named" && tokens[index].channel === "trivia") {
    index++;
  }
  return index;
}

function lexicalDiagnostic(diagnostic: LexDiagnostic): ParseDiagnostic {
  return {
    code: "PARSE_LEXICAL_ERROR",
    message: diagnostic.message,
    span: diagnostic.span,
  };
}

function eofToken(offset: number): Token {
  return {
    type: "eof",
    text: "",
    span: { start: offset, end: offset },
    channel: "main",
  };
}

function currentSpan(token: Token): Span {
  return token.span;
}

function spanFromFragments(parts: readonly Fragment[]): Span | null {
  return parts.reduce<Span | null>(
    (span, part) => combineSpans(span, part.span),
    null,
  );
}

function spanFromChildren(children: readonly SyntaxElement[]): Span | null {
  return children.reduce<Span | null>(
    (span, child) => combineSpans(span, child.span),
    null,
  );
}

function combineSpans(left: Span | null, right: Span | null): Span | null {
  if (!left) return right;
  if (!right) return left;
  return {
    start: Math.min(left.start, right.start),
    end: Math.max(left.end, right.end),
  };
}
`;
}

function bnfTableRows<T>(
  table: ReadonlyMap<number, ReadonlyMap<number, T>>,
  encode: (key: number, value: T) => unknown,
): unknown[] {
  const maxState = Math.max(-1, ...table.keys());
  const rows: unknown[] = [];
  for (let state = 0; state <= maxState; state++) {
    const entries = [...(table.get(state)?.entries() ?? [])]
      .sort(([left], [right]) => left - right)
      .map(([key, value]) => encode(key, value));
    rows.push(entries);
  }
  return rows;
}

function actionEntry(terminal: number, action: LrAction): unknown {
  if (action.kind === "shift") return [terminal, 1, action.state];
  if (action.kind === "reduce") return [terminal, 2, action.production];
  return [terminal, 3];
}

void (undefined as ReducerSpec | undefined);
