import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import type { BnfGrammar, ReducerSpec } from "./bnf.ts";
import type { LrAction, LrActionSet, LrTable } from "./lr1.ts";
import { collectRuleFieldSchemas } from "./syntax_emit.ts";

export function emitParser(
  analyzed: AnalyzedGrammar,
  bnf: BnfGrammar,
  lr: LrTable,
): string {
  const actionRows = bnfActionTableRows(lr.actions);
  const gotoRows = bnfTableRows(lr.gotos, (nonterminal, target) => [
    nonterminal,
    target,
  ]);
  const productions = bnf.productions.map((production) => ({
    lhs: production.lhs,
    rhsLength: production.rhs.length,
    reducer: production.reducer,
  }));
  const terminalNames = bnf.terminals.map((terminal) => terminal.display);
  const namedTerminals: Array<readonly [string, number]> = [];
  const literalTerminals: Array<readonly [string, number]> = [];
  for (const terminal of bnf.terminals) {
    if (terminal.kind === "named") {
      namedTerminals.push([
        analyzed.tokens[terminal.tokenId!].name,
        terminal.id,
      ]);
    }
    if (terminal.kind === "literal") {
      literalTerminals.push([
        analyzed.literals[terminal.literalId!].value,
        terminal.id,
      ]);
    }
  }
  const ruleNames = analyzed.rules.map((rule) => rule.name);
  const fieldSchemas = collectRuleFieldSchemas(analyzed).map((schema) =>
    [
      schema.ruleId,
      schema.fields.map((field) => [
        field.name,
        { array: field.array, nullable: field.nullable },
      ]),
    ] as const
  );
  const mainTokenKinds = analyzed.tokens
    .filter((token) =>
      token.kind === "token" && analyzed.reachableTokens.has(token.id)
    )
    .map((token) => token.name);
  const triviaTokenKinds = analyzed.tokens
    .filter((token) => token.kind === "skip")
    .map((token) => token.name);

  return `// Generated by @mewhhaha/baba. Do not edit by hand.
import { lex } from "./lexer.ts";
import type {
  AnyRuleNode,
  LexDiagnostic,
  LiteralToken,
  MainNamedToken,
  ParseDiagnostic,
  ParseOptions,
  ParseResult,
  RootNode,
  Span,
  SyntaxElement,
  Token,
} from "./syntax.ts";

type EncodedAction =
  | readonly [terminal: number, kind: 1, state: number]
  | readonly [terminal: number, kind: 2, production: number]
  | readonly [terminal: number, kind: 3];

type RuntimeAction =
  | { kind: "shift"; state: number }
  | { kind: "reduce"; production: number }
  | { kind: "accept" };

interface Production {
  lhs: number;
  rhsLength: number;
  reducer: ReducerSpec;
}

interface ParseBranch {
  states: number[];
  values: unknown[];
  index: number;
}

type BranchAdvanceResult =
  | { kind: "continue" }
  | { kind: "forked" }
  | { kind: "success"; result: ParseResult<RootNode> }
  | { kind: "failure"; failure: ParseFailure };

interface ParseFailure {
  diagnostic: ParseDiagnostic;
  offset: number;
}

type ReducerSpec =
  | { kind: "start" }
  | { kind: "rule"; ruleId: number }
  | { kind: "terminal" }
  | { kind: "ruleRef" }
  | { kind: "identity" }
  | { kind: "sequence" }
  | { kind: "optionalEmpty" }
  | { kind: "optionalSome" }
  | { kind: "repeatEmpty" }
  | { kind: "repeatAppend" }
  | { kind: "repeat1First" }
  | { kind: "repeat1Append" }
  | { kind: "separatedFirst" }
  | { kind: "separatedAppend" }
  | { kind: "field"; name: string };

interface Fragment {
  value: unknown;
  children: SyntaxElement[];
  fields: FieldCapture[];
  span: Span | null;
}

interface FieldCapture {
  name: string;
  value: unknown;
}

interface FieldConfig {
  array: boolean;
  nullable: boolean;
}

interface RuntimeRuleFieldSchema {
  entries: readonly (readonly [name: string, config: FieldConfig])[];
  byName: Record<string, FieldConfig>;
}

const EOF_TERMINAL = ${bnf.eofTerminal};
const ACTIONS: readonly (readonly EncodedAction[])[] = ${
    JSON.stringify(actionRows)
  };
const GOTOS: readonly (readonly (readonly [nonterminal: number, state: number])[])[] = ${
    JSON.stringify(gotoRows)
  };
const PRODUCTIONS: readonly Production[] = ${JSON.stringify(productions)};
const TERMINAL_NAMES: readonly string[] = ${JSON.stringify(terminalNames)};
const NAMED_TERMINALS = new Map<string, number>(${
    JSON.stringify(namedTerminals)
  });
const LITERAL_TERMINALS = new Map<string, number>(${
    JSON.stringify(literalTerminals)
  });
const MAIN_TOKEN_KINDS = new Set<string>(${JSON.stringify(mainTokenKinds)});
const TRIVIA_TOKEN_KINDS = new Set<string>(${JSON.stringify(triviaTokenKinds)});
const RULE_NAMES: readonly string[] = ${JSON.stringify(ruleNames)};
const EMPTY_PARSE_DIAGNOSTICS: readonly ParseDiagnostic[] = [];
const MAX_PARSE_BRANCHES = 100000;
const RULE_FIELD_SCHEMA_ENTRIES: readonly (
  readonly [
    ruleId: number,
    fields: readonly (readonly [
      name: string,
      config: FieldConfig,
    ])[],
  ]
)[] = ${JSON.stringify(fieldSchemas)};
const RULE_FIELD_SCHEMAS: readonly (RuntimeRuleFieldSchema | undefined)[] = (() => {
  const schemas: (RuntimeRuleFieldSchema | undefined)[] = [];
  for (const [ruleId, entries] of RULE_FIELD_SCHEMA_ENTRIES) {
    const byName = Object.create(null) as Record<string, FieldConfig>;
    for (const [name, config] of entries) byName[name] = config;
    schemas[ruleId] = { entries, byName };
  }
  return schemas;
})();

export function parse(
  source: string,
  options: ParseOptions = {},
): ParseResult<RootNode> {
  const lexed = lex(source, options);
  return parseTokenList(
    source,
    lexed.tokens,
    lexicalDiagnostics(lexed.diagnostics),
  );
}

export function parseTokens(
  source: string,
  tokens: readonly Token[],
): ParseResult<RootNode> {
  const streamDiagnostics = validateTokenStream(source, tokens);
  const tokenDiagnostics = lexicalTokenDiagnostics(tokens);
  return parseTokenList(
    source,
    tokens,
    combineDiagnostics(streamDiagnostics, tokenDiagnostics),
  );
}

export function parseTokensUnchecked(
  source: string,
  tokens: readonly Token[],
): ParseResult<RootNode> {
  return parseTokenList(source, tokens, lexicalTokenDiagnostics(tokens));
}

function parseTokenList(
  source: string,
  tokens: readonly Token[],
  lexicalDiagnostics: readonly ParseDiagnostic[],
): ParseResult<RootNode> {
  if (lexicalDiagnostics.length > 0) {
    return {
      ok: false,
      root: null,
      source,
      tokens,
      diagnostics: lexicalDiagnostics,
    };
  }

  const pending: ParseBranch[] = [{
    states: [0],
    values: [null],
    index: 0,
  }];
  let bestFailure: ParseFailure | null = null;
  let exploredBranches = 0;

  while (pending.length > 0) {
    const branch = pending.pop()!;
    exploredBranches++;
    if (exploredBranches > MAX_PARSE_BRANCHES) {
      return {
        ok: false,
        root: null,
        source,
        tokens,
        diagnostics: [{
          code: "PARSER_BRANCH_LIMIT",
          message: "Parser exceeded the branch exploration limit.",
          span: { start: source.length, end: source.length },
        }],
      };
    }

    while (true) {
      const advanced = advanceBranch(source, tokens, branch, pending);
      if (advanced.kind === "continue") continue;
      if (advanced.kind === "forked") break;
      if (advanced.kind === "success") return advanced.result;
      bestFailure = betterFailure(bestFailure, advanced.failure);
      break;
    }
  }

  return {
    ok: false,
    root: null,
    source,
    tokens,
    diagnostics: [
      bestFailure?.diagnostic ?? {
        code: "PARSER_INTERNAL_ERROR",
        message: "Parser exhausted all branches without a diagnostic.",
        span: { start: source.length, end: source.length },
      },
    ],
  };
}

function advanceBranch(
  source: string,
  tokens: readonly Token[],
  branch: ParseBranch,
  pending: ParseBranch[],
): BranchAdvanceResult {
  branch.index = skipTrivia(tokens, branch.index);
  const token = tokens[branch.index] ?? eofToken(source.length);
  const terminal = tokenToTerminal(token);
  const state = branch.states[branch.states.length - 1];
  const actions = findActions(state, terminal);

  if (actions.length === 0) {
    const expected = expectedTerminals(state);
    const found = tokenDisplay(token);
    const code = expected.includes("EOF") && found !== "EOF"
      ? "PARSE_TRAILING_INPUT"
      : "PARSE_UNEXPECTED_TOKEN";
    return {
      kind: "failure",
      failure: {
        offset: token.span.start,
        diagnostic: {
          code,
          message: \`Unexpected token \${found}.\`,
          span: token.span,
          expected,
          found,
        },
      },
    };
  }

  if (actions.length > 1) {
    for (let index = actions.length - 1; index >= 0; index--) {
      const fork = cloneBranch(branch);
      const advanced = applyAction(source, tokens, fork, token, actions[index]);
      if (advanced.kind === "success" || advanced.kind === "failure") {
        return advanced;
      }
      pending.push(fork);
    }
    return { kind: "forked" };
  }

  return applyAction(source, tokens, branch, token, actions[0]);
}

function applyAction(
  source: string,
  tokens: readonly Token[],
  branch: ParseBranch,
  token: Token,
  action: RuntimeAction,
): BranchAdvanceResult {
  if (action.kind === "shift") {
    branch.states.push(action.state);
    branch.values.push(token);
    branch.index++;
    return { kind: "continue" };
  }

  if (action.kind === "accept") {
    const accepted = branch.values[branch.values.length - 1];
    const root = isRuleNode(accepted)
      ? accepted as RootNode
      : isFragment(accepted) && isRuleNode(accepted.value)
      ? accepted.value as RootNode
      : null;
    if (root) {
      return {
        kind: "success",
        result: {
          ok: true,
          root,
          source,
          tokens,
          diagnostics: [],
        },
      };
    }
    return {
      kind: "failure",
      failure: {
        offset: source.length,
        diagnostic: {
          code: "PARSER_INTERNAL_ERROR",
          message: "Parser accepted without producing a root node.",
          span: { start: source.length, end: source.length },
        },
      },
    };
  }

  const production = PRODUCTIONS[action.production];
  const rhsValues = production.rhsLength === 0
    ? []
    : branch.values.splice(
      branch.values.length - production.rhsLength,
      production.rhsLength,
    );
  branch.states.splice(
    branch.states.length - production.rhsLength,
    production.rhsLength,
  );
  let reduced: unknown;
  try {
    reduced = reduceProduction(
      production.reducer,
      rhsValues,
      token.span.start,
    );
  } catch (error) {
    return {
      kind: "failure",
      failure: {
        offset: token.span.start,
        diagnostic: internalParserDiagnostic(error, token.span),
      },
    };
  }
  const gotoState = findGoto(
    branch.states[branch.states.length - 1],
    production.lhs,
  );
  if (gotoState === undefined) {
    return {
      kind: "failure",
      failure: {
        offset: currentSpan(token).start,
        diagnostic: {
          code: "PARSER_INTERNAL_ERROR",
          message: "Parser table is missing a goto entry.",
          span: currentSpan(token),
        },
      },
    };
  }
  branch.states.push(gotoState);
  branch.values.push(reduced);
  return { kind: "continue" };
}

function cloneBranch(branch: ParseBranch): ParseBranch {
  return {
    states: [...branch.states],
    values: [...branch.values],
    index: branch.index,
  };
}

function betterFailure(
  current: ParseFailure | null,
  candidate: ParseFailure,
): ParseFailure {
  if (!current || candidate.offset > current.offset) return candidate;
  if (candidate.offset < current.offset) return current;
  const currentExpected = current.diagnostic.expected?.length ?? 0;
  const candidateExpected = candidate.diagnostic.expected?.length ?? 0;
  return candidateExpected > currentExpected ? candidate : current;
}

function reduceProduction(
  reducer: ReducerSpec,
  rhs: readonly unknown[],
  offset: number,
): unknown {
  switch (reducer.kind) {
    case "start":
      return rhs[0];
    case "rule": {
      const fragment = toFragment(rhs[0]);
      const node = {
        type: "rule",
        name: RULE_NAMES[reducer.ruleId],
        span: fragment.span ?? spanFromChildren(fragment.children) ?? { start: 0, end: 0 },
        children: fragment.children,
        fields: buildFields(reducer.ruleId, fragment.fields),
      };
      return node as unknown as AnyRuleNode;
    }
    case "terminal":
      return tokenFragment(rhs[0] as MainNamedToken | LiteralToken);
    case "ruleRef":
      return ruleFragment(rhs[0] as AnyRuleNode);
    case "identity":
    case "optionalSome":
      return toFragment(rhs[0]);
    case "sequence":
      return sequenceFragment(rhs, offset);
    case "optionalEmpty":
      return emptyFragment(null, offset);
    case "repeatEmpty":
      return emptyFragment([], offset);
    case "repeatAppend":
    case "repeat1Append":
      return appendFragment(toFragment(rhs[0]), toFragment(rhs[1]));
    case "repeat1First": {
      const item = toFragment(rhs[0]);
      item.value = [item.value];
      return item;
    }
    case "separatedFirst": {
      const item = toFragment(rhs[0]);
      item.value = [item.value];
      return item;
    }
    case "separatedAppend":
      return appendSeparatedFragment(
        toFragment(rhs[0]),
        toFragment(rhs[1]),
        toFragment(rhs[2]),
      );
    case "field": {
      const fragment = toFragment(rhs[0]);
      fragment.fields.push({ name: reducer.name, value: fragment.value });
      return fragment;
    }
  }
}

function tokenFragment(token: MainNamedToken | LiteralToken): Fragment {
  return {
    value: token,
    children: [token],
    fields: [],
    span: token.span,
  };
}

function ruleFragment(node: AnyRuleNode): Fragment {
  return {
    value: node,
    children: [node],
    fields: [],
    span: node.span,
  };
}

function sequenceFragment(values: readonly unknown[], offset: number): Fragment {
  const fragmentValues: unknown[] = [];
  const children: SyntaxElement[] = [];
  const fields: FieldCapture[] = [];
  let span: Span | null = null;
  for (const value of values) {
    const part = toFragment(value);
    fragmentValues.push(part.value);
    appendAll(children, part.children);
    appendAll(fields, part.fields);
    span = combineSpans(span, part.span);
  }
  return {
    value: fragmentValues,
    children,
    fields,
    span: span ?? { start: offset, end: offset },
  };
}

function emptyFragment(value: unknown, offset: number): Fragment {
  return {
    value,
    children: [],
    fields: [],
    span: { start: offset, end: offset },
  };
}

function appendFragment(list: Fragment, item: Fragment): Fragment {
  const values = asMutableArray(list.value);
  values.push(item.value);
  appendAll(list.children, item.children);
  appendAll(list.fields, item.fields);
  return {
    value: values,
    children: list.children,
    fields: list.fields,
    span: combineSpans(list.span, item.span),
  };
}

function appendSeparatedFragment(
  list: Fragment,
  separator: Fragment,
  item: Fragment,
): Fragment {
  const values = asMutableArray(list.value);
  values.push(item.value);
  appendAll(list.children, separator.children);
  appendAll(list.children, item.children);
  appendAll(list.fields, separator.fields);
  appendAll(list.fields, item.fields);
  return {
    value: values,
    children: list.children,
    fields: list.fields,
    span: combineSpans(combineSpans(list.span, separator.span), item.span),
  };
}

function asFragment(value: unknown): Fragment {
  if (isFragment(value)) return value;
  throw new Error("Expected parser reduction fragment.");
}

function toFragment(value: unknown): Fragment {
  if (isFragment(value)) return value;
  if (isRuleNode(value)) return ruleFragment(value);
  if (isMainSyntaxToken(value)) return tokenFragment(value);
  throw new Error("Expected parser reduction fragment, rule node, or token.");
}

function asMutableArray(value: unknown): unknown[] {
  if (Array.isArray(value)) return value;
  throw new Error("Expected parser reduction array.");
}

function appendAll<T>(target: T[], values: readonly T[]): T[] {
  for (const value of values) target.push(value);
  return target;
}

function combineDiagnostics(
  left: readonly ParseDiagnostic[],
  right: readonly ParseDiagnostic[],
): readonly ParseDiagnostic[] {
  if (left.length === 0) return right;
  if (right.length === 0) return left;
  return [...left, ...right];
}

function lexicalDiagnostics(
  diagnostics: readonly LexDiagnostic[],
): readonly ParseDiagnostic[] {
  if (diagnostics.length === 0) return EMPTY_PARSE_DIAGNOSTICS;
  const parsed: ParseDiagnostic[] = [];
  for (const diagnostic of diagnostics) {
    parsed.push(lexicalDiagnostic(diagnostic));
  }
  return parsed;
}

function lexicalTokenDiagnostics(
  tokens: readonly Token[],
): readonly ParseDiagnostic[] {
  let diagnostics: ParseDiagnostic[] | null = null;
  for (const token of tokens) {
    if (
      token.type !== "error" &&
      (isTriviaToken(token) || tokenToTerminal(token) >= 0)
    ) {
      continue;
    }
    diagnostics ??= [];
    diagnostics.push(lexicalTokenDiagnostic(token));
  }
  return diagnostics ?? EMPTY_PARSE_DIAGNOSTICS;
}

function buildFields(
  ruleId: number,
  captures: readonly FieldCapture[],
): Record<string, unknown> {
  const schema = RULE_FIELD_SCHEMAS[ruleId];
  if (!schema || schema.entries.length === 0) {
    if (captures.length > 0) {
      throw new Error("Rule has field captures but no field schema.");
    }
    return Object.create(null) as Record<string, unknown>;
  }
  const fields = Object.create(null) as Record<string, unknown>;
  const counts = Object.create(null) as Record<string, number>;
  for (const [name, config] of schema.entries) {
    fields[name] = config.array ? [] : config.nullable ? null : undefined;
    counts[name] = 0;
  }
  for (const capture of captures) {
    const config = schema.byName[capture.name];
    if (!config) {
      throw new Error(\`Unknown field capture '\${capture.name}'.\`);
    }
    counts[capture.name] = (counts[capture.name] ?? 0) + 1;
    if (config.array) {
      const values = fields[capture.name];
      if (!Array.isArray(values)) {
        throw new Error(\`Array field '\${capture.name}' was not initialized as an array.\`);
      }
      values.push(capture.value);
    } else {
      if ((counts[capture.name] ?? 0) > 1) {
        throw new Error(\`Scalar field '\${capture.name}' was captured more than once.\`);
      }
      fields[capture.name] = capture.value;
    }
  }
  for (const [name, config] of schema.entries) {
    const count = counts[name] ?? 0;
    if (config.array) {
      if (!Array.isArray(fields[name])) {
        throw new Error(\`Array field '\${name}' was not initialized as an array.\`);
      }
      continue;
    }
    if (!config.nullable && count !== 1) {
      throw new Error(\`Required field '\${name}' was captured \${count} times.\`);
    }
    if (config.nullable && count > 1) {
      throw new Error(\`Nullable field '\${name}' was captured more than once.\`);
    }
  }
  return fields;
}

function findActions(state: number, terminal: number): RuntimeAction[] {
  const actions: RuntimeAction[] = [];
  for (const entry of ACTIONS[state] ?? []) {
    if (entry[0] !== terminal) continue;
    if (entry[1] === 1) {
      actions.push({ kind: "shift", state: entry[2] });
    } else if (entry[1] === 2) {
      actions.push({ kind: "reduce", production: entry[2] });
    } else {
      actions.push({ kind: "accept" });
    }
  }
  return actions;
}

function findGoto(state: number, nonterminal: number): number | undefined {
  for (const entry of GOTOS[state] ?? []) {
    if (entry[0] === nonterminal) return entry[1];
  }
  return undefined;
}

function expectedTerminals(state: number): readonly string[] {
  return [...new Set((ACTIONS[state] ?? []).map((entry) => TERMINAL_NAMES[entry[0]]))]
    .sort();
}

function tokenToTerminal(token: Token): number {
  if (token.type === "eof") return EOF_TERMINAL;
  if (token.type === "named" && token.channel === "main") {
    return NAMED_TERMINALS.get(token.kind) ?? -1;
  }
  if (token.type === "literal") {
    return LITERAL_TERMINALS.get(token.literal) ?? -1;
  }
  return -1;
}

function isTriviaToken(token: Token): boolean {
  return token.type === "named" && token.channel === "trivia";
}

function lexicalTokenDiagnostic(token: Token): ParseDiagnostic {
  if (token.type === "error") {
    return {
      code: "PARSE_LEXICAL_ERROR",
      message: \`Unexpected character \${JSON.stringify(token.text)}.\`,
      span: token.span,
      found: JSON.stringify(token.text),
    };
  }
  return {
    code: "PARSE_LEXICAL_ERROR",
    message: \`Token \${tokenDisplay(token)} is not part of this parser's terminal set.\`,
    span: token.span,
    found: tokenDisplay(token),
  };
}

function isRuleNode(value: unknown): value is AnyRuleNode {
  return !!value &&
    typeof value === "object" &&
    (value as { type?: unknown }).type === "rule";
}

function isFragment(value: unknown): value is Fragment {
  return !!value &&
    typeof value === "object" &&
    "value" in value &&
    "children" in value &&
    "fields" in value;
}

function isMainSyntaxToken(
  value: unknown,
): value is MainNamedToken | LiteralToken {
  return !!value &&
    typeof value === "object" &&
    (
      (value as { type?: unknown }).type === "literal" ||
      ((value as { type?: unknown; channel?: unknown }).type === "named" &&
        (value as { channel?: unknown }).channel === "main")
    );
}

function validateTokenStream(
  source: string,
  tokens: readonly Token[],
): ParseDiagnostic[] {
  const diagnostics: ParseDiagnostic[] = [];
  let previousEnd = 0;
  let eofIndex = -1;

  for (let index = 0; index < tokens.length; index++) {
    const token = tokens[index];
    const span = token.span;
    if (
      !Number.isInteger(span.start) ||
      !Number.isInteger(span.end) ||
      span.start < 0 ||
      span.end < span.start ||
      span.end > source.length
    ) {
      diagnostics.push(invalidTokenStream(
        \`Token at index \${index} has an invalid span.\`,
        clampSpan(span, source.length),
      ));
      continue;
    }

    if (span.start > previousEnd) {
      const gapDiagnostic = validateSourceGap(source, previousEnd, span.start);
      if (gapDiagnostic) diagnostics.push(gapDiagnostic);
    }

    if (span.start < previousEnd) {
      diagnostics.push(invalidTokenStream(
        \`Token at index \${index} overlaps a previous token.\`,
        span,
      ));
    }
    previousEnd = Math.max(previousEnd, span.end);

    if (token.type === "eof") {
      if (eofIndex !== -1) {
        diagnostics.push(invalidTokenStream(
          "Token stream contains more than one EOF token.",
          span,
        ));
      }
      eofIndex = index;
      if (
        token.text !== "" ||
        token.channel !== "main" ||
        span.start !== span.end ||
        span.start !== source.length
      ) {
        diagnostics.push(invalidTokenStream(
          "EOF token must have empty text, main channel, and an empty span at the end of the source.",
          span,
        ));
      }
      continue;
    }

    if (eofIndex !== -1) {
      diagnostics.push(invalidTokenStream(
        "Token stream contains tokens after EOF.",
        span,
      ));
    }

    if (span.start === span.end) {
      diagnostics.push(invalidTokenStream(
        \`Token at index \${index} has zero width.\`,
        span,
      ));
    }

    const sourceText = source.slice(span.start, span.end);
    if (token.text !== sourceText) {
      diagnostics.push(invalidTokenStream(
        \`Token at index \${index} text does not match the source slice.\`,
        span,
      ));
    }
    if (token.type === "literal") {
      if (token.channel !== "main" || token.text !== token.literal) {
        diagnostics.push(invalidTokenStream(
          "Literal tokens must use the main channel and text equal to the literal.",
          span,
        ));
      }
    } else if (token.type === "named") {
      if (token.channel !== "main" && token.channel !== "trivia") {
        diagnostics.push(invalidTokenStream(
          "Named tokens must use the main or trivia channel.",
          span,
        ));
      } else if (token.channel === "main") {
        if (!MAIN_TOKEN_KINDS.has(token.kind)) {
          diagnostics.push(invalidTokenStream(
            \`Named token kind '\${token.kind}' is not a main token kind.\`,
            span,
          ));
        }
      } else if (!TRIVIA_TOKEN_KINDS.has(token.kind)) {
        diagnostics.push(invalidTokenStream(
          \`Named token kind '\${token.kind}' is not a trivia token kind.\`,
          span,
        ));
      }
    } else if (token.type === "error") {
      if (token.channel !== "error") {
        diagnostics.push(invalidTokenStream(
          "Error tokens must use the error channel.",
          span,
        ));
      }
    } else {
      diagnostics.push(invalidTokenStream("Token has an unknown type.", span));
    }
  }

  if (eofIndex !== -1 && eofIndex !== tokens.length - 1) {
    diagnostics.push(invalidTokenStream(
      "EOF must be the final token in the stream.",
      tokens[eofIndex]?.span ?? { start: source.length, end: source.length },
    ));
  }
  if (previousEnd < source.length && eofIndex === -1) {
    const gapDiagnostic = validateSourceGap(source, previousEnd, source.length);
    if (gapDiagnostic) diagnostics.push(gapDiagnostic);
  }
  return diagnostics;
}

function validateSourceGap(
  source: string,
  start: number,
  end: number,
): ParseDiagnostic | null {
  if (start === end) return null;
  const text = source.slice(start, end);
  const lexed = lex(text, { preserveTrivia: true });
  const nonEofTokens = lexed.tokens.filter((token) => token.type !== "eof");
  if (
    lexed.diagnostics.length === 0 &&
    nonEofTokens.length > 0 &&
    nonEofTokens.every((token) =>
      token.type === "named" &&
      token.channel === "trivia" &&
      token.span.start >= 0 &&
      token.span.end <= text.length
    )
  ) {
    return null;
  }
  return invalidTokenStream(
    "Token stream omits nontrivia source text.",
    { start, end },
  );
}

function invalidTokenStream(message: string, span: Span): ParseDiagnostic {
  return {
    code: "PARSE_INVALID_TOKEN_STREAM",
    message,
    span,
  };
}

function clampSpan(span: Span, sourceLength: number): Span {
  const start = Math.min(Math.max(0, span.start), sourceLength);
  const end = Math.min(Math.max(start, span.end), sourceLength);
  return { start, end };
}

function internalParserDiagnostic(error: unknown, span: Span): ParseDiagnostic {
  return {
    code: "PARSER_INTERNAL_ERROR",
    message: error instanceof Error ? error.message : String(error),
    span,
  };
}

function tokenDisplay(token: Token): string {
  if (token.type === "eof") return "EOF";
  if (token.type === "named") return token.kind;
  if (token.type === "literal") return JSON.stringify(token.literal);
  return JSON.stringify(token.text);
}

function skipTrivia(tokens: readonly Token[], start: number): number {
  let index = start;
  while (tokens[index]?.type === "named" && tokens[index].channel === "trivia") {
    index++;
  }
  return index;
}

function lexicalDiagnostic(diagnostic: LexDiagnostic): ParseDiagnostic {
  return {
    code: "PARSE_LEXICAL_ERROR",
    message: diagnostic.message,
    span: diagnostic.span,
  };
}

function eofToken(offset: number): Token {
  return {
    type: "eof",
    text: "",
    span: { start: offset, end: offset },
    channel: "main",
  };
}

function currentSpan(token: Token): Span {
  return token.span;
}

function spanFromFragments(parts: readonly Fragment[]): Span | null {
  return parts.reduce<Span | null>(
    (span, part) => combineSpans(span, part.span),
    null,
  );
}

function spanFromChildren(children: readonly SyntaxElement[]): Span | null {
  return children.reduce<Span | null>(
    (span, child) => combineSpans(span, child.span),
    null,
  );
}

function combineSpans(left: Span | null, right: Span | null): Span | null {
  if (!left) return right;
  if (!right) return left;
  return {
    start: Math.min(left.start, right.start),
    end: Math.max(left.end, right.end),
  };
}
`;
}

function bnfTableRows<T>(
  table: ReadonlyMap<number, ReadonlyMap<number, T>>,
  encode: (key: number, value: T) => unknown,
): unknown[] {
  const maxState = Math.max(-1, ...table.keys());
  const rows: unknown[] = [];
  for (let state = 0; state <= maxState; state++) {
    const entries = [...(table.get(state)?.entries() ?? [])]
      .sort(([left], [right]) => left - right)
      .map(([key, value]) => encode(key, value));
    rows.push(entries);
  }
  return rows;
}

function bnfActionTableRows(
  table: ReadonlyMap<number, ReadonlyMap<number, LrActionSet>>,
): unknown[] {
  const maxState = Math.max(-1, ...table.keys());
  const rows: unknown[] = [];
  for (let state = 0; state <= maxState; state++) {
    const entries = [...(table.get(state)?.entries() ?? [])]
      .sort(([left], [right]) => left - right)
      .flatMap(([terminal, actions]) =>
        actions.map((action) => actionEntry(terminal, action))
      );
    rows.push(entries);
  }
  return rows;
}

function actionEntry(terminal: number, action: LrAction): unknown {
  if (action.kind === "shift") return [terminal, 1, action.state];
  if (action.kind === "reduce") return [terminal, 2, action.production];
  return [terminal, 3];
}

void (undefined as ReducerSpec | undefined);
