import type {
  BabaMetadata,
  Diagnostic,
  GeneratedFile,
  PortabilityMode,
  TypeScriptTargetOptions,
} from "../../ast.ts";
import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import type { RegexAst } from "../../compiler/regex/ast.ts";
import {
  buildLexerDfa,
  type LexerRegexSpec,
} from "../../compiler/regex/lexer.ts";
import { isRegexNullable } from "../../compiler/regex/nullable.ts";
import { regexOverlapWitness } from "../../compiler/regex/overlap.ts";
import { parsePortableRegex } from "../../compiler/regex/parser.ts";
import { type BnfGrammar, lowerToBnf } from "./bnf.ts";
import { buildCanonicalLr1Table, type LrTable } from "./lr1.ts";
import { emitLexer } from "./lexer_emit.ts";
import { emitParser } from "./parser_emit.ts";
import { emitSyntax } from "./syntax_emit.ts";

export interface TypeScriptPlan {
  analyzed: AnalyzedGrammar;
  bnf: BnfGrammar;
  lr: LrTable;
  directory: string;
  generatedBytes: number;
  diagnostics: readonly Diagnostic[];
}

const DEFAULT_LEXER_STATE_LIMIT = 50_000;

interface TypeScriptRegexAnalysis {
  diagnostics: readonly Diagnostic[];
  astByTokenId: ReadonlyMap<number, RegexAst>;
}

export function planTypeScriptTarget(
  analyzed: AnalyzedGrammar,
  options: TypeScriptTargetOptions = {},
  metadata: BabaMetadata = {},
  portability: PortabilityMode = "warn",
): TypeScriptPlan | { diagnostics: readonly Diagnostic[] } {
  const regexAnalysis = analyzeTypeScriptRegexes(analyzed);
  const diagnostics: Diagnostic[] = [
    ...typescriptCapabilityDiagnostics(analyzed, metadata, portability),
    ...regexAnalysis.diagnostics,
    ...typescriptLiteralDiagnostics(analyzed),
    ...typescriptTokenOverlapDiagnostics(analyzed, regexAnalysis.astByTokenId),
    ...typescriptLiteralOverlapDiagnostics(
      analyzed,
      regexAnalysis.astByTokenId,
    ),
    ...typescriptOptionsDiagnostics(options),
  ];
  if (!hasErrors(diagnostics)) {
    diagnostics.push(
      ...typescriptLexerStateDiagnostics(
        analyzed,
        regexAnalysis.astByTokenId,
        options,
      ),
    );
  }
  if (hasErrors(diagnostics)) return { diagnostics };

  const bnf = lowerToBnf(analyzed);
  diagnostics.push(...bnf.diagnostics);
  if (hasErrors(diagnostics)) return { diagnostics };

  const lr = buildCanonicalLr1Table(bnf, {
    stateLimit: options.parserStateLimit ?? 20_000,
    itemLimit: options.parserItemLimit,
    tableEntryLimit: options.parserTableEntryLimit,
  });
  diagnostics.push(...lr.diagnostics);
  if (hasErrors(diagnostics)) return { diagnostics };
  const generatedSources = typeScriptSources(analyzed, bnf, lr, options);
  const generatedBytes = byteLength(
    generatedSources.map((source) => source.content).join(""),
  );
  if (
    options.generatedByteLimit !== undefined &&
    generatedBytes > options.generatedByteLimit
  ) {
    diagnostics.push({
      code: "TS_GENERATED_BYTE_LIMIT",
      severity: "error",
      backend: "typescript",
      message:
        `The TypeScript target generated ${generatedBytes} bytes, exceeding the configured limit (${options.generatedByteLimit}).`,
    });
  }
  if (hasErrors(diagnostics)) return { diagnostics };
  if (options.reportParserStats) {
    diagnostics.push(parserStatsDiagnostic(analyzed, bnf, lr, generatedBytes));
  }

  return {
    analyzed,
    bnf,
    lr,
    directory: options.directory ?? "typescript",
    generatedBytes,
    diagnostics,
  };
}

export function emitTypeScriptTarget(
  plan: TypeScriptPlan,
  options: TypeScriptTargetOptions = {},
): GeneratedFile[] {
  const dir = plan.directory;
  return typeScriptSources(plan.analyzed, plan.bnf, plan.lr, options).map((
    file,
  ) => ({
    path: `${dir}/${file.path}`,
    content: file.content,
    kind: "source",
  }));
}

function typeScriptSources(
  analyzed: AnalyzedGrammar,
  bnf: BnfGrammar,
  lr: LrTable,
  options: TypeScriptTargetOptions,
): Array<{ path: string; content: string }> {
  return [
    {
      path: "syntax.ts",
      content: emitSyntax(analyzed),
    },
    {
      path: "lexer.ts",
      content: emitLexer(analyzed, options),
    },
    {
      path: "parser.ts",
      content: emitParser(analyzed, bnf, lr),
    },
    {
      path: "mod.ts",
      content: typeScriptModSource(),
    },
  ];
}

function typeScriptModSource(): string {
  return `// Generated by @mewhhaha/baba. Do not edit by hand.
export * from "./syntax.ts";
export { lex } from "./lexer.ts";
export { parse, parseTokens, parseTokensUnchecked } from "./parser.ts";
`;
}

function typescriptCapabilityDiagnostics(
  analyzed: AnalyzedGrammar,
  metadata: BabaMetadata,
  portability: PortabilityMode,
): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];
  for (const external of analyzed.reachableExternals) {
    diagnostics.push({
      code: "TS_EXTERNAL_TOKENS_UNSUPPORTED",
      severity: "error",
      backend: "typescript",
      message:
        `The TypeScript target cannot generate scanner behavior for external token '${external}'. Generate only Tree-sitter output or replace the external token with an explicit portable token.`,
    });
  }

  for (const [ruleName, ruleMeta] of Object.entries(metadata.rules ?? {})) {
    if (ruleMeta.token?.kind === "token.immediate") {
      diagnostics.push({
        code: "TS_TOKEN_IMMEDIATE_UNSUPPORTED",
        severity: "error",
        backend: "typescript",
        message:
          `The TypeScript target does not support token.immediate metadata on rule '${ruleName}' because it may alter accepted whitespace.`,
      });
    }
    if (
      portability !== "off" &&
      (ruleMeta.paths || ruleMeta.wrap || ruleMeta.fields)
    ) {
      diagnostics.push({
        code: "PORTABILITY_TREE_SHAPE_DIFFERS",
        severity: "warning",
        backend: "typescript",
        message:
          `Tree-sitter shaping metadata on rule '${ruleName}' is ignored by the TypeScript CST target.`,
      });
    }
  }

  const skipNames = new Set(
    analyzed.tokens.filter((token) => token.kind === "skip").map((token) =>
      token.name
    ),
  );
  for (const extra of metadata.extras ?? []) {
    if (extra.kind !== "rule" || !skipNames.has(extra.name)) {
      if (portability === "off") continue;
      diagnostics.push({
        code: "PORTABILITY_TREE_SITTER_EXTRA",
        severity: portability === "strict" ? "error" : "warning",
        backend: "typescript",
        message:
          "Tree-sitter extras that are not EBNF skip declarations are ignored by the TypeScript target.",
      });
    }
  }

  return diagnostics;
}

function analyzeTypeScriptRegexes(
  analyzed: AnalyzedGrammar,
): TypeScriptRegexAnalysis {
  const diagnostics: Diagnostic[] = [];
  const astByTokenId = new Map<number, RegexAst>();
  for (const token of analyzed.tokens) {
    if (token.kind === "token" && !analyzed.reachableTokens.has(token.id)) {
      continue;
    }
    let ast: RegexAst;
    try {
      ast = parsePortableRegex(token.pattern);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      diagnostics.push({
        code: "TS_LEXER_UNSUPPORTED_REGEX",
        severity: "error",
        backend: "typescript",
        message:
          `Token '${token.name}' is outside Baba's portable regex subset: ${message}`,
        span: token.span,
      });
      continue;
    }
    astByTokenId.set(token.id, ast);
    if (isRegexNullable(ast)) {
      diagnostics.push({
        code: "TS_LEXER_EMPTY_TOKEN",
        severity: "error",
        backend: "typescript",
        message: `Token '${token.name}' must not match empty text.`,
        span: token.span,
      });
    }
  }
  return { diagnostics, astByTokenId };
}

function typescriptTokenOverlapDiagnostics(
  analyzed: AnalyzedGrammar,
  astByTokenId: ReadonlyMap<number, RegexAst>,
): Diagnostic[] {
  const tokens = analyzed.tokens.filter((token) =>
    token.kind === "skip" ||
    (token.kind === "token" && analyzed.reachableTokens.has(token.id))
  );
  const diagnostics: Diagnostic[] = [];
  for (let leftIndex = 0; leftIndex < tokens.length; leftIndex++) {
    for (
      let rightIndex = leftIndex + 1;
      rightIndex < tokens.length;
      rightIndex++
    ) {
      const left = tokens[leftIndex];
      const right = tokens[rightIndex];
      const leftAst = astByTokenId.get(left.id);
      const rightAst = astByTokenId.get(right.id);
      if (!leftAst || !rightAst) continue;
      const witness = regexOverlapWitness(leftAst, rightAst);
      if (!witness) continue;
      if (left.priority !== right.priority) continue;
      const selected = left.declarationOrder < right.declarationOrder
        ? left
        : right;
      const shadowed = selected === left ? right : left;
      const skipOnly = left.kind === "skip" && right.kind === "skip";
      diagnostics.push({
        code: "TS_LEXER_TOKEN_OVERLAP",
        severity: skipOnly ? "warning" : "error",
        backend: "typescript",
        message: `${tokenLabel(left)} and ${tokenLabel(right)} can both match ${
          JSON.stringify(witness)
        }. The standalone lexer would select ${tokenLabel(selected)} before ${
          tokenLabel(shadowed)
        } for this input by declaration order.`,
        span: right.span,
      });
    }
  }
  return diagnostics;
}

function typescriptLiteralDiagnostics(analyzed: AnalyzedGrammar): Diagnostic[] {
  return analyzed.literals
    .filter((literal) =>
      analyzed.reachableLiterals.has(literal.id) && literal.value.length === 0
    )
    .map((literal): Diagnostic => ({
      code: "TS_LEXER_GENERATION_ERROR",
      severity: "error",
      backend: "typescript",
      message:
        "The TypeScript target cannot generate a zero-length literal token.",
      span: literal.span,
    }));
}

function typescriptLiteralOverlapDiagnostics(
  analyzed: AnalyzedGrammar,
  astByTokenId: ReadonlyMap<number, RegexAst>,
): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];
  const tokens = analyzed.tokens.filter((token) =>
    token.kind === "skip" ||
    (token.priority > 0 &&
      (token.kind === "token" && analyzed.reachableTokens.has(token.id)))
  );
  const literals = analyzed.literals.filter((literal) =>
    analyzed.reachableLiterals.has(literal.id)
  );
  for (const token of tokens) {
    const tokenAst = astByTokenId.get(token.id);
    if (!tokenAst) continue;
    for (const literal of literals) {
      const witness = regexOverlapWitness(tokenAst, literalAst(literal.value));
      if (!witness) continue;
      if (token.kind === "skip") {
        diagnostics.push({
          code: "TS_LEXER_TOKEN_OVERLAP",
          severity: "error",
          backend: "typescript",
          message: `${tokenLabel(token)} and literal ${
            JSON.stringify(literal.value)
          } can both match ${
            JSON.stringify(witness)
          }. Trivia cannot overlap a reachable literal because that literal may be skipped before the parser can consume it.`,
          span: token.span,
        });
        continue;
      }
      diagnostics.push({
        code: "TS_LEXER_TOKEN_OVERLAP",
        severity: "error",
        backend: "typescript",
        message: `${tokenLabel(token)} and literal ${
          JSON.stringify(literal.value)
        } can both match ${
          JSON.stringify(witness)
        }. Priority ${token.priority} would select ${
          tokenLabel(token)
        } before the literal, making the literal unavailable for this input.`,
        span: token.span,
      });
    }
  }
  return diagnostics;
}

function typescriptLexerStateDiagnostics(
  analyzed: AnalyzedGrammar,
  astByTokenId: ReadonlyMap<number, RegexAst>,
  options: TypeScriptTargetOptions,
): Diagnostic[] {
  const limit = options.lexerStateLimit ?? DEFAULT_LEXER_STATE_LIMIT;
  const specs: LexerRegexSpec[] = [];
  for (const token of analyzed.tokens) {
    if (
      token.kind !== "skip" &&
      !(token.kind === "token" && analyzed.reachableTokens.has(token.id))
    ) {
      continue;
    }
    const ast = astByTokenId.get(token.id);
    if (!ast) continue;
    specs.push({
      ast,
      type: "named",
      priority: token.priority,
      order: token.declarationOrder,
    });
  }
  for (const literal of analyzed.literals) {
    if (!analyzed.reachableLiterals.has(literal.id)) continue;
    specs.push({
      ast: literalAst(literal.value),
      type: "literal",
      priority: 0,
      order: literal.sourceOrder,
    });
  }
  const dfa = buildLexerDfa(specs);
  if (dfa.states.length <= limit) return [];
  return [{
    code: "TS_LEXER_STATE_LIMIT",
    severity: "error",
    backend: "typescript",
    message:
      `The TypeScript lexer generated ${dfa.states.length} DFA states, exceeding the configured limit (${limit}).`,
  }];
}

function literalAst(value: string): RegexAst {
  const items: RegexAst[] = [];
  for (let index = 0; index < value.length;) {
    const codePoint = value.codePointAt(index)!;
    items.push({ kind: "literal", codePoint });
    index += codePoint > 0xffff ? 2 : 1;
  }
  if (items.length === 0) return { kind: "empty" };
  return items.length === 1 ? items[0] : { kind: "sequence", items };
}

function typescriptOptionsDiagnostics(
  options: TypeScriptTargetOptions,
): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];
  const directory = options.directory ?? "typescript";
  if (!isSafeRelativeDirectory(directory)) {
    diagnostics.push({
      code: "TS_LEXER_GENERATION_ERROR",
      severity: "error",
      backend: "typescript",
      message:
        `Invalid TypeScript output directory '${directory}'. Use a relative directory without '.', '..', empty components, absolute paths, drive prefixes, or backslashes.`,
    });
  }
  if (
    options.lexerStateLimit !== undefined &&
    (!Number.isInteger(options.lexerStateLimit) ||
      options.lexerStateLimit < 1)
  ) {
    diagnostics.push({
      code: "TS_LEXER_STATE_LIMIT",
      severity: "error",
      backend: "typescript",
      message: "lexerStateLimit must be a positive integer.",
    });
  }
  if (
    options.parserStateLimit !== undefined &&
    (!Number.isInteger(options.parserStateLimit) ||
      options.parserStateLimit < 1)
  ) {
    diagnostics.push({
      code: "TS_PARSER_STATE_LIMIT",
      severity: "error",
      backend: "typescript",
      message: "parserStateLimit must be a positive integer.",
    });
  }
  if (
    options.parserItemLimit !== undefined &&
    (!Number.isInteger(options.parserItemLimit) ||
      options.parserItemLimit < 1)
  ) {
    diagnostics.push({
      code: "TS_PARSER_ITEM_LIMIT",
      severity: "error",
      backend: "typescript",
      message: "parserItemLimit must be a positive integer.",
    });
  }
  if (
    options.parserTableEntryLimit !== undefined &&
    (!Number.isInteger(options.parserTableEntryLimit) ||
      options.parserTableEntryLimit < 1)
  ) {
    diagnostics.push({
      code: "TS_PARSER_TABLE_ENTRY_LIMIT",
      severity: "error",
      backend: "typescript",
      message: "parserTableEntryLimit must be a positive integer.",
    });
  }
  if (
    options.generatedByteLimit !== undefined &&
    (!Number.isInteger(options.generatedByteLimit) ||
      options.generatedByteLimit < 1)
  ) {
    diagnostics.push({
      code: "TS_GENERATED_BYTE_LIMIT",
      severity: "error",
      backend: "typescript",
      message: "generatedByteLimit must be a positive integer.",
    });
  }
  return diagnostics;
}

function parserStatsDiagnostic(
  analyzed: AnalyzedGrammar,
  bnf: BnfGrammar,
  lr: LrTable,
  generatedBytes: number,
): Diagnostic {
  const stats = lr.stats;
  return {
    code: "TS_PARSER_STATS",
    severity: "information",
    backend: "typescript",
    message: [
      "TypeScript parser planning statistics:",
      `rules: ${analyzed.reachableRules.size}`,
      `BNF productions: ${bnf.productions.length}`,
      `LR states: ${stats.states}`,
      `LR core items: ${stats.coreItems}`,
      `LR items: ${stats.items}`,
      `ACTION entries: ${stats.actionEntries}`,
      `GOTO entries: ${stats.gotoEntries}`,
      `table entries: ${stats.tableEntries}`,
      `generated bytes: ${generatedBytes}`,
    ].join("\n"),
  };
}

function byteLength(source: string): number {
  return new TextEncoder().encode(source).length;
}

function tokenLabel(token: AnalyzedGrammar["tokens"][number]): string {
  return `${token.kind} ${token.name}`;
}

function isSafeRelativeDirectory(directory: string): boolean {
  if (
    directory.length === 0 ||
    directory.includes("\0") ||
    directory.includes("\\") ||
    directory.startsWith("/") ||
    /^[A-Za-z]:/.test(directory)
  ) {
    return false;
  }
  return directory.split("/").every((component) =>
    component !== "" && component !== "." && component !== ".."
  );
}

function hasErrors(diagnostics: readonly Diagnostic[]): boolean {
  return diagnostics.some((diagnostic) =>
    (diagnostic.severity ?? "error") === "error"
  );
}
