import type {
  BabaMetadata,
  Diagnostic,
  GeneratedFile,
  PortabilityMode,
  TypeScriptTargetOptions,
} from "../../ast.ts";
import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import type { Dfa } from "../../compiler/regex/dfa.ts";
import type { BnfGrammar } from "./bnf.ts";
import type { LrTable } from "./lr1.ts";
import type {
  PortableParserPlanMetadata,
  PortableParserPlanV1,
} from "../runtime/portable_plan.ts";
import { RUNTIME_IMPLEMENTATION_METADATA } from "../runtime/implementation.ts";
import { emitLexer } from "./lexer_emit.ts";
import { emitParser } from "./parser_emit.ts";
import { emitSyntax } from "./syntax_emit.ts";
import {
  planRuntimeParserTarget,
  type RuntimeParserPlan,
  type RuntimeParserPlanningOptions,
} from "../runtime/plan.ts";

export interface TypeScriptPlan {
  analyzed: AnalyzedGrammar;
  bnf: BnfGrammar;
  lr: LrTable;
  dfa: Dfa;
  portable: PortableParserPlanV1;
  portableMetadata: PortableParserPlanMetadata;
  directory: string;
  generatedBytes: number;
  diagnostics: readonly Diagnostic[];
}

export function planTypeScriptTarget(
  analyzed: AnalyzedGrammar,
  options: TypeScriptTargetOptions = {},
  metadata: BabaMetadata = {},
  portability: PortabilityMode = "warn",
): TypeScriptPlan | { diagnostics: readonly Diagnostic[] } {
  const diagnostics = [...typescriptOptionsDiagnostics(options)];
  const runtimePlan = planRuntimeParserTarget(
    analyzed,
    runtimePlanningOptions(options),
    metadata,
    portability,
    { backend: "typescript", codePrefix: "TS", label: "TypeScript" },
  );
  diagnostics.push(...runtimePlan.diagnostics);
  if (hasErrors(diagnostics) || !isRuntimePlan(runtimePlan)) {
    return { diagnostics };
  }
  const generatedSources = typeScriptSources(
    analyzed,
    runtimePlan.bnf,
    runtimePlan.lr,
    runtimePlan.dfa,
    runtimePlan.portableMetadata,
    options,
  );
  const generatedBytes = byteLength(
    generatedSources.map((source) => source.content).join(""),
  );
  if (
    options.generatedByteLimit !== undefined &&
    generatedBytes > options.generatedByteLimit
  ) {
    diagnostics.push({
      code: "TS_GENERATED_BYTE_LIMIT",
      severity: "error",
      backend: "typescript",
      message:
        `The TypeScript target generated ${generatedBytes} bytes, exceeding the configured limit (${options.generatedByteLimit}).`,
    });
  }
  if (hasErrors(diagnostics)) return { diagnostics };
  if (options.reportParserStats) {
    diagnostics.push(
      parserStatsDiagnostic(
        analyzed,
        runtimePlan.bnf,
        runtimePlan.lr,
        generatedBytes,
      ),
    );
  }

  return {
    analyzed,
    bnf: runtimePlan.bnf,
    lr: runtimePlan.lr,
    dfa: runtimePlan.dfa,
    portable: runtimePlan.portable,
    portableMetadata: runtimePlan.portableMetadata,
    directory: options.directory ?? "typescript",
    generatedBytes,
    diagnostics,
  };
}

export function emitTypeScriptTarget(
  plan: TypeScriptPlan,
  options: TypeScriptTargetOptions = {},
): GeneratedFile[] {
  const dir = plan.directory;
  return typeScriptSources(
    plan.analyzed,
    plan.bnf,
    plan.lr,
    plan.dfa,
    plan.portableMetadata,
    options,
  ).map((file) => ({
    path: `${dir}/${file.path}`,
    content: file.content,
    kind: "source",
  }));
}

function typeScriptSources(
  analyzed: AnalyzedGrammar,
  bnf: BnfGrammar,
  lr: LrTable,
  dfa: Dfa,
  portableMetadata: PortableParserPlanMetadata,
  options: TypeScriptTargetOptions,
): Array<{ path: string; content: string }> {
  return [
    {
      path: "syntax.ts",
      content: emitSyntax(analyzed),
    },
    {
      path: "lexer.ts",
      content: emitLexer(analyzed, options, dfa),
    },
    {
      path: "parser.ts",
      content: emitParser(analyzed, bnf, lr),
    },
    {
      path: "mod.ts",
      content: typeScriptModSource(portableMetadata),
    },
  ];
}

function typeScriptModSource(
  portableMetadata: PortableParserPlanMetadata,
): string {
  return `// Generated by @mewhhaha/baba. Do not edit by hand.
export const parserPlanFormat = ${
    JSON.stringify(portableMetadata.format)
  } as const;
export const parserPlanVersion = ${portableMetadata.version};
export const parserPlanSemantics = ${
    JSON.stringify(portableMetadata.semantics)
  } as const;
export const parserPlanHash = ${JSON.stringify(portableMetadata.hash)} as const;
export const runtimeImplementationFormat = ${
    JSON.stringify(RUNTIME_IMPLEMENTATION_METADATA.format)
  } as const;
export const runtimeImplementationVersion = ${RUNTIME_IMPLEMENTATION_METADATA.version};
export const runtimeImplementationSemantics = ${
    JSON.stringify(RUNTIME_IMPLEMENTATION_METADATA.semantics)
  } as const;
export const runtimeImplementationHash = ${
    JSON.stringify(RUNTIME_IMPLEMENTATION_METADATA.hash)
  } as const;
export * from "./syntax.ts";
export { lex } from "./lexer.ts";
export { parse, parseTokens, parseTokensUnchecked } from "./parser.ts";
`;
}

function typescriptOptionsDiagnostics(
  options: TypeScriptTargetOptions,
): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];
  const directory = options.directory ?? "typescript";
  if (!isSafeRelativeDirectory(directory)) {
    diagnostics.push({
      code: "TS_LEXER_GENERATION_ERROR",
      severity: "error",
      backend: "typescript",
      message:
        `Invalid TypeScript output directory '${directory}'. Use a relative directory without '.', '..', empty components, absolute paths, drive prefixes, or backslashes.`,
    });
  }
  if (
    options.generatedByteLimit !== undefined &&
    (!Number.isInteger(options.generatedByteLimit) ||
      options.generatedByteLimit < 1)
  ) {
    diagnostics.push({
      code: "TS_GENERATED_BYTE_LIMIT",
      severity: "error",
      backend: "typescript",
      message: "generatedByteLimit must be a positive integer.",
    });
  }
  return diagnostics;
}

function parserStatsDiagnostic(
  analyzed: AnalyzedGrammar,
  bnf: BnfGrammar,
  lr: LrTable,
  generatedBytes: number,
): Diagnostic {
  const stats = lr.stats;
  return {
    code: "TS_PARSER_STATS",
    severity: "information",
    backend: "typescript",
    message: [
      "TypeScript parser planning statistics:",
      `rules: ${analyzed.reachableRules.size}`,
      `BNF productions: ${bnf.productions.length}`,
      `LR states: ${stats.states}`,
      `LR core items: ${stats.coreItems}`,
      `LR items: ${stats.items}`,
      `ACTION entries: ${stats.actionEntries}`,
      `GOTO entries: ${stats.gotoEntries}`,
      `table entries: ${stats.tableEntries}`,
      `generated bytes: ${generatedBytes}`,
    ].join("\n"),
  };
}

function byteLength(source: string): number {
  return new TextEncoder().encode(source).length;
}

function isSafeRelativeDirectory(directory: string): boolean {
  if (
    directory.length === 0 ||
    directory.includes("\0") ||
    directory.includes("\\") ||
    directory.startsWith("/") ||
    /^[A-Za-z]:/.test(directory)
  ) {
    return false;
  }
  return directory.split("/").every((component) =>
    component !== "" && component !== "." && component !== ".."
  );
}

function hasErrors(diagnostics: readonly Diagnostic[]): boolean {
  return diagnostics.some((diagnostic) =>
    (diagnostic.severity ?? "error") === "error"
  );
}

function runtimePlanningOptions(
  options: TypeScriptTargetOptions,
): RuntimeParserPlanningOptions {
  return {
    lexerStateLimit: options.lexerStateLimit,
    regexAstNodeLimit: options.regexAstNodeLimit,
    regexBoundedRepeatLimit: options.regexBoundedRepeatLimit,
    regexNfaStateLimit: options.regexNfaStateLimit,
    regexDfaStateLimit: options.regexDfaStateLimit,
    regexOverlapStateLimit: options.regexOverlapStateLimit,
    parserStateLimit: options.parserStateLimit,
    parserItemLimit: options.parserItemLimit,
    parserTableEntryLimit: options.parserTableEntryLimit,
  };
}

function isRuntimePlan(
  value: RuntimeParserPlan | { diagnostics: readonly Diagnostic[] },
): value is RuntimeParserPlan {
  return "bnf" in value;
}
