import type {
  BabaMetadata,
  Diagnostic,
  GeneratedFile,
  TypeScriptTargetOptions,
} from "../../ast.ts";
import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import { type BnfGrammar, lowerToBnf } from "./bnf.ts";
import { buildCanonicalLr1Table, type LrTable } from "./lr1.ts";
import { emitLexer } from "./lexer_emit.ts";
import { emitParser } from "./parser_emit.ts";
import { emitSyntax } from "./syntax_emit.ts";

export interface TypeScriptPlan {
  analyzed: AnalyzedGrammar;
  bnf: BnfGrammar;
  lr: LrTable;
  directory: string;
  diagnostics: readonly Diagnostic[];
}

export function planTypeScriptTarget(
  analyzed: AnalyzedGrammar,
  options: TypeScriptTargetOptions = {},
  metadata: BabaMetadata = {},
): TypeScriptPlan | { diagnostics: readonly Diagnostic[] } {
  const diagnostics: Diagnostic[] = [
    ...typescriptCapabilityDiagnostics(analyzed, metadata),
    ...typescriptRegexDiagnostics(analyzed),
    ...typescriptLiteralDiagnostics(analyzed),
    ...typescriptTokenOverlapDiagnostics(analyzed),
    ...typescriptOptionsDiagnostics(options),
  ];
  if (hasErrors(diagnostics)) return { diagnostics };

  const bnf = lowerToBnf(analyzed);
  diagnostics.push(...bnf.diagnostics);
  if (hasErrors(diagnostics)) return { diagnostics };

  const lr = buildCanonicalLr1Table(bnf, {
    stateLimit: options.parserStateLimit ?? 20_000,
  });
  diagnostics.push(...lr.diagnostics);
  if (hasErrors(diagnostics)) return { diagnostics };

  return {
    analyzed,
    bnf,
    lr,
    directory: options.directory ?? "typescript",
    diagnostics,
  };
}

export function emitTypeScriptTarget(
  plan: TypeScriptPlan,
  options: TypeScriptTargetOptions = {},
): GeneratedFile[] {
  const dir = plan.directory;
  return [
    {
      path: `${dir}/syntax.ts`,
      content: emitSyntax(plan.analyzed),
      kind: "source",
    },
    {
      path: `${dir}/lexer.ts`,
      content: emitLexer(plan.analyzed, options),
      kind: "source",
    },
    {
      path: `${dir}/parser.ts`,
      content: emitParser(plan.analyzed, plan.bnf, plan.lr),
      kind: "source",
    },
    {
      path: `${dir}/mod.ts`,
      content:
        `// Generated by @mewhhaha/baba. Do not edit by hand.\nexport * from "./syntax.ts";\nexport { lex } from "./lexer.ts";\nexport { parse, parseTokens } from "./parser.ts";\n`,
      kind: "source",
    },
  ];
}

function typescriptCapabilityDiagnostics(
  analyzed: AnalyzedGrammar,
  metadata: BabaMetadata,
): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];
  for (const external of analyzed.reachableExternals) {
    diagnostics.push({
      code: "TS_EXTERNAL_TOKENS_UNSUPPORTED",
      severity: "error",
      backend: "typescript",
      message:
        `The TypeScript target cannot generate scanner behavior for external token '${external}'. Generate only Tree-sitter output or replace the external token with an explicit portable token.`,
    });
  }

  for (const [ruleName, ruleMeta] of Object.entries(metadata.rules ?? {})) {
    if (ruleMeta.token?.kind === "token.immediate") {
      diagnostics.push({
        code: "TS_TOKEN_IMMEDIATE_UNSUPPORTED",
        severity: "error",
        backend: "typescript",
        message:
          `The TypeScript target does not support token.immediate metadata on rule '${ruleName}' because it may alter accepted whitespace.`,
      });
    }
    if (ruleMeta.paths || ruleMeta.wrap || ruleMeta.fields) {
      diagnostics.push({
        code: "PORTABILITY_TREE_SHAPE_DIFFERS",
        severity: "warning",
        backend: "typescript",
        message:
          `Tree-sitter shaping metadata on rule '${ruleName}' is ignored by the TypeScript CST target.`,
      });
    }
  }

  const skipNames = new Set(
    analyzed.tokens.filter((token) => token.kind === "skip").map((token) =>
      token.name
    ),
  );
  for (const extra of metadata.extras ?? []) {
    if (extra.kind !== "rule" || !skipNames.has(extra.name)) {
      diagnostics.push({
        code: "PORTABILITY_TREE_SITTER_EXTRA",
        severity: "warning",
        backend: "typescript",
        message:
          "Tree-sitter extras that are not EBNF skip declarations are ignored by the TypeScript target.",
      });
    }
  }

  return diagnostics;
}

function typescriptRegexDiagnostics(analyzed: AnalyzedGrammar): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];
  for (const token of analyzed.tokens) {
    if (token.kind === "token" && !analyzed.reachableTokens.has(token.id)) {
      continue;
    }
    const unsupported = findUnsupportedPortableRegexConstruct(token.pattern);
    if (unsupported) {
      diagnostics.push({
        code: "TS_LEXER_UNSUPPORTED_REGEX",
        severity: "error",
        backend: "typescript",
        message: `${
          token.kind === "skip" ? "Skip" : "Token"
        } '${token.name}' uses ${unsupported}, which is outside Baba's portable regex subset.`,
        span: token.span,
      });
      continue;
    }
    let regex: RegExp;
    try {
      regex = new RegExp(token.pattern, "y");
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      diagnostics.push({
        code: "TS_LEXER_UNSUPPORTED_REGEX",
        severity: "error",
        backend: "typescript",
        message:
          `Token '${token.name}' does not compile as JavaScript regex: ${message}`,
        span: token.span,
      });
      continue;
    }
    regex.lastIndex = 0;
    const match = regex.exec("");
    if (match?.[0] === "") {
      diagnostics.push({
        code: "TS_LEXER_EMPTY_TOKEN",
        severity: "error",
        backend: "typescript",
        message: `Token '${token.name}' must not match empty text.`,
        span: token.span,
      });
    }
  }
  return diagnostics;
}

function typescriptTokenOverlapDiagnostics(
  analyzed: AnalyzedGrammar,
): Diagnostic[] {
  const tokens = analyzed.tokens.filter((token) =>
    token.kind === "token" && analyzed.reachableTokens.has(token.id)
  );
  const diagnostics: Diagnostic[] = [];
  for (let leftIndex = 0; leftIndex < tokens.length; leftIndex++) {
    for (
      let rightIndex = leftIndex + 1;
      rightIndex < tokens.length;
      rightIndex++
    ) {
      const left = tokens[leftIndex];
      const right = tokens[rightIndex];
      const witness = tokenOverlapWitness(left.pattern, right.pattern);
      if (!witness) continue;
      diagnostics.push({
        code: "TS_LEXER_TOKEN_OVERLAP",
        severity: "error",
        backend: "typescript",
        message: `Token ${left.name} and token ${right.name} can both match ${
          JSON.stringify(witness)
        }. The standalone lexer would always select ${left.name} by declaration order, making ${right.name} unavailable for this input.`,
        span: right.span,
      });
    }
  }
  return diagnostics;
}

function typescriptLiteralDiagnostics(analyzed: AnalyzedGrammar): Diagnostic[] {
  return analyzed.literals
    .filter((literal) =>
      analyzed.reachableLiterals.has(literal.id) && literal.value.length === 0
    )
    .map((literal): Diagnostic => ({
      code: "TS_LEXER_GENERATION_ERROR",
      severity: "error",
      backend: "typescript",
      message:
        "The TypeScript target cannot generate a zero-length literal token.",
      span: literal.span,
    }));
}

function typescriptOptionsDiagnostics(
  options: TypeScriptTargetOptions,
): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];
  const directory = options.directory ?? "typescript";
  if (!isSafeRelativeDirectory(directory)) {
    diagnostics.push({
      code: "TS_LEXER_GENERATION_ERROR",
      severity: "error",
      backend: "typescript",
      message:
        `Invalid TypeScript output directory '${directory}'. Use a relative directory without '.', '..', empty components, absolute paths, drive prefixes, or backslashes.`,
    });
  }
  if (
    options.parserStateLimit !== undefined &&
    (!Number.isInteger(options.parserStateLimit) ||
      options.parserStateLimit < 1)
  ) {
    diagnostics.push({
      code: "TS_PARSER_STATE_LIMIT",
      severity: "error",
      backend: "typescript",
      message: "parserStateLimit must be a positive integer.",
    });
  }
  return diagnostics;
}

function findUnsupportedPortableRegexConstruct(
  pattern: string,
): string | undefined {
  let escaped = false;
  let inClass = false;
  for (let index = 0; index < pattern.length; index++) {
    const char = pattern[index];
    if (escaped) {
      if (!inClass && /^[1-9]$/.test(char)) return "backreferences";
      if (!inClass && (char === "p" || char === "P")) {
        return "Unicode property escapes";
      }
      if (!inClass && "sSdDwWbB".includes(char)) {
        return "regex shorthand classes or boundaries";
      }
      escaped = false;
      continue;
    }
    if (char === "\\") {
      escaped = true;
      continue;
    }
    if (char === "[" && !inClass) {
      inClass = true;
      continue;
    }
    if (char === "]" && inClass) {
      inClass = false;
      continue;
    }
    if (inClass) continue;
    if (char === "^" || char === "$") return "anchors";
    if (char === "(" && pattern[index + 1] === "?") {
      const operator = pattern.slice(index + 2, index + 4);
      if (
        pattern[index + 2] === "=" ||
        pattern[index + 2] === "!" ||
        operator === "<=" ||
        operator === "<!"
      ) {
        return "lookaround assertions";
      }
      if (/^<[_A-Za-z]/.test(pattern.slice(index + 2))) {
        return "named capture groups";
      }
      return "inline regex flags or extensions";
    }
    if (
      (char === "*" || char === "+" || char === "?") &&
      pattern[index + 1] === "?"
    ) {
      return "lazy quantifiers";
    }
    if (char === "}" && pattern[index + 1] === "?") {
      return "lazy quantifiers";
    }
  }
  return undefined;
}

function tokenOverlapWitness(left: string, right: string): string | null {
  const leftLiteral = simpleRegexLiteral(left);
  const rightLiteral = simpleRegexLiteral(right);
  if (
    leftLiteral !== null && rightLiteral !== null &&
    leftLiteral === rightLiteral
  ) {
    return leftLiteral;
  }
  if (left === right) return leftLiteral ?? left;
  return null;
}

function simpleRegexLiteral(pattern: string): string | null {
  let result = "";
  let escaped = false;
  for (const char of pattern) {
    if (escaped) {
      if ("|()[]{}*+?.^$".includes(char) || char === "\\" || char === "/") {
        result += char;
        escaped = false;
        continue;
      }
      return null;
    }
    if (char === "\\") {
      escaped = true;
      continue;
    }
    if ("|()[]{}*+?.^$".includes(char)) return null;
    result += char;
  }
  return escaped ? null : result;
}

function isSafeRelativeDirectory(directory: string): boolean {
  if (
    directory.length === 0 ||
    directory.includes("\0") ||
    directory.includes("\\") ||
    directory.startsWith("/") ||
    /^[A-Za-z]:/.test(directory)
  ) {
    return false;
  }
  return directory.split("/").every((component) =>
    component !== "" && component !== "." && component !== ".."
  );
}

function hasErrors(diagnostics: readonly Diagnostic[]): boolean {
  return diagnostics.some((diagnostic) =>
    (diagnostic.severity ?? "error") === "error"
  );
}
