import type { AnalyzedGrammar } from "../../compiler/ir.ts";
import { collectRuleFieldSchemas } from "../runtime/field_schema.ts";
import type { PortableParserPlanV1 } from "../runtime/portable_plan.ts";

export function emitSyntax(analyzed: AnalyzedGrammar): string {
  const namedTokens = analyzed.tokens.filter((token) =>
    token.kind === "skip" ||
    (token.kind === "token" && analyzed.reachableTokens.has(token.id))
  );
  const mainTokens = namedTokens.filter((token) => token.kind === "token");
  const triviaTokens = namedTokens.filter((token) => token.kind === "skip");
  const literals = analyzed.literals.filter((literal) =>
    analyzed.reachableLiterals.has(literal.id)
  );
  const rules = analyzed.rules.filter((rule) =>
    analyzed.reachableRules.has(rule.id)
  );
  const fieldSchemas = collectRuleFieldSchemas(analyzed);
  const rootSchema = fieldSchemas.find((schema) =>
    schema.ruleId === analyzed.rootRule
  );
  return emitSyntaxModel({
    mainTokenKinds: mainTokens.map((token) => token.name),
    triviaTokenKinds: triviaTokens.map((token) => token.name),
    literalKinds: literals.map((literal) => literal.value),
    ruleNames: rules.map((rule) => rule.name),
    fieldSchemas,
    rootNodeType: rootSchema?.nodeType ?? "AnyRuleNode",
  });
}

export function emitSyntaxFromPortablePlan(
  plan: PortableParserPlanV1,
): string {
  const namedTokens = plan.symbols.tokens.filter((token) => token.reachable);
  const mainTokens = namedTokens.filter((token) => token.kind === "token");
  const triviaTokens = namedTokens.filter((token) => token.kind === "skip");
  const literals = plan.symbols.literals.filter((literal) => literal.reachable);
  return emitSyntaxModel({
    mainTokenKinds: mainTokens.map((token) => token.name),
    triviaTokenKinds: triviaTokens.map((token) => token.name),
    literalKinds: literals.map((literal) => literal.value),
    ruleNames: plan.cst.rules.map((rule) => rule.ruleName),
    fieldSchemas: plan.cst.rules,
    rootNodeType: plan.cst.rootNodeType,
  });
}

function emitSyntaxModel(model: {
  mainTokenKinds: readonly string[];
  triviaTokenKinds: readonly string[];
  literalKinds: readonly string[];
  ruleNames: readonly string[];
  fieldSchemas: readonly {
    readonly ruleName: string;
    readonly nodeType: string;
    readonly fields: readonly {
      readonly name: string;
      readonly type: string;
    }[];
  }[];
  rootNodeType: string;
}): string {
  const lines: string[] = [
    "// Generated by @mewhhaha/baba. Do not edit by hand.",
    "",
    "export interface Span {",
    "  start: number;",
    "  end: number;",
    "}",
    "",
    "export interface Position {",
    "  line: number;",
    "  column: number;",
    "}",
    "",
    "export interface SourceMap {",
    "  readonly source: string;",
    "  positionAt(offset: number): Position;",
    "}",
    "",
    "export function createSourceMap(source: string): SourceMap {",
    "  let lineStarts: readonly number[] | null = null;",
    "  const starts = (): readonly number[] => {",
    "    if (lineStarts) return lineStarts;",
    "    const values = [0];",
    "    for (let index = 0; index < source.length; index++) {",
    "      const code = source.charCodeAt(index);",
    "      if (code === 13) {",
    "        if (source.charCodeAt(index + 1) === 10) index++;",
    "        values.push(index + 1);",
    "      } else if (code === 10) {",
    "        values.push(index + 1);",
    "      }",
    "    }",
    "    lineStarts = values;",
    "    return values;",
    "  };",
    "  return {",
    "    source,",
    "    positionAt(offset: number): Position {",
    "      const clamped = Math.min(Math.max(0, offset), source.length);",
    "      const values = starts();",
    "      let low = 0;",
    "      let high = values.length - 1;",
    "      while (low <= high) {",
    "        const mid = Math.floor((low + high) / 2);",
    "        if (values[mid] <= clamped) low = mid + 1;",
    "        else high = mid - 1;",
    "      }",
    "      const lineIndex = Math.max(0, low - 1);",
    "      return {",
    "        line: lineIndex + 1,",
    "        column: clamped - values[lineIndex] + 1,",
    "      };",
    "    },",
    "  };",
    "}",
    "",
    "export function positionAt(source: string, offset: number): Position {",
    "  return createSourceMap(source).positionAt(offset);",
    "}",
    "",
    "export interface LexDiagnostic {",
    '  code: "LEX_UNEXPECTED_CHARACTER";',
    "  message: string;",
    "  span: Span;",
    "}",
    "",
    "export interface ParseDiagnostic {",
    "  code:",
    '    | "PARSE_LEXICAL_ERROR"',
    '    | "PARSE_UNEXPECTED_TOKEN"',
    '    | "PARSE_TRAILING_INPUT"',
    '    | "PARSE_INVALID_TOKEN_STREAM"',
    '    | "PARSER_BRANCH_LIMIT"',
    '    | "PARSER_TRACE_LIMIT"',
    '    | "PARSER_AMBIGUOUS_PARSE"',
    '    | "PARSER_INTERNAL_ERROR";',
    "  message: string;",
    "  span: Span;",
    "  runtimeCode: number;",
    "  runtimeDetail: number;",
    '  runtimeDetailKind: "none" | "parser-state";',
    "  runtimeDetailKindId: number;",
    "  expected?: readonly string[];",
    "  found?: string;",
    "}",
    "",
    "export type MainTokenKind =",
    ...unionLines(model.mainTokenKinds),
    "",
    "export type TriviaTokenKind =",
    ...unionLines(model.triviaTokenKinds),
    "",
    "export type NamedTokenKind = MainTokenKind | TriviaTokenKind;",
    "",
    "export type AnyMainTokenKind = MainTokenKind extends never",
    "  ? string",
    "  : MainTokenKind;",
    "",
    "export type AnyTriviaTokenKind = TriviaTokenKind extends never",
    "  ? string",
    "  : TriviaTokenKind;",
    "",
    "export type AnyNamedTokenKind = NamedTokenKind extends never",
    "  ? string",
    "  : NamedTokenKind;",
    "",
    "export type LiteralKind =",
    ...unionLines(model.literalKinds),
    "",
    "export type AnyLiteralKind = LiteralKind extends never",
    "  ? string",
    "  : LiteralKind;",
    "",
    "export interface MainNamedToken<K extends string = AnyMainTokenKind> {",
    '  type: "named";',
    "  kind: K;",
    "  text: string;",
    "  span: Span;",
    '  channel: "main";',
    "}",
    "",
    "export interface TriviaToken<K extends string = AnyTriviaTokenKind> {",
    '  type: "named";',
    "  kind: K;",
    "  text: string;",
    "  span: Span;",
    '  channel: "trivia";',
    "}",
    "",
    "export type NamedToken<K extends NamedTokenKind = NamedTokenKind> =",
    "  K extends MainTokenKind",
    "    ? MainNamedToken<K>",
    "    : K extends TriviaTokenKind",
    "    ? TriviaToken<K>",
    "    : never;",
    "",
    "export interface LiteralToken<L extends string = AnyLiteralKind> {",
    '  type: "literal";',
    "  literal: L;",
    "  text: L;",
    "  span: Span;",
    '  channel: "main";',
    "}",
    "",
    "export interface ErrorToken {",
    '  type: "error";',
    "  text: string;",
    "  span: Span;",
    '  channel: "error";',
    "}",
    "",
    "export interface EofToken {",
    '  type: "eof";',
    '  text: "";',
    "  span: Span;",
    '  channel: "main";',
    "}",
    "",
    "export type Token =",
    "  | MainNamedToken",
    "  | TriviaToken",
    "  | LiteralToken",
    "  | ErrorToken",
    "  | EofToken;",
    "",
    "export type RuleName =",
    ...unionLines(model.ruleNames),
    "",
    "export interface RuleNodeBase<N extends RuleName = RuleName> {",
    '  type: "rule";',
    "  name: N;",
    "  span: Span;",
    "  tokenRange: { start: number; end: number };",
    "  children: readonly SyntaxElement[];",
    "  fields: unknown;",
    "}",
    "",
    "export type EmptyFields = Record<string, never>;",
    "",
  ];

  for (const schema of model.fieldSchemas) {
    lines.push(
      `export interface ${schema.nodeType} extends RuleNodeBase<${
        quote(schema.ruleName)
      }> {`,
    );
    if (schema.fields.length === 0) {
      lines.push("  fields: EmptyFields;");
    } else {
      lines.push("  fields: {");
      for (const field of schema.fields) {
        lines.push(`    ${safeProperty(field.name)}: ${field.type};`);
      }
      lines.push("  };");
    }
    lines.push("}", "");
  }

  lines.push(
    "export type AnyRuleNode =",
    ...unionLines(model.fieldSchemas.map((schema) => schema.nodeType), false),
    "",
    `export type RootNode = ${model.rootNodeType};`,
    "",
    "export type SyntaxElement =",
    "  | AnyRuleNode",
    "  | MainNamedToken",
    "  | LiteralToken;",
    "",
    "export interface LexOptions {",
    "  preserveTrivia?: boolean;",
    "}",
    "",
    "export interface LexResult {",
    "  source: string;",
    "  tokens: readonly Token[];",
    "  diagnostics: readonly LexDiagnostic[];",
    "}",
    "",
    "export interface ContextualLexingStats {",
    "  ambiguousLexicalSites: number;",
    "  contextualCandidateChecks: number;",
    "  attemptedTokenSelections: number;",
    "  reductionsBeforeTokenSelection: number;",
    "}",
    "",
    "export interface ParseOptions {",
    "  preserveTrivia?: boolean;",
    "  contextualLexingStats?: (stats: ContextualLexingStats) => void;",
    "  maxExploredBranches?: number;",
    "  maxQueuedBranches?: number;",
    "  maxTraceActions?: number;",
    '  ambiguityMode?: "first-success" | "reject-ambiguous-success";',
    "}",
    "",
    "export type ParseResult<Root extends AnyRuleNode = RootNode> =",
    "  | {",
    "    ok: true;",
    "    root: Root;",
    "    source: string;",
    "    tokens: readonly Token[];",
    "    diagnostics: readonly [];",
    "  }",
    "  | {",
    "    ok: false;",
    "    root: null;",
    "    source: string;",
    "    tokens: readonly Token[];",
    "    diagnostics: readonly ParseDiagnostic[];",
    "  };",
    "",
  );

  return `${lines.join("\n")}\n`;
}

function unionLines(values: readonly string[], quoteValues = true): string[] {
  if (values.length === 0) return ["  never;"];
  const sorted = [...values];
  return sorted.map((value, index) =>
    `  | ${quoteValues ? quote(value) : value}${
      index === sorted.length - 1 ? ";" : ""
    }`
  );
}

function safeProperty(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : quote(name);
}

function quote(value: string): string {
  return JSON.stringify(value);
}
