import type { AnalyzedExpression, AnalyzedGrammar } from "../../compiler/ir.ts";

export interface RuleFieldInfo {
  name: string;
  type: string;
  array: boolean;
  nullable: boolean;
}

export interface RuleFieldSchema {
  ruleId: number;
  ruleName: string;
  nodeType: string;
  fields: readonly RuleFieldInfo[];
}

interface Occurrence {
  min: number;
  max: number | null;
  types: Set<string>;
}

type OccurrenceMap = Map<string, Occurrence>;

export function emitSyntax(analyzed: AnalyzedGrammar): string {
  const namedTokens = analyzed.tokens.filter((token) =>
    token.kind === "skip" ||
    (token.kind === "token" && analyzed.reachableTokens.has(token.id))
  );
  const mainTokens = namedTokens.filter((token) => token.kind === "token");
  const triviaTokens = namedTokens.filter((token) => token.kind === "skip");
  const literals = analyzed.literals.filter((literal) =>
    analyzed.reachableLiterals.has(literal.id)
  );
  const rules = analyzed.rules.filter((rule) =>
    analyzed.reachableRules.has(rule.id)
  );
  const fieldSchemas = collectRuleFieldSchemas(analyzed);
  const rootSchema = fieldSchemas.find((schema) =>
    schema.ruleId === analyzed.rootRule
  );

  const lines: string[] = [
    "// Generated by @mewhhaha/baba. Do not edit by hand.",
    "",
    "export interface Span {",
    "  start: number;",
    "  end: number;",
    "}",
    "",
    "export interface Position {",
    "  line: number;",
    "  column: number;",
    "}",
    "",
    "export interface SourceMap {",
    "  readonly source: string;",
    "  positionAt(offset: number): Position;",
    "}",
    "",
    "export function createSourceMap(source: string): SourceMap {",
    "  let lineStarts: readonly number[] | null = null;",
    "  const starts = (): readonly number[] => {",
    "    if (lineStarts) return lineStarts;",
    "    const values = [0];",
    "    for (let index = 0; index < source.length; index++) {",
    "      const code = source.charCodeAt(index);",
    "      if (code === 13) {",
    "        if (source.charCodeAt(index + 1) === 10) index++;",
    "        values.push(index + 1);",
    "      } else if (code === 10) {",
    "        values.push(index + 1);",
    "      }",
    "    }",
    "    lineStarts = values;",
    "    return values;",
    "  };",
    "  return {",
    "    source,",
    "    positionAt(offset: number): Position {",
    "      const clamped = Math.min(Math.max(0, offset), source.length);",
    "      const values = starts();",
    "      let low = 0;",
    "      let high = values.length - 1;",
    "      while (low <= high) {",
    "        const mid = Math.floor((low + high) / 2);",
    "        if (values[mid] <= clamped) low = mid + 1;",
    "        else high = mid - 1;",
    "      }",
    "      const lineIndex = Math.max(0, low - 1);",
    "      return {",
    "        line: lineIndex + 1,",
    "        column: clamped - values[lineIndex] + 1,",
    "      };",
    "    },",
    "  };",
    "}",
    "",
    "export function positionAt(source: string, offset: number): Position {",
    "  return createSourceMap(source).positionAt(offset);",
    "}",
    "",
    "export interface LexDiagnostic {",
    '  code: "LEX_UNEXPECTED_CHARACTER";',
    "  message: string;",
    "  span: Span;",
    "}",
    "",
    "export interface ParseDiagnostic {",
    "  code:",
    '    | "PARSE_LEXICAL_ERROR"',
    '    | "PARSE_UNEXPECTED_TOKEN"',
    '    | "PARSE_TRAILING_INPUT"',
    '    | "PARSE_INVALID_TOKEN_STREAM"',
    '    | "PARSER_BRANCH_LIMIT"',
    '    | "PARSER_INTERNAL_ERROR";',
    "  message: string;",
    "  span: Span;",
    "  expected?: readonly string[];",
    "  found?: string;",
    "}",
    "",
    "export type MainTokenKind =",
    ...unionLines(mainTokens.map((token) => token.name)),
    "",
    "export type TriviaTokenKind =",
    ...unionLines(triviaTokens.map((token) => token.name)),
    "",
    "export type NamedTokenKind = MainTokenKind | TriviaTokenKind;",
    "",
    "export type AnyMainTokenKind = MainTokenKind extends never",
    "  ? string",
    "  : MainTokenKind;",
    "",
    "export type AnyTriviaTokenKind = TriviaTokenKind extends never",
    "  ? string",
    "  : TriviaTokenKind;",
    "",
    "export type AnyNamedTokenKind = NamedTokenKind extends never",
    "  ? string",
    "  : NamedTokenKind;",
    "",
    "export type LiteralKind =",
    ...unionLines(literals.map((literal) => literal.value)),
    "",
    "export type AnyLiteralKind = LiteralKind extends never",
    "  ? string",
    "  : LiteralKind;",
    "",
    "export interface MainNamedToken<K extends string = AnyMainTokenKind> {",
    '  type: "named";',
    "  kind: K;",
    "  text: string;",
    "  span: Span;",
    '  channel: "main";',
    "}",
    "",
    "export interface TriviaToken<K extends string = AnyTriviaTokenKind> {",
    '  type: "named";',
    "  kind: K;",
    "  text: string;",
    "  span: Span;",
    '  channel: "trivia";',
    "}",
    "",
    "export type NamedToken<K extends NamedTokenKind = NamedTokenKind> =",
    "  K extends MainTokenKind",
    "    ? MainNamedToken<K>",
    "    : K extends TriviaTokenKind",
    "    ? TriviaToken<K>",
    "    : never;",
    "",
    "export interface LiteralToken<L extends string = AnyLiteralKind> {",
    '  type: "literal";',
    "  literal: L;",
    "  text: L;",
    "  span: Span;",
    '  channel: "main";',
    "}",
    "",
    "export interface ErrorToken {",
    '  type: "error";',
    "  text: string;",
    "  span: Span;",
    '  channel: "error";',
    "}",
    "",
    "export interface EofToken {",
    '  type: "eof";',
    '  text: "";',
    "  span: Span;",
    '  channel: "main";',
    "}",
    "",
    "export type Token =",
    "  | MainNamedToken",
    "  | TriviaToken",
    "  | LiteralToken",
    "  | ErrorToken",
    "  | EofToken;",
    "",
    "export type RuleName =",
    ...unionLines(rules.map((rule) => rule.name)),
    "",
    "export interface RuleNodeBase<N extends RuleName = RuleName> {",
    '  type: "rule";',
    "  name: N;",
    "  span: Span;",
    "  children: readonly SyntaxElement[];",
    "  fields: unknown;",
    "}",
    "",
    "export type EmptyFields = Record<string, never>;",
    "",
  ];

  for (const schema of fieldSchemas) {
    lines.push(
      `export interface ${schema.nodeType} extends RuleNodeBase<${
        quote(schema.ruleName)
      }> {`,
    );
    if (schema.fields.length === 0) {
      lines.push("  fields: EmptyFields;");
    } else {
      lines.push("  fields: {");
      for (const field of schema.fields) {
        lines.push(`    ${safeProperty(field.name)}: ${field.type};`);
      }
      lines.push("  };");
    }
    lines.push("}", "");
  }

  lines.push(
    "export type AnyRuleNode =",
    ...unionLines(fieldSchemas.map((schema) => schema.nodeType), false),
    "",
    `export type RootNode = ${rootSchema?.nodeType ?? "AnyRuleNode"};`,
    "",
    "export type SyntaxElement =",
    "  | AnyRuleNode",
    "  | MainNamedToken",
    "  | LiteralToken;",
    "",
    "export interface LexOptions {",
    "  preserveTrivia?: boolean;",
    "}",
    "",
    "export interface LexResult {",
    "  source: string;",
    "  tokens: readonly Token[];",
    "  diagnostics: readonly LexDiagnostic[];",
    "}",
    "",
    "export interface ParseOptions {",
    "  preserveTrivia?: boolean;",
    "}",
    "",
    "export type ParseResult<Root extends AnyRuleNode = RootNode> =",
    "  | {",
    "    ok: true;",
    "    root: Root;",
    "    source: string;",
    "    tokens: readonly Token[];",
    "    diagnostics: readonly [];",
    "  }",
    "  | {",
    "    ok: false;",
    "    root: null;",
    "    source: string;",
    "    tokens: readonly Token[];",
    "    diagnostics: readonly ParseDiagnostic[];",
    "  };",
    "",
  );

  return `${lines.join("\n")}\n`;
}

export function collectRuleFieldSchemas(
  analyzed: AnalyzedGrammar,
): RuleFieldSchema[] {
  const nodeTypesByRuleId = collectNodeTypeNames(analyzed);
  return analyzed.rules
    .filter((rule) => analyzed.reachableRules.has(rule.id))
    .map((rule) => {
      const occurrences = collectFieldOccurrences(
        analyzed,
        rule.expression,
        nodeTypesByRuleId,
      );
      const fields = [...occurrences.entries()].map(([name, occurrence]) => {
        const type = unionType([...occurrence.types]);
        const array = occurrence.max === null || occurrence.max > 1;
        const nullable = !array && occurrence.min === 0;
        return {
          name,
          type: array
            ? readonlyArrayType(type)
            : nullable
            ? `${type} | null`
            : type,
          array,
          nullable,
        };
      }).sort((left, right) => left.name.localeCompare(right.name));
      return {
        ruleId: rule.id,
        ruleName: rule.name,
        nodeType: nodeTypesByRuleId.get(rule.id) ?? nodeTypeName(rule.name),
        fields,
      };
    });
}

export function nodeTypeName(ruleName: string): string {
  const words = ruleName.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const base = (words.length ? words : [ruleName]).map((word) =>
    `${word.slice(0, 1).toUpperCase()}${word.slice(1)}`
  ).join("");
  const safe = base.replace(/[^A-Za-z0-9_]/g, "") || "Rule";
  return `${/^[0-9]/.test(safe) ? "_" : ""}${safe}Node`;
}

function collectFieldOccurrences(
  analyzed: AnalyzedGrammar,
  expression: AnalyzedExpression,
  nodeTypesByRuleId: ReadonlyMap<number, string>,
): OccurrenceMap {
  switch (expression.kind) {
    case "field": {
      const inner = collectFieldOccurrences(
        analyzed,
        expression.expression,
        nodeTypesByRuleId,
      );
      addOccurrence(inner, expression.name, {
        min: 1,
        max: 1,
        types: new Set([
          expressionType(analyzed, expression.expression, nodeTypesByRuleId),
        ]),
      });
      return inner;
    }
    case "sequence":
      return combineSequence(
        expression.items.map((item) =>
          collectFieldOccurrences(analyzed, item, nodeTypesByRuleId)
        ),
      );
    case "choice":
      return combineChoice(
        expression.options.map((option) =>
          collectFieldOccurrences(analyzed, option, nodeTypesByRuleId)
        ),
      );
    case "optional":
      return scaleOptional(
        collectFieldOccurrences(
          analyzed,
          expression.expression,
          nodeTypesByRuleId,
        ),
      );
    case "repeat":
      return scaleRepeat(
        collectFieldOccurrences(
          analyzed,
          expression.expression,
          nodeTypesByRuleId,
        ),
        false,
      );
    case "repeat1":
      return scaleRepeat(
        collectFieldOccurrences(
          analyzed,
          expression.expression,
          nodeTypesByRuleId,
        ),
        true,
      );
    case "separated":
      return combineSequence([
        scaleRepeat(
          collectFieldOccurrences(analyzed, expression.item, nodeTypesByRuleId),
          true,
        ),
        scaleRepeat(
          collectFieldOccurrences(
            analyzed,
            expression.separator,
            nodeTypesByRuleId,
          ),
          false,
        ),
      ]);
    case "ref":
    case "literal":
      return new Map();
  }
}

function expressionType(
  analyzed: AnalyzedGrammar,
  expression: AnalyzedExpression,
  nodeTypesByRuleId: ReadonlyMap<number, string>,
): string {
  switch (expression.kind) {
    case "field":
      return expressionType(analyzed, expression.expression, nodeTypesByRuleId);
    case "ref":
      if (expression.reference.kind === "rule") {
        return nodeTypesByRuleId.get(expression.reference.ruleId) ??
          nodeTypeName(analyzed.rules[expression.reference.ruleId].name);
      }
      if (expression.reference.kind === "token") {
        return `NamedToken<${
          quote(analyzed.tokens[expression.reference.tokenId].name)
        }>`;
      }
      return "never";
    case "literal":
      return `LiteralToken<${quote(expression.value)}>`;
    case "sequence":
      return `readonly [${
        expression.items.map((item) =>
          expressionType(analyzed, item, nodeTypesByRuleId)
        ).join(", ")
      }]`;
    case "choice":
      return unionType(
        expression.options.map((option) =>
          expressionType(analyzed, option, nodeTypesByRuleId)
        ),
      );
    case "optional":
      return `${
        expressionType(analyzed, expression.expression, nodeTypesByRuleId)
      } | null`;
    case "repeat":
    case "repeat1":
      return readonlyArrayType(
        expressionType(analyzed, expression.expression, nodeTypesByRuleId),
      );
    case "separated":
      return readonlyArrayType(
        expressionType(analyzed, expression.item, nodeTypesByRuleId),
      );
  }
}

function collectNodeTypeNames(
  analyzed: AnalyzedGrammar,
): ReadonlyMap<number, string> {
  const used = new Map<string, number>();
  for (const reserved of reservedGeneratedTypeNames) {
    used.set(reserved, 1);
  }
  const result = new Map<number, string>();
  for (const rule of analyzed.rules) {
    if (!analyzed.reachableRules.has(rule.id)) continue;
    const base = nodeTypeName(rule.name);
    const count = used.get(base) ?? 0;
    used.set(base, count + 1);
    result.set(rule.id, count === 0 ? base : `${base}${count + 1}`);
  }
  return result;
}

const reservedGeneratedTypeNames = new Set([
  "Span",
  "Position",
  "SourceMap",
  "LexDiagnostic",
  "ParseDiagnostic",
  "MainTokenKind",
  "TriviaTokenKind",
  "NamedTokenKind",
  "AnyMainTokenKind",
  "AnyTriviaTokenKind",
  "LiteralKind",
  "MainNamedToken",
  "TriviaToken",
  "NamedToken",
  "LiteralToken",
  "ErrorToken",
  "EofToken",
  "Token",
  "RuleName",
  "RuleNodeBase",
  "AnyRuleNode",
  "RootNode",
  "SyntaxElement",
  "LexOptions",
  "LexResult",
  "ParseOptions",
  "ParseResult",
]);

function combineSequence(maps: readonly OccurrenceMap[]): OccurrenceMap {
  const result: OccurrenceMap = new Map();
  for (const map of maps) {
    for (const [name, occurrence] of map) {
      const existing = result.get(name);
      if (!existing) {
        result.set(name, cloneOccurrence(occurrence));
        continue;
      }
      existing.min += occurrence.min;
      existing.max = existing.max === null || occurrence.max === null
        ? null
        : existing.max + occurrence.max;
      for (const type of occurrence.types) existing.types.add(type);
    }
  }
  return result;
}

function combineChoice(maps: readonly OccurrenceMap[]): OccurrenceMap {
  const result: OccurrenceMap = new Map();
  const names = new Set<string>();
  for (const map of maps) for (const name of map.keys()) names.add(name);
  for (const name of names) {
    let min = Number.POSITIVE_INFINITY;
    let max: number | null = 0;
    const types = new Set<string>();
    for (const map of maps) {
      const occurrence = map.get(name);
      min = Math.min(min, occurrence?.min ?? 0);
      if (occurrence?.max === null) {
        max = null;
      } else if (max !== null) {
        max = Math.max(max, occurrence?.max ?? 0);
      }
      for (const type of occurrence?.types ?? []) types.add(type);
    }
    result.set(name, { min, max, types });
  }
  return result;
}

function scaleOptional(map: OccurrenceMap): OccurrenceMap {
  const result: OccurrenceMap = new Map();
  for (const [name, occurrence] of map) {
    result.set(name, { ...cloneOccurrence(occurrence), min: 0 });
  }
  return result;
}

function scaleRepeat(map: OccurrenceMap, oneOrMore: boolean): OccurrenceMap {
  const result: OccurrenceMap = new Map();
  for (const [name, occurrence] of map) {
    result.set(name, {
      min: oneOrMore ? occurrence.min : 0,
      max: occurrence.max === 0 ? 0 : null,
      types: new Set(occurrence.types),
    });
  }
  return result;
}

function addOccurrence(
  map: OccurrenceMap,
  name: string,
  occurrence: Occurrence,
): void {
  const existing = map.get(name);
  if (!existing) {
    map.set(name, cloneOccurrence(occurrence));
    return;
  }
  existing.min += occurrence.min;
  existing.max = existing.max === null || occurrence.max === null
    ? null
    : existing.max + occurrence.max;
  for (const type of occurrence.types) existing.types.add(type);
}

function cloneOccurrence(occurrence: Occurrence): Occurrence {
  return {
    min: occurrence.min,
    max: occurrence.max,
    types: new Set(occurrence.types),
  };
}

function unionLines(values: readonly string[], quoteValues = true): string[] {
  if (values.length === 0) return ["  never;"];
  const sorted = [...values];
  return sorted.map((value, index) =>
    `  | ${quoteValues ? quote(value) : value}${
      index === sorted.length - 1 ? ";" : ""
    }`
  );
}

function unionType(types: readonly string[]): string {
  const unique = [...new Set(types)].sort();
  if (unique.length === 0) return "never";
  return unique.join(" | ");
}

function readonlyArrayType(type: string): string {
  return `ReadonlyArray<${type}>`;
}

function safeProperty(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : quote(name);
}

function quote(value: string): string {
  return JSON.stringify(value);
}
