use-grammars = { only = ["brainfuck"] }

[[language]]
name = "brainfuck"
scope = "source.brainfuck"
file-types = ["bf"]
comment-token = "#"
grammar = "brainfuck"
roots = ["grammar.ebnf"]
rainbow-brackets = true

[[grammar]]
name = "brainfuck"
source = { path = "generated" }
